### ISSUE TITLE
devDependencies/node-sass3.4.2 not support nodejs 8.11

### ISSUE THREAD

**Issue by mengqingchao2012** [openstf/stf#1013]
hello，I start stf with nodejs8.11 on deepin linux.  but it report node-sass not suppport,

I upgrade it to latests 4.11.0, then stf is ok   

will you consider update it or give a notice?

**Comment by sorccu** [comment]
Sorry but I don’t know of anyone else using that distribution. I think you’re on your own. If you can find a fix (or cause) by yourself, we can maybe do something about it. But I don’t think we’ll be able to spend any time on trying to figure it out.

**Comment by sorccu** [comment]
Maybe use docker instead?

**Comment by mengqingchao2012** [comment]
haha ,thank you. i want to learn how to develop stf , so docker is not suit for me.
and i know docker is a good choice，thank you
