### ISSUE TITLE
devices keep disconnected while the provider's log said it's providing all devices

### ISSUE THREAD

**Issue by lgzwo** [openstf/stf#1023]
I am trying to deploy STF server following the [DEPLOYMENT.MD](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). I have start all the containers and the web page looks fine except that all devices keep disconnect.
Here is my provider's log:
>2019-03-07T02:56:06.662Z INF/device:resources:minirev 530 [192.168.199.211:5555] Installing "/app/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
2019-03-07T02:56:06.809Z INF/device:plugins:forward 530 [192.168.199.211:5555] Launching reverse port forwarding service
2019-03-07T02:56:06.819Z INF/device:plugins:forward 530 [192.168.199.211:5555] Connecting to reverse port forwarding service
2019-03-07T02:56:07.325Z INF/device:plugins:connect 530 [192.168.199.211:5555] Listening on port 15173
2019-03-07T02:56:07.332Z INF/device 530 [192.168.199.211:5555] Fully operational
2019-03-07T02:56:11.699Z INF/provider 1 [*] Providing all 1 device(s)

Here is all the containers:
 > NAMES
 stf-provider-beijing
 stf-reaper
 stf-app-3100
 stf-api-3800
 stf-websocket-3700
 stf-processor-3300
 rethinkdb-proxy-28015
 rethinkdb
 nostalgic_brattain
 stf-triproxy-dev
 stf-triproxy-app
 stf-storage-temp-3600
 stf-storage-plugin-image
 stf-storage-plugin-apk
 stf-auth-3200
 adbd

Here is the provider's service:

    [Unit]
    Description=STF provider
    After=adbd.service
    BindsTo=adbd.service
    [Service]
    EnvironmentFile=/etc/environment
    TimeoutStartSec=0
    Restart=always
    ExecStartPre=/usr/bin/docker pull openstf/stf:latest
    ExecStartPre=-/usr/bin/docker kill %p-%i
    ExecStartPre=-/usr/bin/docker rm %p-%i
    ExecStart=/usr/bin/docker run --rm \
      --name %p-%i \
      --net host \
      openstf/stf:latest \
      stf provider \
        --name "%H/%i" \
        --connect-sub tcp://devside.stf.ott.qiyi.domain:7250 \
        --connect-push tcp://devside.stf.ott.qiyi.domain:7270 \
        --storage-url http://stf.ott.qiyi.domain/ \
        --public-ip ${COREOS_PRIVATE_IPV4} \
        --adb-host 10.1.97.153 \
        --min-port=15000 \
        --max-port=25000 \
        --heartbeat-interval 10000 \
        --allow-remote \
        --screen-ws-url-pattern "ws://stf.ott.qiyi.domain/d/%i/<%= serial %>/<%= publicPort %>/"
    ExecStop=-/usr/bin/docker stop -t 10 %p-%i

**Comment by lgzwo** [comment]
problem solved by deploying stf-triproxy-app to a new host

**Comment by ldonlytest** [comment]
How can I solve it?

**Comment by Richard1ybb** [comment]
> problem solved by deploying stf-triproxy-app to a new host

Can you share how you solved it?
I have encountered the same problem.
