### ISSUE TITLE
Help / Multiple Devices

### ISSUE THREAD

**Issue by jorgehmsp** [openstf/stf#1029]
Hello, @sorccu first I will congratulate you and all another genius of this fantastic project. I am working in a project I need to send multiple apps for multiple devices and if possible also send multiple adb shell commands.

I am working with the lasted version for 2 days and my team is exploring all the platform to get the best practices, you have some fast help for me?

Thanks!!!

Jorge H

**Comment by sorccu** [comment]
Thanks! I may be able to answer if you have a reasonably specific question, but other than that I don’t have enough time to provide guidance :(

You could perhaps use the API to reserve multiple devices and then run multiple adb install commands in parallel.

**Comment by koral--** [comment]
No matter if devices are connected via STF or not you can use solutions like this: https://stackoverflow.com/questions/17882474/running-adb-commands-on-all-connected-devices to invoke the same adb command on multiple connected devices.

If you are using Gradle task to install APKs then it will work out of the box. By default app is installed on all connected devices.
