### ISSUE TITLE
stf cannot work on android tv?

### ISSUE THREAD

**Issue by wanglinbjjx** [openstf/stf#1035]
hi:
when i connect an android tv, it not work as below:
minitouch says: "Unable to find a suitable touch device"
does the minitouch support android tv? thanks!

**Comment by sorccu** [comment]
Some are supported, not all. Not all devices expose a touch device so minitouch doesn’t work.

**Comment by wanglinbjjx** [comment]
thanks！
Does the stf support keyevent on tv?

**Comment by amet123** [comment]
Hi , what about washing machine android based ???
