### ISSUE TITLE
Redirecting screen stream plugin's output to the STF app unit and then access it from public IP

### ISSUE THREAD

**Issue by ndimer** [openstf/stf#1049]
Hi,

This is more of a question than an issue.

If I understand right, when it comes to streaming the device screen, STF UI directly connects to the provider's screen stream plugin port (usually 7400). That means the provider's stream plugin port and IP address must be publically accessible within the network where STF UI is open.

If my assumption is right, would it be possible to route the device screen's stream to STF's app unit first and then for STF UI to read the stream from the already public IP address of its unit?

Thanks,
Nick

**Comment by sorccu** [comment]
Use nginx. See the deployment guide.

**Comment by ndimer** [comment]
> Use nginx. See the deployment guide.

I saw the guide, but the guide assumes the NGINX server has inbound access to the provider's server (floor 4 and floor 8). In my case, the provider doesn't have any inbound ports open, so all the communication must be outbound, from the provider to the app unit. I wonder if it's possible to configure STF, so the provider can use only outbound communication?

**Comment by ndimer** [comment]
> > Use nginx. See the deployment guide.
> 
> I saw the guide, but the guide assumes the NGINX server has inbound access to the provider's server (floor 4 and floor 8). In my case, the provider doesn't have any inbound ports open, so all the communication must be outbound, from the provider to the app unit. I wonder if it's possible to configure STF, so the provider can use only outbound communication?

Ok, I solved it with SSH tunneling. That way, the provider and app units can be in two different networks with a firewall in between.
