### ISSUE TITLE
STF resolution ratio  problem

### ISSUE THREAD

**Issue by xushan1988** [openstf/stf#1060]
![image](https://user-images.githubusercontent.com/51977133/59729706-3a16a380-9272-11e9-8ad5-92a4114a1dbe.png)

Blurred font problem

./stf provider --name local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip xx.xx.xx.xx --storage-url http://xx.xx.xx.xx:7100/ --adb-host xx.xx.xx.xx --adb-port 5037 --vnc-initial-size 1080x2248 --mute-master never --allow-remote

Resolution setting：1080x2248，all the same blurred font

**Comment by sorccu** [comment]
VNC settings are irrelevant.

**Comment by xushan1988** [comment]
How does that work out?

**Comment by sorccu** [comment]
You can try --screen-jpeg-quality, it’s the only setting that might help.

**Comment by xushan1988** [comment]
![image](https://user-images.githubusercontent.com/51977133/59731380-7220e500-9278-11e9-9e97-c46b27c8f00b.png)
![image](https://user-images.githubusercontent.com/51977133/59731392-7cdb7a00-9278-11e9-9a83-420e6ecf0f1b.png)

SCREEN_JPEG_QUALITY || 90

all the same blurred font，why？

**Comment by xushan1988** [comment]
modify SCREEN_JPEG_QUALITY  value，the system will be slow

**Comment by xushan1988** [comment]
@sorccu  
modify SCREEN_JPEG_QUALITY value，the system will be slow

**Comment by sorccu** [comment]
Then you have to modify the code to always use a higher resolution.

There is no option you can use.

**Comment by xushan1988** [comment]
@sorccu
![image](https://user-images.githubusercontent.com/51977133/59732622-a945c500-927d-11e9-9995-eb4d78a919e0.png)
modify default resolution，all the same blurred font

**Comment by sorccu** [comment]
You’re modifying the wrong values. There is no cli option you can use. Modifying the cli code is useless.

**Comment by xushan1988** [comment]
@sorccu
How do you do it?

**Comment by xushan1988** [comment]
./stf provider --name local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip xx.xx.xx.xx --storage-url http://xx.xx.xx.xx:7100/ --adb-host xx.xx.xx.xx --adb-port 5037 --vnc-initial-size 600x800 --screen-jpeg-quality 100 --mute-master never --allow-remote

-screen-jpeg-quality 100    yes？

**Comment by sorccu** [comment]
Modify https://github.com/openstf/stf/blob/616d4407ce1494a7a89ed6c1a17677b88e15e455/lib/units/device/plugins/screen/stream.js#L164 and hardcode width/height to whatever values you want inside the function. If that helps, then you can work on a more proper solution by yourself.

I will not be able to help you further.

**Comment by xushan1988** [comment]
@sorccu
Thank you very much.
