### ISSUE TITLE
Add fitler.data/filter.pid/filter.tid validation

### ISSUE THREAD

**Issue by lukzeg** [openstf/stf#1073]
**Is your feature request related to a problem? Please describe.**
As the end user which use logger in the web GUI, sometimes I'm making mistakes(typos), which cause losing adb logs. It will be good to have some validation of filter.data/ filter.pid/ filter.tid fields, to avoid of inserting not correct values, or informing end user, that the values are incorrect.
![image](https://user-images.githubusercontent.com/22797365/61394065-a2cd5c00-a8c2-11e9-976e-672476d88095.png)

**Describe the solution you'd like**
It will be good to set regex to filter data. As well we can filter values which end user set to TID and PID fields.
![image](https://user-images.githubusercontent.com/22797365/61394505-8b42a300-a8c3-11e9-9448-7caa48b916ac.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Steps to reproduce**
1. Assign device to be active
2. Start logging
3. Insert "abs" text in the TID/PID field.
4. Insert invalid text in the Time field

**Comment by koral--** [comment]
Merged, thanks.
