### ISSUE TITLE
The test device is released after reselecting device from device list view 

### ISSUE THREAD

**Issue by lukzeg** [openstf/stf#1076]
**What is the issue or idea you have?**
The test device is released after re-selecting him again from device view

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
N/A

**Please provide the steps to reproduce the issue.**
1. Login
2. Select one of available test devices from Device -> Device Icon List view
3. Wait for redirecting to Control View
4. Navigate to Devices list view by clicking *Devices* on top Navigation view
5. Re-select test device clicking on *device image* or *device name*
![image](https://user-images.githubusercontent.com/22797365/61459205-81c14580-a96c-11e9-9299-449c85ba89cd.png)

**What is the expected behavior?**
The user should be redirected to Control View

**What is the actual behavior?**
The test device is released. Is no longer assigned to end user.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
N/A

**Please run `stf doctor` and paste the output here.**
N/A

**Comment by koral--** [comment]
Merged, thanks.
