### ISSUE TITLE
Can we Power off and On any device? Not restart.

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#1082]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sorccu** [comment]
No. There is no API or command to turn the device off.

There is no way to turn a device on if it’s off, because it can’t accept any commands.

**Comment by suvansh-dev** [comment]
@sorccu  But how does alarms work in switch off mode? Can't we use that alarm stuff to make this work?
