### ISSUE TITLE
Two instances of rethinkdb

### ISSUE THREAD

**Issue by anirudh8860** [openstf/stf#1084]
Hey, I want to know whether I can run two instances of "rethinkdb --bind all" on two different machines on the same network.

If not, what would be the workaround?

NOTE: My ultimate motive is I want to make two STF URLs available on the same network.

**Comment by denis99999** [comment]
Hi @anirudh8860 

Yes you can! I didn't try this configuration, but normally you have just to set the `RETHINKDB_PORT_28015_TCP ` environment variable in the `/etc/environment` file of each machine from which you launch STF, for instance:  `RETHINKDB_PORT_28015_TCP=tcp://@IP_RETHINKDB_1:28015`.

You can also do that using the `ambassador `container following the example done in the documentation with the `rethinkdb-proxy-28015.service`.
