### ISSUE TITLE
[ Tests ] Error: TypeError: protractor.getInstance is not a function [Google Chrome v77.0.3865.75]

### ISSUE THREAD

**Issue by lukzeg** [openstf/stf#1098]
**What is the issue or idea you have?**
The current implementation of tests which use protractor and jasmine is a little bit out of date.
When we run cmd:
```
gulp protractor
```
I receive:
```
Error: TypeError: protractor.getInstance is not a function
```
From the logs:
```
 [22:10:25] I/downloader - curl -o /home/luze/apps/luze_stf/second_repo/stf/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.26linux64.zip https://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
```
we can see that we are using chrome driver in v.2.26 which is a little bit out of date for Google Chrome browser v77.
It will be good to update tests to be more up to date and use latest ver of Google Chrome browser

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
No

**Please provide the steps to reproduce the issue.**
1. Download source code
2. Run -> npm install
3. Run -> rethinkdb
4. Run -> ./bin/stf local
5. Run -> gulp protractor

**What is the expected behavior?**
Tests should be executed. The test results should be reported to some folder

**Actual Results:**
In the console we can see:
```
Error: TypeError: protractor.getInstance is not a function
```

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
No

**Please run `stf doctor` and paste the output here.**
N/A

**Comment by sorccu** [comment]
I suppose this is now fixed.
