### ISSUE TITLE
How to change the port 7100 ?

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#110]
At first, my English is so bad. :)

Thanks for STF, it is really useful for us. But I have a problem that I cannot use 7100 in my company's server, so I must change 7100 to another, but I don't find how to do that. 

Who can tell me ? Thanks very much.

**Comment by vbanthia** [comment]
``` 
stf local --poorxy-port xxxx
```

**Comment by LiufxLucky365** [comment]
Yes ! That works ! Thanks so much !!!

BTW, where do get the option information ? I don't see that in the help

**Comment by vbanthia** [comment]
For specific command options, you need to check command help

eg. ``` stf local --help ```

**Comment by LiufxLucky365** [comment]
Thank you.

**Comment by sorccu** [comment]
Yeah, that's the way to do it right now. As a side note, we need to work on the `--help` output, many of the descriptions are not actually very helpful to beginners right now.
