### ISSUE TITLE
STF local/distributed crashing with similar errors

### ISSUE THREAD

**Issue by giulio1979** [openstf/stf#1102]
Hi,

Both my containers and local mode have issues on the websocket part. Any ideas ?

Thanks

2019-09-23T15:41:20.577Z INF/db 69 [*] Connecting to 172.17.0.6:28015
lib/cli websocket

Options:
  -h, --help          Show help.                                       [boolean]
  -V, --version       Show version.                                    [boolean]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to.
                                                              [array] [required]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.
                                                              [array] [required]
  --port, -p          The port to bind to.              [number] [default: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.
                       [string] [required] [default: "YOUR_SESSION_SECRET_HERE"]
  --ssid, -i          The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --storage-url, -r   URL to the storage unit.               [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

Unexpected token ...
2019-09-23T15:41:20.838Z FTL/cli:local 25 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by giulio1979** [comment]
the NPM downloaded in the Dockerfile was too old, used a more recent one and things got sorted

**Comment by Willow-AlibabaCloud** [comment]
@giulio1979 Hi, whick module version you have updated?
same issue here, and I used the latest package.json in github, still not work.

**Comment by WillPangZi** [comment]
@giulio1979  Hi, whick module version you have updated?
same issue here, and I used the latest package.json in github, still not work.

**Comment by giulio1979** [comment]
Hi, I didnt touch the node modules but the actual node/npm binaries. 
I switched to nodejs-8.12.0 from the 6 in the Dockerfile.
