### ISSUE TITLE
Homebrew installation method for the requirements does not work on MacOS anymore

### ISSUE THREAD

**Issue by ardaozerten** [openstf/stf#1109]
When I try to install all dependencies with "`brew install`" command on terminal, I receive an error message and none of the dependencies are installed on MacOS 10.13.1

```
IST01-ozertena:~ ozertena$ sudo brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

Could you please update requirements installation instructions for MacOS on README.md file?

**Comment by sorccu** [comment]
Our instructions do not use sudo.

**Comment by OKNoah** [comment]
If you're Mac brew requires sudo you need to fix permissions. Also I did `rethinfdb daemon` rather than the other instructions from brew after installing.
