### ISSUE TITLE
Where to buy the cabinet to place phones

### ISSUE THREAD

**Issue by frankbp** [openstf/stf#111]
Just a question not so related with STF itself, we would like to know where to buy such cabinet to place all the mobile devices

**Comment by sorccu** [comment]
It's our own design, but we had it made at a company that specializes in making office furniture/design. We're planning on open sourcing the design as well, but I haven't had time to clean up the plans yet. The original ticket is #1, so I'm closing this one as a duplicate for now.

**Comment by sorccu** [comment]
If you *really* need to buy one directly, I could probably have one made for you, but it would be very expensive. I'd have to think about it a bit more, but we're talking somewhere around $2000-3000 for a single shelf that houses 50-56 devices. Shipping would be very expensive as well. And that's without PCs, hubs, switches and cables.

**Comment by frankbp** [comment]
thanks for the reply.
could it be possible to send me the picture of the shelf and if better the production shelf so that I can send it to my boss to make the decision?
