### ISSUE TITLE
AndroidQ support

### ISSUE THREAD

**Issue by scvjx** [openstf/stf#1110]
There have been some questions about Android Q's inability to support minitouch. Is there a solution?

**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by koral--** [comment]
Duplicate of https://github.com/openstf/stf/issues/1028
