### ISSUE TITLE
After installing the app through the stf webpage, the app is deleted after the phone is released.

### ISSUE THREAD

**Issue by lianhj** [openstf/stf#1114]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by jachstet-sea** [comment]
This is by design, please search for other issues with the same content before you create a new one:
#242

**Comment by koral--** [comment]
Duplicate of #242. Thanks @jachstet-sea for pointing this out.
