### ISSUE TITLE
OAuth documentation missing

### ISSUE THREAD

**Issue by radekstasiak** [openstf/stf#1118]
Hi,

Im slighlty confused as Im trying to look up the documentation on how to use OAuth with the STF login. As far as I remember it used to be part of the README.md however can't find it there anymore. Can you point to a correct place where I read a bit on how to integrate it with STF please?

**Comment by jon2kx** [comment]
It's found here: https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md  However it doesn't seem to work for me using Microsoft Azure. Best of luck, and if you figure it out, give me a shout.

**Comment by koral--** [comment]
Here are OAuth docs: https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md#option-b-oauth-20
What exactly is missing?

**Comment by radekstasiak** [comment]
dzięki @koral-- ;) I got it running with Google OAuth by executing stf from the command line with the following options:

stf local --auth-type oauth2 --auth-options '["--oauth-authorization-url","https://accounts.google.com/o/oauth2/v2/auth","--oauth-token-url","https://www.googleapis.com/oauth2/v4/token","--oauth-userinfo-url","https://www.googleapis.com/oauth2/v3/userinfo","--oauth-client-id","xxx.apps.googleusercontent.com","--oauth-client-secret","xxx","--oauth-callback-url","http://my.domain.com:7100/auth/oauth/callback","--oauth-scope","openid email"]' --public-ip x.x.x.x
