### ISSUE TITLE
LADP Authentication argument 

### ISSUE THREAD

**Issue by kotini** [openstf/stf#1141]
I am able to login my lap using python code as below 
``
import ldap
 username="xyzdomain\\username"
l = ldap.initialize('ldap://autoad.myserver.auto')
password="abcd1234"
try:
  l.protocol_version = ldap.VERSION3
  l.set_option(ldap.OPT_REFERRALS, 0)
  result=l.simple_bind_s(username, password)
  valid = True
  print ("Success")
except:
 print ("Fail")

``

how to pass argument when we running in docker ? I ran like this it didnt work 

``docker run --network=host openstf/stf stf local --auth-type ldap --auth-options '["--ldap-url","ldap://autoad.myserver.auto'"]
``

**Comment by kotini** [comment]
If i pass argument like this its working 

--auth-options '["--ldap-bind-credentials","***","--ldap-bind-dn","CN=***CN=***,DC=***,DC=***","--ldap-search-class","person","--ldap-search-dn","DC=***,DC=***","--ldap-search-field","sAMAccountName","--ldap-url","***","--ldap-username-field","sAMAccountName","--app-url","http://STF_SERVER:7100"]'

**Comment by ommikadam** [comment]
@kotini can you please help me with the ldap as I am trying to achieve but the above command is not working mine config is 
stf auth-ldap --ldap-bind-credentials example@123 --ldap-bind-dn CN=omkar.kadam,DC=example,DC=in --ldap-search-class person --ldap-search-dn DC=apmosys,DC=in --ldap-search-field sAMAccountName --ldap-url ldap://192.168.0.14:389 --ldap-username-field sAMAccountName --app-url https://${PUBLIC_IP}/ --port 3000

**Comment by kotini** [comment]
@ommikadam it should be like this

--auth-type ldap 



--auth-type ldap --auth-options '["--ldap-bind-credentials","....","--ldap-bind-dn","....","--ldap-search-class","person","....","--ldap-search-field","sAMAccountName","--ldap-url","....","--ldap-username-field","sAMAccountName","--app-url","http://${PUBLIC_IP}:7100”]'
