### ISSUE TITLE
 When is Android10 supported?

### ISSUE THREAD

**Issue by liyaoyao6342** [openstf/stf#1155]
**What is the issue or idea you have?**

A demand

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by fuheperpromise** [comment]
STF does not support Android 10，when will stf support android10?

**Comment by jesshowe** [comment]
I also am interested in knowing the status of Android 10 support. Thanks for y'all's hard work!

**Comment by koral--** [comment]
Duplicate of https://github.com/openstf/stf/issues/1028

**Comment by ii958** [comment]
Thanks@koral
