### ISSUE TITLE
conect device using genymotion and virtual box by STF

### ISSUE THREAD

**Issue by ulisoa11** [openstf/stf#1167]
Hello friends... I AM USING GENYMOTION SOFTWARE  BUT THE VIRTUAL DEVICES CREATED ARE NOT DETECTED BY STF farm

-->Can we connect virtual devices created in virtualbox WHIT Genymotion
on openstf?

they will have information that can help me, thank

**Comment by jachstet-sea** [comment]
Do those devices show up in `adb devices` on the machine you are running OpenSTF on?
Have you tried the `--allow-remote` option?

**Comment by ulisoa11** [comment]
@jachstet-sea @sorccu 

hello i tried with the command, But i can't to connect genymotion emulators con stf farm
"I AM USING GENYMOTION SOFTWARE BUT THE VIRTUAL DEVICES CREATED ARE NOT DETECTED BY STF farm"

figure 1. active device is displayed
<img width="1424" alt="Captura de Pantalla 2020-04-21 a la(s) 20 59 41" src="https://user-images.githubusercontent.com/34754791/79932413-146aa580-8413-11ea-9dc5-1dfe7acf0fa8.png">

figure 2. add stf localhost
<img width="1424" alt="Captura de Pantalla 2020-04-21 a la(s) 21 00 50" src="https://user-images.githubusercontent.com/34754791/79932493-40862680-8413-11ea-88c4-e022a668c89a.png">

**Comment by jachstet-sea** [comment]
When I mentioned the `--allow-remote` parameter, that is for running `stf local --allow-remote`. That is not a parameter for adb.

**Comment by ulisoa11** [comment]
Hello i use the comand mentioned and the response is satifactory, @jachstet-sea  thanks you

![image](https://user-images.githubusercontent.com/34754791/80315625-7124e200-87be-11ea-9a9f-472694c1d75c.png)

therefore genymotion and stf are compatible
Best regards ulisoa
