### ISSUE TITLE
on some devices,it will install STFservices.apk repeatedly,!!!!

### ISSUE THREAD

**Issue by thinkcy** [openstf/stf#1200]
![image](https://user-images.githubusercontent.com/26139195/76299670-74d7d480-62f6-11ea-8d6f-51c840cd255b.png)

**Comment by thinkcy** [comment]
Although I have already installed STFservice.apk,it will install STFservices.apk repeatedly,And the prompt "service had an error: error: not found; no service started."

**Comment by koral--** [comment]
What is the device model?

**Comment by denis99999** [comment]
Hi @thinkcy ,

Perhaps a permission issue on your phone, check the permission manager..
Otherwise, try this: remove manually the STFService from active applications, it should trigger the installation again and perhaps it will success, I met this issue on Android GO (API 29)

**Comment by thinkcy** [comment]
> What is the device model?

on Meizu、OPPO by android 9

**Comment by thinkcy** [comment]
> Hi @thinkcy ,
> 
> Perhaps a permission issue on your phone, check the permission manager..
> Otherwise, try this: remove manually the STFService from active applications, it should trigger the installation again and perhaps it will success, I met this issue on Android GO (API 29)

I did, but it couldn't..Unless I use this command in advance：adb shell am start -n jp.co.cyberagent.stf/.IdentityActivity

**Comment by koral--** [comment]
I've encountered the same issue on several devices with API 29.
They are in remote location so I could not just check what is going on on the screen.
After restarting and dismissing keyguard and starting IdentityActivity they started working. Not sure which steps were relevant exactly.

**Comment by thinkcy** [comment]
> I've encountered the same issue on several devices with API 29.
> They are in remote location so I could not just check what is going on on the screen.
> After restarting and dismissing keyguard and starting IdentityActivity they started working. Not sure which steps were relevant exactly.

The previous version did not have this problem. This problem was only discovered after supporting Android 10 . It was reinstalled every time the phone was connected, which was very annoying.

**Comment by lin54241930** [comment]
> > 我在使用API​​ 29的多个设备上遇到了相同的问题。
> > 它们位于远程位置，因此我不能仅检查屏幕上正在发生什么。
> > 重新启动并关闭键盘锁并启动IdentityActivity之后，他们开始工作。不知道哪些步骤是完全相关的。
> 
> 以前的版本没有此问题。仅在支持Android 10后才发现此问题。每次连接电话时都会重新安装它，这很烦人。
Modify (requiredversion: '2.4.2') to (requiredversion: '2.4.3') in the file (LIB / units / device / resources / service. JS)


> > I've encountered the same issue on several devices with API 29.
> > They are in remote location so I could not just check what is going on on the screen.
> > After restarting and dismissing keyguard and starting IdentityActivity they started working. Not sure which steps were relevant exactly.
> 
> The previous version did not have this problem. This problem was only discovered after supporting Android 10 . It was reinstalled every time the phone was connected, which was very annoying.

Modify (requiredversion: '2.4.2') to (requiredversion: '2.4.3') in the file (LIB / units / device / resources / service. JS)

**Comment by thinkcy** [comment]
> > > 我在使用API​​ 29的多个设备上遇到了相同的问题。
> > > 它们位于远程位置，因此我不能仅检查屏幕上正在发生什么。
> > > 重新启动并关闭键盘锁并启动IdentityActivity之后，他们开始工作。不知道哪些步骤是完全相关的。
> > 
> > 
> > 以前的版本没有此问题。仅在支持Android 10后才发现此问题。每次连接电话时都会重新安装它，这很烦人。
> > Modify (requiredversion: '2.4.2') to (requiredversion: '2.4.3') in the file (LIB / units / device / resources / service. JS)
> 
> > > I've encountered the same issue on several devices with API 29.
> > > They are in remote location so I could not just check what is going on on the screen.
> > > After restarting and dismissing keyguard and starting IdentityActivity they started working. Not sure which steps were relevant exactly.
> > 
> > 
> > The previous version did not have this problem. This problem was only discovered after supporting Android 10 . It was reinstalled every time the phone was connected, which was very annoying.
> 
> Modify (requiredversion: '2.4.2') to (requiredversion: '2.4.3') in the file (LIB / units / device / resources / service. JS)

so good,Is the reason

**Comment by koral--** [comment]
@lin54241930 Fixed in the `latest` tag on DockerHub. Thanks for the investigation.
