### ISSUE TITLE
Some phones will automatically return to their original state if they are not used

### ISSUE THREAD

**Issue by RmondJone** [openstf/stf#1202]
Some phones will automatically return to their original state if they are not used，APPs previously installed through the browser or dragged and installed apps will be automatically deleted。I use the latest Master code, compile locally and link。

**Comment by denis99999** [comment]
@RmondJone ,

Yes, by default after 15 mn the phone is released, you can customize this value at provider level using the `--group-timeout` parameter.
Regarding the apps you can also customize the behaviour using the `--cleanup` or `--no-cleanup` parameter.
Do `stf provider --help` command for more explanations.

**Comment by RmondJone** [comment]
Thank You!

**Comment by FRodero** [comment]
Hi @denis99999 @RmondJone ,

How and Where could I use that command?
I am inside of docker STF and I am typing the following command: "stf provider --no-cleanup"
The result is not work properly.

Could you help me?

Thanks in advance.

**Comment by denis99999** [comment]
Hi @FRodero ,

Can you explain what is not work properly ?

**Comment by FRodero** [comment]
Hi @denis99999 ,

I am trying execute the following command: "stf provider --no-cleanup".
>> stf@30df6e383b5d:/app/bin$ stf provider --no-cleanup

Answer:
"""
/app/bin/stf provider [serial..]

Options:
  -h, --help               Show help.                                  [boolean]
  -V, --version            Show version.                               [boolean]
  --adb-host               The ADB server host.  [string] [default: "127.0.0.1"]
  --adb-port               The ADB server port.         [number] [default: 5037]
  --allow-remote, -R       Whether to allow remote devices in STF. Highly
                           unrecommended due to almost unbelievable slowness on
                           the ADB side and duplicate device issues when used
                           locally while having a cable connected at the same
                           time.                                       [boolean]
  --boot-complete-timeout  How long to wait for boot to complete during device
                           setup.                      [number] [default: 60000]
  --cleanup                Attempt to reset the device between uses by
                           uninstallingapps, resetting accounts and clearing
                           caches. Does not do a perfect job currently. Negate
                           with --no-cleanup.          [boolean] [default: true]
  --connect-push, -p       Device-side ZeroMQ PULL endpoint to connect to.
                                                              [array] [required]
  --connect-sub, -s        Device-side ZeroMQ PUB endpoint to connect to.
                                                              [array] [required]
  --connect-url-pattern    The URL pattern to use for `adb connect`.
                                 [string] [default: "${publicIp}:${publicPort}"]
  --group-timeout, -t      Timeout in seconds for automatic release of inactive
                           devices.                      [number] [default: 900]
  --heartbeat-interval     Send interval in milliseconds for heartbeat messages.
                                                       [number] [default: 10000]
  --lock-rotation          Whether to lock rotation when devices are being used.
                           Otherwise changing device orientation may not always
                           work due to sensitive sensors quickly or immediately
                           reverting it back to the physical orientation.
                                                                       [boolean]
  --max-port               Highest port number for device workers to use.
                                                        [number] [default: 7700]
  --min-port               Lowest port number for device workers to use.
                                                        [number] [default: 7400]
  --mute-master            Whether to mute master volume.
                        [choices: "always", "inuse", "never"] [default: "never"]
  --name, -n               An easily identifiable name for the UI and/or log
                           output.            [string] [default: "30df6e383b5d"]
  --public-ip              The IP or hostname to use in URLs.
                                                [string] [default: "172.17.0.4"]
  --screen-jpeg-quality    The JPG quality to use for the screen.
                                                          [number] [default: 80]
  --screen-ping-interval   The interval at which to send ping messages to keep
                           the screen WebSocket alive. [number] [default: 30000]
  --screen-reset           Go back to home screen and reset screen rotation when
                           user releases device. Negate with --no-screen-reset.
                                                       [boolean] [default: true]
  --screen-ws-url-pattern  The URL pattern to use for the screen WebSocket.
                            [string] [default: "ws://${publicIp}:${publicPort}"]
  --storage-url, -r        The URL to the storage unit.      [string] [required]
  --vnc-initial-size       The initial size to use for the experimental VNC
                           server.                 [string] [default: "600x800"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_PROVIDER_` (e.g. `STF_PROVIDER_NAME`).

Missing required arguments: connect-push, connect-sub, storage-url
"""

I have launched command inside of docker STF. Probably, I did wrongly.
How and Where could I use '--no-cleanup'?

Thanks!

**Comment by denis99999** [comment]
You have to provide more argument to the stf provider unit as it is shown to you in the error message : `...Missing required arguments: connect-push, connect-sub, storage-url...`
Look at `doc/DEPLOYMENT.md` for some examples!
Yes, you can use this `--no-cleanup` option here! To get help about it: `stf provider --help`

**Comment by FRodero** [comment]
I can't find which mean these arguments (connect-push, connect-sub, storage-url). That is my problem.
I don't know how I should fill in each ones.

I saw this example:
  --connect-sub tcp://appside.stf.example.org:7150
  --connect-push tcp://appside.stf.example.org:7170
OR
   --connect-sub tcp://devside.stf.example.org:7250 
   --connect-push tcp://devside.stf.example.org:7270

Thanks!
