### ISSUE TITLE
FIX  for some time stf provider disconnect due to zmq subscriber not received message for long time

### ISSUE THREAD

**Issue by kotini** [openstf/stf#1203]
Can we add below solution in lib/units/processor/index.js

As i see device subscriber if don't receive message for long time its disconnects .
And i see device send heat beat in lib/units/device/plugins/heartbeat.js.
Same time processor can we reply ok ? so that device scribe receive the message and then device will active always .

In processor processor/index.js once we receive  DeviceHeartbeatMessage then we can send reply to solo.js subscribe and sub.js subscribe reply.okay("server received heartbeat")

When DeviceReadyMessage -> Then note down channel 
When JoinGroupMessage -> Then note down channel for remote connection 
When DeviceHeartbeatMessage received then -> send reply to both the channel with device serial .

**Comment by denis99999** [comment]
@kotini ,
The system works fine for many years, so I think it is not a good idea to modify the core processing of STF to fit your specific requirements, rather it seems you have a networking issue between your provider and the main processes, perhaps a FW that cuts the connection after a while, or something like that..
I recommend you to look at #528 (and referenced issues) about ZMQ timeouts, from my side I set ZMQ environment variables as follow for all concerned processes:
```
ZMQ_TCP_KEEPALIVE="1"
ZMQ_TCP_KEEPALIVE_IDLE="120"
```

**Comment by koral--** [comment]
@kotini What bigger problem are you trying to solve?

**Comment by kotini** [comment]
@denis99999 @koral-- last code working fine 

ZMQ_TCP_KEEPALIVE="1"
ZMQ_TCP_KEEPALIVE_IDLE="120"
