### ISSUE TITLE
Samsung note 10+ screen is grey

### ISSUE THREAD

**Issue by kapilshra** [openstf/stf#1216]
Hi Team,

Samsung note10+ screen is coming grey on STF. Problem started with new build. It worked with old image without any issue.

List of devices attached
RFCM700R97M            device usb:3-3 product:d2xxx model:SM_N976B device:d2x transport_id:16

Please let me know if you need more information.

Also I found SIM related fields are coming blanks such as IMSI, IMEI and ICCID.
This happening with all mobiles.

Regards
Kapil Sharma

**Comment by koral--** [comment]
Are there any error messages in logs?

**Comment by kapilshra** [comment]
Hi Koral, It seems internet speed is the root cause, S10+ worked once, afterwards speed of internet reduced again. One of our provider is located at residential location. I'll test S10+ at another location. Sorry for bothering. I'll check and post the update.
