### ISSUE TITLE
Getting gateway timeout error while trying to add device to Bookable group.

### ISSUE THREAD

**Issue by imran-abbas1** [openstf/stf#1219]
**What is the issue or idea you have?**
When i try to add any device to bookable group i get a gateway timeout error
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
It happens on every device
**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**
I should be able to add devices in the same way as users are added to the group
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
![timeout](https://user-images.githubusercontent.com/44003067/79824857-e48cb500-83b4-11ea-84a6-d1af2046b0f5.PNG)

**Please run `stf doctor` and paste the output here.**

**Comment by denis99999** [comment]
@imran-abbas1,
You meet a network issue between internal units of STF, perhaps a firewall one.. 
Can you provide complete logs on STF starting and on the adding operation ?
Please run stf doctor also ?
Do you run STF in local mode or in full deployment mode ? On last case, please give me the architecture you are using (i.e. what unit on what machine) ?

**Comment by imran-abbas1** [comment]
@denis99999 thanks for the prompt response.
I am running all the units on a single system using the docker compose command and firewall of  the hosted machine is already disabled. 
I am not not getting any errors in the log.

Although this is what i get while trying to add device in the group.
nginx_1_d8143c2523f3    | 1**.***.**.** - - [22/Apr/2020:05:27:08 +0000] "PUT /api/v1/devices/01b8c0300d5cc4c3/groups/15a2a47a99844e3aabfc14920cb48887 HTTP/1.1" 504 50 "http://***.***.**.***/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"

**Comment by denis99999** [comment]
@imran-abbas1 if you want help, can you provide me the logs as asked, run `stf doctor` as asked also, and provide me your `docker-compose file`, I suspect you made a mistake in that file.
Do you use directly the API or the GUI to add your device to the bookable group ?
Can you also make a test : launch STF in local mode running the command `stf local` and let me know if you encounter the same issue.

**Comment by imran-abbas1** [comment]
@denis99999 I am directly using the **api** to add device to the group.
We are running STF in **docker** and not on local system. While running stf on local mode group functionality isn't visible in UI.

STF version on local:- 3.4.1
here is the screenshot of STF running on local
![stf local](https://user-images.githubusercontent.com/44003067/80094146-63cfe380-8583-11ea-9017-31d06d8c9abf.PNG)

Here is the output of the commands
docker images
docker ps -a

![docker output1](https://user-images.githubusercontent.com/44003067/80093625-70a00780-8582-11ea-89e9-0df5bdfe16f3.png)

![docker output2](https://user-images.githubusercontent.com/44003067/80093663-86153180-8582-11ea-835f-ec56194fda83.png)

Here is the docker-compose.yml file
version: '3'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
  adb:
          image: sorccu/adb:latest
    restart: unless-stopped
    privileged: true
    volumes:


      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 5037:5037
  rethinkdb:
    image: rethinkdb:2.3
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
  app:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf app --auth-url http://${PUBLIC_IP}/auth/mock/ --websocket-url ws://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
  auth:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf auth-mock --app-url http://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
  processor:
     image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
  triproxy:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
  dev-triproxy:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
  migrate:
    image: openstf/stf:latest
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf migrate
    depends_on:
      - rethinkdb
  provider:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://${PUBLIC_IP}/ --public-ip ${PUBLIC_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${PUBLIC_IP}/d/nuc/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp
 reaper:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
  storage-plugin-apk:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-apk --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-plugin-image:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-image --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
  websocket:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf websocket --port 3000 --storage-url http://${PUBLIC_IP}/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
  api:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy

**Comment by denis99999** [comment]
@imran-abbas1,

I see, you have omitted to launch the `groups-engine` unit which is the core of the device booking/partitioning system, look at [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md#stf-groups-engineservice) and eventually details at [GroupFeature.pdf](https://github.com/openstf/stf/tree/master/doc/GroupFeature.pdf) for that, after what it should be run fine!

In short, you have just to add a unit in your `docker-compose.yml` file, something like that in accordance with your configuration:
```
groups-engine:
image: openstf/stf:latest
restart: unless-stopped
environment:
- SECRET
- RETHINKDB_PORT_28015_TCP
command: stf groups-engine --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
depends_on:
- rethinkdb
- ...
```

**Comment by imran-abbas1** [comment]
@denis99999 Thank you the above solutions works for me.
One more thing if you could help me, you ever run parallel tests on STF or you know someone who could help me out with running parallel tests on STF. It would be of great help.
Thanks again !

**Comment by denis99999** [comment]
@imran-abbas1, concerning the testing purpose, I recommend you to post a special issue (question) for that ?

**Comment by imran-abbas1** [comment]
@denis99999 , I will post a new issue for the same. Thanks for your help.

**Comment by imran-abbas1** [comment]
@denis99999 Can you help me out with another issue i am facing.
I was trying to run stf locally but i am not getting any groups functionality in UI. Although my STF version is 3.4.1.

**Comment by denis99999** [comment]
You have to use the latest version from master code, because the archived v3.4.1 version does not include the group feature!

**Comment by imran-abbas1** [comment]
Okay but @denis99999 how to use the latest version because running **npm install -g stf** command will always install v3.4.1.

**Comment by jachstet-sea** [comment]
Yes, as denis99999 already said: There hasn't been a release of STF since that feature was merged to master. Try: `npm install -g https://github.com/openstf/stf.git`. The version number will still be v3.4.1 but the group feature should be in.

**Comment by imran-abbas1** [comment]
okay thanks @jachstet-sea i will try this.
