### ISSUE TITLE
Upgrade to Node 12, node 8 is already deprecated version

### ISSUE THREAD

**Issue by Amrkamel1** [openstf/stf#1221]
**Is your feature request related to a problem?**
it will be great to update the node version in json package as Node 8 is not supported any more and become deprecated version, also many dependencies require node 12 to avoid having some issue such as appium and many others

**Describe the solution you'd like**
Switch to Node12

**Comment by koral--** [comment]
Duplicate of https://github.com/openstf/stf/issues/1134
