### ISSUE TITLE
Help required running parallel test using appium server.

### ISSUE THREAD

**Issue by imran-abbas1** [openstf/stf#1225]
**What is the issue or idea you have?**
I want to run parallel tests using appium server
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

I have STF deployed on the server.
Here is the output i get after trying to run the test
![error output stf parallel test](https://user-images.githubusercontent.com/44003067/80350994-35a61880-888f-11ea-89e5-758162e4f9c2.png)

**Comment by koral--** [comment]
You need to resolve highlighted error:
![image](https://user-images.githubusercontent.com/3340954/80434740-eac1ea80-88fa-11ea-8c57-83fd401b7a8e.png)

AFAIR appium needs separate servers for each device.

**Comment by imran-abbas1** [comment]
@koral-- thanks for the prompt response.
I was trying to run the test parallely on two devices.
On the first device appium settings starts successfully and then the app launches.
This is the log for the first device
![1](https://user-images.githubusercontent.com/44003067/80451217-e3253480-8940-11ea-8c1f-44f0b76faceb.png)
but for the second device i get the error now, i think the error could possible be because of either of the two reasons.
a)- **forwarding system: 8201 to device: 6790** because for the first device also it is **forwarding system: 8200 to device: 6790** or 
b)- **io.appium.settings not installed**
The logs of second device are
![2](https://user-images.githubusercontent.com/44003067/80451463-91c97500-8941-11ea-9006-55e5ae65c386.png)
![3](https://user-images.githubusercontent.com/44003067/80451477-9aba4680-8941-11ea-9bae-c0c50d492c3e.png)
![4](https://user-images.githubusercontent.com/44003067/80451490-a148be00-8941-11ea-8408-8727e6521404.png)
