### ISSUE TITLE
[Query] How to setup OpenSTF to get access over HTTPS (instead of http)

### ISSUE THREAD

**Issue by dewanganajay** [openstf/stf#1227]
[Query] How to setup OpenSTF to get access over HTTPS (instead of http)

Please suggest if there is way do setup OpenSTF with HTTPS? Guidance and steps on which component(s) need to be deployed / changed / updated will help.

Thanks in advance !!

**Comment by jachstet-sea** [comment]
There is quite some documentation and discussions about that topic at https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md and https://github.com/openstf/stf/issues/767

Please search before you ask and ask more specific in case you encounter any problems
