### ISSUE TITLE
 How to get the parameter remoteconnecturl without using STF machine

### ISSUE THREAD

**Issue by wangshaoce** [openstf/stf#1228]
If I use this interface http://192.168.11.197:7100/api/v1/devices/942bbbbd3 to get the remoteconnecturl parameter, I will not be able to get the remoteconnecturl until I control this phone

**Comment by denis99999** [comment]
@wangshaoce ,
Yes, it is a normal behavior.

**Comment by wangshaoce** [comment]
why,and what can i do ?  get the remoteconnecturl  before I control this phone

**Comment by denis99999** [comment]
This URL is dynamically generated and you can't `ADB connect` to the device if it is not under control, so you have first to take control the device using the corresponding API, and after you have to get the remote debug URL to ADB connect to the device (i.e. under control).

**Comment by wangshaoce** [comment]
OK thanks for your answer
