### ISSUE TITLE
How to remove devices no longer used in STF UI?

### ISSUE THREAD

**Issue by marcoantoniomartin** [openstf/stf#123]
Dear all,

I've been exploring and wondering how to remove those devices that we know we'll no longer be using for testing in our STF interfaces. How could we remove their log from the app in order to clear and update the interface with the used and existing devices?

Many thanks,

Marco

**Comment by sorccu** [comment]
Hi,

You have to open the RethinkDB admin UI, usually localhost:8080. Go to the
data explorer and run:

r.db('stf').table('devices').get('SERIAL').delete()

Where SERIAL is the device serial (you can toggle it on in the detailed
device list).

**Comment by marcoantoniomartin** [comment]
Thank you very much, @sorccu ! It worked perfectly. It's amazing to continue learning and developing with this beautiful tools STF is.

**Comment by GJSmith3rd** [comment]
This was very helpful!

**Comment by gfedrigo81** [comment]
hi, I am not familiar with the tool.
Can you please explain what I need to do step by step to be able to open the RethinkDB admin UI?
Thank you.
