### ISSUE TITLE
Device List's "Notes" Feature

### ISSUE THREAD

**Issue by vbanthia** [openstf/stf#124]
Device List has a "Notes" column. I don't know what was the real intention behind this feature, but I can say it will be good to write notes or remarks for a device. 

Currently, it is only ReadOnly and there is no way to update this from STF UI. Only way is to update DB directly.

Can you tell me what was the real intention behind this column? And is there any plan to make it editable?

**Comment by sorccu** [comment]
We just modify the DB directly since RethinkDB is pretty easy to use and
the notes almost never change. It will become editable if someone
implements it, personally I don't have time for it right now.

The original intention was to show which ones of our devices had
carrier billing accounts available.

**Comment by ma3tk** [comment]
Hi. I use this column as the place where I put the device in real.
I wrote how to update using RQL and you can use it if you needed.

Go to your Rethinkdb Admin Tool -> Data Explorer -> Run below RQL.
# Change your own model and notes as you like!
# if you have same model, change the filter

```
r.do(
  r.db("stf").table("devices").filter({model: "SC-02C"}).update({"notes": "A1"}),
  r.db("stf").table("devices").filter({model: "SC-05G"}).update({"notes": "A2"}),
  r.db("stf").table("devices").filter({model: "SC-06D"}).update({"notes": "A3"}),
  r.db("stf").table("devices").filter({model: "Nexus 7"}).update({"notes": "B1"})
)
```

**Comment by vbanthia** [comment]
In my case, I don't want to give users direct DB access thats why I was looking for some way to edit it from STF UI itself.

BTW, instead of using filters, you should use primaryKey to access the device which is device serial for devices table (https://github.com/openstf/stf/blob/master/lib/db/tables.js#L29). 

```
r.db("stf").table("devices").get('DEVICE_SERIAL').update({notes: "A1"})
```

**Comment by ma3tk** [comment]
ah, i could understand well. thank you for your nice filter. :+1:

**Comment by vbanthia** [comment]
Pull request regarding this feature - https://github.com/openstf/stf/pull/147
