### ISSUE TITLE
Is there any way to remotely connect and monitor the device from a different network (without USB)?

### ISSUE THREAD

**Issue by imran-abbas1** [openstf/stf#1245]
**What is the issue or idea you have?**
I want to remotely connect and monitor the device from a different network (without USB).
Adb requires to connect the device atleast once via usb. Is there any other way to achieve the same without connecting device via usb?
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by koral--** [comment]
Such feature has been officially added in Android 11: https://android-developers.googleblog.com/2020/04/android-11-developer-preview-3.html

Apart from that some manufacturers add option like "Wireless debugging" to their ROMs even on older versions. So in such case you can just enable it.
Of course you need to ensure network connectivity eg. forward appropriate ports.

If there is no such option in settings (and you don't want to root your device) there is no solution completely without USB.
