### ISSUE TITLE
I set the login type is google auth, how to login with admin?

### ISSUE THREAD

**Issue by luoxi001713** [openstf/stf#1249]
Now I can only use my google account to login, but it doesn't have admin permission. I want to use the group to book devices, but found all devices are in the Common group and can't see this group in my google login account.

So I guess this is a permission issue, how to login by admin?

Thanks

**Comment by koral--** [comment]
You can change your account type directly in Rethinkdb console.

**Comment by denis99999** [comment]
Hi @luoxi001713 ,
To get admin role, you have to login with admin credentials, normally you have specified these information at STF database creation step (cf. section `Running` of `README.md` or `doc/GroupFeature.pdf`), if not and if default credentials does not fit your requirements, you have to re-create the STF database providing the expecting information.

**Comment by denis99999** [comment]
> 
> 
> You can change your account type directly in Rethinkdb console.

I feel it is not recommended to do that because the built-in admin user may be referenced by other objects as Groups, Access Tokens and Devices, and it may lead to inconsistency, so in such situation it is highly recommended to re-create the STF database providing the expecting information.

**Comment by luoxi001713** [comment]
> > You can change your account type directly in Rethinkdb console.
> 
> I feel it is not recommended to do that because the built-in admin user may be referenced by other objects as Groups, Access Tokens and Devices, and it may lead to inconsistency, so in such situation it is highly recommended to re-create the STF database providing the expecting information.

@denis99999 thank you very much, it is really helpful.
