### ISSUE TITLE
Can't move devices from Common group

### ISSUE THREAD

**Issue by luoxi001713** [openstf/stf#1250]
When I connected 2 devices(simulator), the default group is Common group. I want move them from Common group, so it can be added to other group and to use the set schedule function. 

But can't delete it, see the picture, how to do it?
<img width="880" alt="728ED67B-63C6-4531-8B7A-7C2C0D31F3EA" src="https://user-images.githubusercontent.com/18004375/86377620-20000580-bcbb-11ea-8135-835168fd3577.png">

**Comment by koral--** [comment]
Open the second (not Common) group and then add devices to it.
![image](https://user-images.githubusercontent.com/3340954/86380830-db5d7580-bc8c-11ea-8b8a-7deebb9e3f09.png)

**Comment by luoxi001713** [comment]
> Open the second (not Common) group and then add devices to it.
> ![image](https://user-images.githubusercontent.com/3340954/86380830-db5d7580-bc8c-11ea-8b8a-7deebb9e3f09.png)

@koral-- 
I opened another, but there is no available devices, see the whole screen.
<img width="1651" alt="Screenshot 2020-07-03 at 12 02 39 AM" src="https://user-images.githubusercontent.com/18004375/86383557-c00c5d80-bcc0-11ea-98fe-36eb9c676c95.png">

**Comment by denis99999** [comment]
@luoxi001713 ,
@koral-- is right, you have to create (i.e. as admin role) a `bookable` group (i.e. partitioning action) and not a transient group (i.e. `once `class) as shown in your picture, after what you will be able to add devices to this `bookable `group, and once it is done you will be able to make a reservation using your `once `group or another transient group.
All that is explained in detail in the documentation provided on Group feature (i.e. `doc/GroupFeature.pdf`), in particular at section 5 where a full example is done, so I recommended you to read it carefully before to play with the Group feature.

**Comment by luoxi001713** [comment]
> @luoxi001713 ,
> @koral-- is right, you have to create (i.e. as admin role) a `bookable` group (i.e. partitioning action) and not a transient group (i.e. `once `class) as shown in your picture, after what you will be able to add devices to this `bookable `group, and once it is done you will be able to make a reservation using your `once `group or another transient group.
> All that is explained in detail in the documentation provided on Group feature (i.e. `doc/GroupFeature.pdf`), in particular at section 5 where a full example is done, so I recommended you to read it carefully before to play with the Group feature.

Thanks @denis99999, it works now.
