### ISSUE TITLE
Can I get the devices' real time state from rethinkdb ?

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#131]
Dear all:

I try to use STF in my platform, I want to read the devices' state from rethinkdb real time, and parse the device's serial, then jump to the phone control page directly.

The state i want to get is :
1. when the device is disconnected
2. when the device is connected, but preparing STF service
3. when the device is connected, but being used
4. when the device is connected, and is free

But i don't know which field ?
```json
{
"abi":  "armeabi-v7a" ,
"airplaneMode": false ,
"battery": {
"health":  "good" ,
"level": 82 ,
"scale": 100 ,
"source":  "unknown_0" ,
"status":  "discharging" ,
"temp": 30 ,
"voltage": 3.967
} ,
"browser": {
"apps": [
{
"id":  "com.baidu.browser.inter/.BrowserActivity" ,
"name":  "Baidu" ,
"selected": false ,
"system": false ,
"type":  "baidu"
} ,
{
"id":  "com.google.android.browser/com.android.browser.BrowserActivity" ,
"name":  "Browser" ,
"selected": false ,
"system": true ,
"type":  "google-android-browser"
} ,
{
"id":  "com.opera.browser/com.opera.Opera" ,
"name":  "Opera" ,
"selected": false ,
"system": false ,
"type":  "opera"
} ,
{
"id":  "com.opera.mini.android/.Browser" ,
"name":  "Opera Mini" ,
"selected": false ,
"system": false ,
"type":  "opera-mini"
} ,
{
"id":  "com.opera.mini.native/com.opera.mini.android.Browser" ,
"name":  "Opera Mini" ,
"selected": false ,
"system": false ,
"type":  "opera-mini-native"
} ,
{
"id":  "com.UCMobile.intl/com.UCMobile.main.UCMobile" ,
"name":  "UC" ,
"selected": false ,
"system": false ,
"type":  "uc"
}
] ,
"selected": false
} ,
"channel":  "ELxYMOBOrR/NMj9TSalbkYBqjJg=" ,
"createdAt": Thu Oct 15 2015 07:46:31 GMT+00:00 ,
"display": {
"density": 2 ,
"fps": 58.98100280761719 ,
"height": 1280 ,
"id": 0 ,
"rotation": 0 ,
"secure": true ,
"size": 4.619571685791016 ,
"url":  "ws://172.18.182.19:7404" ,
"width": 720 ,
"xdpi": 315.3103332519531 ,
"ydpi": 318.7450866699219
} ,
"manufacturer":  "SAMSUNG" ,
"model":  "Galaxy Nexus" ,
"network": {
"connected": true ,
"failover": false ,
"roaming": false ,
"subtype":  "" ,
"type":  "WIFI"
} ,
"operator": null ,
"owner": null ,
"phone": {
"iccid": null ,
"imei":  "351554052641959" ,
"network":  "HSDPA" ,
"phoneNumber": null
} ,
"platform":  "Android" ,
"presenceChangedAt": Thu Oct 15 2015 08:59:31 GMT+00:00 ,
"present": false ,
"product":  "yakju" ,
"provider": {
"channel":  "6chwLcCuQj6VHvyoMYmHlQ==" ,
"name":  "liufuxindeMacBook-Pro.local"
} ,
"ready": true ,
"reverseForwards": [ ],
"sdk":  "18" ,
"serial":  "172.18.176.103:5555" ,
"status": 3 ,
"statusChangedAt": Thu Oct 15 2015 08:09:58 GMT+00:00 ,
"version":  "4.3"
}
```

**Comment by sorccu** [comment]
I'm not completely sure what you mean, but if you're using a remote device, the remote address *is* the serial as far as ADB/STF are concerned. So, in your case it would be `"172.18.176.103:5555"`.

By the way using remote devices with STF is not recommended. The ADB remote protocol is very slow, it will be many times slower than just using USB directly.

**Comment by LiufxLucky365** [comment]
I have another platform, and I want to display the devices' state which are connected to STF in my platform, and users can choose the device which can be used, and jump to the STF's control page directly.

But, the problem is, when i read the device from rethinkdb the STF use, I find i can't know which device is connected and which can be used.

Thanks. I have no choice, but using a remote device, perhaps the device number is about 400.

**Comment by sorccu** [comment]
Ok, well, knowing that is actually kind of tricky... it's because there are several independent components that update the device information, and whether a device is usable or not depends on several different pieces of information. The only parts in the system that know the full state of a device are a) the client browser, and b) the device worker itself. So, you have to implement the same logic in your system.

The logic is here: https://github.com/openstf/stf/blob/master/res/app/components/stf/device/device-service.js#L56

**Comment by LiufxLucky365** [comment]
That code run in server ? I insert some debug code like:
```javascript
function sync(data) {
      console.log('+++++++++++++++++++++++++++++++');
      // usable IF device is physically present AND device is online AND
      // preparations are ready AND the device has no owner or we are the
      // owner
      data.usable = data.present && data.status === 3 && data.ready &&
        (!data.owner || data.using)

      // Make sure we don't mistakenly think we still have the device
      if (!data.usable || !data.owner) {
        data.using = false
      }

      EnhanceDeviceService.enhance(data)
    }
```
but i have not seen any output in my server console.

when do the function sync run ?

Thanks again.

**Comment by sorccu** [comment]
No. Everything inside the `res` folder runs on the client side only.

**Comment by LiufxLucky365** [comment]
i find what i need from the console output:
```shell
INF/provider 3444 [*] Found device "172.18.176.138:5555" (offline)
INF/provider 3444 [*] Registered device "172.18.176.138:5555"
INF/reaper 3443 [reaper001] Device "172.18.176.138:5555" is present
INF/provider 3444 [*] Device "172.18.176.138:5555" is now "device" (was "offline")
INF/device:support:push 3463 [172.18.176.138:5555] Sending output to "tcp://127.0.0.1:7116"
INF/device 3463 [172.18.176.138:5555] Preparing device
INF/device:support:sub 3463 [172.18.176.138:5555] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 3463 [172.18.176.138:5555] Subscribing to permanent channel "*ALL"
INF/device:support:properties 3463 [172.18.176.138:5555] Loading properties
INF/device:support:abi 3463 [172.18.176.138:5555] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 3463 [172.18.176.138:5555] Checking whether we need to install STFService
INF/device:resources:service 3463 [172.18.176.138:5555] Running version check
INF/device:resources:service 3463 [172.18.176.138:5555] STFService up to date
INF/device:plugins:service 3463 [172.18.176.138:5555] Launching agent
INF/device:plugins:service 3463 [172.18.176.138:5555] Launching service
INF/device:plugins:service 3463 [172.18.176.138:5555] Agent says: "Listening on port 1090"
INF/device:plugins:service 3463 [172.18.176.138:5555] Agent says: "InputClient started"
INF/device:plugins:display 3463 [172.18.176.138:5555] Reading display info
INF/device:plugins:phone 3463 [172.18.176.138:5555] Fetching phone info
INF/device:plugins:identity 3463 [172.18.176.138:5555] Solving identity
INF/device:plugins:solo 3463 [172.18.176.138:5555] Subscribing to permanent channel "x/7BGbNJ2M+jTdnf9l9ehmN2x4E="
INF/device:plugins:screen:stream 3463 [172.18.176.138:5555] Starting WebSocket server on port 7400
INF/device:plugins:browser 3463 [172.18.176.138:5555] Loading browser list
INF/device:plugins:browser 3463 [172.18.176.138:5555] Updating browser list
WRN/device:plugins:browser 3463 [172.18.176.138:5555] Unmapped browser "com.snda.wifilocating"
WRN/device:plugins:browser 3463 [172.18.176.138:5555] Unmapped browser "com.baidu.searchbox"
INF/device:plugins:mute 3463 [172.18.176.138:5555] Will not mute master volume during use
WRN/device:plugins:data 3463 [172.18.176.138:5555] Unable to find device data { serial: '172.18.176.138:5555',
```
I can see the new device's life cycle. So i think i can insert hook code in the nodejs's server side, write these in a db, so i can share the devices' state with my platform. Do you think this plan can be realized ?

Do you have another better ? 

sorry for disturb you so much....

**Comment by sorccu** [comment]
Why can you not just use the code I linked? All the parameters (except
"using") are available in the database...

**Comment by LiufxLucky365** [comment]
Can you describe more detail ? I just try some ways, but i don't know when and where the function sync execute.

I have not used nodejs before, please forgive my stupid question.

**Comment by sorccu** [comment]
The JSON you posted contains the `present`, `status`, `ready` and `owner` fields. You can therefore do the equivalent of  `data.usable = data.present && data.status === 3 && data.ready && (!data.owner || data.using)` in your own code, in any language (although you'll have to remove the "using" condition since there's no property for it).

**Comment by LiufxLucky365** [comment]
The JSON i posted ? i think your mean is that i insert some code into the function sync, so when the client side sync the device state to the server, it also sync the state to my own platform. is it right ?

can you tell me when the function sync execute ?

**Comment by sorccu** [comment]
Just read the data from the database like you did earlier. You can use
RethinkDB changefeeds (https://rethinkdb.com/docs/changefeeds/javascript/)
to watch for updates in realtime.

**Comment by LiufxLucky365** [comment]
Yes ! Perfect, this is what i really want. I understand what you mean. Thank you so much !

owner   : 'not null' if device has been used;
ready    : false if device is preparing ( may installing STF);
present : i see it always true...is it right ?
status   : i see it always 3

do i describe right ?

**Comment by sorccu** [comment]
* `owner` is null when no one is using a device, otherwise an object describing the owner
* `ready` is true if STF has finished initializing the device (i.e. when you see the "Fully operational" message in the logs)
* `present` is supposed to be true if the device is physically connected to the system. HOWEVER, it can also be false if a device stops sending a heartbeat message to the system for some reason (like process death) even if the device is still physically connected. For example, if a device shuts down, it will still be physically connected but the system won't know about it, so it'll have `present: false`. If the system starts receiving heartbeat messages from that device again, then it's set to `present: true` again.
* `status` is one of https://github.com/openstf/stf/blob/master/lib/wire/wire.proto#L159. `OFFLINE` is different from `present`, if a device is `OFFLINE` it means that it usually means that the ADB connection is either still being initialized or could not be established. If a device stays `OFFLINE` for a long time, it usually means that the system doesn't have enough resources to handle that many USB devices, or that there is not enough power available.

**Comment by LiufxLucky365** [comment]
Thanks, you are a so nice man. Thanks for your help, thanks.
