### ISSUE TITLE
Anybody who knows how to set the JWT secret ?

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#137]
I check the code and i need to set my own JWT token, but i don't know where to get the STF's secret or set my own secret.

the code is here
https://github.com/openstf/stf/blob/master/lib/units/app/middleware/auth.js#L10

**Comment by sorccu** [comment]
Check `stf local --help` and `stf auth-mock --help`.

**Comment by LiufxLucky365** [comment]
thanks, i use wrong option before
