### ISSUE TITLE
Can't controll device disconnected status 

### ISSUE THREAD

**Issue by rocketb** [openstf/stf#140]
Hello, I'm having some trouble connecting to the device, when i plug it i see only gray picture of device and disconnected status. Every new device I connect will displays as disconnected.

![mage of stf-app](https://cloud.githubusercontent.com/assets/1926748/10632581/0bbd252e-77ee-11e5-92ce-3b800d3c042c.png)
harlog - https://gist.github.com/rocketb/4ebfedf5b31c4d29c850

Provider log - https://gist.github.com/rocketb/f4c589248859d971e6d6

In my configuration I have 2 machines, one with rethinkdb and second with app, running all services, webserver, stf-provider, adbd

App machine have openned ports 80, 3000-3600, 15000-15100

Where could be a problem and how can I find it?

**Comment by rocketb** [comment]
Close, bad config.

**Comment by ckJIag** [comment]
Please, can you specify where was the problem? I'm currently in the same situation (although I'm connected to devices with adb via custom open-vpn tunnel). Many thanks.
