### ISSUE TITLE
No English word shown in my Chrome when STF is running on my windows 7 only Japaneses

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#144]
I am running STF locally on my Windows 7 and linked to remote rethinkdb on other Linux VM. Everything works fine except no English word shown in Chrome. But when I set it to Japanese or Russian, it shows properly. Could you please give me some hints about solving this problem? I am thinking if it relates to Jade. Thanks.

**Comment by Tierney0115** [comment]
Does anyone try to connect STF from Chrome on Win 7? I got no English Support only Japanese and Russian. And also I got nothing shown from IE on Win 7. Local Linux Firefox could work. I start STF by using: stf local --public-ip xxx on my Linux and try to connect it from other Win 7. Thanks.

**Comment by gunta** [comment]
Cannot reproduce.

Tried with:
- Windows 7 (Version 6.1.7601)
- Chrome 46.0.2490.80 m (Latest)
- IE 10.0.9200

On Chrome I was able to see English or any language without problems. 
IE also worked (at least the device list works fine; controlling the device has a bug so it doesn't).

Can you post a screenshot? Is your Windows edition special or somehow have some different font settings? Do you have an `adblocker`?
Try with disabling all the extensions in Chrome.

**Comment by Tierney0115** [comment]
Thank you for your reply.

My environment is Windows 7 (Version 6.1.7601) with  Chrome 43.0.2357.132

By the way the system is running on a virtual machine, I think it relates to the problem since my PC with Windows works fine also. 

I am sorry for the inconvenient that I cannot upload screenshot since I am in company network. The browser just cannot show all the English words, but other pictures and functions just works fine.

Thanks.

**Comment by vbanthia** [comment]
One of my colleague also had the same problem in his windows machine, I don't know his environment details. But he fixed this problem by enabling DirectWrite flag for chrome.

These are the instructions to enable DirectWrite flag. http://www.tekrevue.com/tip/chrome-font-rendering-windows/

**Comment by gunta** [comment]
Couldn't reproduce with neither toggling DirectWrite nor ClearType on Windows 7.
It could be the GPU, GPU drivers or ad-blocking.

@Tierney0115 can you try disabling all Chrome extensions?

**Comment by Tierney0115** [comment]
@vbanthia Thank for your help. But it still can not fix the bug.
@gunta I have tried to disabled all extensions but still not work. Thanks anyway. The Firefox works fine in my environment. It should be caused by some setting problems of my Chrome.

**Comment by Tierney0115** [comment]
I finally figured it out. Deleted the Lato from font-family worked for me. Thanks all.

**Comment by gunta** [comment]
@Tierney0115 did you deleted Lato from the CSS or from your system fonts?

**Comment by Tierney0115** [comment]
@gunta Yes. Sorry for the delay reply

**Comment by gunta** [comment]
@Tierney0115 which one? CSS or system fonts?
