### ISSUE TITLE
How to setup development environment

### ISSUE THREAD

**Issue by Pushkaa** [openstf/stf#145]
Hi,

We would like to know how to setup a development environment.
We searched in your documentations and didn't find how to run STF from the source code.
How can we modify the source code and deploy the changes?

Thanks.

**Comment by sorccu** [comment]
It's in the README. Just clone the repo and start from https://github.com/openstf/stf#building.

**Comment by Pushkaa** [comment]
Thanks, we had an error during the npm install and we missed it.
