### ISSUE TITLE
localhost:7404 Blank webpage

### ISSUE THREAD

**Issue by hemant4524** [openstf/stf#150]
When i run this http://localhost:7404 url in my mac- chrome browser, blank web page display.

Log
INF/provider 8654 [*] Device "23b11e90" is now "device" (was "offline")
INF/device:support:push 9317 [23b11e90] Sending output to "tcp://127.0.0.1:7116"
INF/device 9317 [23b11e90] Preparing device
INF/device:support:sub 9317 [23b11e90] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 9317 [23b11e90] Subscribing to permanent channel "*ALL"
INF/device:support:properties 9317 [23b11e90] Loading properties
INF/device:support:abi 9317 [23b11e90] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 9317 [23b11e90] Checking whether we need to install STFService
INF/device:resources:service 9317 [23b11e90] Running version check
INF/device:resources:service 9317 [23b11e90] STFService up to date
INF/device:plugins:service 9317 [23b11e90] Launching agent
INF/device:plugins:service 9317 [23b11e90] Launching service
INF/device:plugins:service 9317 [23b11e90] Agent says: "Listening on port 1090"
INF/device:plugins:service 9317 [23b11e90] Agent says: "InputClient started"
INF/provider 8654 [*] Providing 2 of 1 device(s); waiting for "23b11e90"
INF/device:plugins:display 9317 [23b11e90] Reading display info
INF/device:plugins:phone 9317 [23b11e90] Fetching phone info
INF/device:plugins:identity 9317 [23b11e90] Solving identity
INF/device:plugins:solo 9317 [23b11e90] Subscribing to permanent channel "e8eKWom6kdFoDU+xSlbBFomw/N8="
INF/device:plugins:screen:stream 9317 [23b11e90] Starting WebSocket server on port 7408
WRN/device:plugins:data 9317 [23b11e90] Unable to find device data { serial: '23b11e90',
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  operator: null,
  model: 'GT-S7562',
  version: '4.0.4',
  abi: 'armeabi-v7a',
  sdk: '15',
  product: 'kylexx',
  display: 
   { id: 0,
     width: 480,
     height: 800,
     xdpi: 239.06,
     ydpi: 236.28,
     size: 3.94,
     density: 1.5,
     fps: 60,
     secure: false,
     rotation: 0,
     url: 'ws://localhost:7408' },
  phone: { imei: '--------', network: 'UNKNOWN' } }
INF/device:plugins:touch 9317 [23b11e90] Touch origin is top left
INF/device:plugins:touch 9317 [23b11e90] Requesting touch consumer to start
INF/device:plugins:touch 9317 [23b11e90] Launching screen service
INF/device:plugins:touch 9317 [23b11e90] Connecting to minitouch service
INF/device:plugins:touch 9317 [23b11e90] minitouch says: "Type B touch device sec_touchscreen (480x800 with 5 contacts) detected on /dev/input/event0 (score 1100)"
INF/device:plugins:touch 9317 [23b11e90] minitouch says: "Connection established"
INF/device:plugins:touch 9317 [23b11e90] Reading minitouch banner
INF/device:plugins:vnc 9317 [23b11e90] Starting VNC server on port 7410
INF/device:plugins:browser 9317 [23b11e90] Loading browser list
INF/device:plugins:browser 9317 [23b11e90] Updating browser list
WRN/device:plugins:browser 9317 [23b11e90] Unmapped browser "devian.tubemate.home"
INF/device:plugins:mute 9317 [23b11e90] Will not mute master volume during use
INF/device:plugins:forward 9317 [23b11e90] Launching reverse port forwarding service
INF/device:plugins:forward 9317 [23b11e90] Connecting to reverse port forwarding service
INF/device:plugins:connect 9317 [23b11e90] Listening on port 7409
INF/device 9317 [23b11e90] Fully operational
INF/provider 8654 [*] Providing all 1 device(s)

**Comment by sorccu** [comment]
That's because the URL is http://localhost:7100 just like the README says.

**Comment by hemant4524** [comment]
Same issue with this url http://localhost:7100/auth/mock/

**Comment by sorccu** [comment]
Are you following the README exactly? If not, you need to post every single command you ran, starting from `git clone`, or we can't help.

**Comment by hemant4524** [comment]
Yes i followed all instruction from README.

**Comment by hemant4524** [comment]
If you want some log report from me i'll provide you.

**Comment by hemant4524** [comment]
Now working fine i followed all steps from REDME

**Comment by sorccu** [comment]
Great!

**Comment by pahnpiseth** [comment]
@hemant4524  please tell me,how to fix it...

**Comment by tulasikrishan89** [comment]
same issue http://localhost:7100/auth/mock/ is BLANK

**Comment by thinkhy** [comment]
@tulasikrishan89 How did you deploy STF on server?

**Comment by tulasikrishan89** [comment]
@thinkhy the issue was resolved. Downgraded the node to @8,
I am not running on the server yet our company blocked the default sft ports, need to find a solution
