### ISSUE TITLE
How can i alter the STF UI ?

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#152]
I want to update the STF UI Theme, hide some button or some useless module for me. But when i change some jade file, and restart STF, i found it doesn't work. 

What's more, does STF use some build tool? i see the build directory, how to rebuild STF?

Thanks

**Comment by gunta** [comment]
We're using webpack and gulp for building.

First run `gulp clean` to get rid of the `build` directory.

After that, just running `stf local` will take care of rebuilding on the fly any front-end asset with webpack.

**Comment by LiufxLucky365** [comment]
I haven't used this two tools before, i install gulp through `npm install gulp` and in the stf derctory run common `gulp clean`, it reports this error
![image](https://cloud.githubusercontent.com/assets/3864063/10836824/26339644-7eed-11e5-970f-0d5160f50ca8.png)

**Comment by gunta** [comment]
@LiufxLucky365 if you want to develop you're supposed to use code from github, not from npm.
Grab your stf from https://github.com/openstf/stf.git

**Comment by LiufxLucky365** [comment]
yes, your answer is helpful for me, thank you.

But when i run `gulp clean`, report many module miss error, now i just `npm install` them one by one. I think there must be some auto install scripts?
