### ISSUE TITLE
Screenshot button press disconnect stf server connection.

### ISSUE THREAD

**Issue by hemant4524** [openstf/stf#156]
When i press screenshot button press disconnect stf server connection.

Logs:
 Capturing screenshot
INF/storage:temp 3724 [*] Uploaded "591ed406.jpg" to "/var/folders/_2/gtz250tn4ql569c0y733t8tc0000gn/T/upload_be05e340923862c495043ede59fd8e75"
INF/device:support:storage 3728 [591ed406] Uploaded to "/s/image/6bc210e8-fd35-4333-b1e2-a2cfcd8ed991/591ed406.jpg"
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn gm ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
ERR/poorxy 3727 [*] Proxy had an error Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
FTL/cli:local 3713 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/software/Downloads/DeviceTest/stf-master/lib/util/procutil.js:49:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
INF/cli:local 3713 [*] Shutting down all child processes
INF/util:lifecycle 3715 [app001] Winding down for graceful exit
INF/util:lifecycle 3716 [dev001] Winding down for graceful exit
INF/util:lifecycle 3717 [proc001] Winding down for graceful exit
INF/util:lifecycle 3718 [proc002] Winding down for graceful exit
INF/util:lifecycle 3719 [reaper001] Winding down for graceful exit
INF/util:lifecycle 3723 [*] Winding down for graceful exit
INF/util:lifecycle 3720 [*] Winding down for graceful exit
INF/util:lifecycle 3721 [*] Winding down for graceful exit
INF/auth-mock 3721 [*] Waiting for client connections to end
INF/util:lifecycle 3722 [*] Winding down for graceful exit
INF/provider 3720 [*] Gracefully killing device worker "591ed406"
INF/util:lifecycle 3728 [591ed406] Winding down for graceful exit
INF/device:plugins:screen:stream 3728 [591ed406] Requesting frame producer to stop
WRN/db 3717 [proc001] Connection closed
INF/device:plugins:screen:stream 3728 [591ed406] Disconnecting from minicap service
WRN/db 3718 [proc002] Connection closed
INF/db 3717 [proc001] Connecting to 127.0.0.1:28015
INF/db 3718 [proc002] Connecting to 127.0.0.1:28015
WRN/db 3719 [reaper001] Connection closed
INF/db 3719 [reaper001] Connecting to 127.0.0.1:28015
IMP/device:plugins:group 3728 [591ed406] No longer owned by "hpatel@yopmail.com"
INF/device:plugins:group 3728 [591ed406] Unsubscribing from group channel "vb79K3IVRUubV2CtbBAl1A=="
WRN/db 3723 [*] Connection closed
INF/db 3723 [*] Connecting to 127.0.0.1:28015
INF/provider 3720 [*] Device worker "591ed406" stopped cleanly
INF/provider 3720 [*] Device worker "591ed406" has retired

**Comment by sorccu** [comment]
People always ask this, it's because you don't have GraphicsMagick
installed, or it's not in your PATH.

**Comment by hemant4524** [comment]
I install GraphicsMagick and image capture successfully but image is broken can't open in browser.

**Comment by sorccu** [comment]
Yeah, but if you get the `Error: spawn gm ENOENT` error it means GraphicsMagick is not installed. Otherwise it works fine, there has never been any other reason for broken images yet.

**Comment by hemant4524** [comment]
I put GraphicsMagick version
softwares-iMac-2:platform-tools software$ gm version
GraphicsMagick 1.3.22 2015-10-04 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2015 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 no
  Ghostscript (Library)    no
  JBIG                     no
  JPEG-2000                no
  JPEG                     no
  Little CMS               no
  Loadable Modules         no
  OpenMP                   no
  PNG                      no
  TIFF                     no
  TRIO                     no
  UMEM                     no
  WebP                     no
  WMF                      no
  X11                      no
  XML                      yes
  ZLIB                     yes

Host type: x86_64-apple-darwin15.0.0

Configured using the command:
  ./configure 

Final Build Parameters:
  CC       = gcc
  CFLAGS   = -g -O2 -Wall -D_THREAD_SAFE
  CPPFLAGS = -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2
  CXX      = g++
  CXXFLAGS = -D_THREAD_SAFE
  LDFLAGS  = -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib
  LIBS     = -lbz2 -lxml2 -lz -lm -lpthread

**Comment by hemant4524** [comment]
Physical location of screenshots file in mac?

**Comment by vbanthia** [comment]
Closing this issue as this is not the problem of this project. If you follow the README and install all the dependencies as per instructions, screenshot feature should be working properly.
