### ISSUE TITLE
error: missing required argument `--screen-port'

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#164]
my device sometimes does not work and the server gives the following message, util i restart stf . anybody can give me a hand?

INF/device:plugins:service 28177 [030b337e215f78a6] Launching service
FTL/device:plugins:service 28177 [030b337e215f78a6] Service connection could not be relaunched Error: Service had an error: "Error type 2"
    at /root/stf/stf/lib/units/device/plugins/service.js:155:23
From previous event:
    at /root/stf/stf/lib/units/device/plugins/service.js:130:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at callService (/root/stf/stf/lib/units/device/plugins/service.js:124:10)
    at openService (/root/stf/stf/lib/units/device/plugins/service.js:172:14)
    at Socket.endListener (/root/stf/stf/lib/units/device/plugins/service.js:195:9)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 28177 [030b337e215f78a6] Shutting down due to fatal error
INF/provider 28011 [*] Cleaning up device worker "030b337e215f78a6"
ERR/provider 28011 [*] Device worker "030b337e215f78a6" died with code 1
INF/provider 28011 [*] Restarting device worker "030b337e215f78a6"

  error: missing required argument `--screen-port'

**Comment by sorccu** [comment]
This should be fixed in the master branch. See #138 for details.

**Comment by channingbreeze** [comment]
thank you very much!

**Comment by deshak9** [comment]
I was also tackling with similar kind of issue for send grid.

I got it worked by adding following header.

"Content-Type": "application/json; charset=utf8"
