### ISSUE TITLE
Remote debugging from IntelliJ IDE is really slow

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#178]
I used IntelliJ to connect to the phone which is plugging in other computer which is running STF locally with public IP. 
All debugging processes are slow including loading frames, loading variables and loading the Threads. Every step into or  step over hit will take about 5-6 seconds to load data.
Do you have any clue about which part limit the speed of remote debugging? It is very smooth to debug APP locally with real phone.
Thanks.

**Comment by channingbreeze** [comment]
Same with Eclipse debugging

**Comment by sorccu** [comment]
Merging to openstf/adbkit#41.
