### ISSUE TITLE
Git clone?

### ISSUE THREAD

**Issue by Azusanya** [openstf/stf#18]
![bug](https://cloud.githubusercontent.com/assets/13414843/8785019/79afa4ce-2f57-11e5-966d-c9f2179ac1d9.png)  

I'm a rookie and I don't know what's wrong. Wish you could tell me how to fix it. 
Thank you.

**Comment by Azusanya** [comment]
![2](https://cloud.githubusercontent.com/assets/13414843/8785156/506c352c-2f58-11e5-80fe-6ff3b442c195.png)

**Comment by gunta** [comment]
Hi!

STF is supposed to run in a server (Linux or Mac).

We don't support installation in Windows, sorry. I have just updated `package.json` to reflect that.

Once you get STF installed in a server, you will be able to access that server from your Windows machines without any problem (even from Internet Explorer).

**Comment by sorccu** [comment]
I don't think blacklisting w32 is fair. Although we never tried it, it might work via cygwin as long as you're determined enough to get everything necessary installed. I reverted the commit and put a small reminder about Windows to the installation docs.

**Comment by sorccu** [comment]
@Azusanya We don't provide Windows support, but the error looks like you don't have Git installed (or it's unable to find it for some reason).
