### ISSUE TITLE
Screen is black when connect  to a Visual Machine

### ISSUE THREAD

**Issue by tongtong301** [openstf/stf#181]
When I using "adb connect“ to a Visual Studio Emulator for Android,the micap,minitouch can be installed and run, and when I slide,the emulator slide normal, but the screen on the dashborad is always black.
Can you tell me the reason?If I use Genymotion,will it work?
Thx.

**Comment by sorccu** [comment]
No, STF isn't designed to work with emulators. It's because they don't use
SurfaceFlinger for rendering like real devices. It might be possible to
make some emulators work, but I don't think it's worth the time and effort.

If you have a compelling use case, feel free to let us know.
