### ISSUE TITLE
Docker image building problem

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#182]
If I change the source code. Can I just create my own docker image by running 'docker build -t myname/stf:dev .' based on your Dockfile? 

Thanks.

**Comment by vbanthia** [comment]
Theoretically it should work until and unless you are not adding a new OS level dependency and using latest kernels and docker.

You may get npm installation error sometime in that case just try rebuilding.

If you not able to build image by your own then you can also use cloud services to build docker image such as docker hub.
