### ISSUE TITLE
Frame freezes when a screenshot is taken.

### ISSUE THREAD

**Issue by FelixHahn** [openstf/stf#184]
Hi,

at first, I'am writing my master thesis about remote controlling a smartphone for a german automotive company and we're amazed how capable your solution is compared to the other solutions there are considering they all cost a lot of money.
Especially your capabilities for manual testing! They are miles better then every solution I looked into. Maybe we are missing one or two features but the rest ist amazing. It could happen that we will try to develop them in house and we are willing to share them with you. Right now I'am evaluating this scenario and calculating the possible costs for one or two small features and a big feature like Appium integration or iOS support. I wil discuss my results with my higher ups and can give you a feedback if you want to.

Right now we're testing your solution with serveral employees who are doing manuel application test for one of our costumers. We got a very postive feedback. 

But there is one big issue. I don't know if it's a problem with our hubs (the plugable hubs are ordered) or if it's a bug:

Every time we want to take a screenshot with "right click" on the screen and "Save Screenshot" the screen freezes and we must refresh the page to control the smartphone again. Is it a known bug or is it a problem on our configuration. 

We're running STF on a ubuntu server on a ESXi host with stf version 1.0.10.
I can't see any errors in the server logs.

Oh and I actually talked to the CTO of Testobject and he mentioned he was/is in touch with you guys. For more information we may write a personal message.

Thank you for your amazing work and your help!

Kind regards

Felix Hahn

**Comment by vbanthia** [comment]
Thanks for reporting the bug.

It will be fixed once this [PR](https://github.com/openstf/stf/issues/186) is merged.

**Comment by gunta** [comment]
Hi! 
Thanks for your feedback, definitely we welcome contributions.

About the Appium integration, there is some discussion about the test automation, check [here](https://github.com/openstf/stf/issues/38). This has chances of being implemented soon-ish.

As for iOS support, you can check [here](https://github.com/openstf/stf/issues/64). This has less chances of happening anytime soon, however any contribution would be appreciated.

The "Save Screenshot" behaviour you mention is a known bug and we'll fix it asap (actually its the first time we hear of someone actually using this feature).

Honestly I don't remember of us talking to any Testobject employee, but it may be just bad memory ;)

**Comment by FelixHahn** [comment]
Hi,

thank you for your quick responses.

We will definitly integrate your solution into our test infrastructure.
Just to give you a short idea what we're doing:
We're a automotive engineering company working for nearly every big car manufactor worldwide. We have several departments which are specialized on testing only the car infotainment systems (contains the navigationssystem, radio, multimedia, connectivity of the vehicle, whole speedometer unit etc.). We also developing mobile applications which are interacting with the car infotainment systems. Also there is a lot of work for us to do with interfaces like Android Auto, Apple Car Play, Mirrorlink, VW Appconnect .... With these interfaces the smartphone will be deeply integrated in the electronics of the car. That means a immense testing effort. Furthermore we have a lot of interoperability (IOP) tests between smartphones and the infotainmentsystems. Not only for bluetooth, also for WLAN, USB-Connection, Android Auto, Apple CarPlay and so on. Therefor we often need 100+ different devices per test.

The main unit of the infotainment system (mainly it is the big screen where the sat nav sits) is running a operating system pretty similar to a normal computer. That means there are different software releases, updates and versions which are depending on which system you selected buying you car and which car you got. Some of them are highly modular and you get the same system from different manufacturer without even noticing :).

Ideally we would like to have a second way to connect the smartphone to your STF solution. Not USB, we're looking for someting like ADB Wireless. For some test cases (Android Auto, Mirrorlilnk) we need to connect the phones via USB to the infotainment system. 

We have 5 features we're missing right now:
1.) iOS support
2.) direct access to the file system of an Android Phone (For some test cases we need to put some dummy data into some folders. It would be nice if we could do that remotly)
3.) Video capturing a test run
4.) Appium support (test automation)
5.) A second way to connect a Smartphone to STF (maybe ADB Wireless will work)

Goal of my thesis was to get a remote control into our company network. Therefor I looked into many different solutions (f.e. TestObject, Experitest, Keynote .....). And for manual testing you got by far the best solution for us an we will start using your software in the future. Right now we're testing it with only a small team. But we're looking forward to work with you.

Right now we're in the process of checking if we could share the features we may develop in the future. But it's looking good.
We're planning to develop features in house through bachelor and or master theses and we definitly want to cooperate and share with you.

It would be nice if we could talk about our cooperation via mail. 
Please feel free to contact me:  felix.hahn@iav.de


Right now we're doing some manual testing for different android application on STF and we must take screeshots from every HMI error we detect. The best practice for us is to use this screenshot feature. Unfortunaly the Screenshot task in your dashboard forgets all the saved screenshots when switching into another task. Maybe I should also report this as a bug.

I did read all these issues and like the ideas which are behind these approaches.

Kind regards

Felix Hahn
