### ISSUE TITLE
error when npm install in Odroid ArmV7 CPU

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#194]
gyp: Undefined variable yasm_format in deps/libjpeg-turbo.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.82-39
gyp ERR! command "/root/node-v4.1.2-linux-armv7l/bin/node" "/root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm/jpegturbo.node" "--module_name=jpegturbo" "--module_path=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm"
gyp ERR! cwd /root/stf-master/node_modules/jpeg-turbo
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/node-v4.1.2-linux-armv7l/bin/node /root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm/jpegturbo.node --module_name=jpegturbo --module_path=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/stf-master/node_modules/jpeg-turbo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.10.82-39
node-pre-gyp ERR! command "/root/node-v4.1.2-linux-armv7l/bin/node" "/root/stf-master/node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/stf-master/node_modules/jpeg-turbo
node-pre-gyp ERR! node -v v4.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/root/node-v4.1.2-linux-armv7l/bin/node /root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm/jpegturbo.node --module_name=jpegturbo --module_path=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm' (1)
npm verb unsafe-perm in lifecycle true
npm info jpeg-turbo@0.3.0 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/jpeg-turbo-712d5d6e1a1ca886.lock for /root/stf-master/node_modules/jpeg-turbo
npm verb stack Error: jpeg-turbo@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/root/node-v4.1.2-linux-armv7l/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid jpeg-turbo@0.3.0
npm verb cwd /root/stf-master
npm ERR! Linux 3.10.82-39
npm ERR! argv "/root/node-v4.1.2-linux-armv7l/bin/node" "/usr/local/bin/npm" "install" "--verbose" "--unsafe-perm"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! jpeg-turbo@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpeg-turbo@0.3.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the jpeg-turbo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpeg-turbo
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/jpeg-turbo
npm info preuninstall jpeg-turbo@0.3.0
npm info uninstall jpeg-turbo@0.3.0
npm verb unbuild rmStuff jpeg-turbo@0.3.0 from /root/stf-master/node_modules
npm info postuninstall jpeg-turbo@0.3.0
npm verb gentlyRm don't care about contents; nuking /root/stf-master/node_modules/jpeg-turbo

npm ERR! Please include the following file with any support request:
npm ERR!     /root/stf-master/npm-debug.log

Thanks

**Comment by sorccu** [comment]
Are you running npm as root, or perhaps with sudo? Because NPM doesn't like
when you do that.

**Comment by Tierney0115** [comment]
I have tried other user as well and they all have the same error when npm install jpeg-turbo@0.3.0 package. It seems like it has some error to rebuild the module: module=/root/stf-master/node_modules/jpeg-turbo/lib/binding/node-v46-linux-arm/jpegturbo.node

**Comment by sorccu** [comment]
I will look into this sometime this week, I had to replace the cooler on my
XU4 because the default one is a bit noisy.

**Comment by Tierney0115** [comment]
OK, Very appreciate :)

**Comment by sorccu** [comment]
It should work now, but you should run `npm update jpeg-turbo` in your stf repo first to make sure it gets v0.3.2 instead of v0.3.1.

By the way my XU4 is 100% silent now, and runs at 40-50° when idle, and between 60-75° when doing heavier things. If you max out all 8 cores with `stress --cpu 8` it does go above 95° after a minute or two, though. I'll keep trying different cooling options, but I think this one's already pretty good for our purposes.

Thanks for reporting the issue!
