### ISSUE TITLE
Can't take screenshot. The image "<url to screenshot file>" cannot be displayed because it contains errors.

### ISSUE THREAD

**Issue by rseek** [openstf/stf#20]
Hello!
Thank you for awesome software!

Unfortunately I faced some problem with taking screenshots, I hope you can help me.
When I try to take a screenshot, I see an icon which shows screenshot image is not available:
![torn_minicap](https://cloud.githubusercontent.com/assets/12827469/8823163/26704b46-3084-11e5-93b0-372b8676a4a5.png)
When I try to click this image, I see following error message in a new browser tab:
`The image "http://<my-ip>:7100/s/image/5aac3806-8ba7-4f29-bc49-1bcc1f28dede/<deviceName>.jpg" cannot be displayed because it contains errors.`

I tried to download image by url, and noticed image is just empty file(0 bytes size).

Stf is launched in "local" mode on my ubuntu 14.04 desktop like this:
`stf local --public-ip <my-ip>`
[there is no X server running on desktop, if it is important]
I am trying to take screenshot from my laptop

So, in console log I noticed following messages:
`INF/device:plugins:screen:capture 25422 [<deviceName>] Capturing screenshot
INF/storage:temp 25341 [*] Uploaded "<deviceName>.jpg" to "/tmp/upload_04db85c0a0bff470298192dcaffd7049"
INF/device:support:storage 25422 [<deviceName>] Uploaded to "/s/image/5aac3806-8ba7-4f29-bc49-1bcc1f28dede/<deviceName>.jpg"
`

I checked the file `/tmp/upload_04db85c0a0bff470298192dcaffd7049` and found my screenshot.

**Comment by sorccu** [comment]
Hmm, I think you're probably missing GraphicsMagick (the `gm`) command. Perhaps [this](https://github.com/openstf/docker-openstf-base/blob/master/Dockerfile) will help you find the right packages?

Let me know how it turns out.

**Comment by rseek** [comment]
Thank you for your answer, the problem really was with GraphicsMagick.

Originally I downloaded it from their official site and built from source with `make; make install`.
(Cause in your doc there is a link to their site ;))

But now I installed it from ubuntu repository and uninstalled version from official site and now everything work fine.

Thank you again, and sorry for dumb questions :)
