### ISSUE TITLE
Tried Setup in Virtual Box -FAILED!

### ISSUE THREAD

**Issue by knopsl** [openstf/stf#208]
my Setup was relatively effordless with instructions from here:
https://gist.github.com/pvsune/a2122369f91d2a518271

everything worked fine in my Virtual Box with Ubuntu 14.04.3-desktop-amd64 to the point of installing stf itself.

i do 'npm install -g stf'
-> works nicely
i go into stf in npm-modules 
i do 'npm install'
=> stf is vanished from modules and i can't do the last part with bower and npm link
Please help me. I would love to show stf to my QA team.

greetings Markus

**Comment by vbanthia** [comment]
I don't think those instructions are correct specially `installation` part.

If you are installation stf globally using `npm install -g stf`. You don't need to do `npm install` again.
Just skip the second step. You already install stf in `npm install -g stf` command.

Go to the step 3 and run stf app

**Comment by vbanthia** [comment]
Also, if you are using Virtual box, you won't be able to see devices until and unless you use [usbfilters](https://www.virtualbox.org/manual/ch03.html#idp46608643879360)

BTW, what host OS are you on? Windows? Mac? or something else?

**Comment by knopsl** [comment]
Host OS is Windows 7 64bit, I'll try again from scratch.

**Comment by knopsl** [comment]
is there a gist i can use?

**Comment by knopsl** [comment]
or would you provide a working virtualbox image for testing purposes?

**Comment by vbanthia** [comment]
well, ideally it should work if you are using Virtual Box. Installation will go smooth. The only problem will be filtering usb devices in Virtual box every time you add new one.

Other way you can try is by installing some linux OS on bare metal by making hard disk partition. This will give you real Linux OS instead of VM.

**Comment by knopsl** [comment]
tyring to install the whole thing for two days now, always errors. rethinkdb works fine, but stf doesn't start

**Comment by vbanthia** [comment]
we cannot figure out the problem if you don't provide us error log or other important information regarding your setup.

**Comment by knopsl** [comment]
I'll do as you recommended me before, start from scratch and put the whole error output here. Will be some time till I'm there. Maybe tomorrow. Thx in advance.

**Comment by knopsl** [comment]
Started from scratch with instructions:https://gist.github.com/pvsune/a2122369f91d2a518271
just used sudo npm install -g stf
then started rethinkdb (which works fine)
the started stf with "stf local" command 
Errors in TXT
[error_when_startstf.txt](https://github.com/openstf/stf/files/69709/error_when_startstf.txt)

**Comment by sorccu** [comment]
If the installation doesn't show any errors, it could be that you're
hitting a known bug in npm 2. Try running npm rebuild zmq OR upgrade to
latest node 5.x (that comes with npm 3).
