### ISSUE TITLE
Change mock auth to ldap 

### ISSUE THREAD

**Issue by romitincedoinc** [openstf/stf#215]
Hi

I m trying to figure out the auth module which is mock by default. now i want to change it to ldap and connect it to my ldap server. So could you  please help in finding the file in which i need to perform changes.

**Comment by vbanthia** [comment]
To use ldap, you will need to start you stf-auth unit using ldap settings. You can find ldap related options using `stf auth-ldap --help` command. After reconfiguration restart you `stf-auth` unit.

In case you are using `stf local` then check ldap related options using `stf local --help`

**Comment by vbanthia** [comment]
or check https://github.com/openstf/stf/issues/47

**Comment by romitincedoinc** [comment]
Thanks For your quick reply. Let me try with oAuth & with Ldap.

**Comment by vbanthia** [comment]
Duplicate of https://github.com/openstf/stf/issues/47
