### ISSUE TITLE
problem with minitouch

### ISSUE THREAD

**Issue by likezjuisee** [openstf/stf#232]
I hava written a python script to call minitouch socket server, but i came with the problem below, it seems like the heads of the request is wrong.

--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:1111
Origin: http://localhost:1111
Sec-WebSocket-Key: zreWTQ9Syce2aG2b7sohOA==
Sec-WebSocket-Version: 13

-----------------------
--- response header ---
v 1
^ 10 720 1280 0
error: Invalid header
### closed ###

my script:
#coding=gbk
import websocket
import thread
import time
import ssl
import socket

def on_message(ws, message):
    print message

def on_error(ws, error):
    print 'error: ' + str(error)

def on_close(ws):
    print "### closed ###"

def on_open(ws):
    ws.send("d 0 100 100 50")
    ws.send("c")
    ws.send("u 0 ")
    ws.send("c")
    ws.close()

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("ws://localhost:1111/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})

**Comment by sorccu** [comment]
minicap doesn't provide a WebSocket server. It's a raw socket. Raw sockets are very different from WebSockets. You MIGHT be able to use something like http://websocketd.com/ if you really don't feel like playing with sockets yourself, but I've never tried using it.

**Comment by likezjuisee** [comment]
Yes,  I have tried the socket method. But, it wasn't useful also. When I input 2 command, the cmd.exe is blocked. Here is my python code:

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost',1111))
while 1:
    cmd=raw_input("Please input cmd:")  
    s.sendall(cmd)
    data=s.recv(1024)     
    print data
s.close() 

the log:

--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:1111
Origin: http://localhost:1111
Sec-WebSocket-Key: 4JwELC7XpMgKlXWh+mYLzw==
Sec-WebSocket-Version: 13


-----------------------
--- response header ---
v 1
^ 10 720 1280 0
error: Invalid header
### closed ###
Please input cmd:d 0 100 100 50
v 1
^ 10 720 1280 0
$ 9315

Please input cmd:c

**Comment by sorccu** [comment]
Why does your log still show a HTTP request?

**Comment by likezjuisee** [comment]
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Because of this?
socket.AF_INET is explained to ipv4, and socket.SOCK_STREAM is tcp connection.
