### ISSUE TITLE
which nodejs file in the stf project controls the minitouch in android?

### ISSUE THREAD

**Issue by likezjuisee** [openstf/stf#239]
I am writing the client script to control the minitouch, so I need a sample, thanks.

**Comment by sorccu** [comment]
It's [this one](https://github.com/openstf/stf/blob/b9fd290da8e87679972dea4c430bb6f71bd82c84/lib/units/device/plugins/touch/index.js).

**Comment by likezjuisee** [comment]
Could you show me a single nodejs file which can control the minitouch, I am not familiar with the nodejs coding. The index.js is too complicated for me.

**Comment by sorccu** [comment]
That's the only one we have. But it's doing exactly what the [minitouch](https://github.com/openstf/minitouch) documentation shows.
