### ISSUE TITLE
Does STF support Nexus 6P (Android M, USB Type-c)?

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#241]
Someone said the Nexus 6P cannot be supported. I cannot get the real phone to test at this time or check the log.

Is anyone using Nexus 6P with STF? Thanks

**Comment by vbanthia** [comment]
I have used it once and did not find any problem with STF

**Comment by rocketb** [comment]
![stf](https://cloud.githubusercontent.com/assets/1926748/12261366/b8575f14-b931-11e5-8c51-624e5bd6886f.png)

Nexus 6x with Android 6.0.1 + USB Type-C works fine
