### ISSUE TITLE
In the same local area network, the other computer connected to the configuration of the computer's address, no phone screen

### ISSUE THREAD

**Issue by foolishgao** [openstf/stf#246]
the error is, no phone screen,and a dialog prompt error as well

**Comment by vbanthia** [comment]
Could you provide more information about your setup?

Please also provide STF logs

**Comment by foolishgao** [comment]
WRN/util:datautil 2913 [*] Device database does not have a match for device "0123456789ABCDEF" (model "undefined"/"undefined")
WRN/util:datautil 2913 [*] Device database does not have a match for device "TA00403N2P" (model "XT1085"/"victara_retcn")
WRN/util:datautil 2913 [*] Device database does not have a match for device "e1f2ffd" (model "MI 2"/"aries")

**Comment by sorccu** [comment]
If there's no screen but it otherwise works fine, you may have missed the `--public-ip` option. You need to set it to access STF from another computer.
