### ISSUE TITLE
How can i control more than 160 devices.

### ISSUE THREAD

**Issue by JabariDuan** [openstf/stf#258]
I noticed that there is Location label in the Details‘s information.
So can i add devices in the other PC ? And what i need to do？

if i can’t do this，can you tell me what did you do？
my partner tell me that they did try control a large number of devices on the same PC.(use the usb hub), but the effect is not good.

I'm sorry about my English. and thanks for any help you can give.

**Comment by sorccu** [comment]
You need to do a full deployment, as described in [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). This allows you to provide devices from multiple machines.

**Comment by JabariDuan** [comment]
Thanks for your help
I have got STF running via stf local. 
Can i just make a provider with adbd.service and stf-provider@.service on the other PCs to provide devices from multiple machines?

**Comment by krisdyZJU** [comment]
@JabariDuan how did it go on?  did you succeed to just make a provider with adbc.service and stf-provider@.service on the other PCs to provide devices from multiple machines or do a full deployment as sorccu recommended in [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md)

I am a newbie for openstf, still have the same problem as you mentioned, any advice?
