### ISSUE TITLE
How to use REST API to reset device timeout from being kickout?

### ISSUE THREAD

**Issue by BigWavelet** [openstf/stf#259]
@vbanthia Need your help.

I can use rest api to reserve a device, but it will be released automaticly when timeout. (In my machine is 10min), Want to know how to rest the timeout use api. thanks.

**Comment by vbanthia** [comment]
You can set optional `timeout` parameter while adding a new device, something like this

```js
var device = {serial: 'yyyy', timeout: 900000 }

client.then(function(api) {
  return api.user.addUserDevice({device: device})
    .then(function(res) {
      console.log(res.obj)
      // { success: true, description: 'Device successfully added' }
    })
})
.catch(function(err) {
  console.log(err)
})
```

`timeout` is in ms

**Comment by vbanthia** [comment]
Currently, you cannot reset the `timeout` for the devices being used. You can only set it while adding it.

**Comment by BigWavelet** [comment]
@vbanthia  Thanks

**Comment by cemakkok** [comment]
@vbanthia how can i use your code sample, i cannot see any sample in the project like that api.user....., how can i get client object ?  for example i wanna add this code to work when client click a device. 

Which js class, must i edit ?

Thanks for your answer.
