### ISSUE TITLE
How can i provide devices from multiple machines

### ISSUE THREAD

**Issue by JabariDuan** [openstf/stf#260]
Thanks for Sorccu's help
I have got STF running via stf local.
Can i just make a provider with adbd.service and stf-provider@.service on the other PCs to provide devices from multiple machines?

**Comment by vbanthia** [comment]
No, you cannot do this via `stf local`. `stf local` is made for development purpose not for production.

As said earlier, you will need to do a full deployment as described [here](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) to use multiple providers.

**Comment by JabariDuan** [comment]
I got it
Thanks for your help

**Comment by codeskyblue** [comment]
Actually, Use `stf local` + `stf provider` works fine for me.

**Comment by sorccu** [comment]
Yes it does, but you need to know what you're doing like you apparently do :) Anyway we only provide step-by-step instructions for a full deployment and `stf local` isn't super reliable, it might fail to restart processes that die and we know it has other bugs too.
