### ISSUE TITLE
ADB over network

### ISSUE THREAD

**Issue by brunotvaz** [openstf/stf#268]
Hi guys,

First of all let me congratulate you guys for this excellent piece of software. CONGRATULATIONS !!!
I am truly impressed but can't make it work over the network.
STF does work when I have the phone connected via USB cable but not over the network.
This is how I have my lab configured:
STF server (192.168.1.66) -> Router (192.168.1.254) -> Android Phone (192.168.1.65)
![stf_lab](https://cloud.githubusercontent.com/assets/1796032/13177831/7945d8c8-d713-11e5-80bf-9737de1d4a46.png)
I've configured the android phone to do ADB over network:
![android-phone](https://cloud.githubusercontent.com/assets/1796032/13177993/7d162376-d714-11e5-9fca-e0187c1b64ca.png)
Then I started STF using the following commands:
stf local --public-ip 192.168.1.66
stf local --public-ip 192.168.1.66 --allow-remote
NONE worked unfortunately. I did forward port 5555 on the router to point to the smartphone but it still refuses to detect the phone.
Am I doing something wrong? Can you please point me in the right direction ? Many thanks in advance.

**Comment by brunotvaz** [comment]
When I connect the phone using the USB cable, STFService starts and everything seems to work fine.
As soon as I disconnect the USB cable the phone appears disconnected in the STF webpage.
I've also rebooted the phone and tried to connect 1st via network and no STFService was started. Meaning that the server couldn't see the phone?
From the STF machine (UBUNTU) I run the following command:
telnet 192.168.1.65 5555
The phone replied with:
Escape character is 'ʌ]'
Which means that there is a connection from STF to the smartphone port 5555 so why doesn't ADB over network works ?

**Comment by sorccu** [comment]
Did you run adb connect ip:port? Also using adb over wifi is a bad idea
(even though it works), search the issues to find out why.

**Comment by brunotvaz** [comment]
Spot on Sorccu ! I've read the following page to come up to the same conclusion:
https://www.learn2crack.com/2014/07/adb-android-debug-bridge-over-wifi.html
I did "adb connect 192.168.1.65" and it connected fine ! Great stuff. Thanks for that :)
Now the next step is to test STF with a "PUBLIC IP" and the smartphone over the 3G network instead of Wifi.
Again thank you for your support Sorccu. Much appreciated.

**Comment by deg0nz** [comment]
@brunotvaz: can you tell something about the performance with stf over wifi? i believe it's pretty slow...

**Comment by sorccu** [comment]
STF over WIFI with USB devices is fine. ADB over WIFI is super slow, and if you connect those devices to STF they will also be very slow, because there's nothing we can do to fix the slowness of ADB itself.
