### ISSUE TITLE
 Device database does not have a match for device "0123456789ABCDEF" 

### ISSUE THREAD

**Issue by yrguo** [openstf/stf#269]
Screen sharing on some devices only shows grey！
 Device database does not have a match for device "0123456789ABCDEF" (model " E50 T1"/"Hasee E50 T1")

Please tell me the reason and how to solve this problem！

**Comment by sorccu** [comment]
That's not a problem. It just means that we don't have a picture for that device. Also, stop spamming. Within just a few hours, you emailed us directly in Chinese, which we cannot read, then posted this issue, and are spamming other issues as well.

Furthermore, your device is broken. USB serial numbers are supposed to be unique, but yours is "0123456789ABCDEF". It means that the manufacturer has no idea what they're doing. STF does not work if you have multiple devices with the same serial number connected to the system. If you had multiple devices connected to the system, this is most likely the reason.

Anyway please post the full log output, all the way from `stf local`, otherwise it's impossible to say anything.

**Comment by yrguo** [comment]
@sorccu 
My device is not bad;
I inserted two usb devices,
Serial numbers are
c349c632 device
0123456789ABCDEF device

The same performance,
Device database does not have a match for device "0123456789ABCDEF" (model "E50 T1" / "Hasee E50 T1")
Device database does not have a match for device "c349c632" (model "SM-J5108" / "j5xltezm")
 
Can you tell me which phone models and  pictures your supported ？？

**Comment by sorccu** [comment]
A missing picture is not a problem. It just won't look pretty in the UI.

You need to show the full log or there's nothing I can do to help.

**Comment by yrguo** [comment]
@sorccu 

I start from the beginning stf to the usb device。
full log as：


INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 4431 [*] Connecting to 127.0.0.1:28015
INF/db:setup 4431 [*] Database "stf" already exists
INF/db:setup 4431 [*] Table "users" already exists
INF/db:setup 4431 [*] Table "accessTokens" already exists
INF/db:setup 4431 [*] Table "vncauth" already exists
INF/db:setup 4431 [*] Table "devices" already exists
INF/db:setup 4431 [*] Table "logs" already exists
INF/db:setup 4431 [*] Index "users"."adbKeys" already exists
INF/db:setup 4431 [*] Index "accessTokens"."email" already exists
INF/db:setup 4431 [*] Index "vncauth"."response" already exists
INF/db:setup 4431 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 4431 [*] Index "devices"."owner" already exists
INF/db:setup 4431 [*] Index "devices"."present" already exists
INF/db:setup 4431 [*] Index "devices"."providerChannel" already exists
INF/db:setup 4431 [*] Waiting for index "users"."adbKeys"
INF/db:setup 4431 [*] Waiting for index "accessTokens"."email"
INF/db:setup 4431 [*] Waiting for index "vncauth"."response"
INF/db:setup 4431 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 4431 [*] Waiting for index "devices"."owner"
INF/db:setup 4431 [*] Waiting for index "devices"."present"
INF/db:setup 4431 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 4431 [*] Index "users"."adbKeys" is ready
INF/db:setup 4431 [*] Index "accessTokens"."email" is ready
INF/db:setup 4431 [*] Index "vncauth"."response" is ready
INF/db:setup 4431 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 4431 [*] Index "devices"."owner" is ready
INF/db:setup 4431 [*] Index "devices"."present" is ready
INF/db:setup 4431 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name yrguo-System-Product-Name --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 192.168.39.94 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --allow-remote"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://192.168.39.94:7100/"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://192.168.39.94:7100/auth/mock/ --websocket-url http://192.168.39.94:7110/"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 4428 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 4437 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 4437 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 4437 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/triproxy 4434 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 4434 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 4434 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/db 4441 [proc002] Connecting to 127.0.0.1:28015
INF/reaper 4444 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 4444 [reaper001] Reaping devices with no heartbeat
INF/db 4444 [reaper001] Connecting to 127.0.0.1:28015
INF/processor 4441 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 4441 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/reaper 4444 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/db 4438 [proc001] Connecting to 127.0.0.1:28015
INF/processor 4438 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/reaper 4444 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/processor 4438 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/poorxy 4468 [*] Listening on port 7100
INF/auth-mock 4450 [*] Listening on port 7120
INF/storage:plugins:image 4462 [*] Listening on port 7103
INF/provider 4447 [*] Subscribing to permanent channel "u6jyAleKTceXdmspAqNgmQ=="
INF/provider 4447 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 4447 [*] Receiving input from "tcp://127.0.0.1:7114"
INF/storage:plugins:apk 4465 [*] Listening on port 7104
INF/provider 4447 [*] Tracking devices
INF/provider 4447 [*] Found device "c349c632" (device)
INF/reaper 4444 [reaper001] Device "c349c632" is present
INF/provider 4447 [*] Registered device "c349c632"
INF/storage:temp 4459 [*] Listening on port 7102
INF/app 4453 [*] Using pre-built resources
INF/app 4453 [*] Listening on port 7105
INF/db 4453 [*] Connecting to 127.0.0.1:28015
INF/websocket 4456 [*] Subscribing to permanent channel "*ALL"
INF/websocket 4456 [*] Listening on port 7110
INF/db 4456 [*] Connecting to 127.0.0.1:28015
INF/websocket 4456 [*] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 4456 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/device:support:push 4485 [c349c632] Sending output to "tcp://127.0.0.1:7116"
INF/device 4485 [c349c632] Preparing device
INF/device:support:sub 4485 [c349c632] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 4485 [c349c632] Subscribing to permanent channel "*ALL"
INF/device:support:properties 4485 [c349c632] Loading properties
INF/device:support:abi 4485 [c349c632] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 4485 [c349c632] Checking whether we need to install STFService
INF/device:resources:service 4485 [c349c632] Running version check
INF/device:resources:service 4485 [c349c632] STFService up to date
INF/device:plugins:service 4485 [c349c632] Launching agent
INF/device:plugins:service 4485 [c349c632] Launching service
INF/device:plugins:service 4485 [c349c632] Agent says: "Listening on port 1090"
INF/device:plugins:service 4485 [c349c632] Agent says: "InputClient started"
INF/device:plugins:display 4485 [c349c632] Reading display info
INF/device:plugins:phone 4485 [c349c632] Fetching phone info
INF/device:plugins:identity 4485 [c349c632] Solving identity
INF/device:plugins:solo 4485 [c349c632] Subscribing to permanent channel "jn4921UkxrOZ/xxtWgLa2UwxOK4="
INF/device:plugins:screen:stream 4485 [c349c632] Starting WebSocket server on port 7400
WRN/device:plugins:data 4485 [c349c632] Unable to find device data { serial: 'c349c632',
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  operator: ',',
  model: 'SM-J5108',
  version: '5.1.1',
  abi: 'armeabi-v7a',
  sdk: '22',
  product: 'j5xltezm',
  display: 
   { id: 0,
     width: 720,
     height: 1280,
     xdpi: 282.7130126953125,
     ydpi: 281.3529968261719,
     fps: 60,
     density: 2,
     rotation: 270,
     secure: true,
     size: 5.21376997057658,
     url: 'ws://192.168.39.94:7400' },
  phone: { imei: '357107070002250', network: 'UNKNOWN' } }
INF/device:plugins:touch 4485 [c349c632] Touch origin is top left
INF/device:plugins:touch 4485 [c349c632] Requesting touch consumer to start
INF/device:plugins:touch 4485 [c349c632] Launching screen service
INF/device:plugins:touch 4485 [c349c632] Connecting to minitouch service
INF/device:plugins:touch 4485 [c349c632] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 4485 [c349c632] minitouch says: "Type B touch device sec_touchscreen (719x1279 with 10 contacts) detected on /dev/input/event2 (score 1100)"
INF/device:plugins:touch 4485 [c349c632] Reading minitouch banner
INF/device:plugins:touch 4485 [c349c632] minitouch says: "Connection established"
INF/device:plugins:vnc 4485 [c349c632] Starting VNC server on port 7402
INF/device:plugins:browser 4485 [c349c632] Loading browser list
INF/device:plugins:browser 4485 [c349c632] Updating browser list
WRN/device:plugins:browser 4485 [c349c632] Unmapped browser "com.baidu.searchbox"
WRN/device:plugins:browser 4485 [c349c632] Unmapped browser "sogou.mobile.explorer"
WRN/device:plugins:browser 4485 [c349c632] Unmapped browser "com.xinmei365.font"
INF/device:plugins:mute 4485 [c349c632] Will not mute master volume during use
INF/device:plugins:forward 4485 [c349c632] Launching reverse port forwarding service
INF/device:plugins:forward 4485 [c349c632] Connecting to reverse port forwarding service
INF/device:plugins:connect 4485 [c349c632] Listening on port 7401
INF/device 4485 [c349c632] Fully operational
INF/provider 4447 [*] Providing all 1 device(s)
WRN/util:datautil 4453 [*] Device database does not have a match for device "c349c632" (model "SM-J5108"/"j5xltezm")

**Comment by yrguo** [comment]
@sorccu 
This problem has been solved;
I inquired about your file called devices-latest.json ,
Nexus 5 phone is supported.
But I still want to add more supported models;
Can I  add other models? How do I add?
In addition to adding th file called devices-latest.json , but also to add images?

**Comment by fireblue** [comment]
Enable MTP in storage settings and this issue can be solved. I came across this issue yesterday.

**Comment by hemano** [comment]
You need to make sure that STFService on the mobile is running and not blocked by any other application.

**Comment by denis99999** [comment]
Hi fireblue, where I can enable MTP in storage settings ? Is there a documentation somewhere about all these settings ?
Thanks.
