### ISSUE TITLE
Wireless display of the phone doesn't work

### ISSUE THREAD

**Issue by Matthieu33** [openstf/stf#270]
Hello !
I would like to use STF without plugging an USB cable on my device.
It works perfectly when it is plugged but when I use "stf local --allow-remote --public-ip 192.168.43.1", the phone is detected but I get "WRN/util:datautil 7829 [*] Device database does not have a match for device "192.168.43.1:5555" (model "KC-S701"/"KC-S701")" warning message and I don't have the screen of my device on my browser:
![screenshot1](https://cloud.githubusercontent.com/assets/17450497/13317603/442cb6fa-dbb6-11e5-99ef-02cfd8104c0b.png)
![screenshot2](https://cloud.githubusercontent.com/assets/17450497/13317609/4c4cd202-dbb6-11e5-85ae-c0ebd279614a.png)

Thank you for your help,
Matthieu

**Comment by sorccu** [comment]
That's not recommended because adb over wifi is super super slow. You can search past issues for more details.

I suspect your issue may be caused by a firewall, but perhaps not. Open your browser's developer tools. There should be a failed WebSocket request. Take a screenshot of that request incl. headers if there are any, and post it here.

**Comment by Matthieu33** [comment]
Indeed there is a failed WebSocket request.

First, when I try to connect to localhost:71000, I am redirected to 192.168.43.1:7100/auth/mock but the connection fails and I get warning on the console : The use of "getPeventDefault()" is obsolete. Use "defaultPrevented()" instead.
![screen1](https://cloud.githubusercontent.com/assets/17450497/13424107/edffe206-df9e-11e5-8569-3c344d1cbbe9.png)

Then I replace the IP address with localhost and I get the authentication page:
![screen2](https://cloud.githubusercontent.com/assets/17450497/13424112/fbb71d7e-df9e-11e5-8f8a-b3e8e8627db2.png)

Finally when I authenticate I am redirected once again to an url beginning with the IP and when I replace the IP with localhost, I get this error on the console : Firefox can't establish a connexion with server at address ws://192.168.43.1:7110/socket.io/...
![screen3](https://cloud.githubusercontent.com/assets/17450497/13424144/162606ac-df9f-11e5-881d-547b6890c6cf.png)

![screen4](https://cloud.githubusercontent.com/assets/17450497/13424146/1badbbc4-df9f-11e5-9f25-41fa3a1166c0.png)

**Comment by sorccu** [comment]
How are you launching stf? If you use `stf local --public-ip 1.2.3.4`, then you should only access http://1.2.3.4:7100. If you don't give the `--public-ip` option, then you should only access http://localhost:7100. You can't mix them reliably.

**Comment by Matthieu33** [comment]
Ok, I launch with **stf local --allow-remote --public-ip 1.2.3.4**

**Comment by Matthieu33** [comment]
Am I supposed to have a "STF" folder (or similar) on my smartphone ? Because I just have the "STFService" application and I can't even locate where it is installed...

**Comment by sorccu** [comment]
No, it doesn't have a launcher action so that it doesn't interfere with the
original UI. You can still access and uninstall it from settings, though.

**Comment by Matthieu33** [comment]
Ok, thank you

**Comment by Matthieu33** [comment]
I solved my problem !
Actually I didn't have to use --public-ip.

I connected my device to the same WLAN as my computer, I ran **rethinkdb**, then **adb connect 1.2.3.4** in another shell and finally **stf local --allow-remote**
I have wireless access to my device from localhost:7100
It is indeed slower than through USB but there is less than 5 seconds lag

Thank you for your help and advice !
