### ISSUE TITLE
recommended usb hubs not available

### ISSUE THREAD

**Issue by rompic** [openstf/stf#280]
hi there!

are there any updates on the recommended usb hubs? http://plugable.com/products/usb2-hub7bc is not available (at least in europe). I'm especially looking for more information concerning "Note that ORICO also provides hubs that are identical to Plugable's offerings, the latter of which seem to be rebrands."

Best,
Roman

**Comment by Rabusek** [comment]
Being you I'd just try to find hubs with good external power source - 60/48W should do.

Also, I'm using a normal, 4-port hubs without any external power source and it works for me, although I'm connecting just 14 devices at once.

**Comment by harishnazief** [comment]
@Rabusek, are you using 4 port hubs with usb 2.0 or usb 3.0?

**Comment by Rabusek** [comment]
@harishnazief 3.0

**Comment by banoraga** [comment]
@Rabusek, could you share OS, USB PCI Card and USB Hub that you use for STF? Are you disable the 3.0? Is it stable using 3.0?

**Comment by Rabusek** [comment]
@banoraga Mac OSX 10.10, it's not PCI card, it's just a hub - TP Link UH700. I'm not disablind 3.0. It's stable, but i can't connect more than ~20 devices

**Comment by pwicherski** [comment]
@Rabusek @banoraga Linux FTW in this situation?

**Comment by sorccu** [comment]
We still recommend the plugable hub. Closing the issue as it's pretty old and the situation has likely been resolved in some way already.
