### ISSUE TITLE
Device is not recognised when it is connected over USB.

### ISSUE THREAD

**Issue by PattabhiramaPandit** [openstf/stf#286]
We have set up the cluster and we were able to get the stf up and running with the 172.8.... Stuff..

When I connect the device I am not able to see the device. But when I did adb devices in coreos-1 console , I am able to see the device listed. But not in stf. Please advise

**Comment by PattabhiramaPandit** [comment]
The device is android device..

**Comment by vbanthia** [comment]
Looks like you are trying to run setup example which is in different repo. Please don't mix issues between different repository. 

Also, it's hard to identify problem with current information. Please post everything what you have done to run that sample with fleetctl logs.

**Comment by PattabhiramaPandit** [comment]
Agree, thanks a lot we were able to get that up.

**Comment by krisdyZJU** [comment]
@vbanthia 
I follow the steps as described in DEPLOYMENT.md and try to deploy STF in production mode, I start adbd and stf-provider service in one host as Provider side which has one android device plugged in, and the other services started in another host as App side, but when I start stf-provider service at last, the log said:
<img width="653" alt="2016-04-07 10 49 37" src="https://cloud.githubusercontent.com/assets/9692934/14339302/37ddfbfa-fcb0-11e5-8cf4-fadb4db7c0c2.png">


as you can see, the device is ignored, can you help to see and give some suggestions, thanks in advance.

and also @PattabhiramaPandit ,can you give me some hit how you fix it? thanks
