### ISSUE TITLE
Want to list only connected device

### ISSUE THREAD

**Issue by murtaza61** [openstf/stf#287]
How can i do that?

**Comment by SergKhachko** [comment]
I'm not sure that system can be configured to forget previously connected devices, but if you need to remove old one, do this:

1. Make sure RethinkDB config contains bind=all. Also find http-port section in the same config to make HTTP connections for appropriate port.
2. Go to RethinkDB DBMS through your browser: http://server_ip:8080
3. Navigate to DataExplorer
4. Run r.db('stf').table('devices').get('SERIAL').delete() (where SERIAL is your device serial number from list of connected devices)

**Comment by murtaza61** [comment]
Thanks for reply. I used below command and clear devices data in rethinkdb.
sudo recli -d stf 'r.table("devices").delete()'
