### ISSUE TITLE
How can I use openstf for running appium tests

### ISSUE THREAD

**Issue by jogjitu** [openstf/stf#288]
I want to use open stf for running our appium tests. I have installed the beta version of release which has api's. 

Our framework is in ruby and wanted to know how can use the api's provided to run our appium tests.

I am having issue accessing the url http://vbanthia.github.io/angular-swagger-ui/ it shows 404.

**Comment by rseek** [comment]
It is not like you can use STF to run tests.
STF could only be a device provider for you to use with appium or any other framework.

API is more or less documented [here](https://github.com/openstf/stf/blob/2.0.0/doc/API.md), so you should just implement neccessary API calls in your framework.

Or you can try some [python utils](https://github.com/2gis/stf-utils) to work with STF API and connect devices using python script.

1. Connect device from STF using [stf utils](https://github.com/2gis/stf-utils)
2. Start appium server locally
3. Run your tests
