### ISSUE TITLE
screenshot error in production mode

### ISSUE THREAD

**Issue by krisdyZJU** [openstf/stf#295]
I follow the step as described in [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md), start STF in production mode, everything goes well except screenshot and install apk files, I dig into the log, and find the log like:
INF/device:plugins:screen:capture 136 [HC46XWY03146] Capturing screenshot
ERR/device:support:storage 136 [HC46XWY03146] Upload to "30.35.104.17/s/upload/image" failed **_Error: Invalid URI "30.35.104.17/s/upload/image"_**
at Request.init (/app/node_modules/request/request.js:287:31)
at new Request (/app/node_modules/request/request.js:141:8)
....

Am I missing something?

**Comment by sorccu** [comment]
Looks to me like you did not follow the instructions. You need to include `http://` or `https://` in `--storage-url` like the deployment guide shows.

**Comment by krisdyZJU** [comment]
Thanks @sorccu 

my fault, I add "http://" before the ip of "--storage", it works fine now, so close it.
