### ISSUE TITLE
device was found but ignored

### ISSUE THREAD

**Issue by krisdyZJU** [openstf/stf#297]
I set up STF in production mode, below is a short description about how I did:
Host A which has one device plugged in: start adbd.service, stf-provider@1.service, stf-triproxy-dev.service
Host B: start the rest services including: rethinkdb-proxy-28015.service, stf-app@3100...stf-processor@1.service, stf-reaper.service, stf-triproxy-app.service
Host C: rethinkdb server

I start rethinkdb server in Host C first, and then all services in Host B, and last, adbd、str-triproxy-dev、stf-provider@1 services in Host A, but when provider finally ignored the devices which I plug in Host A. the log is:

 ** Message: No devices in use, exit
INF/provider 1 [*] Subscribing to permanent channel "XRHjEnMWRueBkCV52TeM/w=="
INF/provider 1 [*] Sending output to "tcp://30.35.104.20:7270"
INF/provider 1 [*] Receiving input from "tcp://30.35.104.20:7250"
INF/provider 1 [*] Tracking devices
INF/provider 1 [*] Found device "DU2TAN14A6009598" (device)
INF/provider 1 [*] Providing all 0 of 1 device(s); **ignoring** "DU2TAN14A6009598"

I make sure the usb line and the device are all okay, since I use the same data line and android device when I use stf local, it works well.

so I guess there must be some communication problem which lead stf ignore the device, but I can not find a fix, any help or suggestions are appreciated, thanks.

Actually I succeed to setup STF in production mode using one dev side host and app side host as described in [this issue](https://github.com/openstf/stf/issues/294), but when I use another host as dev side, the device ignore problem happen again, which I do not know why it happens...

**Comment by krisdyZJU** [comment]
it is because of the firewall, disable it fix the problem

**Comment by habeebshk** [comment]
did you fix the problem?

**Comment by krisdyZJU** [comment]
disable the firewall to fix it
