### ISSUE TITLE
How to config the unit file when deploy STF with more than one dev host in production mode

### ISSUE THREAD

**Issue by krisdyZJU** [openstf/stf#299]
as described below, I want to deploy STF in production mode with more than one host which has devices plugged in:

<img width="440" alt="2016-04-08 8 23 25" src="https://cloud.githubusercontent.com/assets/9692934/14383455/ce344d30-fdc7-11e5-84dd-313ee68416dd.png">

I distribute the service as displayed on the right side. (ps: I succeed to deploy STF when there is only one host with devices plugged in according to this service distribution, now I want to deploy STF with two Dev side hosts)

I see the [DEPLOYMENT](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md)，"devside.stf.example.org" only appears in stf-processor.service and stf-reaper.service, so I guess I only need to config the two ip in these two services, like below:

`stf-processor@.service`
```
[Unit]
Description=STF processor
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  --link rethinkdb-proxy-28015:rethinkdb \
  openstf/stf:latest \
  stf processor %p-%i \
    --connect-app-dealer tcp://HOST_C_IP:7160,tcp://HOST_C_IP:7160 \
    --connect-dev-dealer tcp://HOST_A_IP:7260,tcp://HOST_B_IP:7260
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```

`stf-reaper.service`
```
[Unit]
Description=STF reaper
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  --link rethinkdb-proxy-28015:rethinkdb \
  openstf/stf:latest \
  stf reaper dev \
    --connect-push tcp://HOST_A_IP:7270,tcp://HOST_B_IP:7270 \
    --connect-sub tcp://HOST_C_IP:7150,tcp://HOST_C_IP:7150\
    --heartbeat-timeout 30000
ExecStop=-/usr/bin/docker stop -t 10 %p
```

After I deploy STF, I try to use the device in browser, but I find I can not manipulate the device from browser side, I know there must be some problem in the unit file configuration, but I really do not know how, any suggestions and help is appreciated, thanks in advance.

**Comment by sorccu** [comment]
You can have more than one stf-triproxy-dev running if you need extreme scalability, but your graph is a bit off. The stf-triproxy-dev is a contact point for ALL the services running on ALL the provider machines. Therefore if you put it directly on a provider machine, all other provider machines and stf-processors would have to connect to that one.

Like the deployment docs say, the provider machines are only supposed to have adbd and stf-provider running. You should put the stf-triproxy-dev unit wherever it's convenient, usually the application server. Keep in mind that the triproxies are bind points, i.e. they must have some kind of a static address e.g. a dns entry or a static IP. If you put the triproxy on the provider machine, all other machines will need to know its address, which is annoying and even impossible in some environments. I would recommend getting started with only one stf-triproxy-dev, and if you really, really insist, you can try adding more once you get that running.

**Comment by krisdyZJU** [comment]
@sorccu Thanks for your quick reply.
Actually I did as you said at first, start stf-triproxy-dev service in the application service side, but all devices are ignored when I start stf-provider service at last in dev side, then I try to start stf-triproxy-dev service in dev side and solve the problem, you can find the detail in this [issue](https://github.com/openstf/stf/issues/294) I closed.

if really as you suggested, I should start stf-triproxy-dev in application service side, then what can I do to avoid the device ignorance problem?

**Comment by krisdyZJU** [comment]
really as the [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) said, I read it thoroughly and finally I find the problem, I misunderstand what devside.stf.example.org really stands, now everything goes fine now except some device will offline suddenly, I will handle it.

Thanks again for this excellent project!

**Comment by xiaweixing** [comment]
@krisdyZJU could you please share with us what your final solution is?  Thx!
