### ISSUE TITLE
How to be scope in the IP address?

### ISSUE THREAD

**Issue by shkd** [openstf/stf#3]
Thank you for a great app! Immediately, we are using.

When you start with "$stf local" command, you can use in the http://localhost:7100, for example, start at IP address, such as 192.168.1.100, and we would like to access from other PC.

The start-up command was some experience, but the connection to the DB is becomes to "127.0.0.1:28015", it can not be started.
*"rethinkdb" is, "- bind all" you have to start it with the option.

In order to use to share the STF is allowed to access from other PC, but I want to start with IP address, Could you tell me how?

**Comment by sorccu** [comment]
Hi,

Thank you!

You can change the IP address STF uses by launching STF with `stf local
--public-ip 192.168.1.100`. You should then be able to access it from other
machines via http://192.168.1.100:7100.

Note that for a real deployment you would not use `stf local` at all, but
instead start all the processes separately. Currently we lack documentation
for doing that, but `lib/cli.js` might give you a few hints. Later on we'll
publish systemd unit configurations to make it easier.

You can change the RethinkDB address by setting the RETHINKDB_PORT_28015_TCP
environment variable (it's link docker --link format). By default it's
`tcp://127.0.0.1:28015`. Users will not connect to the database directly,
though, so you usually don't have to change the address if you run STF
locally.

So, if you wanted to change both the public IP and the RethinkDB address,
you'd launch STF with something like this:

```
RETHINKDB_PORT_28015_TCP=tcp://192.168.1.100:28015 stf local
--public-ip 192.168.1.100
```

And you should be OK.

**Comment by shkd** [comment]
Thanks for the quick reply!
A result, I were able to use without problems.
Thank you!
