### ISSUE TITLE
minitouch ended without any exception, how to debug minitouch

### ISSUE THREAD

**Issue by yuzhidi** [openstf/stf#300]
sometimes log say "Shell keeping minitouch running ended unexpectedly"
There is not any exception or backtrace in stf or device log.
How can I debug this issue?

**Comment by chenpig1123** [comment]
Modify the minitouch source code and rebuild it, push your new .so to device, then exec them.
You need android-ndk for building the minitouch source code.

**Comment by vbanthia** [comment]
Read [this](https://github.com/openstf/minicap/blob/master/README.md) and [this](https://github.com/openstf/minicap/tree/master/jni/minicap-shared) for documentation. And there are also some instructions in this [issue](https://github.com/openstf/minicap/issues/8) which may be helpful
