### ISSUE TITLE
Using STF for Test Automation

### ISSUE THREAD

**Issue by cdtdx** [openstf/stf#301]
Hi all,

I see @vbanthia asked automation issue(below) one year ago. I want to know the progress about this. Could any developer @sorccu @lenciel @aberoham @gunta @jlhonora  help to answer this?
=================================================
Hello guys,

Thanks for this awesome tool. I had fun in setting up this locally and its quite useful for debugging my apps.

The kind of feature I wish from STF is running UI Test Suites (Appium, Robotium, monkey runner etc) parallel on multiple devices similar to services such as testdroid, AWS Device Farm etc.

For this, they provide a feature for creating custom device pool where user can create a device group of their target devices. Then you upload your apk file and test suites then they will run your test and provide test results. They also provide apis for these features which makes CI integration easier.

I think it will be really helpful to have this kind of facility On-premises. It will give better control.

I want to know if this feature or something similar to this, is in your roadmap? If it is, please share how you want to implement this. I will be glad to contribute :)

Thanks,

**Comment by vbanthia** [comment]
This is already implemented in 2.0.0 branch and will be available in next major release. If you want to use it now, then use 2.0.0 branch. To know more about its usages refer this https://github.com/openstf/stf/pull/200
