### ISSUE TITLE
some err after update sft

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#305]
I try to update stf for the new master version,but there is some problem after update  it.

INF/util:procutil 6819 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 6824 [*] Connecting to 127.0.0.1:28015
undefined:1
ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
^

SyntaxError: Unexpected token E
    at Object.parse (native)
    at Socket.handshake_callback (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/net.js:624:35)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)

/usr/local/lib/node_modules/stf/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by sorccu** [comment]
Sounds like your RethinkDB is too old, or possibly too new. Please post the exact version.

**Comment by 0x88l** [comment]
I didn't change the version of rethinkdb. And it work before  I try to  npm install sft again.

**Comment by sorccu** [comment]
When you submit a new issue, there's a template with required information. It seems like you've removed the whole template. We can't help you because you're not giving us enough information.

**Comment by gunta** [comment]
@0x88l Can you at least paste the output of `stf doctor`?

**Comment by LearnShare** [comment]
Just update RethinkDB, 2.3.0 is OK.

**Comment by 0x88l** [comment]
@gunta  NO, stf  doctor is'nt work too.  I try to del all of stf \rethinkdb  and reinstall them.But there is err when  npm download . I think that my rethinkdb(version 2.3.0) is noproblem.

**Comment by gunta** [comment]
Can you post the output of `stf doctor`?
Also can you post what error you get when "npm download"?

If you don't post any of the required information no one will be able to help you.

**Comment by 0x88l** [comment]
I have remove stf and rebuild the enviroment again. The err has been dispose off.  But I still  try  to 
recurrence this problem.

**Comment by 0x88l** [comment]
@gunta  I try to install master version that you have been updated with translation of zh_cn,but there is err like this:

INF/reaper 2289 [reaper001] Device "00664B4FEAF8" is present
INF/app 2304 [*] Using webpack
module.js:341
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/webpack.config.js:3:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/app/index.js:56:31)
    at Command.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:829:27)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1366:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
FTL/cli:local 2263 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:100:13)

**Comment by gunta** [comment]
Can you post what you get after doing `npm install` ?

**Comment by 0x88l** [comment]
Is it the log of npm install ?

**Comment by gunta** [comment]
Yes

**Comment by 0x88l** [comment]
The log:

root:~# npm install -g  --save https://github.com/openstf/stf/tarball/master
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
/usr/local/bin/stf -> /usr/local/lib/node_modules/stf/bin/stf

> jpeg-turbo@0.4.0 install /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

[jpeg-turbo] Success: "/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v47-linux-x64/jpegturbo.node" is installed via remote

> dtrace-provider@0.6.0 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node scripts/install.js


> bufferutil@1.2.1 install /usr/local/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/stf/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/stf/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/stf/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/utf-8-validate/build'

> zmq@2.14.0 install /usr/local/lib/node_modules/stf/node_modules/zmq
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/stf/node_modules/zmq/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  COPY Release/zmq.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/zmq/build'
/usr/local/lib
└─┬ stf@1.1.1
  ├─┬ adbkit@2.4.1
  │ ├── adbkit-logcat@1.0.3

**Comment by sorccu** [comment]
First, never run npm as root, it causes all kinds of things (mostly native
extension builds) not to work properly as some kind of a security measure.
Use your own user, create a separate user, or use something like the nobody
user.

Second, If you want to install from master, you have to clone the
repository first. Otherwise it might be missing some things that are
normally built before publishing. After running npm install in the repo,
run npm link and it will be accessible globally.

**Comment by 0x88l** [comment]
I use git to download the master-version and do "npm link",and it's works.Thank you sorccu's and gunta answers.

**Comment by neofreko** [comment]
Just in case someone stumble upon this issue:
* run `npm rebuild` if you switch node version
* For RethinkDB. Make sure installed rethinkdb is compatible with our rethinkdb package. In my case I'm using RethinkDB 2.2.2 against rethinkdb 2.2.0 (npm)
* For jpeg-turbo issue, don't use 6.x. use node 5.x instead

**Comment by shouse** [comment]
I got the jpeg-turbo issue and followed @neofreko advice, using node 5.x.  This was during initial install, but a search got me here so I'd like to say thanks.
