### ISSUE TITLE
add android device throught wifi

### ISSUE THREAD

**Issue by linshougeng** [openstf/stf#310]
the open-stf  just suport adding an android device through  usb-cable( or usb-hub ) ???????

how to add an android devices through wireless network (wifi ) ?? does it suport it ?

thank you very much ! !

**Comment by sorccu** [comment]
It does, with the `--allow-remote` option. However, there are several problems with that. The ADB wifi protocol is very, very slow. It can easily be 10x slower than USB. If you search the issues you can find more detailed information.

**Comment by linshougeng** [comment]
something i have to do  in my android devices ???

**Comment by sorccu** [comment]
No, just connect to it normally with `adb connect`. Just keep in mind that there's nothing we can do about the slowness.

**Comment by linshougeng** [comment]
thank you for your answer

C:\Users\Administrator>adb connect 172.27.150.58:7100
connected to 172.27.150.18:7100

it shows success ,but i can't see any devices in http://172.27.150.18:7100/#!/devices

why ??

**Comment by sorccu** [comment]
No... that's not how it works. You need to read http://developer.android.com/tools/help/adb.html#wireless. Please try to figure it out on your own, this isn't a bug and walking you through it is a huge waste of our time.
