### ISSUE TITLE
how to reboot stf 

### ISSUE THREAD

**Issue by linshougeng** [openstf/stf#314]
how to reboot stf 
start:
stf local --public-ip 172.23.150.18 --allow-remote & 

thanks for your help

**Comment by 0x88l** [comment]
killall -9 node
stf local .....

**Comment by chenpig1123** [comment]
ps aux | grep node
ps aux | grep provider
ps aux | grep device

You can see all the process about stf, you can kill just one device process, or just one provider process, or the server process.
