### ISSUE TITLE
There is a bug when upload a package over 40MB

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#317]
version：master
The webside crash down every time when you upload a package(.apk) over 40MB.

**Comment by sorccu** [comment]
When you create an issue on GitHub, there's a template that you must fill in. Without the information in the template, you're not giving us enough information to do anything about the problem without wasting hours of our own time. For example, you're saying that the website crashes. That doesn't really say anything to us. Please create a new issue and fill in the issue template, and include the log messages that show the crash.
