### ISSUE TITLE
There is a bug when upload a package over 40MB.（with info）

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#318]
I'm so sorry that haven't put the info of errs at last time.
version: master
activity: 
1.select a phone and connect ,
2.click the tab "drop file to upload".
3.Choose the a over 40MB apk package and upload
result:
when the package upload,the stf server was crash at the sametime and couldn't  visit the website
There is the err  info.
![image](https://cloud.githubusercontent.com/assets/18346467/15002519/7e6594c8-11d4-11e6-8507-a5c62ff89a32.png)

**Comment by sorccu** [comment]
I don't think the size of the package is related. The automatic launcher activity detection seems to be failing for some reason. Is there any chance you could send the `.apk` file to me?

**Comment by 0x88l** [comment]
I would sent email to you.But I have tried to install  several kinds of apk, it also crash.

**Comment by 0x88l** [comment]
It also crash that I have tried to install several kinds of apk,.





At 2016-05-04 19:22:39, "Simo Kinnunen" <notifications@github.com> wrote:


I don't think the size of the package is related. The automatic launcher activity detection seems to be failing for some reason. Is there any chance you could send the .apk file to me?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub

从网易163邮箱发来的云附件
test.apk (94.41M, 2016年5月20日 9:04 到期)
下载

**Comment by 0x88l** [comment]
There is another crash log when I tried to install the apk(test-errsocket.apk). The err log was print that socket hang up.

 

从网易163邮箱发来的云附件
test-errsocket.apk (47.82M, 2016年5月20日 10:24 到期)
下载

**Comment by sorccu** [comment]
Could you also send me the TVGames apk?

**Comment by 0x88l** [comment]
This is the tv-game that you need.
从网易163邮箱发来的云附件
TVGame for stf.apk (107.13M, 2016年5月21日 8:25 到期)
下载

**Comment by sorccu** [comment]
And which operating system and which version of Node.js are you using? You seem to have removed all the details from the template again so I'm forced to ask them one by one, which is super slow.

**Comment by 0x88l** [comment]
System: ubuntu 16.04
nodejs :v5.10.0

**Comment by sorccu** [comment]
`stf local` or full docker deployment?

**Comment by 0x88l** [comment]
I didn't have docker deployment. But I can build it on Monday.What do I need to do if I build it up?

**Comment by 0x88l** [comment]
@sorccu Hi,I have build docker. what do I need to do now ?

**Comment by chenpig1123** [comment]
Hi, about the "越南棋牌大厅体验包-4.28-10h.apk", it's funny, you can remove the "包" from the file name of your apk, then this apk file can be installed normally.

I think you want to solve this kind of problems forever, you can rename the Chinese file name to a Latin one, after you receive file and store it to /tmp on sever

And you're supposed to know the code of temp.js, aren't you?

**Comment by 0x88l** [comment]
Oh my god!!!Why didn't I think of this issue yet.Thank you for @chenpig1123 .
