### ISSUE TITLE
How the site is set to a language default?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#319]
It's possible that  I want to set 'zh_CN' for default Language ?And what should I do?

Thanks.

**Comment by gunta** [comment]
Do you mean that even if you change it to zh_CN from the UI it gets back to EN ?

**Comment by 0x88l** [comment]
I want  the first time who has logined is Chinese rather than English. Is it  possible?

**Comment by gunta** [comment]
Supposedly STF should auto-detect the browser language, however there might be a bug.

Can you paste the output you get from here: http://jsbin.com/qirazahuyi/edit?console ?

**Comment by 0x88l** [comment]
Thank you very much.

**Comment by gunta** [comment]
@0x88l so can you paste the output from here:  http://jsbin.com/qirazahuyi/edit?console ? I think there may be a bug related to the language matching.

**Comment by 0x88l** [comment]
"navigator.userAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
"navigator.language: zh-CN"
"navigator.userLanguage: undefined"
"navigator.languages: zh-CN,zh"
"navigator.browserLanguage:undefined"
"navigator.systemLanguage:undefined"
"navigator.userLanguage:undefined"

**Comment by gunta** [comment]
@0x88l So I found the bug, thank you!

**Comment by 0x88l** [comment]
@gunta  Would you update the code?
