### ISSUE TITLE
All devices get disconnected a few minutes after stf is lanuched

### ISSUE THREAD

**Issue by ohadaseo-jelly** [openstf/stf#327]
Hi!
First, Id like to note that this tool is amazing.
Well, I've been using Stf for the past two months.
I'm running it on Mac-Mini with OS X El-Capitan, 2.5 Ghz Intel Core i5 processor and 8 GB 1600 mhz DDR 3.
On the first month everything worked great, I had 1-15 devices connected at the same time.
Three weeks ago things started to get complicated.
Suddenly. All of my devices started to disconnect on after another, The log had this errors:
"WRN/util:datautil 2786 [*] Device database does not have a match for device "3404dc1ba49bc00f" (model "SM-N900"/"ha3gxx")
WRN/util:datautil 2786 [*] Device database does not have a match for device "320859920cfc518b" (model "SM-G900H"/"k3gxx")
WRN/util:datautil 2786 [*] Device database does not have a match for device "4df179475aa04fd5" (model "GT-I9300"/"m0xx")"
Id like to note that these devices are common devices who have been working great for the first month of use.
I tried updating rethinkdb version, Tried to remove Stf and rethinkdb and reinstalling, But nothing helped.
Additionally, The connection to Stf via the browser got disconnected randomly.
In sorry i couldn't you some screenshots.

Appreciate your support.
Thank You.

**Comment by sorccu** [comment]
Those are not errors. They are simple warnings saying that there's no matching entry in the device database, meaning it can't show the device name or image. It has no effect on functionality. Please try to look for the real error instead.

Mac Mini is not good for STF. In our experience you can only connect about 8 devices to a Mac Mini before it becomes unstable. Also, OS X is bad for STF because ADB's OS X implementation is very unreliable.

I don't think there's anything we can do really. You need either more hardware or different hardware for that amount of devices.

**Comment by ohadaseo-jelly** [comment]
Would you suggest using a Linux machine instead? Or even a windows?

**Comment by sorccu** [comment]
We've never tested Windows so I'm not sure how reliable it would be. I would recommend a Linux machine. Installing Linux on your Mini is an option, but the device limit is more of a hardware limit, so it won't really increase the number of devices you can use.

**Comment by ohadaseo-jelly** [comment]
So how can we explain the fact that it worked fine for 5 weeks using 12-15 devices?

**Comment by sorccu** [comment]
Sometimes you get lucky for a while. Or perhaps you started using more
devices simultaneously. Anyway, isn't random and unpredictable behavior is
the very definition of instability?

If you want to stick to a mini, I would not recommend using more than 8
devices. Combined with the difficulty of dealing with Apple's UEFI  for
anything but OS X, we consider minis nothing but a waste of time.

**Comment by ohadaseo-jelly** [comment]
OK.
Ill try a Linux machine, Thank you!

**Comment by sorccu** [comment]
Note: please read the README fully before choosing your new machine. You
don't have to use the same components, but you need to understand that
there are very complex hardware issues involved. It will help in the long
run.

**Comment by ohadaseo-jelly** [comment]
Can your recommend of a preferred Linux version to use?
Thank You!

**Comment by sorccu** [comment]
We don't have time to keep track of Linux versions, but generally we use
the latest stable kernel. I guess that would be 4.6 now. Even if an older
kernel worked better, there would eventually be a need to update it anyway.
Better to stick to latest versions.

**Comment by ohadaseo-jelly** [comment]
Thank you for your help.
