### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by korolle** [openstf/stf#328]
Write please instructions for beginners or record a video installation please.
I really liked your project. I want to test it. But I can not figure out how to run it on Linux.

**Comment by vbanthia** [comment]
Check [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) and [setup-exmaples](https://github.com/openstf/setup-examples)

**Comment by korolle** [comment]
Yes, you wrote to me how to run . But, how to install?

**Comment by 0x88l** [comment]
You can google it.
