### ISSUE TITLE
Device showing offline (device is connected to VM)

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#329]
I have STF deployed on Oracle VM box. 2 devices are connected properly and available in usb filter also. But device showing offline and then gets disconnected. 
please find below logs:
Lost device "c8ee0c84" (offline)
ADB lists a weird device : "??????"
ADB lists a weird device : "??????"
Providing all 0 device(s)

**Comment by sorccu** [comment]
The issue is not related to STF. Something is wrong with your hardware. Usually it's caused by insufficient power supply. You'll see the same by running `adb devices -l`.
