### ISSUE TITLE
how to deploy without systemd

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#33]
hi, my computer doesn't has systemd and it uses init , can stf deploy on my computer?
and my computer only has one port for public net and the port is 80, how can i deploy stf on my computer and visit it from the public net?
thank you for this wonderful project , it helps me a lot

**Comment by sorccu** [comment]
Hi,

Unfortunately we have very limited resources and are therefore only able to
document a very narrow range of possible deployments. What you can do,
though, is to take the `docker run` commands from the example unit files
and write corresponding service configs for whatever init system you're
using, or if you don't even have access to docker, just take note of the
environment variables and the stf commands. It will be a lot more tricky
without docker, though. Also, remember to replace %p and %i where
necessary, %i means the unit filename after @ (if you were using systemd)
without extension, and %p means the part before @ (or the whole name
without extension if none).

However, if you only have a single computer, you might as well use `stf
local --public-ip <your ip here>` the make things easier for yourself.
Making sure that it restarts if it dies is left to you. If you need it to
run on port 80 you could set up a simple nginx reverse proxy, or for a
super lazy solution add a `--port 80` option and run STF as root, but
that's not secure at all.

Simo

**Comment by sorccu** [comment]
Closing this ticket because we don't have the resources to test and keep up another set of deployment instructions.
