### ISSUE TITLE
Error starting stf-migrate

### ISSUE THREAD

**Issue by ktmdan** [openstf/stf#331]
I receive the following error when trying to run the stf-migrate docker. 

INF/db 1 [*] Connecting to 172.17.0.2:28015
undefined:1
ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
^

SyntaxError: Unexpected token E
    at Object.parse (native)
    at Socket.handshake_callback (/app/node_modules/rethinkdb/net.js:624:35)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Tried rethinkdb version 2.1.1 and 2.3.2.

**Comment by sorccu** [comment]
Maybe your STF version is too old.

**Comment by ktmdan** [comment]
Thanks stupid mistake.  The deployment doc should be updated to version 2.3.2

[Unit]
Description=RethinkDB
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull rethinkdb:**2.1.1**
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStartPre=/usr/bin/mkdir -p /srv/rethinkdb
ExecStartPre=/usr/bin/chattr -R +C /srv/rethinkdb
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -v /srv/rethinkdb:/data \
  -e "AUTHKEY=YOUR_RETHINKDB_AUTH_KEY_HERE_IF_ANY" \
  --net host \
  rethinkdb:**2.1.1** \
  rethinkdb --bind all \
    --cache-size 8192
ExecStop=-/usr/bin/docker stop -t 10 %p
