### ISSUE TITLE
Ignoring devices.

### ISSUE THREAD

**Issue by ktmdan** [openstf/stf#332]
I'm getting this error from the provider.  Why does it ignore devices?

May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Tracking devices
May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Found device "0123456789ABCDEF" (device)
May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Found device "0123456789ABCDEF" (device)
May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Found device "0123456789ABCDEF" (device)
May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Found device "0123456789ABCDEF" (device)
May 20 17:32:13 black-pearl docker[1311]: INF/provider 1 [*] Found device "0123456789ABCDEF" (device)
May 20 17:32:23 black-pearl docker[1311]: INF/provider 1 [*] Providing all 0 of 5 device(s); ignoring "0123456789ABCDEF", "0123456789ABCDEF", "012345

**Comment by ktmdan** [comment]
Ok so this was because it was not able to connect to the server.

**Comment by habeebshk** [comment]
hey @ktmdan was the provider not able to connect to the stf-app, can you please elaborate as i am stuck on this.
Thanks

**Comment by ktmdan** [comment]
This was years ago...  Don't remember the issue I think it was the wrong adb or something.

**Comment by pj1124** [comment]
How do you solve this problem？Thank you!
