### ISSUE TITLE
sudo npm install -g stf.error

### ISSUE THREAD

**Issue by zjj796** [openstf/stf#341]
ERR! build error 
fatal error: zmq.h: No such file or directory

stf@ubuntu:~$ sudo npm install -g stf
[sudo] password for stf: 
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
/usr/local/bin/stf -> /usr/local/lib/node_modules/stf/bin/stf

> dtrace-provider@0.5.0 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node scripts/install.js

> jpeg-turbo@0.3.2 install /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

[jpeg-turbo] Success: "/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v46-linux-x64/jpegturbo.node" is installed via remote

> bufferutil@1.2.1 install /usr/local/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/stf/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/utf-8-validate/build'

> zmq@2.15.2 install /usr/local/lib/node_modules/stf/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
compilation terminated.
zmq.target.mk:90: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/zmq
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "stf"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stf/npm-debug.log
npm ERR! code 1
stf@ubuntu:~$

**Comment by sorccu** [comment]
It says you don't have zeromq libraries installed.

**Comment by zjj796** [comment]
thanks，reinstall zeromq,then ok
