### ISSUE TITLE
remote access failed

### ISSUE THREAD

**Issue by zjj796** [openstf/stf#343]
sft run on my VMware. system is ubuntu,Real machine is windows 7
then open http://localhost:7100/, i can login on my VMware.
then open 192.168.75.128:7100 on my  windows 7. url also display http://localhost:7100/.so open failed
picture  like this
![image](https://cloud.githubusercontent.com/assets/19684548/15735962/19f7650e-28cf-11e6-84d0-9cfad28af1b4.png)

**Comment by sorccu** [comment]
When you create an issue, there's a template that you seem to have removed. It includes commonly asked questions, like "Q. How do I connect to my local STF from another computer?" which applies in this case as well.

**Comment by zjj796** [comment]
OK,thank u.Next time I will do

**Comment by zjj796** [comment]
start stf:
stf local --public-ip <your_internal_network_ip_here>
another computer can connect stf now.

**Comment by skumar1122** [comment]
Hi @zjj796 ,

I ca run Stf locally ,I am trying to run on remote and followed 

**stf local --public-ip <your_internal_network_ip_here>
stf local 10.x.x.x 10..y.y.y**
I can still see its running locally but not on remote address which i mentioned above.
Please let me know If I am doing anything wrong ?

Thanks

**Comment by perfectspr** [comment]
Maybe you need to add-R option

发自我的 iPhone

在 2017年2月9日，20:04，sk <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi @zjj796<https://github.com/zjj796> ,

I ca run Stf locally ,I am trying to run on remote and followed

stf local --public-ip <your_internal_network_ip_here>
stf local 10.x.x.x 10..y.y.y
I can still see its running locally but not on remote address which i mentioned above.
Please let me know If I am doing anything wrong ?

Thanks

**Comment by skumar1122** [comment]
@perfectspr 

Got it working now !
stf local --public-ip 10.X.X.X
