### ISSUE TITLE
Apk delete after user disconnect?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#346]
STF has been run.
Operating:
1.choose one of the device.
2.upload the apk and install it.
3.to disconnect device.
4.to choose the same device again.

Result:
Already installed app is deleted when the second use.

Question:
Whether has a feature that to del the last user's record?

**Comment by vbanthia** [comment]
It is a feature.

**Comment by 0x88l** [comment]
Thanks.

**Comment by sorccu** [comment]
We should add a flag to disable it though.

**Comment by sorccu** [comment]
Ok I finally added it. You can now use `stf local -C` or `stf local --no-cleanup`. Same for the provider unit if you run it separately. Thanks!
