### ISSUE TITLE
Not showing Visually on Browser

### ISSUE THREAD

**Issue by FaisKhan** [openstf/stf#347]
I have configured the Server in Mac OSx Yosemite it working perfectly fine.
Apk also install on my 3 android device 
Moto X2
Samsung Note 3
Samsung S4

other device i will do it later, but i am having problem on visual after running 
stf local

i can't seems to see thing on browser further it is working on console side perfectly as soon as i connect the device console automatically pics up and installs it inside the mobile device.

But still i can't see any thing only blank browser i am attaching some of my screen shot which are running
and browser can't have any html on body side...
kindly help me on this .... i have to finish one of my project....

<img width="1440" alt="screen shot 2016-06-13 at 5 45 53 pm" src="https://cloud.githubusercontent.com/assets/17251873/16034103/374412a2-3229-11e6-81bd-ac08e3995007.png">
<img width="1440" alt="screen shot 2016-06-13 at 5 45 59 pm" src="https://cloud.githubusercontent.com/assets/17251873/16034104/37baa868-3229-11e6-8a5c-337ef3588e39.png">
<img width="1440" alt="screen shot 2016-06-13 at 5 46 39 pm" src="https://cloud.githubusercontent.com/assets/17251873/16034105/37bbf344-3229-11e6-9430-ff4613354ee4.png">

Regards
Faisal

**Comment by 0x88l** [comment]
Second pic was report that path err. Have you use the stf's package.json ?

**Comment by FaisKhan** [comment]
i have download like this folder 
stf-master-3
so i have configured 
when prompt in this folder path with json file
"sudo npm install"
then i will run rethink db with same path 
and run stf local with in same path?

**Comment by FaisKhan** [comment]
i have these errors .. kindly guide me on it
ERROR in ./res/app/app.js
Module not found: Error: Cannot resolve module 'angular' in /Users/Faisal/Downloads/stf-master-4/res/app
 @ ./res/app/app.js 2:2-20

ERROR in ./res/auth/ldap/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular' in /Users/Faisal/Downloads/stf-master-4/res/auth/ldap/scripts
 @ ./res/auth/ldap/scripts/entry.js 4:2-20

ERROR in ./res/auth/mock/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular' in /Users/Faisal/Downloads/stf-master-4/res/auth/mock/scripts
 @ ./res/auth/mock/scripts/entry.js 4:2-20

ERROR in ./res/app/app.js
Module not found: Error: Cannot resolve module 'angular-route' in /Users/Faisal/Downloads/stf-master-4/res/app
 @ ./res/app/app.js 3:2-26

ERROR in ./res/auth/ldap/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-route' in /Users/Faisal/Downloads/stf-master-4/res/auth/ldap/scripts
 @ ./res/auth/ldap/scripts/entry.js 5:2-26

ERROR in ./res/auth/mock/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-route' in /Users/Faisal/Downloads/stf-master-4/res/auth/mock/scripts
 @ ./res/auth/mock/scripts/entry.js 5:2-26

ERROR in ./res/app/app.js
Module not found: Error: Cannot resolve module 'angular-touch' in /Users/Faisal/Downloads/stf-master-4/res/app
 @ ./res/app/app.js 4:2-26

ERROR in ./res/auth/ldap/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-touch' in /Users/Faisal/Downloads/stf-master-4/res/auth/ldap/scripts
 @ ./res/auth/ldap/scripts/entry.js 6:2-26

ERROR in ./res/auth/mock/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-touch' in /Users/Faisal/Downloads/stf-master-4/res/auth/mock/scripts
 @ ./res/auth/mock/scripts/entry.js 6:2-26

ERROR in ./res/web_modules/gettext/index.js
Module not found: Error: Cannot resolve module 'angular-gettext' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/gettext
 @ ./res/web_modules/gettext/index.js 1:0-26

ERROR in ./res/web_modules/angular-hotkeys/index.js
Module not found: Error: Cannot resolve module 'angular-hotkeys/build/hotkeys.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-hotkeys
 @ ./res/web_modules/angular-hotkeys/index.js 1:0-44

ERROR in ./res/web_modules/angular-hotkeys/index.js
Module not found: Error: Cannot resolve module 'angular-hotkeys/build/hotkeys.js' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-hotkeys
 @ ./res/web_modules/angular-hotkeys/index.js 3:0-43

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'bootstrap/dist/css/bootstrap.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 1:0-43

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'components-font-awesome/css/font-awesome.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 5:0-55

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'font-lato-2-subset' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 7:0-29

ERROR in ./res/web_modules/ui-bootstrap/index.js
Module not found: Error: Cannot resolve module 'angular-bootstrap/ui-bootstrap-tpls' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/ui-bootstrap
 @ ./res/web_modules/ui-bootstrap/index.js 1:0-53

ERROR in ./res/web_modules/angular-borderlayout/index.js
Module not found: Error: Cannot resolve module 'angular-borderlayout/src/borderLayout.js' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-borderlayout
 @ ./res/web_modules/angular-borderlayout/index.js 1:0-51

ERROR in ./res/web_modules/angular-borderlayout/index.js
Module not found: Error: Cannot resolve module 'angular-borderlayout/src/borderLayout.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-borderlayout
 @ ./res/web_modules/angular-borderlayout/index.js 2:0-52

ERROR in ./res/web_modules/angular-xeditable/index.js
Module not found: Error: Cannot resolve module 'angular-xeditable/dist/js/xeditable.js' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-xeditable
 @ ./res/web_modules/angular-xeditable/index.js 1:0-49

ERROR in ./res/web_modules/angular-xeditable/index.js
Module not found: Error: Cannot resolve module 'angular-xeditable/dist/css/xeditable.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-xeditable
 @ ./res/web_modules/angular-xeditable/index.js 2:0-51

ERROR in ./res/app/components/stf/device/device-service.js
Module not found: Error: Cannot resolve module 'oboe' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/device
 @ ./res/app/components/stf/device/device-service.js 1:11-26

ERROR in ./res/app/control-panes/dashboard/clipboard/index.js
Module not found: Error: Cannot resolve module 'angular-elastic' in /Users/Faisal/Downloads/stf-master-4/res/app/control-panes/dashboard/clipboard
 @ ./res/app/control-panes/dashboard/clipboard/index.js 3:0-26

ERROR in ./res/app/components/stf/common-ui/table/index.js
Module not found: Error: Cannot resolve module 'ng-table/dist/ng-table' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/common-ui/table
 @ ./res/app/components/stf/common-ui/table/index.js 2:0-40

ERROR in ./res/app/components/stf/common-ui/notifications/index.js
Module not found: Error: Cannot resolve module 'angular-animate' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/common-ui/notifications
 @ ./res/app/components/stf/common-ui/notifications/index.js 1:0-26

ERROR in ./res/app/components/stf/common-ui/enable-autofill/index.js
Module not found: Error: Cannot resolve module 'angular-cookies' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/common-ui/enable-autofill
 @ ./res/app/components/stf/common-ui/enable-autofill/index.js 1:0-26

ERROR in ./res/web_modules/ng-context-menu/index.js
Module not found: Error: Cannot resolve module 'ng-context-menu/dist/ng-context-menu' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/ng-context-menu
 @ ./res/web_modules/ng-context-menu/index.js 1:0-47

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/rect.js' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 3:0-29

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/packer.js' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 4:0-31

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/item.js' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 5:0-29

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/packery.js' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 6:14-46

ERROR in ./res/app/settings/general/local/index.js
Module not found: Error: Cannot resolve module 'angular-bootstrap/ui-bootstrap-tpls' in /Users/Faisal/Downloads/stf-master-4/res/app/settings/general/local
 @ ./res/app/settings/general/local/index.js 1:0-28

ERROR in ./res/web_modules/ng-file-upload/index.js
Module not found: Error: Cannot resolve module 'ng-file-upload/angular-file-upload-shim' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/ng-file-upload
 @ ./res/web_modules/ng-file-upload/index.js 1:0-50

ERROR in ./res/web_modules/ng-file-upload/index.js
Module not found: Error: Cannot resolve module 'ng-file-upload/angular-file-upload' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/ng-file-upload
 @ ./res/web_modules/ng-file-upload/index.js 2:0-45

ERROR in ./res/app/components/stf/logcat/logcat-service.js
Module not found: Error: Cannot resolve module 'underscore.string/index' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/logcat
 @ ./res/app/components/stf/logcat/logcat-service.js 2:9-37

ERROR in ./res/web_modules/angular-growl/index.js
Module not found: Error: Cannot resolve module 'angular-growl-v2/build/angular-growl.js' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-growl
 @ ./res/web_modules/angular-growl/index.js 1:0-50

ERROR in ./res/app/components/stf/common-ui/modals/fatal-message/index.js
Module not found: Error: Cannot resolve module 'angular-route' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/common-ui/modals/fatal-message
 @ ./res/app/components/stf/common-ui/modals/fatal-message/index.js 1:0-24

ERROR in ./res/web_modules/angular-ladda/index.js
Module not found: Error: Cannot resolve module 'angular-ladda/src/angular-ladda' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/angular-ladda
 @ ./res/web_modules/angular-ladda/index.js 3:0-42

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 1:0-17

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'd3' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 3:0-13

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'epoch/dist/css/epoch.min.css' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 4:0-39

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'epoch/dist/js/epoch.min.js' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 5:0-37

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'ng-epoch' in /Users/Faisal/Downloads/stf-master-4/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 6:0-19

ERROR in ./res/app/components/stf/angular-draggabilly/index.js
Module not found: Error: Cannot resolve module 'draggabilly' in /Users/Faisal/Downloads/stf-master-4/res/app/components/stf/angular-draggabilly
 @ ./res/app/components/stf/angular-draggabilly/index.js 1:18-40

**Comment by 0x88l** [comment]
Try "npm link" at the stf'dir.

**Comment by FaisKhan** [comment]
npm link will all those, module that are include to work for project, i am trying to install them individually also, but some of them are giving this error
Faisals-MBP:stf-master-4 Faisal$ sudo npm install ng-epoch
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng-epoch"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ng-epoch
npm ERR! 404 
npm ERR! 404  'ng-epoch' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Faisal/Downloads/stf-master-4/npm-debug.log
Faisals-MBP:stf-master-4 Faisal$

**Comment by 0x88l** [comment]
404 no found is network problem.Try to use vnp.
