### ISSUE TITLE
Cannot change orientation to Landscape for m2 note device

### ISSUE THREAD

**Issue by maryiavarabyeva** [openstf/stf#348]
Hello,

i'm trying to change orientation for m2 note device (Android 5.1) by  clicking Landscape button on STF UI, but nothing happened. If I change it manually, working fine. Also switching from Landscape to Portrait works good via button click

No changes in STF logs after clicking Landscape mode 

Thanks,
Maria

**Comment by sorccu** [comment]
Try using the `--lock-rotation` flag to make it more reliable. Otherwise the device may realize it's not actually rotated, and turn back immediately.

**Comment by sorccu** [comment]
I believe this was resolved with the comment above. Feel free to open a new issue if not.
