### ISSUE TITLE
Devices without PTP, how to connect?

### ISSUE THREAD

**Issue by pwicherski** [openstf/stf#354]
## What's the problem (or question)?

How to connect devices which don't have PTP?

## What should have happened?

Device should be able to connect to STF.

## Do you have an idea for a solution?

Nope.

## How can we reproduce the issue?

1. Connect almost any Sony device. 

## Help us understand your issue by providing context.

I can't connect device to STF.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): local
* Version used (git hash or `stf -V`): not relevant.
* Environment name and version (e.g. Chrome 39, node.js 5.4): not relevant.
* Operating System and version: Ubuntu 14.04 LTS
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here: not relevant.

**Comment by sorccu** [comment]
Operating system IS relevant.

**Comment by pwicherski** [comment]
@sorccu OK, updated.

**Comment by sorccu** [comment]
Your old ubuntu probably has libmtp installed, which changes device permissions and makes ADB unable to see them. Try running adb as root and see if anything changes.

ALL devices should be able to connect. Sometimes you have to choose between MTP and PTP mode, but one will work.

**Comment by pwicherski** [comment]
ahhh. You are right!

**Comment by PiotrOrzechowski** [comment]
Just for the record:

The other workaround is to simply get rid of libmtp  with `sudo apt-get purge --purge libmtp9 libmtp-common libmtp-runtime` ([source](http://stackoverflow.com/a/35506088)) if you don't need to use it (some devices may not be accessible with your file browser etc.).

Just remember to check if `/etc/udev/rules.d/51-android.rules` needs to be updated with your device ids ([source](https://developer.android.com/studio/run/device.html#setting-up)).

This way `adb` will be able to work properly without `root` privileges.

**Comment by sorccu** [comment]
Sure, however it's easier to check if it's the cause or not by temporarily switching to root.
