### ISSUE TITLE
Are there examples of the use of the stf parameters?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#357]
There is to many stf's parameters.But there  haven't a example of them.Can anybody provide it ?

root@boyaatest:/home/boyaa-test# stf --help

  Usage: stf [options] [command]

  Commands:

    provider [options] [serial...]          start provider
    device [options] <serial>               start device worker
    processor [options] <name>              start processor
    reaper [options] <name>                 start reaper
    triproxy [options] <name>               start triproxy
    auth-ldap [options]                     start LDAP auth client
    auth-oauth2 [options]                   start OAuth 2.0 auth client
    auth-saml2 [options]                    start SAML 2.0 auth client
    auth-mock [options]                     start mock auth client
    auth-openid [options]                   start openid auth client
    notify-hipchat [options]                start HipChat notifier
    notify-slack [options]                  start Slack notifier
    log-rethinkdb [options]                 start a rethinkdb log recorder
    poorxy [options]                        start a poor reverse proxy for local development
    app [options]                           start app
    websocket [options]                     start websocket
    storage-temp [options]                  start temp storage
    storage-s3 [options]                    start s3 storage
    storage-plugin-image [options]          start storage image plugin
    storage-plugin-apk [options]            start storage apk plugin
    migrate                                 migrates the database to the latest version
    generate-fake-device [options] [model]  generates a fake device for testing
    local [options] [serial...]             start everything locally
    doctor [options]                        diagnose issues before starting

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

**Comment by sorccu** [comment]
See stf <command> -h and/or the deployment guide
