### ISSUE TITLE
Task switcher button missing

### ISSUE THREAD

**Issue by juliusspencer** [openstf/stf#358]
## What's the problem (or question)?

I can not switch tasks / apps using a task switching button (square) on devices without software buttons. 

## What should have happened?

The button would show the list of previously used applications.

## Do you have an idea for a solution?

The menu button has been deprecated so it could be used as the switching button.
## How can we reproduce the issue?

1. Connect to a device without software buttons.
2. Open an application (A)
3. Open another application (B)
4. Try to switch to the application (A) without using the Home button.
## Help us understand your issue by providing context.

I need to be able to test using the switcher.
## Please tell us details about your environment.

Output from doctor:

```
INF/util:doctor 35838 [*] OS Arch: x64
INF/util:doctor 35838 [*] OS Platform: darwin
INF/util:doctor 35838 [*] OS Platform: 14.5.0
INF/util:doctor 35838 [*] Using Node 6.2.2
INF/util:doctor 35838 [*] Using RethinkDB client 2.3.2
INF/util:doctor 35838 [*] Using ZeroMQ 4.1.4
INF/util:doctor 35838 [*] Local ADB 1.0.36

INF/util:doctor 35838 [*] Local RethinkDB server 2.3.4
INF/util:doctor 35838 [*] ProtoBuf 2.6.1
INF/util:doctor 35838 [*] GraphicsMagick 1.3.24

```

**Comment by pwicherski** [comment]
@juliusspencer the only way I could find is to use ADB Shell Commands from within STF
`input keyevent 219`
It should bring up the application switcher dialog :)

Someone can create pull request for making this as a button.
Would love to do it, but for now I don't know how :)
Maybe someday.

**Comment by juliusspencer** [comment]
Thank you @pwicherski for the quick feedback. I'm don't know enough about how it all works. I should take a look at the source.

**Comment by zedixns** [comment]
A solution I found that I managed to test on 3 different phones is also using an ADB command but slightly different.

`adb shell input keyevent KEYCODE_APP_SWITCH`

When connected to a device using the console I've sent this command and all 3 phones responded correctly by opening the Recent Apps Screen.

I would suggest that instead of the "Menu button" there would be the "Recent button". Or at least have an option somewhere to select which button you'd like at that position.

**Comment by peterszel** [comment]
With this solution, you can change the behavior of context menu button to app switch button behavior:

1. Stop the OpenSTF server and open this file:
//usr/local/lib/node_modules/stf/node_modules/adbkit/lib/adb/keycode.js

2. Modify the value of KEYCODE_MENU to 187 (It's the value of KEYCODE_APP_SWITCH key):
KEYCODE_MENU: 187,

3. Start the server. Now you can use the lower left key for switching apps:
[screen_shot_2017-07-19_at_17_02_03](https://user-images.githubusercontent.com/15833365/28375162-13f2df68-6ca7-11e7-8391-7f96241ed8fa.png)

**Comment by sorccu** [comment]
App switch key is already there in the master branch (see [CHANGELOG.md](https://github.com/openstf/stf/blob/master/CHANGELOG.md)), which you can use either by building from source or by using the docker images. You'll then have 4 buttons in the blue bottom bar.
