### ISSUE TITLE
No direct preview on the dashboard.

### ISSUE THREAD

**Issue by prutapptic** [openstf/stf#36]
I'm trying to use STF with a tablet Asus Nexus 7 with Android 4.2.2.
The device is controllable but the preview is grey and always grey.
See this attachment: 
![capture d ecran 2015-07-27 a 17 49 50](https://cloud.githubusercontent.com/assets/13520796/8910896/a9adc28c-3489-11e5-8e6e-81fa957c3e79.png)

**Comment by sorccu** [comment]
Weird, we have the same device and it works. Can you open the developer tools in Chrome and see if you might have some sort of errors in the console?

**Comment by prutapptic** [comment]
It seems that there're no error in chrome.

![capture d ecran 2015-07-27 a 18 08 52](https://cloud.githubusercontent.com/assets/13520796/8911097/a8a4cb64-348a-11e5-8687-77381c760cd4.png)

**Comment by sorccu** [comment]
Could you try in incognito mode (and make sure no extensions are enabled) just to see if it makes a difference? We had something similar happen a long long time ago and that was the reason.

**Comment by jonalmeida** [comment]
@sorccu This is the same issue that I'm seeing that I mentioned in #31 .
![screen shot 2015-07-26 at 21 37 35](https://cloud.githubusercontent.com/assets/1370580/8918962/9849c810-3470-11e5-9dc4-a6f8578e9f2a.png)

**Comment by sorccu** [comment]
Can one of you guys (or both) provide the full output from `stf local`, up to where you attempt to use the device and only see gray? There shouldn't be any private information there except perhaps usernames in paths, although more importantly your phone's IMEI and phone number may be visible if the device wasn't found in our database.

**Comment by jonalmeida** [comment]
@sorccu Here is the output: https://gist.github.com/jonalmeida/38ea576eeba5dedc4c43

It includes the the shutdown logging as well right after startup.

**Comment by sorccu** [comment]
Did you attempt to use the device when that log was being captured? I'm not seeing any evidence of the screen WebSocket being used (or actually the device being used at all).

**Comment by sorccu** [comment]
I need the log to be able to say anything, but could you pull the latest master from Git and try `stf local --provider-min-port 15000 --provider-max-port 25000`? Perhaps a firewall/iptables/something is blocking one of the default ports (7400-7700). I wouldn't say it's very likely but worth a try anyway.

**Comment by sorccu** [comment]
FWIW here's the same Nexus 7 with the same Android version running in our system.

![screen shot 2015-07-28 at 12 40 23 pm](https://cloud.githubusercontent.com/assets/32509/8923043/3dcf3ac6-3526-11e5-8faf-6eb3ae02aac0.jpg)

**Comment by jonalmeida** [comment]
Here are logs with some interaction that shows up on the device, but I still can't see anything here. (This is via `stf local` only though): https://gist.github.com/jonalmeida/278f7b8eef52913886e2

**Comment by jonalmeida** [comment]
@sorccu Here are logs with the min and max ports set on a Galaxy Nexus (which shows the grey) followed by a Nexus 5 (which works fine): https://gist.github.com/jonalmeida/86fb7e11cc0eb7d97065

**Comment by sorccu** [comment]
Here's my Galaxy Nexus working fine. :(

![screen shot 2015-07-28 at 2 15 49 pm](https://cloud.githubusercontent.com/assets/32509/8924035/a4e7e304-3533-11e5-97a4-c269408a28af.jpg)

**Comment by sorccu** [comment]
I'm closing this ticket in favor of the earlier #31. Let's continue there.
