### ISSUE TITLE
Not able to connect more than 10 devices to ubuntu

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#360]
I want to connect 50 devices using local STF to the HP Elite Desk 800 G2 having ubuntu 14.0 LTS installed on it. on UI it shows **preparing** and **offline**. Could you please tell me what was the reason behind this?

We are using plugable usb 7 port hub, 32 GB RAM, i7 processor.

**Comment by sorccu** [comment]
Your processor sucks. Get a PCIe USB card or you're just wasting your own time. Additionally, #354 may be related.

**Comment by sorccu** [comment]
Or more precisely, the chipset sucks. Recent consumer Intel chipsets are not good with a large number of USB devices.
