### ISSUE TITLE
after gulp build,stf local wrong

### ISSUE THREAD

**Issue by zjj796** [openstf/stf#361]
after gulp build,stf local wrong

few days ago, download the code form openstf. 
sudo gulp build
few errors

then
res/web_modules/epoch/index.js
//require('ng-epoch')
res/web_modules/nine-bootstrap/index.js
//require('font-lato-2-subset')

sudo gulp build
no error

stf local
![image](https://cloud.githubusercontent.com/assets/19684548/16612596/55182c14-439a-11e6-9052-c88d012ba240.png)

![image](https://cloud.githubusercontent.com/assets/19684548/16612622/6ed619ae-439a-11e6-9ee4-b1c1b4e65ad2.png)

ubuntu
npm@3.9.5
node 6.2.2
gulp 3.9.1

thanks

**Comment by sorccu** [comment]
You updated your Node.js and now the native extensions that were built for an older version no longer work.

Remove the `node_modules` folder and run `npm install` again.
