### ISSUE TITLE
Error: Cannot find module 'zmq'

### ISSUE THREAD

**Issue by niuniudd** [openstf/stf#363]
when I start stf by command：stf lcoal，output:
root@dupeng-OptiPlex-3020:/home/dd/zeromq-4.1.4# stf local
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js migrate"
INF/db 20886 [*] Connecting to 127.0.0.1:28015
INF/db:setup 20886 [*] Database "stf" already exists
INF/db:setup 20886 [*] Table "users" already exists
INF/db:setup 20886 [*] Table "accessTokens" already exists
INF/db:setup 20886 [*] Table "vncauth" already exists
INF/db:setup 20886 [*] Table "devices" already exists
INF/db:setup 20886 [*] Table "logs" already exists
INF/db:setup 20886 [*] Index "users"."adbKeys" already exists
INF/db:setup 20886 [*] Index "accessTokens"."email" already exists
INF/db:setup 20886 [*] Index "vncauth"."response" already exists
INF/db:setup 20886 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 20886 [*] Waiting for index "users"."adbKeys"
INF/db:setup 20886 [*] Waiting for index "accessTokens"."email"
INF/db:setup 20886 [*] Waiting for index "vncauth"."response"
INF/db:setup 20886 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 20886 [*] Index "devices"."owner" already exists
INF/db:setup 20886 [*] Index "devices"."present" already exists
INF/db:setup 20886 [*] Index "devices"."providerChannel" already exists
INF/db:setup 20886 [*] Index "users"."adbKeys" is ready
INF/db:setup 20886 [*] Waiting for index "devices"."owner"
INF/db:setup 20886 [*] Waiting for index "devices"."present"
INF/db:setup 20886 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 20886 [*] Index "accessTokens"."email" is ready
INF/db:setup 20886 [*] Index "vncauth"."response" is ready
INF/db:setup 20886 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 20886 [*] Index "devices"."owner" is ready
INF/db:setup 20886 [*] Index "devices"."present" is ready
INF/db:setup 20886 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js provider --name dupeng-OptiPlex-3020 --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 20880 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
module.js:442
    throw err;
    ^

Error: Cannot find module 'zmq'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/lib/util/zmqutil.js:7:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/lib/units/triproxy/index.js:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
FTL/cli:local 20880 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
INF/cli:local 20880 [*] Shutting down all child processes

**I used 2 ways to install zmq,but also get the error：cannot find module ‘zmq’**：

1. npm install zmq 

root@dd-OptiPlex-3020:/home/dd/zeromq-4.1.5# npm install zmq

> zmq@2.15.3 install /home/dd/node_modules/zmq
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/dupeng/node_modules/zmq/.node-gyp"
make:进入目录'/home/dd/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  COPY Release/zmq.node
make:离开目录“/home/dd/node_modules/zmq/build”
/home/dd
└── zmq@2.15.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/dd/package.json'
npm WARN dd No description
npm WARN dd No repository field.
npm WARN dd No README data
npm WARN dd No license field.

2. install from source

I download the source,version:4.1.5
used these commands:
./configure
make
make install
ldconfig
output：
root@dupeng-OptiPlex-3020:/home/dd/zeromq-4.1.5# make install
Making install in doc
make[1]: 正在进入目录 `/home/dd/zeromq-4.1.5/doc'
make[2]: 正在进入目录 `/home/dd/zeromq-4.1.5/doc'
make[2]: 没有什么可以做的为 `install-exec-am'。
test -z "/usr/local/share/man/man3" || /bin/mkdir -p "/usr/local/share/man/man3"
test -z "/usr/local/share/man/man7" || /bin/mkdir -p "/usr/local/share/man/man7"
make[2]:正在离开目录 `/home/dd/zeromq-4.1.5/doc'
make[1]:正在离开目录 `/home/dd/zeromq-4.1.5/doc'
make[1]: 正在进入目录 `/home/dd/zeromq-4.1.5'
make[2]: 正在进入目录 `/home/dd/zeromq-4.1.5'
test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libzmq.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libzmq.so.5.0.1 /usr/local/lib/libzmq.so.5.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libzmq.so.5.0.1 libzmq.so.5 || { rm -f libzmq.so.5 && ln -s libzmq.so.5.0.1 libzmq.so.5; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libzmq.so.5.0.1 libzmq.so || { rm -f libzmq.so && ln -s libzmq.so.5.0.1 libzmq.so; }; })
libtool: install: /usr/bin/install -c .libs/libzmq.lai /usr/local/lib/libzmq.la
libtool: install: /usr/bin/install -c .libs/libzmq.a /usr/local/lib/libzmq.a
libtool: install: chmod 644 /usr/local/lib/libzmq.a
libtool: install: ranlib /usr/local/lib/libzmq.a
libtool: finish: PATH="/home/dd/android-sdk-linux/tools:/home/dd/android-sdk-linux/platform-tools:/home/dd/jdk1.8.0_91/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/protobuf/bin/:/sbin" ldconfig -n /usr/local/lib
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /bin/bash ./libtool   --mode=install /usr/bin/install -c curve_keygen '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/curve_keygen /usr/local/bin/curve_keygen
test -z "/usr/local/include" || /bin/mkdir -p "/usr/local/include"
 /usr/bin/install -c -m 644 include/zmq.h include/zmq_utils.h '/usr/local/include'
test -z "/usr/local/lib/pkgconfig" || /bin/mkdir -p "/usr/local/lib/pkgconfig"
 /usr/bin/install -c -m 644 src/libzmq.pc '/usr/local/lib/pkgconfig'
make[2]:正在离开目录 `/home/dd/zeromq-4.1.5'

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
stf local
* Version used (git hash or `stf -V`): 
stf：1.1.1
npm:3.10.3
node:6.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
Ubuntu 14.0.4 64bit

**Comment by 0x88l** [comment]
Enter "stf doctor" and paste at this post.

**Comment by niuniudd** [comment]
root@dd-OptiPlex-3020:/home/dd# npm install --unsafe-perm -g stf
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
/usr/local/bin/stf -> /usr/local/lib/node_modules/stf/bin/stf
- qs@6.1.0 node_modules/stf/node_modules/request/node_modules/qs
/usr/local/lib
└─┬ stf@1.1.1 
  ├─┬ jpeg-turbo@0.3.2
  │ └── nan@2.4.0 
  ├── ldapjs@0.7.1  (git+https://github.com/mcavage/node-ldapjs.git#acc1ca8f4314fd9d67561feabc8ce4c235076a5e)
  ├── request@2.73.0 
  └─┬ zmq@2.15.3
    └── nan@2.3.5 

root@dd-OptiPlex-3020:/home/dd# stf doctor
root@dd-OptiPlex-3020:/home/dd# 

I install stf again,the command "stf doctor" output is nothing

**Comment by codeskyblue** [comment]
well, you need install zmq like `brew install zeromq`

**Comment by niuniudd** [comment]
I used 2 ways to install zmq,but also get the error：cannot find module ‘zmq’, I pasted the output.

**Comment by niuniudd** [comment]
...When I reboot the system,stf is running successul,I don`t know why,Now I close this question
