### ISSUE TITLE
Problem in Running Ladp locally

### ISSUE THREAD

**Issue by darshansr** [openstf/stf#371]
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/ldap/ --websocket-url http://localhost:7110/"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js storage-temp --port 7102"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/util:procutil 2456 [*] Forking "/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/cli.js scheduler scheduler --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"

  error: missing required argument `--secret'

FTL/cli:local 2456 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/vphilips/Desktop/stf_development/stf_ladp_local/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
INF/cli:local 2456 [*] Shutting down all child processes

**Comment by sorccu** [comment]
You can see the issue right there in the log. Also, next time please format the log output by wrapping it within ```.
