### ISSUE TITLE
STF server is going down after 24 hours on Ubuntu box

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#373]
Hi STF team,
I downloaded the code from master branch followed below steps:

1. npm install
2. npm link
3. cd bin
4. ./stf local --public-ip ip_address

but after 24 hours server goes down, STF log stops. And I am getting below error in rethinkdb 
**The issue reported is: Some RethinkDB data on this server has been placed into swap memory in the past hour. This may impact performance.**

Now I am sure this is happening because of rethinkdb error OR problem with ubuntu. I am having another STF running from 3 week over mac connected with 30 devices :) but over mac I installed STF using npm install stf -g. What could be the reason? How can I keep STF continuously running over a week.

**Comment by sorccu** [comment]
`stf local` is for development only, it isn't meant to be used for a 24/7 deployment. It MIGHT work, but it might not. For stability, you'd want a full deployment (see the deployment guide).

Anyway make sure that all output gets fully consumed. I remember one case from a really long time ago (should not happen anymore) where we were using another tool (perhaps nodemon, can't be sure anymore) to keep the program up and running. However, that program had some kind of a bug or misconfiguration, and it would run out of buffer space entirely. The program would then get blocked permanently and nothing would work. Make sure you're not doing something similar.

**Comment by tadesushilgithub** [comment]
No I am not doing anything like nodemon. I thought STF stops because of rethinkdb error related to SWAP memory. I will try to fix SWAP memory issue then l'll see how may days stf local continuously works on ubuntu box.
**Please clear my below mentioned doubt :**
But I have scenario like Ubuntu-1 has 20 devices + Ubuntu-2 has 20 devices. Can Deployment guide helps us to bring both 2 boxes under 1 url, Where I can see total 40 devices after login?. I got success using Deployment guide help in setting up the STF in Mac OS but Failed in Ubuntu.
