### ISSUE TITLE
How to find stf'icon name and pictures?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#375]
I want use the Icon of stf,but I can't find them.  (Some jade'Icon corresponding list of names  like 'fa-gears' ,'fa-upload' ,etc.)
![image](https://cloud.githubusercontent.com/assets/18346467/17098522/63926eda-5295-11e6-808b-624c67e976b8.png)

**Comment by sorccu** [comment]
They're from http://fontawesome.io/. May be a bit out of date but you should be able to use most of the icons listed there.
