### ISSUE TITLE
Unrecognized key format adb 

### ISSUE THREAD

**Issue by Bluesmile82** [openstf/stf#379]
## What's the problem (or question)?

Im trying to add a adb key but the app is not recognising the format. The last part of the file reads like:
= name@name.host.com
 
## What should have happened?

It should accept my key. The popup is closing without any answer.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here: 
I am accessing through other computer using stf local with a public ip

**Comment by sorccu** [comment]
Create a new key you're not using and post it here so we can see what it
looks like.

**Comment by Bluesmile82** [comment]
Ok. I regenerated it and its working now. I dont know why. It was maybe corrupted. Thanks
