### ISSUE TITLE
Where is the code about the remote adb debug?

### ISSUE THREAD

**Issue by likezjuisee** [openstf/stf#381]
Use adb connect to connect to a remote device as if it was plugged in to your computer, regardless of ADB mode and whether you're connected to the same network
Run any adb command locally, including shell access
Android Studio and other IDE support, debug your app while watching the device screen on your browser
Supports Chrome remote debug tools

If I want to learn this function, so could you tell me where is the relative code in the project? Thx.

**Comment by sorccu** [comment]
It's in adbkit, one of our dependencies.

**Comment by likezjuisee** [comment]
Could you show me the detail? I am not very clearly yet.

**Comment by sorccu** [comment]
Look, we went through all the trouble to research everything, spending days
if not weeks looking at packet captures, then we actually built it by
ourselves, and finally gave it away for free. Surely you can do a little
grepping to find out where it is?

Alternatively we can provide detailed advice at a hourly rate.

**Comment by likezjuisee** [comment]
OK, I got it.

**Comment by sorccu** [comment]
If you find a bug or want to expand the features, then feel free to ask for help. But we don't provide help if it's something you can look up relatively easily by yourself, because that takes time and doesn't improve the project.
