### ISSUE TITLE
Need to get device custom name so that It can be identified on rack

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#384]
I have 20 devices connected sometimes some devices goes offline means 20 becomes 17 but it's very critical to know which device goes offline. So I renamed devices by setting up there custom name like RACK1DEV3 so that it would be Identified. But I need to extract that and bring it to UI. So I went through some adb getprop i couldn't found. 
My question if I need to bring device name in UI do I need to change stf.apk? or adb getprop can help me so that I'll write API to get that.

**Comment by sorccu** [comment]
Perhaps you could use the notes column in the detailed view. Double click the value (empty by default) and you should be able to enter a note for each device.

**Comment by sorccu** [comment]
Also, if the devices go offline often, but you only have 20 devices, then it's probably a hardware issue.

**Comment by tadesushilgithub** [comment]
But the problem is that User's are often change the Note value every time. Can I get Device name from Android?. The reason of devices goes offline is H/W issue only because I seen that device is not getting connected to the same server but if I remove and add to another server it's work fine and after some days again goes offline :(. I kept usb connection in MTP mode.

**Comment by sorccu** [comment]
What do you mean by device name? What is the value you want to see?

**Comment by tadesushilgithub** [comment]
Please find the Images for more clarity. 

![snap1](https://cloud.githubusercontent.com/assets/17309586/17275077/fd06fed2-56c8-11e6-9c16-c46094d28ea7.jpg)
![snap2](https://cloud.githubusercontent.com/assets/17309586/17275078/fd5d7a50-56c8-11e6-8be8-0a934cefb760.jpg)

**Comment by sorccu** [comment]
Interesting problem, but it looks like it isn't a standard Android feature, and therefore there's no API to access the user-specified device name. Some have had success accessing the bluetooth adapter's device name.

**Comment by tadesushilgithub** [comment]
Ok Thanks @sorccu

**Comment by sorccu** [comment]
I think one way you could do it would be to use Contacts, and look up the device owner's profile or a specific contact. You could then use the contact fields to store information.

Alternatively if you're OK with building your own app, you could just store it in a local file, database or wherever.

**Comment by tadesushilgithub** [comment]
Ya I will try that :).
