### ISSUE TITLE
How do i implement Logout functionality in stf?

### ISSUE THREAD

**Issue by darshansr** [openstf/stf#389]
## What's the problem (or question)?
I need to do logout for a ldap user,

## What should have happened?
i cleared browser side cookies but i know it wont work,
i need to know is their any service method to clear all the session,cookies related information,
Or is their any other solution for Logout,
so that all the devices should be disconnected after he/she logout.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by vbanthia** [comment]
Basically your requirement is to release all user devices once he leaves STF.

I don't think your current idea of logout will serve your requirements as deleting session from browser will not change device owner in STF's database. So, if you want to release all user device you will have to implement a new websocket message something like [this](https://github.com/openstf/stf/blob/master/lib/units/websocket/index.js#L188-L199) which will tell backend to update all current holding devices ownership.

Once you are done with this implementation, you can add a new button something like "Stop Using All" in device list which will call above implemented message.

Anyways, currently STF releases all the device which are not being used for `--group-timeout` time which is `15 mins` by default. So, even if a user forget to release device before leaving STF, that device will be released after 15 mins.

**Comment by darshansr** [comment]
Thank you Vbanthia ,
But i need to do something like below,
![image](https://cloud.githubusercontent.com/assets/13946586/17472183/1696b906-5d67-11e6-82eb-a74c12d783e7.png)
i tried clearing cookies info manually on developer options in chrome, because of that i am login with new session id's,and all other details.
By using $cookies.getAll() and cookies.remove(k) its clearing all cookies on client side, but still i can go back to the previous sessions.
How do i over come this, do i need to clear server side sessions also?,
is there any method to do ?

**Comment by darshansr** [comment]
thank you

**Comment by le91688** [comment]
did you ever implement this?
