### ISSUE TITLE
Support downloading files from a specific device path

### ISSUE THREAD

**Issue by gunta** [openstf/stf#39]
We support pushing files (currently only APK files), so might as well support pulling a file from a path.

**Comment by vrunoa** [comment]
What about adding a section **Folders** (like Dashboard, Screenshots, Automation, Advanced & Info)  and use ```adb shell ls``` to list all of them and each folder, for ex. ```adb shell ls sdcard```. 
And then on each file(that the user can access) use ```adb pull``` ?

**Comment by gunta** [comment]
Yes, in the end a **File Explorer** is in the roadmap. Something like [this](http://zendelsolutions.com/zendel/projects/angular-filemanager/).

**Comment by vrunoa** [comment]
I got the same in mind. Is anybody already implementing this or can I take the lead ?

**Comment by gunta** [comment]
@vrunoa Right now we have few resources, so the answer is no. 
Contributions are welcome! 
If you need any help implementing or have any questions don't hesitate to ask here.

**Comment by vrunoa** [comment]
Yeah, I meant as contribution @gunta . I'll create a fork and a branch called "FileExplorer" and let you know when I got something implemented for you guys to test.

**Comment by gunta** [comment]
We appreciate any contribution. Thank you for your work and looking forward to it.

**Comment by codeskyblue** [comment]
@vrunoa Any progress on this issue?

**Comment by vrunoa** [comment]
hey @codeskyblue , tonight i'll commit some implementations I made.

**Comment by codeskyblue** [comment]
@vrunoa good. currently I only finished download file from a specific path. but list and file explorer not done any yet.

**Comment by rseek** [comment]
File Explorer added in https://github.com/openstf/stf/pull/89 and it is very useful;
Though it supports only downloading files.
Uploading files (not only .apk) would be very useful feature too

**Comment by codeskyblue** [comment]
Should this issue closed, because there is FileExplorer now.

**Comment by sorccu** [comment]
True, I'll close it. However it seems that it doesn't quite work an all recent Android versions, I've had trouble getting it to work on Nexus 5S running Android 7. The list is always empty. But I think that should be a separate issue. Thanks!

**Comment by codeskyblue** [comment]
My pleasure. Great work for the STF team.
