### ISSUE TITLE
Error in gulpfile.js after gulp is upgraded to v4

### ISSUE THREAD

**Issue by darshansr** [openstf/stf#395]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by vbanthia** [comment]
gulp v4 is not released yet. Any specific reason to use unreleased version? Also, what are the errors?

**Comment by darshansr** [comment]
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: run:checkversion

No specific reason i just updated it.After updating got an error.
I looked at all possible solutions,tried changes in gulpfile.js file still getting same error.

Any solution please.

**Comment by sorccu** [comment]
Run `./node_modules/.bin/gulp` instead of your global gulp. So, e.g. `./node_modules/.bin/gulp clean` would be equivalent to `gulp clean`.

**Comment by darshansr** [comment]
thank you
