### ISSUE TITLE
Can't start freshly built STF because of webpack

### ISSUE THREAD

**Issue by gounthar** [openstf/stf#40]
Hi,

here is the log:
 stf local
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js migrate"
INF/db 24095 [*] Connecting to 127.0.0.1:28015
INF/db:setup 24095 [*] Database "stf" already exists
INF/db:setup 24095 [*] Table "users" already exists
INF/db:setup 24095 [*] Table "devices" already exists
INF/db:setup 24095 [*] Table "logs" already exists
INF/db:setup 24095 [*] Index "users"."adbKeys" already exists
INF/db:setup 24095 [*] Index "devices"."owner" already exists
INF/db:setup 24095 [*] Index "devices"."present" already exists
INF/db:setup 24095 [*] Index "devices"."providerChannel" already exists
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js provider --name ubuntu --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 24092 [*] Forking "/usr/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 24098 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 24098 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 24098 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/triproxy 24099 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 24099 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 24099 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/reaper 24104 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 24104 [reaper001] Reaping devices with no heartbeat
INF/db 24104 [reaper001] Connecting to 127.0.0.1:28015
INF/db 24103 [proc002] Connecting to 127.0.0.1:28015
INF/reaper 24104 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 24104 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/processor 24103 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 24103 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/db 24100 [proc001] Connecting to 127.0.0.1:28015
INF/processor 24100 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 24100 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/poorxy 24122 [*] Listening on port 7100
INF/storage:plugins:image 24120 [*] Listening on port 7103
INF/auth-mock 24106 [*] Listening on port 7120
INF/storage:temp 24115 [*] Listening on port 7102
INF/storage:plugins:apk 24121 [*] Listening on port 7104
INF/provider 24105 [*] Subscribing to permanent channel "O6uuMWGCQiygamxH7OprEA=="
INF/provider 24105 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 24105 [*] Receiving input from "tcp://127.0.0.1:7114"
INF/provider 24105 [*] Tracking devices
INF/provider 24105 [*] Found device "0146B5681401101C" (offline)
INF/reaper 24104 [reaper001] Device "0146B5681401101C" is present
INF/provider 24105 [*] Registered device "0146B5681401101C"
INF/app 24107 [*] Using webpack
module.js:338
    throw err;
    ^
Error: Cannot find module './../../../webpack.config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/lib/node_modules/stf/lib/units/app/index.js:56:31)
    at Command.<anonymous> (/usr/lib/node_modules/stf/lib/cli.js:627:27)
    at Command.listener (/usr/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/lib/node_modules/stf/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib/node_modules/stf/lib/cli.js:1102:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
FTL/cli:local 24092 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
INF/cli:local 24092 [*] Shutting down all child processes
INF/util:lifecycle 24098 [app001] Winding down for graceful exit
INF/util:lifecycle 24103 [proc002] Winding down for graceful exit
INF/util:lifecycle 24100 [proc001] Winding down for graceful exit
INF/util:lifecycle 24105 [*] Winding down for graceful exit
INF/util:lifecycle 24104 [reaper001] Winding down for graceful exit
INF/util:lifecycle 24106 [*] Winding down for graceful exit
INF/auth-mock 24106 [*] Waiting for client connections to end
WRN/db 24104 [reaper001] Connection closed
INF/db 24104 [reaper001] Connecting to 127.0.0.1:28015
WRN/db 24100 [proc001] Connection closed
INF/db 24100 [proc001] Connecting to 127.0.0.1:28015
INF/websocket 24110 [*] Subscribing to permanent channel "*ALL"
INF/websocket 24110 [*] Listening on port 7110
INF/util:lifecycle 24110 [*] Winding down for graceful exit
INF/db 24110 [*] Connecting to 127.0.0.1:28015

But... webpack seems to be installed:
npm install webpack -g
npm WARN optional dep failed, continuing fsevents@0.3.6
/usr/bin/webpack -> /usr/lib/node_modules/webpack/bin/webpack.js
webpack@1.10.5 /usr/lib/node_modules/webpack
├── interpret@0.6.5
├── tapable@0.1.9
├── clone@1.0.2
├── memory-fs@0.2.0
├── supports-color@3.1.0 (has-flag@1.0.0)
├── async@1.4.0
├── enhanced-resolve@0.9.0 (graceful-fs@3.0.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── webpack-core@0.6.6 (source-list-map@0.1.5, source-map@0.4.4)
├── watchpack@0.2.8 (graceful-fs@3.0.8, async@0.9.2, chokidar@1.0.5)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── esprima@1.2.5
└── node-libs-browser@0.5.2 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, os-browserify@0.1.2, string_decoder@0.10.31, process@0.11.1, domain-browser@1.1.4, punycode@1.3.2, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.1, stream-browserify@1.0.0, events@1.0.2, vm-browserify@0.0.4, console-browserify@1.1.0, util@0.10.3, http-browserify@1.7.0, readable-stream@1.1.13, url@0.10.3, buffer@3.3.1, browserify-zlib@0.1.4, crypto-browserify@3.2.8)

Can you help?
Thanks.

**Comment by sorccu** [comment]
Hi,

What does `stf -V` output?

**Comment by gounthar** [comment]
Hi,
stf -V
1.0.7

**Comment by sorccu** [comment]
Did you install from NPM with `npm install -g stf`? I just tried it and it works on my computer.

**Comment by gounthar** [comment]
No, I built it.
I went and installed with your command, and it now works.
Go figure. ;-)
Thanks.

**Comment by sorccu** [comment]
Glad you got it working. Can I ask how you built it? From the logs it looks like you managed to install it globally after building, could you post the commands you used so that we can anticipate this in the future?

**Comment by gounthar** [comment]
Well, I did it on an Ubuntu while using the root user I'm afraid.
sudo -E npm install -g
sudo -E bower --allow-root install
