### ISSUE TITLE
Samsung Galaxy Core Prime SM-G361H does not work

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#404]
Hi,

I am facing disconnection issue with one of our device having Android [5.1.1.] It's happening frequently.

WRN/device:plugins:screen:stream 3689 [4200e52bc6b51300] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Disconnecting from minicap service
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Stopping minicap service
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Launching screen service
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "PID: 14180"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: Using projection 480x800@464x773/0"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:240) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Connecting to minicap service
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:243) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:250) Creating virtual display"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:256) Creating buffer queue"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:261) Creating CPU consumer"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1154052 bytes for JPG encoder"
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Reading minicap banner
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
WRN/device:plugins:screen:stream 3689 [4200e52bc6b51300] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 3689 [4200e52bc6b51300] Disconnecting from minicap service
FTL/device:plugins:screen:stream 3689 [4200e52bc6b51300] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/lib/units/device/plugins/screen/stream.js:222:26)
    at FailCounter.emit (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/lib/units/device/plugins/screen/stream.js:215:24)
    at RiskyStream.emit (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/Users/apple/Desktop/stf 2.0.0/stf-2.0.0/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FTL/util:lifecycle 3689 [4200e52bc6b51300] Shutting down due to fatal error
INF/provider 3679 [_] Cleaning up device worker "4200e52bc6b51300"
ERR/provider 3679 [_] Device worker "4200e52bc6b51300" died with code 1
INF/provider 3679 [_] Restarting device worker "4200e52bc6b51300"
INF/device:support:push 3700 [4200e52bc6b51300] Sending output to "tcp://127.0.0.1:7116"
INF/device 3700 [4200e52bc6b51300] Preparing device
INF/device:support:sub 3700 [4200e52bc6b51300] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 3700 [4200e52bc6b51300] Subscribing to permanent channel "_ALL"
INF/device:support:properties 3700 [4200e52bc6b51300] Loading properties
INF/device:support:abi 3700 [4200e52bc6b51300] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 3700 [4200e52bc6b51300] Checking whether we need to install STFService
INF/device:resources:service 3700 [4200e52bc6b51300] Running version check
INF/device:resources:service 3700 [4200e52bc6b51300] STFService up to date
INF/device:plugins:service 3700 [4200e52bc6b51300] Launching agent
INF/device:plugins:service 3700 [4200e52bc6b51300] Launching service
INF/device:plugins:service 3700 [4200e52bc6b51300] Agent says: "Listening on port 1090"
INF/device:plugins:service 3700 [4200e52bc6b51300] Agent says: "InputClient started"
INF/device:plugins:display 3700 [4200e52bc6b51300] Reading display info
INF/device:plugins:phone 3700 [4200e52bc6b51300] Fetching phone info
INF/device:plugins:identity 3700 [4200e52bc6b51300] Solving identity
INF/device:plugins:solo 3700 [4200e52bc6b51300] Subscribing to permanent channel "n7snQ6axOe/KuOMySYWdGnU5520="
INF/device:plugins:screen:stream 3700 [4200e52bc6b51300] Starting WebSocket server on port 7404
WRN/device:plugins:data 3700 [4200e52bc6b51300] Unable to find device data { serial: '4200e52bc6b51300',
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  operator: ',',
  model: 'SM-G361H',
  version: '5.1.1',
  abi: 'armeabi-v7a',
  sdk: '22',
  product: 'coreprimeve3gxx',
  display: 
   { id: 0,
     width: 480,
     height: 800,
     xdpi: 203.1999969482422,
     ydpi: 203.1999969482422,
     fps: 60.000999450683594,
     density: 1.5,
     rotation: 0,
     secure: true,
     size: 4.591300773557018,
     url: 'ws://localhost:7404' },
  phone: { imei: '352724070788533', network: 'UNKNOWN' } }
INF/device:plugins:touch 3700 [4200e52bc6b51300] Touch origin is top left
INF/device:plugins:touch 3700 [4200e52bc6b51300] Requesting touch consumer to start
INF/device:plugins:touch 3700 [4200e52bc6b51300] Launching screen service
INF/device:plugins:touch 3700 [4200e52bc6b51300] Connecting to minitouch service
INF/device:plugins:touch 3700 [4200e52bc6b51300] minitouch says: "Type B touch device sec_touchscreen (479x799 with 10 contacts) detected on /dev/input/event2 (score 1100)"
INF/device:plugins:touch 3700 [4200e52bc6b51300] minitouch says: "Connection established"
![devicedisconnection](https://cloud.githubusercontent.com/assets/17309586/17745070/7b7a4d48-6478-11e6-8c15-562db850a647.JPG)

**Comment by sorccu** [comment]
I think that device probably doesn't work.

**Comment by sorccu** [comment]
Probably the same issue as #366.

**Comment by tadesushilgithub** [comment]
hey @sorccu could you please see the comments. I am seeing here every time mincap is going down and while starting it's facing issues.

**Comment by sorccu** [comment]
Like I said, that device doesn't work. Same issue happens on some other low-end Samsung devices as well.

**Comment by sorccu** [comment]
No need to close the issue, it's useful as a reminder. But for now I'm not sure if we can do anything about it.

**Comment by major-laslo** [comment]
Same issue is present with Samsung Galaxy S5 Neo (also with 5.1.1). It seems that it's triggered once you start interacting with the device in the web interface - The connection is stable without that...you can deploy/start the app and interact through adb.

**Comment by sorccu** [comment]
Both should be fixed in STF 2.2.0 :)
