### ISSUE TITLE
cleanup installed apk when you stop using the device

### ISSUE THREAD

**Issue by gvegaq86** [openstf/stf#406]
Hi, After installing an apk and stop using it, when income back to the apk device is not already installed.

**Comment by sorccu** [comment]
Use the `--no-cleanup` option when starting STF.

**Comment by gvegaq86** [comment]
I tried this option but fails.

geovani@geovani-Vostro-3350:~$ stf local --no-cleanup --public-ip 172.16.99.135
  error: unknown option `--no-cleanup'

**Comment by sorccu** [comment]
Your STF is too old, then.
