### ISSUE TITLE
Running my appium scripts (Java)

### ISSUE THREAD

**Issue by poorvikamahesh** [openstf/stf#408]
Hello,

Apologies in advance if this question seems too basic.

I have been using appium to automate many app on real devices using Java.
Now I would like to run the same scripts via OpenSFT. Is this possible? If so, what are the exact desired capabilities i need to set during my driver creation?

Thanks and Regards,
Poorvika

**Comment by vbanthia** [comment]
You can run test with any Appium client library using STF API. Check this [sample example](https://github.com/openstf/stf-appium-example) which uses Ruby Client library. You do not need to add any extra STF specific capability. Just assume that you are running test on device connected to your local machine.

**Comment by email2vimalraj** [comment]
@poorvikamahesh : Refer this www.vimalselvam.com/2016/08/07/appium-parallel-execution-on-openstf/ for java implementation.
