### ISSUE TITLE
the principle of Realizing  control devices remotely, especially those devices not having root permission

### ISSUE THREAD

**Issue by SanDiegoXu** [openstf/stf#409]
Hi, now I hava an issue，expect to get your consult.

I have researched some applications that realize remotely control to devices.  But almost all require  devices to have root permission.

**So, can you talk about how to realize control devices remotely  in STF ? especially devices don't have root permissions?**
Thank you very much.

**Comment by gunta** [comment]
Basically we did hard work, using private APIs.

So nothing in STF requires root permissions.

If you want to know more details about the implementation, please check our following presentation: 
https://www.youtube.com/watch?v=7FBvRiCdRgs

If you want custom consultation services, you can contact us at contact@openstf.io
