### ISSUE TITLE
Increase timeout for inactive user / lost session 

### ISSUE THREAD

**Issue by martinwoit** [openstf/stf#418]
## What's the problem (or question)?

Hi,
First: Thanks for this wonderful tool! You did a great job!! 

While using STF one question appeared very often: Is it possible to increase the timeout of a device stay connected to a user? After some time of inactivity the user will be removed from the device and the session will be cleared. This means the app under test with all its data is also gone and has to be installed again. Sometimes this is very painful.
## What should have happened?

Let the device stay longer occupied by a user.
## Do you have an idea for a solution?

Add a parameter while starting stf, e.g. --session-timeout 120 #min
## How can we reproduce the issue?

1.
2.
3.
4.
## Please tell us details about your environment.

- we are using `stf local`
- Version used (git hash or `stf -V`): 1.1.1
- Environment name and version: Chrome  52.0.2743.116 (64-bit), node v4.2.6
- Operating System and version: Ubuntu 16.04.1

**Comment by sorccu** [comment]
You can use the --group-timeout parameter or perhaps the --no-cleanup
parameter.
