### ISSUE TITLE
Starting rethinkdb in different port than 8080 (default)

### ISSUE THREAD

**Issue by DineshKumar7** [openstf/stf#42]
I am trying to start rethinkdb in different port than the default one (command used - rethinkdb -o 8081) and then start "stf" (command used - stf local). But I am getting an error as -

INF/util:procutil 6386 [*] Forking "/home/xxx/xxx/stf/lib/cli.js migrate"
INF/db 6394 [*] Connecting to 127.0.0.1:28015
INF/db 6394 [*] Unable to connect to 127.0.0.1:28015
FTL/db 6394 [*] No hosts left to try
FTL/util:lifecycle 6394 [*] Shutting down due to fatal error

/home/zaloraqa/Downloads/stf/node_modules/bluebird/js/main/promise.js:673
           throw e;
                 ^
ExitError: Exit code "1"
   at ChildProcess.<anonymous> (/home/xxxx/xxxx/stf/lib/util/procutil.js:49:23)
   at ChildProcess.emit (events.js:110:17)
   at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

So please let me know is it possible to run stf when renthinkdb not running in default port (8080)

Thanks

**Comment by sorccu** [comment]
Hi, `-o` is for a different thing, you want to use `rethinkdb --http-port 8081` instead.

**Comment by DineshKumar7** [comment]
Thanks it worked
