### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by fanyuRN** [openstf/stf#420]
I meet a problem, and I red https://github.com/openstf/stf/issues/250;but it seem to no  effect;I have tried npm rebuild zmq; 
![9a0b8add-fba8-4bbd-90b0-678d11addee7](https://cloud.githubusercontent.com/assets/20810414/18308165/f80309dc-7525-11e6-88b5-a721283fe117.png)

**Comment by sorccu** [comment]
Remove the entire node_modules folder and run npm install again.

**Comment by fanyuRN** [comment]
@ sorccu，is /usr/local/lib/node_modules/ ?

**Comment by sorccu** [comment]
Ok, maybe it's easier if you do `npm uninstall -g stf` followed by `npm install -g stf`if you've installed it globally.

**Comment by fanyuRN** [comment]
thank you ! I have solved it,

**Comment by HMY314** [comment]
@sorccu  look this,how to solve
![qq 20170611211931](https://user-images.githubusercontent.com/11188841/27011328-baf11fca-4eeb-11e7-8a16-c7110b831260.png)

**Comment by sorccu** [comment]
Not sure, your installation is fucked up. I would really recommend using
NVM to install node instead of using your distro's package manager.
