### ISSUE TITLE
How to add a angularjs modules into stf project? 

### ISSUE THREAD

**Issue by darshansr** [openstf/stf#421]
I need to add some modules to extend the UI features in stf, how to add the modules,
So that i should not get any dependency injection module error.

Please help me out in this.

**Comment by sorccu** [comment]
It would help if you pasted the error (or a screenshot of it) here, and let
us know exactly what changes you made.

**Comment by darshansr** [comment]
i tried adding new bower modules and got success in that. without any module error.
Thank you.
