### ISSUE TITLE
API timeout issue

### ISSUE THREAD

**Issue by xiaweixing** [openstf/stf#423]
## What's the problem (or question)?

Hi,

I have a pretty long-running test, and my script is to call the api to reserve the device before testing starts, and release the device after testing ends.  When testing started, I can see the device was reserved successfully, but after around 15-20 minutes, the device was released automatically even though my testing was still going on.  That is really an unexpected behaviour because someone else can reserve and use it while my testing has not finished yet.

So, can anyone please share why this happened, and any way to avoid it, or extend the timeout? Thanks.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by sorccu** [comment]
Use the `--group-timeout` parameter to choose a longer timeout. STF extends the timeout every time there's a user action (e.g. when the user touches the screen, or in this case, whenever something is written to the device you're `adb connect`ing to). You haven't told us anything about what, and how, you're  testing, but if you simply launch something and wait for it to finish, it's likely that STF doesn't see any "user activity" on the socket and considers the usage session ended. Either increase the timeout or make sure you're doing something every now and then.

**Comment by xiaweixing** [comment]
Hi Sorccu,

Thanks for the reply.
I have a separate automation platform, and just want to reserver/release device during test, so others cannot use them.  So, there's no interaction on STF platform, just on devices (running automation scripts).

So, --group-timeout parameter should be used while starting provider, right?  Then it will be passed to each "stf device" process when starting them?

**Comment by xiaweixing** [comment]
Have tried to start provider with --group-timeout parameter, seems working now. Thanks!

**Comment by vbanthia** [comment]
you can also set `--group-timeout` per device while reserving a device. Some thing like below:

```js
var device = {serial: 'yyyy', timeout: 900000 }

clientWithPromise.then(function(api) {
  return api.user.addUserDevice({device: device})
    .then(function(res) {
      console.log(res.obj)
      // { success: true, description: 'Device successfully added' }
    })
})
.catch(function(err) {
  console.log(err)
})
```

**Comment by xiaweixing** [comment]
Thanks vbanthia for your another great solution!

**Comment by risinek** [comment]
Just to extend @vbanthia answer - you can set the timeout to zero, which will reserve the device for for infinite time, until you free it again using API delete, or clicking Stop using button in UI
