### ISSUE TITLE
Jade renames pug?What have been change?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#424]
I see that jade have been rename pug.Is there any changing or it just being renamed?

**Comment by sorccu** [comment]
Some of our dependencies use it and we have no choice but to wait for them to catch up.

**Comment by gunta** [comment]
We've changed to pug as far as STF is concerned. Some child dependencies may still use jade, but we don't.

If you want to know what are the breaking changes look here: https://github.com/pugjs/pug/issues/2305
