### ISSUE TITLE
Two stf-users can't have same adb-key

### ISSUE THREAD

**Issue by nwlunatic** [openstf/stf#428]
## What's the problem (or question)?

Haven't dig into it much. So I'm not sure if it's an issue or a restriction made by intent.

I have one OS user, one adb-key, two stf-user tokens. And I'm not able to connect devices via API using second token. Currently we are using docker to connect devices and run tests and we need to rebuild docker image for each stf-user.

## What should have happened?
I would like to be able to use devices based only on stf-user token

## How can we reproduce the issue?

1. create two stf-users
2. try to add same adb-key to each user.

Only first one will be able to

## Please tell us details about your environment.

* openstf/stf:v2.0.0-beta
* Mock auth

**Comment by vbanthia** [comment]
It has been discussed here. https://github.com/openstf/stf/issues/170

**Comment by vbanthia** [comment]
Reason why STF does not allow 2 users to have same adb keys is because STF uses adb keys to identify user in remote connect. So, one adb key can only belong to one unique user.

Is there any specific reason for using two different tokens for automated tests on same machine? Can't this be done with same user token?

**Comment by sorccu** [comment]
This is the way it works. The key must be unique for each user, since `adb connect` doesn't send any other identifying information. If two users had the same key, we would not be able to figure out which one is trying to connect.

**Comment by nwlunatic** [comment]
Got it. Sorry for bothering you and not that i haven't found #170 by myself )

The reason we are using two different tokens is because we have two different teams (slightly more actually) and would link to distinguish devices used by them in webapp. Different users from this teams are also using farm to write tests. So we would like to share docker image for running tests instead of Dockerfile, because it would make it much easier to fix bugs in it.

So the two ways of fixing it, is hack around with adb or add some device lockdown logic, that will provide `adb connect` url after it's done. Both of ways look cumbersome.

Can I close this as 	duplicate?

**Comment by vbanthia** [comment]
One possible work around is to store adbkeys of various teams on docker-machine and use data volume option (`-v`) while `docker run`. By this you will not have to create different docker images for different team just because of adbkey.

**Comment by nwlunatic** [comment]
thanks @vbanthia @sorccu
