### ISSUE TITLE
some one stole your device

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#43]
Hi, i am using stf with an android tv magic box , it's os is based on android and it is connected to adb using network , i use --allow-remote to start stf , when i try to control the device , it waits for a while and tells me some one stole your device , i don't know what dose that mean , what errors can cause that ?

**Comment by channingbreeze** [comment]
i catched this message

FTL/device:plugins:service 26170 [192.168.8.23:5555] Service connection could not be relaunched TimeoutError: operation timed out
    at Timer.listOnTimeout (timers.js:119:15)
From previous event:
    at Socket.endListener (/root/stf/stf/lib/units/device/plugins/service.js:196:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 26170 [192.168.8.23:5555] Shutting down due to fatal error

my device is there and adb is connected

**Comment by channingbreeze** [comment]
i got it , it is something wrong with the owner

**Comment by suvansh-dev** [comment]
The same error i am getting with one of the avd, how you solved this error?

**Comment by sorccu** [comment]
That doesn't have anything to do with this issue. The error can occur if the worker process dies, which based on your other posts is indeed happening.
