### ISSUE TITLE
Whether STFService.apk can obtain one of the process's performance data?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#430]
Hi @sorccu 
I want to ask some questions.
1.Whether STFService.apk can obtain one of the process's performance datas? 
2.Whether STFService.apk can read files  from the phone's storage?
3.It STFService.apk are opened source ?

**Comment by sorccu** [comment]
Not sure about 1 and 2, my guess would be no/difficult due to restrictive android permissions. As for 3, see https://github.com/openstf/STFService.apk.

**Comment by 0x88l** [comment]
Thank you
