### ISSUE TITLE
Android6.0 logcat was err

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#432]
There is a bug with android 6.0. Maybe it happened in adbkey-logcat.
device: 
1. huawei PLK-TL01H product:QK1503_A01 model:1503_A01 device:QK1503_A01
2. 360:product:QK1503_A01 model:1503_A01 device:QK1503_A01

step:
1.click one fo android 6.0 device to control
2.click the get logcat 

result:
![image](https://cloud.githubusercontent.com/assets/18346467/18831383/eaf13a1a-8417-11e6-8f81-f5cb8a5bf531.png)

**Comment by sorccu** [comment]
I think this should be fixed in master already.

**Comment by 0x88l** [comment]
Which module cause the problem?Which file should be fix?It is module of adbkey?

**Comment by sorccu** [comment]
This should be fixed in the latest versions (I think 2.1.0). Please open a new ticket if not.
