### ISSUE TITLE
Customize a page

### ISSUE THREAD

**Issue by cemakkok** [openstf/stf#433]
## What's the problem (or question)?
Hi, i have changed some .js file and restart the OpenSTF, i cannot show any difference. What can i do to show it ?

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by sorccu** [comment]
When you install STF from git for the first time, `npm install` runs a script that builds a static copy of the resources. You can run `gulp clean` to get rid of them (or `./node_modules/.bin/gulp clean` if you don't feel like installing gulp for that).

**Comment by rahul0698** [comment]
hi,
I want to know that if I want to customize a page in STF and then after customization if I build my own image and push it on dockerhub, and then pull it while deploying it to real server, the docker file that you provided will do work for building that image or I have to modify something in the docker file? 

Thanks in advance!

**Comment by sorccu** [comment]
It will work unless you need a new native dependency.
