### ISSUE TITLE
Android7.0  case minicap errr

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#434]
step:
1.connect an android 7.0
2.restart stf
3.the devices can't be recognized
devices list:
012e8e2764d6bccc       device product:bullhead model:Nexus_5X device:bullhead

this is the err log:
![image](https://cloud.githubusercontent.com/assets/18346467/18857874/118e0a86-849a-11e6-8864-f178c55bacba.png)

**Comment by sorccu** [comment]
You're using an old version of STF. You MUST have v2.0.1 or higher.

**Comment by 0x88l** [comment]
I have used the old version because I have rewite some code . So I try to Merge the new code.

**Comment by sorccu** [comment]
I believe this issue was fixed by updating your STF :)
