### ISSUE TITLE
The company behind RethinkDB is shutting down.  Do you consider replacing the database?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#443]
There is a sad new that company behind rethinkdb is shuttingdow.Whether STF would plan to replace the database?

**Comment by sorccu** [comment]
It's stable enough as it is right now, let's wait if someone picks it up and it becomes a community project.

**Comment by sorccu** [comment]
If no one does, then we might reconsider at some point in the future.

**Comment by sorccu** [comment]
RethinkDB has now been purchased, relicensed to Apache 2.0, and donated to the community. This 99% ensures that someone will pick it up again.

https://www.joyent.com/blog/the-liberation-of-rethinkdb

**Comment by FranklinYu** [comment]
Please re-consider. There is only one release since 2017, and Ubuntu Bionic (18.04) is not officially supported (rethinkdb/rethinkdb-legacy#6663). It was forked to RebirthDB and merged back, but the problem is not really solved.

**Comment by thinkhy** [comment]
Seems RethinkDB is not bottleneck for common usage of STF.

Franklin Yu <notifications@github.com> 于2018年12月14日周五 上午3:19写道：

**Comment by FranklinYu** [comment]
@thinkhy It is not a performance bottleneck, but a maintenance bottleneck. All the other dependencies are available through `apt install`, and are automatically kept updated. RethinkDB is now the most difficult one to keep updated.
