### ISSUE TITLE
openSTF Installation issues on my mac 10.11.6

### ISSUE THREAD

**Issue by Tanmoyray** [openstf/stf#446]
Last login: Mon Oct 17 17:46:56 on ttys001
Tanmoys-Mac-mini:~ tanmoyray$ brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
armor                      docker                     oysttyer                 
aubio                      elixirscript               pgrouting                
aws-elasticbeanstalk       latex2html                 qca                      
codequery                  mitmproxy                  terraform                
dcmtk                      mkvtoolnix               

Warning: rethinkdb-2.3.5 already installed, it's just not linked
==> Installing dependencies for graphicsmagick: jpeg, libpng, libtiff, freetype
==> Installing graphicsmagick dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.el_capitan.bottle.2
Already downloaded: /Users/tanmoyray/Library/Caches/Homebrew/jpeg-8d.el_capitan.bottle.2.tar.gz
Error: SHA256 mismatch
Expected: bbc74f8b5980065d7bf95927150c2d56806d30abea459c2b1edcbdeed2d7c458
Actual: 87a08f636b46e0ca191e886596c58fd38f1dacc16171b5d5df66203daeeed6a4
Archive: /Users/tanmoyray/Library/Caches/Homebrew/jpeg-8d.el_capitan.bottle.2.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading http://www.ijg.org/files/jpegsrc.v8d.tar.gz
Already downloaded: /Users/tanmoyray/Library/Caches/Homebrew/jpeg-8d.tar.gz
Error: SHA256 mismatch
Expected: 00029b1473f0f0ea72fbca3230e8cb25797fbb27e58ae2e46bb8bf5a806fe0b3
Actual: a375a0d7a054e04edddd4f5b9539e11aeadc5788e62f8a37173ede5efa08c616
Archive: /Users/tanmoyray/Library/Caches/Homebrew/jpeg-8d.tar.gz
To retry an incomplete download, remove the file above.
Tanmoys-Mac-mini:~ tanmoyray$ Tanmoys-Mac-mini:~ tanmoyray$ brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config
-bash: Tanmoys-Mac-mini:~: command not found
Tanmoys-Mac-mini:~ tanmoyray$ ==> Auto-updated Homebrew!
-bash: ==: command not found
Tanmoys-Mac-mini:~ tanmoyray$ Updated 1 tap (homebrew/core).
-bash: syntax error near unexpected token `('
Tanmoys-Mac-mini:~ tanmoyray$

**Comment by sorccu** [comment]
Seems like a problem with brew and/or your shell is broken. It gives you suggestions what to do in that error message, you should do those.

I will close this as off topic, since it happens before anything STF related runs.
