### ISSUE TITLE
Device go back to home screen when we click the "Stop Using"

### ISSUE THREAD

**Issue by WillPangZi** [openstf/stf#449]
## What's the problem (or question)?

Device go back to home screen when we click the "Stop Using". This makes problem for appium automation.

## What should have happened?

Do we have any parameter to prevent device go back to home when the device been kicked?

## How can we reproduce the issue?

1. open device and open an App.
2. Click “stop using"
3. the device screen go back to home.  
4. :(

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md):
 full deployment
* Version used (git hash or `stf -V`): 
latest master
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
Chrome
* Operating System and version: 
Ubuntu server 16.4
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by sorccu** [comment]
I think the reason for that behavior is that if the user left something active that keeps the screen on (like a heavy 3D game), the device would never sleep, destroying the battery and display over time. Therefore the home key is pressed once to avoid that situation.

Maybe we could make it optional, though.

**Comment by WillPangZi** [comment]
Thanks for you reply, sorccu. 
But press the home just make the program running backgroundly. 
If we can make it optional it's better...

To those who needs same feature as me.
/lib/units/device/plugins/group.js
Line:106
comment **servcice.pressKey('home')**

**Comment by vbanthia** [comment]
You will also have to use `--no-cleanup` option otherwise STF will uninstall all new apps installed in user session.
