### ISSUE TITLE
Can't use STF with Docker

### ISSUE THREAD

**Issue by nicocans** [openstf/stf#45]
Hello,
I'm trying to run STF with Docker, but I got an error 

stf@10d2f43a5185:/app$ stf local
INF/util:procutil 13 [*] Forking "/app/lib/cli.js migrate"
INF/db 14 [*] Connecting to 127.0.0.1:28015
INF/db 14 [*] Unable to connect to 127.0.0.1:28015
FTL/db 14 [*] No hosts left to try
FTL/util:lifecycle 14 [*] Shutting down due to fatal error

/app/node_modules/bluebird/js/main/promise.js:673
            throw e;
                  ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

Do you have an idea about the issue?

**Comment by sorccu** [comment]
You need to have a rethinkdb container running as well, and then link to it. There's a bit more complicated example over at https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md, but you could skip the proxy container and just link against the rethinkdb container if you like.

**Comment by nicocans** [comment]
ok, then it would be easier to install all Requirements by hand without Docker, no?

**Comment by sorccu** [comment]
Depends on how much you've used Docker before (especially with linked containers), and what OS you're running on. It won't work on OS X with boot2docker because it won't be able to see your USB devices.

**Comment by rcbop** [comment]
@sorccu regarding OS X + Docker support, if I configure Virtualbox to forward USB ports to guest boot2docker machine would it work? Or using something like https://bitbucket.org/chabernac/adbportforward/wiki/Home ? The last one sounds a bit like a jerry rig.

**Comment by sorccu** [comment]
Yes it would be possible to configure the USB ports, however it's annoying and reliability is questionable. In fact https://github.com/openstf/setup-examples does that but some people are having issues.

The adb port forward thing may or may not work, but you could do pretty much the same thing with `socat` or similar common tools. Or try setting the ADB_HOST and ADB_PORT environment variables and STF will try to use those. Functionality is untested, though.
