### ISSUE TITLE
hi ,I got a  problem in stf (command   stf local )?can you help me ?

### ISSUE THREAD

**Issue by jerry117** [openstf/stf#451]
lijialiangdeMacBook-Pro:~ jerry$ stf local
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 1336 [*] Connecting to 127.0.0.1:28015
INF/db:setup 1336 [*] Database "stf" already exists
INF/db:setup 1336 [*] Table "users" already exists
INF/db:setup 1336 [*] Table "accessTokens" already exists
INF/db:setup 1336 [*] Table "vncauth" already exists
INF/db:setup 1336 [*] Table "devices" already exists
INF/db:setup 1336 [*] Table "logs" already exists
INF/db:setup 1336 [*] Index "users"."adbKeys" already exists
INF/db:setup 1336 [*] Index "accessTokens"."email" already exists
INF/db:setup 1336 [*] Index "vncauth"."response" already exists
INF/db:setup 1336 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 1336 [*] Index "devices"."owner" already exists
INF/db:setup 1336 [*] Index "devices"."present" already exists
INF/db:setup 1336 [*] Waiting for index "users"."adbKeys"
INF/db:setup 1336 [*] Waiting for index "accessTokens"."email"
INF/db:setup 1336 [*] Waiting for index "vncauth"."response"
INF/db:setup 1336 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 1336 [*] Waiting for index "devices"."owner"
INF/db:setup 1336 [*] Waiting for index "devices"."present"
INF/db:setup 1336 [*] Index "devices"."providerChannel" already exists
INF/db:setup 1336 [*] Index "users"."adbKeys" is ready
INF/db:setup 1336 [*] Index "accessTokens"."email" is ready
INF/db:setup 1336 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 1336 [*] Index "vncauth"."response" is ready
INF/db:setup 1336 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 1336 [*] Index "devices"."owner" is ready
INF/db:setup 1336 [*] Index "devices"."present" is ready
INF/db:setup 1336 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name lijialiangdeMacBook-Pro.local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 1335 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
FTL/cli:local 1335 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 1335 [*] Shutting down all child processes
/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

**Comment by sorccu** [comment]
You updated node and now the native modules are out of date. It would be best if you did `rm -rf node_modules` and then ran `npm install` again.

**Comment by jerry117** [comment]
Thank you

**Comment by sorccu** [comment]
It says what the error is. You probably used an older node before. Now
you've upgraded node and the native dependencies were built against the old
version and don't work with the new version without rebuilding. Rm -rf
node_modules and npm install again.
