### ISSUE TITLE
docker stf error

### ISSUE THREAD

**Issue by bgcelite** [openstf/stf#452]
when i run 
"docker run openstf/stf stf local" command,there have a error:
INF/db 12 [*] unable to connect to 127.0.0.1:28015

and the program shutdown

**Comment by vbanthia** [comment]
Because you are doing it wrong. You are not supposed to run `stf local` from `openstf/stf` docker image. Read [DEPLOYMENT doc](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) to understand its proper usage.
