### ISSUE TITLE
Connect device error by provider.

### ISSUE THREAD

**Issue by zangtian2** [openstf/stf#455]
I use by stf local, everything is  ok.However when i start it follow deployment,there are some problems happened.
First,
![provider](https://cloud.githubusercontent.com/assets/20548146/19802598/0f4e9f8c-9d37-11e6-9c2a-02b5db21c063.gif)
And  it looks like good.
![stf](https://cloud.githubusercontent.com/assets/20548146/19802608/172aede6-9d37-11e6-9bb5-90468f8a79c9.gif)

Then i  click the device icon to into the page which is used for control device,the page jump to the control page, and about a few seconds later, nothing disappeared and jump back.Final it shows:
![result](https://cloud.githubusercontent.com/assets/20548146/19802607/16f18376-9d37-11e6-961c-19ece85298c0.gif)
Ofcourse ,the provider is ok.

There is a error "INF/util:datautil 1 [*] Device database does not have an entry for "TQRBBDB671900212" (model "JDN-AL00"/"JDN"). This is not an error, it only means that we don't have data for it yet.".
I think it's the reason,but i didn't find the solution.

Thank you so much.

**Comment by 0x88l** [comment]
Try to reinstall STF-service.

**Comment by zangtian2** [comment]
I tried it.But without effect。

**Comment by lishuai0214** [comment]
why api port is 3100?

**Comment by codeskyblue** [comment]
what kind browser?

**Comment by zangtian2** [comment]
Thank you @codeskyblue  , it costs me so much time .
I use firefox,it caused problem.

**Comment by testerlife** [comment]
@zangtian2 
你好我在搭建stf的服务器中可以正常访问localhost:7100 去管理设备，但是外部使用ip：7100访问时出现了类似的错误：INF/util:datautil 14899 [*] Device database does not have an entry for "APU7N16408000649" (model " NXT-TL00"/"NXT-TL00"). This is not an error, it only means that we don't have data for it yet.

请问这个问题有解决方法吗？
![1](https://cloud.githubusercontent.com/assets/24586119/25302512/0f83eadc-2772-11e7-9a53-4e27ca2b6110.png)

**Comment by lishuai0214** [comment]
websocket的错误，建议去testerhome.com提问

**Comment by lishuai0214** [comment]
@testerlife websocket的错误，建议去testerhome.com提问
