### ISSUE TITLE
Ubuntu always recoginze my deivce under test as an 'offline' status

### ISSUE THREAD

**Issue by liuct** [openstf/stf#456]
Here i paste the output messages derived from terminal, i have tried several times, still can't recoginize the android device connected to my desktop.
I have tried installing STFService APK manually and launch the service instance. It didn't work also.
By typing 'adb devices' command, the device status seems good, and with 'adb shell' i can access the device from my desktop~

Host OS: Ubuntu 12.04 64bit
Device: android 4.4.2
Node (on nvm): v6.9.0

$stf local
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js migrate"
INF/db 1677 [] Connecting to 127.0.0.1:28015
INF/db:setup 1677 [] Database "stf" already exists
INF/db:setup 1677 [] Table "users" already exists
INF/db:setup 1677 [] Table "accessTokens" already exists
INF/db:setup 1677 [] Table "vncauth" already exists
INF/db:setup 1677 [] Table "devices" already exists
INF/db:setup 1677 [] Table "logs" already exists
INF/db:setup 1677 [] Index "users"."adbKeys" already exists
INF/db:setup 1677 [] Index "accessTokens"."email" already exists
INF/db:setup 1677 [] Index "vncauth"."response" already exists
INF/db:setup 1677 [] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 1677 [] Index "devices"."owner" already exists
INF/db:setup 1677 [] Index "devices"."present" already exists
INF/db:setup 1677 [] Index "devices"."providerChannel" already exists
INF/db:setup 1677 [] Waiting for index "users"."adbKeys"
INF/db:setup 1677 [] Waiting for index "accessTokens"."email"
INF/db:setup 1677 [] Waiting for index "vncauth"."response"
INF/db:setup 1677 [] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 1677 [] Waiting for index "devices"."owner"
INF/db:setup 1677 [] Waiting for index "devices"."present"
INF/db:setup 1677 [] Waiting for index "devices"."providerChannel"
INF/db:setup 1677 [] Index "users"."adbKeys" is ready
INF/db:setup 1677 [] Index "accessTokens"."email" is ready
INF/db:setup 1677 [] Index "vncauth"."response" is ready
INF/db:setup 1677 [] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 1677 [] Index "devices"."owner" is ready
INF/db:setup 1677 [] Index "devices"."present" is ready
INF/db:setup 1677 [] Index "devices"."providerChannel" is ready
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull 
tcp://127.0.0.1:7113"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js provider --name liuchengtao-pc --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 1671 [] Forking "/home/liuchengtao/.nvm/versions/node/v6.9.0/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 1684 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 1684 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 1684 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/triproxy 1683 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 1683 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 1683 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/db 1690 [proc001] Connecting to 127.0.0.1:28015
INF/processor 1690 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 1690 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/poorxy 1756 [] Listening on port 7100
INF/reaper 1703 [reaper001] Subscribing to permanent channel "ALL"
INF/reaper 1703 [reaper001] Reaping devices with no heartbeat
INF/db 1703 [reaper001] Connecting to 127.0.0.1:28015
INF/reaper 1703 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 1703 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/auth-mock 1709 [] Listening on port 7120
INF/db 1696 [proc002] Connecting to 127.0.0.1:28015
INF/processor 1696 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 1696 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/storage:plugins:apk 1750 [] Listening on port 7104
INF/storage:plugins:image 1744 [] Listening on port 7103
INF/provider 1708 [] Subscribing to permanent channel "tR+jxuaUQz2Qvqtte+6oWA=="
INF/provider 1708 [] Sending output to "tcp://127.0.0.1:7116"
INF/provider 1708 [] Receiving input from "tcp://127.0.0.1:7114"
INF/provider 1708 [] Tracking devices
INF/provider 1708 [] Found device "e11b1658" (device)
INF/app 1720 [] Using pre-built resources
INF/storage:temp 1738 [] Listening on port 7102
INF/app 1720 [] Listening on port 7105
INF/db 1720 [] Connecting to 127.0.0.1:28015
INF/websocket 1732 [] Subscribing to permanent channel "ALL"
INF/websocket 1732 [] Listening on port 7110
INF/db 1732 [] Connecting to 127.0.0.1:28015
INF/websocket 1732 [] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 1732 [] Receiving input from "tcp://127.0.0.1:7111"
INF/api 1726 [] Subscribing to permanent channel "ALL"
INF/api 1726 [] Listening on port 7106
INF/api 1726 [] Sending output to "tcp://127.0.0.1:7113"
INF/api 1726 [] Receiving input from "tcp://127.0.0.1:7111"
INF/db 1726 [*] Connecting to 127.0.0.1:28015

INF/provider 1708 [*] Providing all 0 of 1 device(s); ignoring "e11b1658"

**Comment by sorccu** [comment]
Try switching the phone between MTP/PTP mode and see if that changes anything. On Linux sometimes only 1 of them works.

By the way your Ubuntu is so old it's practically useless. Please upgrade, we won't help with ancient software.

**Comment by sorccu** [comment]
Alternatively, try running adb as root and see if that changes anything. Note that it is NOT enough to run `sudo adb devices` as it simply connects to the existing adb daemon which may or may not be running as root. Run `adb kill-server` first, followed by `sudo adb start-server`. You can call adb without `sudo` after that.

**Comment by liuct** [comment]
@sorccu  thanks a lot for clarification. I will have a try on upgraded Ubuntu system.

**Comment by liuct** [comment]
@sorccu 

File an new issue for details that i thought may be the root cause
