### ISSUE TITLE
Device 'register' event never triggered in my debugging

### ISSUE THREAD

**Issue by liuct** [openstf/stf#457]
In file "stf/lib/units/provider/index.js"

      var register = new Promise(function(resolve) {
        // Tell others we found a device
        push.send([
          wireutil.global
        , wireutil.envelope(new wire.DeviceIntroductionMessage(
            device.id
          , wireutil.toDeviceStatus(device.type)
          , new wire.ProviderMessage(
              solo
            , options.name
            )
          ))
        ])

        privateTracker.once('register', resolve)
      })

During my debugging process, i found the  'register' event never be triggered.

How about use 
'''
resolve() 
'''
to replace the line 
'''
privateTracker.once('register', resolve)
'''

**Comment by sorccu** [comment]
No, it's supposed to be like that. Sounds like your setup is missing something.

**Comment by liuct** [comment]
@sorccu   
But 'change' and 'remove' event always works and can be triggered. 
I didn't seek out the root cause why register process can't be invoked.  :(
Could you give some suggestions for trouble shooting.

**Comment by liuct** [comment]
After remove & install  again the stf package.
All things work fine on node v6.9.0 runtime~~~
Maybe some of the dependencies have been installed incorrectly.
