### ISSUE TITLE
stf on mac is always ignoring my device

### ISSUE THREAD

**Issue by nocturne-me** [openstf/stf#466]
Hi,

I have installed stf on OS X 10.11.5, there's a problem while I pluged an phone,
The stf log print that it has found my devices, 
INF/provider 514 [*] Found device "03b5ee5ef0b59a18" (device)
and for a while follows as
INF/provider 514 [*] Providing all 0 of 1 device(s); ignoring "03b5ee5ef0b59a18"
And I can't see any device on the website
I have tried 3 different phones, and it appears the same result.

How can I solve this?

**Comment by sorccu** [comment]
What's the exact command you run stf with?

**Comment by sorccu** [comment]
Closing as the request information has not been provided.
