### ISSUE TITLE
Filtered out device

### ISSUE THREAD

**Issue by lhplj** [openstf/stf#469]
Hi
The use of Bare Metal to install coreos, STF deployment of stand-alone normal, and clustering, "adb devices" can see the equipment, but STF does not display mobile phone. View **provider log** shows "**Filtered out device** ..."

$ sudo docker exec b714d3de2123 stf doctor
INF/util:doctor 10 [*] OS Arch: x64
INF/util:doctor 10 [*] OS Platform: linux
INF/util:doctor 10 [*] OS Platform: 4.7.3-coreos-r2
INF/util:doctor 10 [*] Using Node 6.9.1
INF/util:doctor 10 [*] Using RethinkDB client 2.3.3
INF/util:doctor 10 [*] Using ZeroMQ 4.1.4
WRN/util:doctor 10 [*] Executable was not found
WRN/util:doctor 10 [*] Executable was not found
WRN/util:doctor 10 [*] Executable was not found
INF/util:doctor 10 [*] GraphicsMagick 1.3.23

Look forward to your help!

**Comment by terminalone** [comment]
@lhplj Did you find a solution to this problem???I am facing a similar issue

**Comment by liruige01** [comment]
when i run as 'stf local' ,there is no problem, but when i run as 'stf local —public-ip' ,one online device is not show ,the console show 'Filtered out device "d81574df7d12"'

**Comment by thinkhy** [comment]
plz provide more info including log or screenshot. I hit the similar
problem when fill the wrong port for zmq ...

liruige01 <notifications@github.com> 于2018年10月26日周五 下午4:36写道：
