### ISSUE TITLE
Problem connecting more than 8 devices

### ISSUE THREAD

**Issue by HellDima** [openstf/stf#476]
Hello,

We are running STF on Ubuntu 16.4, inside the docker.
It's a local run.

We are trying to connect more than 8 devices and it stop showing to us.
ADB devices:
List of devices attached
84B7N16804001148	device
4dfc4c8d3d785005	device
dd183316	device
a211579a	device
4df194c26c0b8f09	device
LGH850da459a86	device
F5AZCY05E419	device
df58b11703329c01	device

The other devices are not displayed, and it's a random device, depending on what we connect first.

Is this an Ubuntu problem or STF?

**Comment by sorccu** [comment]
It's written in the README. It's a problem with the cpu/chipset and nothing
but a hardware change can solve it.

**Comment by HellDima** [comment]
so how strong suppose to be my PC to run more devices?
we use now:
i5-4590, 16G, with SSD

Or can you give us recommendation on server specs to run more devices?

**Comment by sorccu** [comment]
It's all in the README. It's not about powerful hardware, it's about Intel
only supporting a limited number of USB endpoints in their recent hardware.

Please read the README and close this issue. Everything you've asked is
there.

**Comment by HellDima** [comment]
ok, tnx
