### ISSUE TITLE
XiaoMi5  fails on minitouch

### ISSUE THREAD

**Issue by scottchejin** [openstf/stf#477]
INF/device:plugins:touch 4553 [7d068e69] Launching screen service
INF/device:plugins:touch 4553 [7d068e69] Connecting to minitouch service
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "open: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event8 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event7 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event6 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/mouse2 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/mice for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event5 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/mouse1 for inspectionopen: Permission denied"
INF/device:plugins:touch 4553 [7d068e69] minitouch says: "Unable to open device /dev/input/event2 for inspectionUnable to find a suitable touch device"
WRN/device:plugins:touch 4553 [7d068e69] Shell keeping minitouch running ended unexpectedly

**Comment by sorccu** [comment]
I have one and it works fine. Run `adb shell getevent -ilp` and post the
output. Also, run `adb devices -l` and post the line for your device.

**Comment by scottchejin** [comment]
adb shell getevent -ilp:
could not open /dev/input/event8, Permission denied
could not open /dev/input/event7, Permission denied
could not open /dev/input/event6, Permission denied
could not open /dev/input/mouse2, Permission denied
could not open /dev/input/event3, Permission denied
could not open /dev/input/mouse0, Permission denied
could not open /dev/input/event1, Permission denied
could not open /dev/input/event0, Permission denied
could not open /dev/input/mice, Permission denied
could not open /dev/input/event5, Permission denied
could not open /dev/input/event4, Permission denied
could not open /dev/input/mouse1, Permission denied
could not open /dev/input/event2, Permission denied
===================================================
adb devices -l:
List of devices attached
7d068e69               device usb:1-1 product:gemini model:MI_5 device:gemini

**Comment by sorccu** [comment]
Yeah well that's broken, then. Are you running an official ROM?

**Comment by scottchejin** [comment]
Yes. the MIUI version is :MIUI 8.1 | Stable 8.1.3.0(MAACNDI)
I have another XIAOMI 5,  version is: MIUI 7.3, it works well.

**Comment by sorccu** [comment]
8.0 works fine. Not sure about 8.1, would be unfortunate if they've locked it down.

**Comment by scottchejin** [comment]
Thank you for your help. I will flush 8.0 then try again. Maybe they've locked it  if 8.0 can run well on the same device, and I will post the result later.

**Comment by sorccu** [comment]
Looks like in MIUI 8.1 there's a new setting in Developer options called "USB debugging (Security settings)" that is disabled by default. To enable the setting you have to add your Mi account, but I believe it should work after that.

![mi5_enable_simulated_touch](https://cloud.githubusercontent.com/assets/32509/20514108/8442ffb4-b0cd-11e6-836e-67bdbca62804.png)

Let me know how it goes.

**Comment by scottchejin** [comment]
Yes. I used my MI account then enabled the setting "USB debugging (Security settings)", The device works well.     Thanks for your help.

![image](https://cloud.githubusercontent.com/assets/5362161/20514608/e84fa350-b0c7-11e6-8c79-c5105ee40c61.png)

**Comment by leemeng0x61** [comment]
ha, MI is awesome

**Comment by lql0ve** [comment]
Hey there , 
       I have the same issues , my MI 5s does't have the setting "USB debugging (Security settings)",MIUI Version : 8.0.18 

      adb devices -l : 
           129d5a98               device usb:336592896X product:capricorn model:MI_5s device:capricorn

**Comment by sorccu** [comment]
You probably have to update your phone, then.

**Comment by lql0ve** [comment]
Updating MIUI V8.2.2.0.MAGCNDL , not sure it's have the setting...touch you later

**Comment by sorccu** [comment]
Btw did you happen to have a MI account on that device when you checked? In later versions the option is there and says you have to add a MI account first. I'm thinking that *perhaps* in the initial versions where they did that, they didn't even show the option unless you had an account. It's possible that if you add an account, the option would magically just appear. I have no device to test the theory with, though.

**Comment by lql0ve** [comment]
In the initial versions V8.0 i added a MI accouunt, but it didn't show the option, the I update the MIUI Version to V8.2, it appears.

**Comment by sorccu** [comment]
:(

**Comment by sudheesh001** [comment]
I think this issue needs to be reopened. It doesn't work correctly even on my MI phone. I get the following error
```
[15:39:43] sudheeshsinganamalla:~ $ adb shell getevent -ilp
could not open /dev/input/event13, Permission denied
could not open /dev/input/event12, Permission denied
could not open /dev/input/event11, Permission denied
could not open /dev/input/event10, Permission denied
could not open /dev/input/event9, Permission denied
could not open /dev/input/event8, Permission denied
could not open /dev/input/event7, Permission denied
could not open /dev/input/event4, Permission denied
could not open /dev/input/mouse0, Permission denied
could not open /dev/input/event2, Permission denied
could not open /dev/input/event1, Permission denied
could not open /dev/input/mice, Permission denied
could not open /dev/input/event5, Permission denied
could not open /dev/input/event6, Permission denied
could not open /dev/input/event3, Permission denied
could not open /dev/input/event0, Permission denied
```

and on `stf` I receive the following information

```
FTL/device 45168 [5d89bf39] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/units/device/plugins/touch/index.js:223:24)
    at RiskyStream.emit (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
From previous event:
    at startConsumer (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/units/device/plugins/touch/index.js:511:14)
    at /Users/sudheeshsinganamalla/Documents/GameAutomators/stf/lib/units/device/plugins/touch/index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (/Users/sudheeshsinganamalla/Documents/GameAutomators/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /Users/sudheeshsinganamalla/Documents/GameAutomators/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/event10 for inspectionopen: Permission denied"
INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/event9 for inspectionopen: Permission denied"
INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/event8 for inspectionopen: Permission denied"
INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/event7 for inspectionopen: Permission denied"
INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen: Permission denied"
INF/device:plugins:touch 45174 [5d89bf39] minitouch says: "Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied"
```

**Comment by sorccu** [comment]
Did you read everything in this issue? Did you change the setting that you must change?

**Comment by sudheesh001** [comment]
@sorccu Yes, i've an MI account already registered on the phone and `adb devices` shows up the device name. It works perfectly fine with a Moto G phone.

<img width="1440" alt="screen shot 2017-03-31 at 3 53 10 pm" src="https://cloud.githubusercontent.com/assets/4545925/24546748/4feb0460-162a-11e7-84bc-686e479fc5ca.png">

<img width="1440" alt="screen shot 2017-03-31 at 3 53 03 pm" src="https://cloud.githubusercontent.com/assets/4545925/24546750/53d5c9fc-162a-11e7-9212-c53114844174.png">

**Comment by sorccu** [comment]
But did you change the setting shown in https://github.com/openstf/stf/issues/477#issuecomment-262163984?

**Comment by sudheesh001** [comment]
@sorccu Yes I received 3 warning screens holding up each screen for 5 seconds before the Next button is activated and it didn't show up. I just disconnected the cable and reconnected it and it seems to be working totally fine. 😄 Thank you !

Also is there an API for just using the `<device-screen>` on a seperate webpage ? I am also trying to get this working on Windows to contribute to `openstf` and facing a few issues with `libjpeg-turbo`

**Comment by sorccu** [comment]
Ok good. node-jpeg-turbo is actually already compatible with Windows thanks to a contributor, but that version has not been released yet.

**Comment by sorccu** [comment]
#603 now has a better guide for adding Xiaomi devices to STF.
