### ISSUE TITLE
Adb keys going missing

### ISSUE THREAD

**Issue by major-laslo** [openstf/stf#478]
Running 2.3.0 with stf local on an ubuntu 16.10 machine

**What is the issue or idea you have?**

The user is able to use the device through the web interface, but adb connect does nothing. It says you are connected to the device, but then running 'adb devices' comes up empty. Killing/restarting adb, stf, rethinkdb, or the system does not help.

Re-adding the key through the UI also doesn't help, the 'add' dialog goes away but it doesn't add the key/change anything.

The only workaround/fix I have found so far is to remove the adb keypair of the user on their machine, restart adb so it generates a new one. Then the browser shows a dialog to add the new adb key, and from then on it works fine.

Note that when a user with this bug does 'adb connect', the logs in the terminal on the server do show a new successful connection.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

Doesn't seem to be related to devices, it happens randomly.

**Please provide the steps to reproduce the issue.**

Happens at random and rarely, had it on both windows and macos machines.

**What is the expected behavior?**

adb connect actually showing the device after in adb devices.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

No errors

**Comment by vbanthia** [comment]
Check https://github.com/openstf/stf/issues/170 & https://github.com/openstf/stf/issues/428

**Comment by vbanthia** [comment]
This is basically a limitation of STF. Two users cannot add same adbkey because STF uses adbkey to identify the user. But it should show some error dialogue in case someone try to add duplicate key.

**Comment by major-laslo** [comment]
Interesting...however, these cases all happened on machines other than the PC that is running STF, and the adb keys were not copied/shared intentionally anywhere. I see how re-adding the key wasn't helping because of this limitation, but why did it initially happen?

Basically, if we're not actually trying to use the same keys on multiple PCs, do you see why this problem could arise? And how we can avoid it?

**Comment by vbanthia** [comment]
> Basically, if we're not actually trying to use the same keys on multiple PCs, do you see why this problem could arise? And how we can avoid it?

In most of the cases each PC has its own unique adbkey which you can find in `~/.android` directory. Most probably some body else logged in with that account and has added adbkey into his account that is why other users are not able to use that adbkey.

In case you meet this problem again, you can search for the user who is using that PC adbkey from rethinkdb. Follow these steps.
1. Install adbkit globally
```
npm install -g adbkit
```
2. Get fingerprint of current machine adbkey.pub
```
adbkit pubkey-fingerprint ~/.android/adbkey.pub 
```
3. Go to rethinkdb data explored and fire following query
```
r.db('stf').table('users').getAll($FINERPRINT_STRING, {index: 'adbKeys'});
```

This will give you user who have add adbkey.

**Comment by major-laslo** [comment]
Ah, so if a user forgot his/her login credentials and made a new login with new username but old adb keys, this issue would happen? So once we use active directory accounts and users can't just change their logins, this will stop happening?

That clears up everything, thank you very much! While some error message or feedback would be great to have in these cases, I consider this mystery solved and you may feel free to close the issue.

**Comment by vbanthia** [comment]
STF identify user by its email, so if email is changed then it will be a different user.
