### ISSUE TITLE
how to expand device pool to 100+?

### ISSUE THREAD

**Issue by luisxiaomai** [openstf/stf#48]
Hi 

Firstly, thanks for you great project.
I have a question about how to expand device pool to 100+? Suppose one PC has 4 motherboard's USB ports, and each one connects to a usb hub with 7 ports. It can only connect to 28 devices, how we can expand to 100+?

**Comment by sorccu** [comment]
By starting multiple provider units on multiple PCs. See [doc/DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) for more information.
