### ISSUE TITLE
Latest build openstf/stf docker image doesn't work !

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#483]
### My context
- **latest openstf image from docker hub build last day**
- debian jessie 3.16.0-4-amd64
- full deployment (DEPLOYMENT.md) with one machine running all services except provider service running on another machine (ARM one: openstf/stf-armv7l image)
- see other configuration details in my previous issue #479

### What the issue
- when I connect to the login page, I enter my login/passwd (i.e. mock authentification), then an empty page is returned !!!
- note this issue appear with or without SSL configuration
- note this issue didn't appear in the previous build

### Work around 
- I switched to the previous release v2.3.0 in which this issue doesn't appear

**Comment by sorccu** [comment]
I don't think there have been any changes related to that, and you're the
only person to report this issue. I'm thinking it's probably a
configuration issue.

Things to try:

- try logging in with an incognito window, perhaps there's something wrong
with your cache
- before trying to log in, open chrome developer tools and its network tab.
Make sure "preserve log" or whatever it's currently called is checked. Then
attempt to log in. Paste the relevant requests and responses here.

**Comment by denis99999** [comment]
Hi @sorccu,
I made 4 screenshots, see joined files, I hope it will be sufficient for you to investigate about this issue, I'm waiting for further instructions
<img width="1440" alt="capture d ecran 2016-11-24 a 15 05 59" src="https://cloud.githubusercontent.com/assets/22766602/20601759/79ef079a-b25a-11e6-9bcc-b27b882eefd3.png">
<img width="1197" alt="capture d ecran 2016-11-24 a 15 09 04" src="https://cloud.githubusercontent.com/assets/22766602/20601760/7a02c262-b25a-11e6-9d6d-0372914c2a3d.png">
<img width="1205" alt="capture d ecran 2016-11-24 a 15 10 06" src="https://cloud.githubusercontent.com/assets/22766602/20601761/7a1eb03a-b25a-11e6-9525-baf65f6ce71a.png">
<img width="1203" alt="capture d ecran 2016-11-24 a 15 10 25" src="https://cloud.githubusercontent.com/assets/22766602/20601762/7a223688-b25a-11e6-9f35-eadcbaa8b9f7.png">

**Comment by sorccu** [comment]
Oh... maybe this is related to openstf/stf#482. @gunta any chance you could take a look at the webpack config? Looks like maybe it needs some special handling.

**Comment by denis99999** [comment]
I saw a new release was build this night, so I updated but I have always the same issue, do you have any news about that ?

Note in v2.3.0 this issue doesn't appear so it is not a configuration issue, isn't it ? To simplify my configuration, I made a full deployment on a single machine, but it doesn't change anything.

**Comment by vbanthia** [comment]
Pushed a fix. Could you check if this issue is resolved with latest docker image?

**Comment by denis99999** [comment]
I checked 4 hours ago with latest docker image and it was not resolved.

**Comment by vbanthia** [comment]
There will be a new docker image with fix, can you pull latest image and test it again. I pushed changes 15 mins ago.

**Comment by denis99999** [comment]
It's great it works fine now, thank you very much  @vbanthia !!!
