### ISSUE TITLE
Not enough host controller resources for new device

### ISSUE THREAD

**Issue by uniquezhuo** [openstf/stf#489]
Firstly, thanks for you guys create this great tool。as you can see, I met this problem you have listed:
> unsufficient USB host controller resources

as you describe, I run 'stf local' on ubuntu16.04 and plugin maximum 9 usb devices, if go on to plugin more, then i get this error. I know that i can extend the scale by deploy on server, but own demand is that plugin 30 nexus5 in one host computer.

I can't find disable usb3.0(or xhci) options in my bios, so I bought a PCIE extension card like <a href="https://item.jd.com/1004542.html">this</a>. so can you explain why we need usb extension card to solve this problem , i am so curious。

**Comment by sorccu** [comment]
It's a limitation in recent Intel chipsets. You can't fix it, just believe us and get better hardware. AMD is a lot better but it has been unreliable in other ways, not recommended.
