### ISSUE TITLE
Can not use node -- debug cli local

### ISSUE THREAD

**Issue by YuxinZhou** [openstf/stf#49]
Hi, thank you for your great app. I want to use node --debug to have a better understand of how it works. I tried node -- debug cli local, but it failed, both in node version 0.10 and 0.12. I googled and learned that this is a clustered app and all the workers attempted to listen on the same debug port. So how do you debug in your development? Can I set breakpoint on it? Can I debug it or part of it separately?

**Comment by sqstars** [comment]
Can anyone help on this?

**Comment by sorccu** [comment]
Send the process you want to debug a signal to trigger the debugger. See https://nodejs.org/api/debugger.html#debugger_advanced_usage.

I'm closing this ticket as the signal works fine, even though it is a little bit more annoying to use. I'm not sure if we can make it any easier right now, but feedback and patches are definitely welcome.

**Comment by sqstars** [comment]
https://strongloop.com/strongblog/whats-new-nodejs-v0-12-debugging-clusters/

**Comment by sqstars** [comment]
Thx, sorccu sen. Just try to debug stf modules by node-inspector separately. As you mentioned, the node debugger is a little annoying..
