### ISSUE TITLE
Multiple STF Instances at The Same Network

### ISSUE THREAD

**Issue by cemakkok** [openstf/stf#493]
Hi, 

I have a static ip internet and allow remote usage for my STF. I have already configured router ports with range 7000-8000 for STF machine.  I start STF with this command :

stf local --public-ip x.x.x.x  (i can access remotely like  http://x.x.x.x:7100  )

It works fine and i can test on it. I decided add a new STF node at this network (Ubuntu 16.04) and configured router ports with range 10000-11000 for this new machine. It works perfectly at localhost but  I start this node with this command for remote usage:

stf local --public-ip x.x.x.x --provider x.x.x.x(same as public ip) --provider-min-port 10000 --provider-max-port 11000 --poorxy-port 10100 (i can access remotely like  http://x.x.x.x:10100  )

I can see all device when click one, i cannot device screen on web page and when click the stop using it returns "device not found..". It looks

![image](https://cloud.githubusercontent.com/assets/3465848/20787494/229437a0-b7bd-11e6-8898-f0cfe79429b7.png)

 
What is the problem ? I guess maybe because of websocket port, so i change web socket of new machine with starting parameters but result is the same :(

**Comment by sorccu** [comment]
Follow the deployment guide and do a full deployment. We don't support using `stf local` for that, it's for development or local usage only.

**Comment by cemakkok** [comment]
Thanks for your fast response.

**Comment by cemakkok** [comment]
@sorccu can one STF app  handle multiple ADB connection from different port ?  In this way, i can save my sources.

**Comment by sorccu** [comment]
From different ports? Isn't that what it's doing right now? Or did you mean from a single port? If so, then no. It is not possible due to `adb connect` not giving any identifying information.

**Comment by cemakkok** [comment]
No, for example you have got 5 machine with adb(for each) but STF only run one machine and handle 5 adb. (5 machines are in the same network) .

**Comment by sorccu** [comment]
Currently it isn't doable easily. The easiest way you could do it is to use a different stf port range for each machine (see `stf provider --help` for the options). Then on your public machine, you could proxy each port range to the appropriate machine. You could most likely do it with haproxy, although might take a while to configure it. But it's possible, at least.

**Comment by cemakkok** [comment]
Thank you,

I am grateful to you.
