### ISSUE TITLE
use minicap output in other web page

### ISSUE THREAD

**Issue by AlexGrs** [openstf/stf#494]
Hi Guys,

Is it possible to use the stream of screen from minicap or from openstf from an other webpage ? I want to embed the screen in one tv dashboard we have.

Thank you for your help.

Rgds.

**Comment by sorccu** [comment]
Sure. The minicap readme describes the format, just conect to the socket
and read the data in your app. You don't need to run stf, minicap itself is
enough.

**Comment by AlexGrs** [comment]
Cool. I will try this. Thanks for the update. I will try the node.js example in the repo.
