### ISSUE TITLE
A performance issue after i change some code

### ISSUE THREAD

**Issue by uniquezhuo** [openstf/stf#497]
there is the pictures which can demostrate what have done. <img src="http://ww1.sinaimg.cn/mw690/a5e2541bgw1fafycurub8j21kw0vywwx.jpg"/> <img src="http://ww1.sinaimg.cn/mw690/a5e2541bgw1fafycu3csnj21kw0vy1bi.jpg"/>

as you can see, I rebuild the "Devices" tab content to many canvas so I can watch every devices screen change real-time. so I met the performance issue. cpu 100% and memory 100%.

my solutions:
1. I create a angular directive which contain just one canvas. then i get the screen data from many node process( i have read the code , when a device plugin the a new process was created and a port was distributed).  then i use canvas drawimage function to draw the each blob data at it right position.  it seem has some good effect. memory consumption has down。

2.another solution is that restrict the amount of websocket information transmission。 i setInterval in each node process( the file is stf/lib/units/device/plugins/screen/stream.js ) to control it send frame data every 1000ms.

3. divide into pages. limit  maximum 18 devices send data at each 1s

but there also some problem:
1. send data each 1s make it seem not smooth in browser. but if i send data more faster there are so many request .  chrome not work well.

do you have some advice. i really need a more efficient solution

**Comment by sorccu** [comment]
That's very interesting to see. Unfortunately I don't think you can make it
100% smooth easily. Have you tried making the screen capture size as small
as possible?

I have some improvements coming that will reduce memory usage a bit but I
don't think it would solve your issues.

**Comment by uniquezhuo** [comment]
yeah. I now, thank you. I already worried about the performance when i get the product demand. if it's a C/S architecture not a B/S architecture or using some efficient language like c/java, may be it's more fast. this project seems not suit for this scenario.

**Comment by uniquezhuo** [comment]
I have't forgot to minify the scale of the screen to 250*300. it made some help

**Comment by sorccu** [comment]
Yeah, unfortunately I think limiting the FPS and jpeg quality would be the best option. The current code makes it a bit difficult to do, however. That should improve soonish, though.

You could also build a separate app around minicap.

**Comment by gunta** [comment]
Interesting. Definitely not easy but not impossible neither.

So where did you found the biggest bottleneck right now? 
Canvas drawing / Network / Etc?

If the problem happens to be in client side / canvas drawing you could try drawing in a big single canvas. I suspect browsers are not optimised to have so many canvas drawing at the same time.

**Comment by uniquezhuo** [comment]
I found two bottleneck.
1. Canvas drawing.  although i draw in a big single canvas. but there are so many drawImage function call. now one page max 18 devices. my core-i3 cpu show 60%-70%. if i put more device in one page.  it can expand 100%.
2. Network. one page max 18 devices means 18 websocket requests to handle in one seconds. if chrome can't handle all.  the screen in browser is slower than actual devices.  For example, if i open a second chronograph， it need more than 1s in chrome change from 53s to 54s

**Comment by sorccu** [comment]
That 1s lag is because of another reason. My changes will fix that but I can't promise when I'll have time to merge my changes.

**Comment by sorccu** [comment]
It'll also remove unnecessary drawImage calls.

**Comment by uniquezhuo** [comment]
ok. i also try use node-canvas to merge all imgs into one big img, then send to client. at it reduce the num of request and client's drawimage call.  it solved client performance issue. but node server has more consumption. it's not a good idea. may be this idea can help you

**Comment by gunta** [comment]
For canvas drawing in this case the biggest bottleneck inside `drawImage` should be JPEG decompressing (and uploading to the GPU).

It might be worth investigating to do the image mixing on server side, it will add a lag for sure but it will make client side not eat so much CPU.

**Comment by gunta** [comment]
Definitely doing the image mixing on a separate unit / server (and not with node.js but with something fast like https://github.com/jcupitt/libvips) might be better.

**Comment by jhjx** [comment]
I don't know if your problem is solved,but you can use web worker.I tried to put 21 moblie phones in one page without getting stuck
