### ISSUE TITLE
Oppo A37 after installing the apk  returns an error message

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#498]
Oppo A37 after installing apk restuns an err.
![image](https://cloud.githubusercontent.com/assets/18346467/20913258/1645cba6-bbb1-11e6-95b5-4b6cc129231f.png)

But, 
1.install was success
2.mainifest get fail
3.server err log:
ERR/device:plugins:install 27083 [IN89MNGI99999999] Installation of package "com.boyaa.chinesechess.ky" failed Error: Activity class {com.boyaa.chinesechess.ky/com.boyaa.chinesechess.ky.Game} does not exist.
    at /var/stf/node_modules/adbkit/lib/adb/command/host-transport/startactivity.js:57:21
    at tryCatcher (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by sorccu** [comment]
Sometimes it means that the activity wasn't exported in `AndroidManifest.xml`. Does it work on other devices?

**Comment by 0x88l** [comment]
Other device is ok,Only opp A37.

**Comment by sorccu** [comment]
Could be that a security setting is enabled that prevents the app from
starting via cli. Did you have to do anything special when you plugged in
the phone to get STFService working?

**Comment by 0x88l** [comment]
I have found the in the file 'lib/units/devices/plugins/install.js'.
The code  :
sendProgress('installing_app', guesstimate)
          return promiseutil.periodicNotify(
              adb.installRemote(options.serial, apk)  
//  oppo os return status success , but it still installing. When start activity that  oppo OS  can't find the activity. 
                .timeout(60000 * 5)
......

I set timeout 10s to solve the bug. Maybe you have another better way.
The modify coed:

          sendProgress('installing_app', guesstimate)
          return promiseutil.periodicNotify(
              adb.installRemote(options.serial, apk)
                .timeout(60000 * 5)
                .catch(function(err) {
                  switch (err.code) {
                  case 'INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES':
                  case 'INSTALL_FAILED_VERSION_DOWNGRADE':
                    log.info(
                      'Uninstalling "%s" first due to inconsistent certificates'
                    , pkg
                    )
                    return adb.uninstall(options.serial, pkg)
                      .timeout(15000)
                      .then(function() {
                        return adb.installRemote(options.serial, apk)
                          .timeout(60000 * 5)
                      })
                  default:
                    return Promise.reject(err)
                  }
                })
            , 250
            )
            .progressed(function() {
              guesstimate = Math.min(
                end
              , guesstimate + 1.5 * (end - guesstimate) / (end - start)
              )
              sendProgress('installing_app', guesstimate)
            })
        })
//!!!!!!!!!!!!!!!!!
.then(function () {
          return new Promise(function (resolve, reject) {
            setTimeout(function () {
              //after install really finish,like oppo os
              resolve('')
            }, 1000*10)
          })
        })
/////
