### ISSUE TITLE
How to setup a centralized server to connect to multiple slave server which connects devices

### ISSUE THREAD

**Issue by frankbp** [openstf/stf#50]
As we have dozens of mobile devices we have to connect devices to different servers, then how to setup a central server to access all the devices?

**Comment by sorccu** [comment]
You can check [doc/DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) for a setup similar to ours, although you'll have to be able to figure out how to distribute the units yourself.

**Comment by frankbp** [comment]
get it, thanks a lot.
we may be back to you when we got some troubles. :)
