### ISSUE TITLE
Devices are getting disconnected via remote access

### ISSUE THREAD

**Issue by HannanShaik** [openstf/stf#501]
Hi,

I have cloned the repo from here. It is pointing to master branch.

I followed the below steps to build and run stf.

> First, fetch all NPM and Bower modules:
> 
> `npm install`
> You may also wish to link the module so that you'll be able to access the stf command directly from the command line:
> 
> `npm link`

After this I started stf with the below command.

`stf local --public-ip <<my ip>>`

From my local machine, i am able to access stf and the devices. When my colleague tried launching via IP, she was able to launch. However when she clicked on `Use` for one of the devices, the device section was blank and grey. Then it moved back to device detail page and showed that devices are disconnected.

However, I was able to see the devices all this while.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

I do not see any error message in the log.

**Please run `stf doctor` and paste the output here.**

INF/util:doctor 67561 [*] OS Arch: x64
INF/util:doctor 67561 [*] OS Platform: darwin
INF/util:doctor 67561 [*] OS Platform: 16.1.0
INF/util:doctor 67561 [*] Using Node 6.3.0
INF/util:doctor 67561 [*] Using RethinkDB client 2.3.3
INF/util:doctor 67561 [*] Using ZeroMQ 4.1.5
INF/util:doctor 67561 [*] GraphicsMagick 1.3.24
INF/util:doctor 67561 [*] ProtoBuf 2.6.1
INF/util:doctor 67561 [*] Local ADB 1.0.32

INF/util:doctor 67561 [*] Local RethinkDB server 2.3.4

Please help!

**Comment by HannanShaik** [comment]
@sorccu Can you please help me with this?

**Comment by sorccu** [comment]
Not really, it's a configuration issue for sure. Open the Chrome developer console on your friend's browser and there will probably be some kind of an error in there that should give you ideas about what's wrong.

**Comment by denis99999** [comment]
Hello,
Did you check it is not simply a Firewall issue because it seems to be ?

**Comment by HannanShaik** [comment]
@denis99999 yes this was a firewall issue.
