### ISSUE TITLE
Designer Patterns 

### ISSUE THREAD

**Issue by fabiomeyra** [openstf/stf#504]
Hi all,
well I'm beginner, and I'd like to know, whether was used anyone Designer patterns on development of STF, I'm learning the source code, to understand how things happens there, but it's quite hard to understand them. Do you have any help to developers? STF it's a hard project to study without a apprenticeship direction.

**Comment by sorccu** [comment]
I'm really sorry but aside from the existing documentation you can find in the repo, there's no additional documentation. There's some additional information spread around in various issues here on GitHub. New contributors are very welcome but I'm not sure if any of us has time to provide guidance. I would recommend trying to get started by yourself and then creating new issues for more specific things you are having trouble with.
