### ISSUE TITLE
when we running command npm install -g stf ,we  got an error : npm WARN depricated node-uuid@1.4.7: use uuid module instead/usr/bin/stf -> /usr/lib/node_modules/stf/bin/stf/usr/lib

### ISSUE THREAD

**Issue by Venkatesh01** [openstf/stf#513]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
It's just a warning, already fixed in master though.
