### ISSUE TITLE
when i running command rethinkdb ,i  got a comment :could not create directory 'rethinkdb_data' : permission denied

### ISSUE THREAD

**Issue by Venkatesh01** [openstf/stf#514]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Just follow the README exactly, it'll work fine.

**Comment by Venkatesh01** [comment]
README means??

**Comment by sorccu** [comment]
Sorry I don't think I can help you.

**Comment by Venkatesh01** [comment]
Sorry sorccu it was by mistake , Can you please help us sorccu?

**Comment by Venkatesh01** [comment]
sorry it  was by mistake.
instead of google we typed here.
Can you plz help us?
