### ISSUE TITLE
tcpsocket creation failed for port 29015: address  already in use.

### ISSUE THREAD

**Issue by madangopal918** [openstf/stf#515]
when we execute the command
rethinkdb 

we are getting the above error.
what do  we need to do to proceed further?

**Comment by sorccu** [comment]
It means that something is already running on that port. Probably you
already started rethinkdb and forgot about it.

We don't provide rethinkdb support, if you have an issue starting rethinkdb
ask the rethinkdb people (although this particular request is so basic you
shouldn't need to ask anyone at all).
