### ISSUE TITLE
Problem connecting more than 9 devices

### ISSUE THREAD

**Issue by liuang68** [openstf/stf#519]
hello，everybody，due to the server can only connect 9 usb,which leads to our STF platform can only connect 9 mobiles,   i am confused about this issue, do you have any solutions about this? 
My system is  Ubuntu 16.04 LTS 
greatful

**Comment by sorccu** [comment]
This is a super comon issue. Basically your hardware sucks and you can do
nothing about it without getting better hardware. Read the README, our
advice in there is not a joke.

**Comment by 0x88l** [comment]
Usb-hub need to access external power  or will be disconnect.

**Comment by sorccu** [comment]
While that can also be an issue, this one sounds like the Intel problem
listed in the README.

**Comment by liuang68** [comment]
@ sorccu，hello,i'm trying to use 'stf provider --name "provider-windows_3" --connect-sub tcp://10.100.72.195:7250  --connect-push tcp://10.100.72.195:7270  --storage-url http://10.100.72.195  --public-ip 10.100.72.195 --min-port=30001  --max-port=35000',but error.
![image](https://cloud.githubusercontent.com/assets/24601692/21844135/7b10b6d4-d828-11e6-8730-4f15904a7a10.png)
can you tell me why???

**Comment by sorccu** [comment]
No, it says the device is offline. It's your responsibility to make adb
work first before adding anything to stf.

**Comment by liuang68** [comment]
@sorccu good morning,sorccu,can you tell me how to use 'stf provider''s commands?How do you write inside of the parameters？

**Comment by sorccu** [comment]
See the deployment guide. But if your device is offline, it's not stf's
problem. Make sure things like 'adb shell' work before doing anything.

**Comment by thinkhy** [comment]
I solved the problem by disabling USB3.0 in BIOS. My workstation is a DELL plex, os is Ubuntu 16.04.

**Comment by sorccu** [comment]
Yes, that works on some machines.
