### ISSUE TITLE
Can I access STF from a different network than the machine hosting the devices?

### ISSUE THREAD

**Issue by viktors89** [openstf/stf#522]
**What is the issue or idea you have?**
I've been able to access my devices remotely with different machines that are in the same network. Now I want to do the same from a different network but I'm unable even though I have created a redirection in the router.

Could you please give me some indications on what should be done? I'd be really grateful to you.

Thanks!
Victor

**Comment by viktors89** [comment]
Everything's working now, was making a noob mistake with the IPs

**Comment by suvansh-dev** [comment]
Will you please tell me how you did that?

**Comment by sorccu** [comment]
Seems that OP solved this issue :) Good work!

**Comment by tares003** [comment]
@viktors89 Can tell me how? I am trying to do the samething? any guide would be appreciated!Thanks
