### ISSUE TITLE
Can't connect to rethinkDB

### ISSUE THREAD

**Issue by BGolis** [openstf/stf#524]
Hi,
I've been trying to set up a server with stf for some time now. My problem is that all the services fail because they cannot connect to rethinkDB. The reason for this might be the following:
in Deployment.md you state that after starting rethinkDB one should open the webinterface and run this command:

`r.db('rethinkdb').table('cluster_config').get('auth').update({auth_key: 'newkey'})`

In my case this always throws following error:

> 
{

    "deleted": 0 ,
    "errors": 1 ,
    "first_error": "It's illegal to delete rows from the `rethinkdb.cluster_config` table." ,
    "inserted": 0 ,
    "replaced": 0 ,
    "skipped": 0 ,
    "unchanged": 0

}
<

In my opinion this is the reason why nothing works, but I may be wrong on this one.

Thanks for your help.

**Comment by sorccu** [comment]
The documents could be out of date, they were originally made for pre-2.0 and were perhaps last checked in the early 2.x days. Please check the RethinkDB documentation and post your solution here if you find one. Or make a pull request to update the information.

**Comment by mirceanis** [comment]
You can try setting up the password on the first run of your rethink server.
`rethinkdb --initial-password yourBrandNewKey`

**Comment by BGolis** [comment]
So the solution I've found that seems to work is as @mirceanis suggested:

`r.db('rethinkdb').table('users').get('admin').update({password:'yourBrandNewKey'})`

It seems that you can enter whatever password you want there. At least now all of my services can connect to rethinkDB.

Thank you guys.
