### ISSUE TITLE
#question: Has anyone connected a docker emulator to STF?

### ISSUE THREAD

**Issue by isonic1** [openstf/stf#529]
There are a few docker containers that run android emulator inside of them. The one below in particular you can expose your adb connection to the host machine. Just curious if anyone has attempted this or if it would even work with openstf?

https://hub.docker.com/r/tracer0tong/android-emulator/~/dockerfile/

**Comment by sorccu** [comment]
No, emulators overall are not supported right now (you'll most likely see
just a black screen).

**Comment by isonic1** [comment]
Interesting. I can get the emulator screen to appear and fully interact the STF controls when gpu in ON. With gpu off, it unfortunately does not work. I was running a generic_x86_64 on SDK 23.

emulator -avd EM1 -no-window -gpu on
