### ISSUE TITLE
Provider ignores each device

### ISSUE THREAD

**Issue by martinwoit** [openstf/stf#534]
STF version - 2.3.0 (latest) - Docker
STF version - 2.0.1
Debian - Jessie

Deployment on single machine.

**What is the issue or idea you have?**
Hey,
EACH device will be ignored by provider service. 

```INF/provider 1 [*] Subscribing to permanent channel "NMTZ2IqATEWH19zK+hCkdQ=="
INF/provider 1 [*] Sending output to "tcp://qadevicefarm.de:7270"
INF/provider 1 [*] Receiving input from "tcp://qadevicefarm.de:7250"
INF/provider 1 [*] Tracking devices
INF/provider 1 [*] Found device "47900b6e9dd21100" (device)`
INF/provider 1 [*] Providing all 0 of 3 device(s); ignoring "47900b6e9dd21100", "47900b6e9dd21100", "47900b6e9dd21100"
```

No STFService.apk will be installed on the device.
The setup is almost the same like in the DEPLOYMENT description. The stf-triproxy-dev.service is running.

I also did the setup on another machine with the same result.

In front of the machine where STF is running, an apache is installed, which provides the host name and forwards https access. Therefor I had to adapt the nginx.conf to get rid of mixed content.

But now I'm at my wit's end.

Do I need to configure IPs in the services and let nginx handle all hostname related stuff?
Or do I also have to provide full hostname in the service files?

Thank you for your help.
Martin

**Comment by sorccu** [comment]
Hmm... you're using a public domain name in the provider zmq sockets. Are
you positive that they're actually accessible on the IP it maps to? Please
also try disabling the firewall (e.g. iptables) temporarily on that machine.

The output is weird, it shouldn't show the same serial multiple times.

**Comment by sorccu** [comment]
The domain doesn't return any results on `dig` or `nslookup`. The situation could certainly be different from your network but I suspect that it's simply not able to connect to that address. ZeroMQ does not by default tell you if that's the case, it just keeps waiting for something to appear from somewhere.

**Comment by martinwoit** [comment]
Sorccu!! It is working now!! Changed the domain name to the correct IP.

Thank you for your support!!

(Due to privacy considerations I changed the original domain to a not working one)

**Comment by maykel535** [comment]
I have the same problem?? Where I change it the domain for ip??

Thanks
