### ISSUE TITLE
How do I connect to my local STF from another computer

### ISSUE THREAD

**Issue by skumar1122** [openstf/stf#536]
**What is the issue or idea you have?**
Error in connecting stf remotely.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
SHXXXXXXX    device usb:336592896X product:htc_europe model:HTC_One_M8 device:htc_m8

**Please provide the steps to reproduce the issue.**
Run stf remotely ,
stf local --public-ip <your_internal_network_ip_here>
i.e. (stf local remoteIP localIP)

**What is the expected behavior?**
Should connect to remote address 
https://X.X.X.X:7100

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
skumar$ **stf local 10.1.X.X 10.1.X.X**
INF/util:procutil 64270 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 64271 [*] Connecting to 127.0.0.1:28015
INF/db 64271 [*] Unable to connect to 127.0.0.1:28015
FTL/db 64271 [*] No hosts left to try
FTL/util:lifecycle 64271 [*] Shutting down due to fatal error

/usr/local/lib/node_modules/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Please run `stf doctor` and paste the output here.**
INF/util:doctor 64478 [*] OS Arch: x64
INF/util:doctor 64478 [*] OS Platform: darwin
INF/util:doctor 64478 [*] OS Platform: 15.6.0
INF/util:doctor 64478 [*] Using Node 6.3.1
INF/util:doctor 64478 [*] Using RethinkDB client 2.3.3
INF/util:doctor 64478 [*] Using ZeroMQ 4.2.1
INF/util:doctor 64478 [*] GraphicsMagick 1.3.25
INF/util:doctor 64478 [*] Local ADB 1.0.36

INF/util:doctor 64478 [*] ProtoBuf 3.2.0
ERR/util:doctor 64478 [*] Current ProtoBuf version is not supported, it has to be ~2
INF/util:doctor 64478 [*] Local RethinkDB server 2.3.5

**Comment by vbanthia** [comment]
Two things,
1. Either rethinkdb is not running or your machine is not able to connect with rethinkdb. Check it first.
2. You are using wrong command.  Instead of `stf local 10.1.X.X 10.1.X.X` you need to run `stf local --public-ip <IP_ADDRESS_OF_CURRENT_MACHINE>`. After this, from another machine(should be in same network) access `http://IP_ADDRESS_OF_MACHINE_WHERE_STF_IS_RUNNING:7100`

**Comment by skumar1122** [comment]
@vbanthia 

Perfect mate.
Spot on working now.

Do you know can we run appium Automation scripts on this devices ?

**Comment by vbanthia** [comment]
Yes. Check [this](https://github.com/openstf/stf-appium-example)

**Comment by jrolon** [comment]
Hello @vbanthia
effectively the example that you show us is perfect.

My question is I can send the execution from another computer that is in the same network, when I launch the command DEVICE_SERIAL = XXXXXX ./scripts/run_integration_test.sh, I'm doing it from a windows and the STF I have it in a MAC
