### ISSUE TITLE
Broken touchscreen

### ISSUE THREAD

**Issue by martykan** [openstf/stf#537]
Hello, I have a phone with a broken touchscreen, to the point where the driver doesn't recognize it, so minitouch doesn't have anything to use.

The device is a Xiaomi Redmi 2. Is there a way to go around that?

```
INF/device:plugins:touch 7220 [33dcccfe] Connecting to minitouch service
INF/device:plugins:touch 7220 [33dcccfe] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 7220 [33dcccfe] minitouch says: "Unable to find a suitable touch device"
```

**Comment by sorccu** [comment]
Currently no, but if you need to access the device (perhaps to get
something out of it), you can use an OTG adapter and an actual mouse. Or
perhaps the 'input' command from adb.

**Comment by martykan** [comment]
Would this: https://github.com/vi/virtual_touchscreen work?

**Comment by sorccu** [comment]
It might if you have root.

**Comment by sorccu** [comment]
FWIW I think it's unusual that Linux can't see the device. Thinking a
cable/ribbon might have become loose. Worth thinking about if you can take
it apart.

**Comment by sorccu** [comment]
This doesn't seem to be relevant anymore, so I'm closing the issue.
