### ISSUE TITLE
remote debug the app

### ISSUE THREAD

**Issue by likezjuisee** [openstf/stf#539]
I used the adbkit as a adb proxy. But I came with a problem when I am debugging a app. 
![screenshot_2017-02-14-16-27-00](https://cloud.githubusercontent.com/assets/12730220/22920988/cc80d250-f2d2-11e6-99c8-6f1bb16f115d.png)

It not happened every time.

**Comment by likezjuisee** [comment]
The ide is android studio 2.2.3. The eclipse does not have this problem. I am confused.

**Comment by sorccu** [comment]
This has been moved to openstf/adbkit#62.
