### ISSUE TITLE
Minicap-related issue prevents me from connecting to any phone

### ISSUE THREAD

**Issue by apprayadmin** [openstf/stf#542]
**What is the issue or idea you have?**
If I build stf locally after cloning from github, I cannot connect devices, the following error keeps appearing upon device connect and the stf is not available via browser:

INF/device:resources:minicap 8632 [WUJ01J5TB9] Installing "minicap.so" as "/data/local/tmp/minicap.so"
   (here comes the funny part)
FTL/device 8632 [WUJ01J5TB9] Setup had an error TypeError: Cannot read property 'S_IXUSR' of undefined
    at /var/www/openstf/lib/units/device/resources/minicap.js:91:46
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FTL/util:lifecycle 8632 [WUJ01J5TB9] Shutting down due to fatal error

If I install openstf as a global npm module, it works like a charm - but with local instance, no luck. I've seen some minicap-related issues, but not like this typeerror: cannot read property... so I opened a new issue ticket. 

**Does it only happen on a specific device? Please run adb devices -l and paste the corresponding row.**
I've tried with Sony, Samsung and HTC (Android 4.2, 5.0) as well as different linuxes (ubuntu 14,16, x32-x64, mint, debian), same results. 

Output of adb devices -l is:
List of devices attached
WUJ01J5TB9             device usb:1-2 product:E2105 model:E2105 device:E2105

**Please provide the steps to reproduce the issue.**
apt-get install yasm libzmq3-dbg libzmq3-dev libzmq3 rethinkdb (obviously if a library was missing from ubuntu repos I installed them manually)
(npm install -g stf --unsafe-perm --verbose)
cd /var/www/
git clone https://github.com/openstf/stf.git openstf
cd openstf
npm install -g bower
npm install
bower install --allow-root
rethinkdb
stf local
 + as long as devices are not connected, everything works fine. When I connect a device (either before or after launching stf) the errors start appearing.

**What is the expected behavior?**
No minicap-errors to show up and to be able to load stf device page and connect actually even with my local build, not only as an npm global package

**Do you see errors or warnings in the stf local output? If so, please paste them or the full log here.**
More of the code:
INF/middleware:webpack 8407 [*] Bundle is now valid
INF/webpack:config 8407 [*] Build progress 100% (complete)
INF/device:support:push 8632 [WUJ01J5TB9] Sending output to "tcp://127.0.0.1:7116"
INF/device 8632 [WUJ01J5TB9] Preparing device
INF/device:support:sub 8632 [WUJ01J5TB9] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 8632 [WUJ01J5TB9] Subscribing to permanent channel "*ALL"
INF/device:support:properties 8632 [WUJ01J5TB9] Loading properties
INF/device:support:abi 8632 [WUJ01J5TB9] Supports ABIs armeabi-v7a, armeabi
INF/provider 8397 [*] Providing 0 of 1 device(s); waiting for "WUJ01J5TB9"
INF/device:resources:minicap 8632 [WUJ01J5TB9] Installing "minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 8632 [WUJ01J5TB9] Installing "minicap.so" as "/data/local/tmp/minicap.so"
   (here comes the funny part)
FTL/device 8632 [WUJ01J5TB9] Setup had an error TypeError: Cannot read property 'S_IXUSR' of undefined
    at /var/www/openstf/lib/units/device/resources/minicap.js:91:46
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FTL/util:lifecycle 8632 [WUJ01J5TB9] Shutting down due to fatal error
INF/provider 8397 [*] Cleaning up device worker "WUJ01J5TB9"
ERR/provider 8397 [*] Device worker "WUJ01J5TB9" died with code 1
INF/provider 8397 [*] Restarting device worker "WUJ01J5TB9"

**Please run stf doctor and paste the output here.**
INF/util:doctor 3561 [*] OS Arch: x64
INF/util:doctor 3561 [*] OS Platform: linux
INF/util:doctor 3561 [*] OS Platform: 4.4.0-31-generic
INF/util:doctor 3561 [*] Using Node 4.2.6
INF/util:doctor 3561 [*] Using RethinkDB client 2.3.3
INF/util:doctor 3561 [*] Using ZeroMQ 4.1.4
WRN/util:doctor 3561 [*] Executable was not found
WRN/util:doctor 3561 [*] Executable was not found
INF/util:doctor 3561 [*] Local ADB 1.0.32

INF/util:doctor 3561 [*] Local RethinkDB server 2.3.5~0xenial
/var/www/openstf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0xenial
    at new SemVer (/var/www/openstf/node_modules/semver/semver.js:293:11)
    at Range.test (/var/www/openstf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/var/www/openstf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/var/www/openstf/lib/util/doctor.js:13:15)
    at /var/www/openstf/lib/util/doctor.js:95:7
    at /var/www/openstf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by sorccu** [comment]
Your node is too old. Only 6.9 or newer is supported now. This makes our
life easier.

**Comment by apprayadmin** [comment]
what a silly mistake i did not notice.. thanks for your help. good job guys

**Comment by sorccu** [comment]
It will now show an error when you try to use an older node :)
