### ISSUE TITLE
Error when fixing stf local server listening port to a value less than 1024 (ex: 80) !

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#544]
When I try to launch a STF local server on a listening port < 1024 (ex: 80) instead the default 7100 one, an error occurs, seel the below log.

Is it an error or simply a limitation ?

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
févr. 22 10:11:00 debian docker[5944]: INF/util:procutil 1 [*] Forking "/app/lib/cli poorxy --port 80 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 17 [dev001] PUB socket bound on tcp://127.0.0.1:7114
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 16 [app001] PUB socket bound on tcp://127.0.0.1:7111
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 17 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 16 [app001] DEALER socket bound on tcp://127.0.0.1:7112
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 17 [dev001] PULL socket bound on tcp://127.0.0.1:7116
févr. 22 10:11:03 debian docker[5944]: INF/triproxy 16 [app001] PULL socket bound on tcp://127.0.0.1:7113
févr. 22 10:11:04 debian docker[5944]: INF/poorxy 84 [*] Listening on port 80
févr. 22 10:11:04 debian docker[5944]: events.js:160
févr. 22 10:11:04 debian docker[5944]: throw er; // Unhandled 'error' event
févr. 22 10:11:04 debian docker[5944]: ^
févr. 22 10:11:04 debian docker[5944]: Error: listen EACCES 0.0.0.0:80
févr. 22 10:11:04 debian docker[5944]: at Object.exports._errnoException (util.js:1026:11)
févr. 22 10:11:04 debian docker[5944]: at exports._exceptionWithHostPort (util.js:1049:20)
févr. 22 10:11:04 debian docker[5944]: at Server._listen2 (net.js:1244:19)
févr. 22 10:11:04 debian docker[5944]: at listen (net.js:1293:10)
févr. 22 10:11:04 debian docker[5944]: at Server.listen (net.js:1389:5)
févr. 22 10:11:04 debian docker[5944]: at module.exports (/app/lib/units/poorxy/index.js:67:10)
févr. 22 10:11:04 debian docker[5944]: at Object.module.exports.handler (/app/lib/cli/poorxy/index.js:60:39)
févr. 22 10:11:04 debian docker[5944]: at Object.self.runCommand (/app/node_modules/yargs/lib/command.js:170:22)
févr. 22 10:11:04 debian docker[5944]: at parseArgs (/app/node_modules/yargs/yargs.js:920:28)
févr. 22 10:11:04 debian docker[5944]: at Object.get [as argv] (/app/node_modules/yargs/yargs.js:860:16)
févr. 22 10:11:04 debian docker[5944]: at Object.<anonymous> (/app/lib/cli/index.js:40:3)
févr. 22 10:11:04 debian docker[5944]: at Module._compile (module.js:570:32)
févr. 22 10:11:04 debian docker[5944]: at Object.Module._extensions..js (module.js:579:10)
févr. 22 10:11:04 debian docker[5944]: at Module.load (module.js:487:32)
févr. 22 10:11:04 debian docker[5944]: at tryModuleLoad (module.js:446:12)
févr. 22 10:11:04 debian docker[5944]: at Function.Module._load (module.js:438:3)
févr. 22 10:11:04 debian docker[5944]: FTL/cli:local 1 [*] Child process had an error ExitError: Exit code "1"
févr. 22 10:11:04 debian docker[5944]: at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
févr. 22 10:11:04 debian docker[5944]: at emitTwo (events.js:106:13)
févr. 22 10:11:04 debian docker[5944]: at ChildProcess.emit (events.js:191:7)
févr. 22 10:11:04 debian docker[5944]: at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
févr. 22 10:11:04 debian docker[5944]: INF/cli:local 1 [*] Shutting down all child processes
févr. 22 10:11:04 debian docker[5944]: INF/util:lifecycle 16 [app001] Winding down for graceful exit
févr. 22 10:11:04 debian docker[5944]: INF/util:lifecycle 17 [dev001] Winding down for graceful exit

**Comment by vbanthia** [comment]
Those ports will require root permission. Use `sudo` while running `stf local`×command.

**Comment by sorccu** [comment]
The docker image does not run as root for security reasons. Only root can
bind on low ports. You can use docker's port mapping if you want.

Note that you're running stf local inside the docker image. While it may
work, it is not a supported deployment method. By doing the full deployment
(linked in README) you also set up nginx instead of poorxy (poor proxy).
You can bind nginx to any port you want.

**Comment by denis99999** [comment]
port mapping does not work because I use the "--net host" parameter in the docker run command, is there another way (i.e. except the full deployment) ?

**Comment by sorccu** [comment]
Well you can override the user it runs as I guess... at your own risk though. Try adding `--user root` or `--user 0` to your docker command.

**Comment by denis99999** [comment]
it works fine, thank you very much !
