### ISSUE TITLE
I am trying to upgrade STF from 2.0 to 2.3.0 but facing the error while running the command: npm install -g stf

### ISSUE THREAD

**Issue by deepaksharma17819** [openstf/stf#545]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
You have provided no details. There is no way to help you.
