### ISSUE TITLE
Phone blank screen when VPN connection between STF server and STF provider machines !

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#546]
In labs, I have a full deployment configuration with one machine hosting a STF server and another machine hosting a STF provider, clients and STF machines share the same network without firewall and all work fine !

Nevertheless, in my target deployment all these machines will not be in the same place, and it seems to be sure that a VPN connection will be required between the STF server and the STF provider. In such assumption, even if this VPN connection works well, clients will no be able to reach the provider to remote debug the phones, except if they are part of this VPN, isn't it ? Do you have experimented such architecture or do you have some recommendations about that ?

So, to progress in labs I established a simple VPN connection between the STF server and the STF provider machines, like this:
```
(provider: vpn server) # openvpn --dev tun1 --ifconfig 10.4.0.1 10.4.0.2
(server: vpn client)   # openvpn --remote @provider --dev tun1 --ifconfig 10.4.0.2 10.4.0.1
```
After what, I started the STF server and the STF provider services using the previous tunneling information, all work well through the GUI
- file explorer
- shell
- app upload
- remote debug url (ex: adb connect 10.4.0.1:15009 run from the STF server of course)
- ...

EXCEPT the phone screen appears as blank, so it is impossible to interact with the phone through its screen !

When I click on the "Use" button for a device, I don't see any network traffic on the VPN except the traffic on the ports 7250 and 7270

Here is an extract of the relating nginx configuration:
```
    location ~ "^/d/10.4.0.1/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.4.0.1:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
```

And the web console in Chrome:

<img width="1164" alt="capture d ecran 2017-02-22 a 14 53 27" src="https://cloud.githubusercontent.com/assets/22766602/23214396/d838cde0-f90e-11e6-987f-d12db00fcdc6.png">

**Comment by denis99999** [comment]
I found a work around but I don't know if it is the correct solution : at STF provider side I changed the "screen-ws-url-pattern" parameter value in the corresponding systemd configuration file, replacing the VPN IP address of the STF server by its public IP address, and all work fine now !

But is it a correct solution ?  I tried instead at STF server side to modify the nginx configuration file doing the opposite modification, that is replacing the public IP address by the VPN one at websocket section, but it does not work !

**Comment by denis99999** [comment]
Is it possible to have an answer to my intial question : knowing that in fulll deployment architecture a client has an ADB direct access to the STF provider, and with the assumption that a VPN is required between the STF server and the STF provider, and so between the client and the STF provider for ADB traffic, do you have some recommendations about network configuration to deploy ?
Thanks.

**Comment by sorccu** [comment]
If your developers are willing to do an ssh port forward before running adb
connect, that may also be an option. Or, you can set up a TCP reverse proxy
somewhere that maps connections to the right device port, and then modify
the connect url pattern. If you map the ports 1:1, modifying the pattern
may be all you need. Otherwise you may need to write some code to look up
the right device.

The issue with adb connect is that it doesn't tell the server which device
it wanted to connect to. Therefore you can only differentiate devices by
the destination port/IP. That's why everything but adb connect goes through
nginx, and that's also why it requires you to open more ports. But by using
one of tge two methods above, and perhaps writing some code of your own to
do the ip/port mapping, it's possible to have every client connect to a
single machine.

In general we do not provide detailed help with network configuration and
connectivity, it's too time consuming and really annoying to do without
understanding the way your network is set up. So, in principle, that part
is left to you.

**Comment by denis99999** [comment]
Yes I imagined to do that work, thank you very much to confirm that :-)

**Comment by denis99999** [comment]
Regarding the work around I used to get screen displayed through a VPN, that is specifying at provider side the public IP address of the server into the "screen-ws-url-pattern" parameter, I made a network trace and it seems the provider never establishes a connection to the server using this public IP address, so I suppose the "screen-ws-url-pattern" information is transmitted to the server through the VPN to be processed at server side, may you confirm that to me please ? 

If it is well the case so it is satisfactory for me because the VPN principle would be not violated by a websocket flow which would bypass the VPN.

Nevertheless, don't you think it would be more logical to specify into the "screen-ws-url-pattern" parameter only the IP addresses of the interfaces used by the provider and the server to communicate ?

**Comment by sorccu** [comment]
I'm not sure why you've decided to include the ip address in the URL at
all. Our docs definitely don't say anything about needing to do that. I'd
just give it some sort of a name (e.g. buildingname-5f-001). The only
reason why you'd include the ip is if you wanted to capture it and use in
in proxy_pass... but that would allow anyone to specify any ip and expose
your network. That's a bit of an issue with the dynamic port range as well,
but you can change the regex if needed, at least.
