### ISSUE TITLE
求大神赐教，zuk z1的机子，Thanks！！！

### ISSUE THREAD

**Issue by hehm4** [openstf/stf#547]
aaron@STF:/usr/local/lib/node_modules/stf$ stf local
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 3056 [*] Connecting to 127.0.0.1:28015
INF/db:setup 3056 [*] Database "stf" already exists
INF/db:setup 3056 [*] Table "users" already exists
INF/db:setup 3056 [*] Table "accessTokens" already exists
INF/db:setup 3056 [*] Table "vncauth" already exists
INF/db:setup 3056 [*] Table "devices" already exists
INF/db:setup 3056 [*] Table "logs" already exists
INF/db:setup 3056 [*] Table "reservation" already exists
INF/db:setup 3056 [*] Table "useInfor" already exists
INF/db:setup 3056 [*] Index "users"."adbKeys" already exists
INF/db:setup 3056 [*] Waiting for index "users"."adbKeys"
INF/db:setup 3056 [*] Index "accessTokens"."email" already exists
INF/db:setup 3056 [*] Index "vncauth"."response" already exists
INF/db:setup 3056 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 3056 [*] Index "devices"."owner" already exists
INF/db:setup 3056 [*] Index "devices"."present" already exists
INF/db:setup 3056 [*] Index "devices"."providerChannel" already exists
INF/db:setup 3056 [*] Index "reservation"."userEmail" already exists
INF/db:setup 3056 [*] Index "reservation"."status" already exists
INF/db:setup 3056 [*] Index "reservation"."loginName" already exists
INF/db:setup 3056 [*] Index "reservation"."userGroup" already exists
INF/db:setup 3056 [*] Index "reservation"."manufacturer" already exists
INF/db:setup 3056 [*] Index "reservation"."model" already exists
INF/db:setup 3056 [*] Waiting for index "accessTokens"."email"
INF/db:setup 3056 [*] Waiting for index "vncauth"."response"
INF/db:setup 3056 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 3056 [*] Waiting for index "devices"."owner"
INF/db:setup 3056 [*] Waiting for index "devices"."present"
INF/db:setup 3056 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 3056 [*] Waiting for index "reservation"."userEmail"
INF/db:setup 3056 [*] Waiting for index "reservation"."status"
INF/db:setup 3056 [*] Waiting for index "reservation"."loginName"
INF/db:setup 3056 [*] Waiting for index "reservation"."userGroup"
INF/db:setup 3056 [*] Waiting for index "reservation"."manufacturer"
INF/db:setup 3056 [*] Waiting for index "reservation"."model"
INF/db:setup 3056 [*] Index "users"."adbKeys" is ready
INF/db:setup 3056 [*] Index "accessTokens"."email" is ready
INF/db:setup 3056 [*] Index "devices"."owner" is ready
INF/db:setup 3056 [*] Index "devices"."present" is ready
INF/db:setup 3056 [*] Index "devices"."providerChannel" is ready
INF/db:setup 3056 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 3056 [*] Index "vncauth"."response" is ready
INF/db:setup 3056 [*] Index "reservation"."userEmail" is ready
INF/db:setup 3056 [*] Index "reservation"."status" is ready
INF/db:setup 3056 [*] Index "reservation"."loginName" is ready
INF/db:setup 3056 [*] Index "reservation"."userGroup" is ready
INF/db:setup 3056 [*] Index "reservation"."manufacturer" is ready
INF/db:setup 3056 [*] Index "reservation"."model" is ready
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name STF --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 3050 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 3063 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 3062 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 3063 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 3063 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/triproxy 3062 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 3062 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/reaper 3066 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 3066 [reaper001] Reaping devices with no heartbeat
INF/db 3066 [reaper001] Connecting to 127.0.0.1:28015
INF/reaper 3066 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 3066 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/db 3064 [proc001] Connecting to 127.0.0.1:28015
INF/processor 3064 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 3064 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/db 3065 [proc002] Connecting to 127.0.0.1:28015
INF/processor 3065 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 3065 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/provider 3067 [*] Subscribing to permanent channel "q1Y6AOjySmCd7iMwHdqO2g=="
INF/provider 3067 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 3067 [*] Receiving input from "tcp://127.0.0.1:7114"
INF/poorxy 3074 [*] Listening on port 7100
INF/provider 3067 [*] Tracking devices
INF/storage:plugins:image 3072 [*] Listening on port 7103
INF/auth-mock 3068 [*] Listening on port 7120
INF/storage:temp 3071 [*] Listening on port 7102
INF/storage:plugins:apk 3073 [*] Listening on port 7104
INF/websocket 3070 [*] Subscribing to permanent channel "*ALL"
INF/websocket 3070 [*] Listening on port 7110
INF/db 3070 [*] Connecting to 127.0.0.1:28015
INF/websocket 3070 [*] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 3070 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/app 3069 [*] Using pre-built resources
INF/app 3069 [*] Listening on port 7105
INF/db 3069 [*] Connecting to 127.0.0.1:28015
login submit:hehm4
ITCode Interface Data:
{ expand: 'attributes',
  link: 
   { href: 'http://itcode.lefile.cn/crowd/rest/usermanagement/latest/user?username=hehm4',
     rel: 'self' },
  name: 'hehm4',
  password: 
   { link: 
      { href: 'http://itcode.lefile.cn/crowd/rest/usermanagement/latest/user/password?username=hehm4',
        rel: 'edit' } },
  key: '1409027:a9f475ef29547d46a1580edda718fd2f',
  active: true,
  attributes: 
   { attributes: [],
     link: 
      { href: 'http://itcode.lefile.cn/crowd/rest/usermanagement/latest/user/attribute?username=hehm4',
        rel: 'self' } },
  'first-name': 'HongMei',
  'last-name': 'He',
  'display-name': 'Hongmei HM4 He',
  email: 'hehm4@lenovo.com' }
eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ4NzgxNzM0MDk3MH0.eyJlbWFpbCI6ImhlaG00QGxlbm92by5jb20iLCJuYW1lIjoiaGVobTQifQ.WGXalocn1RaiqWs1H1pPXOKdwiFFV1QBlZ-Qsvjmt1I
INF/util:datautil 3069 [*] Device database does not have an entry for "255f5068" (model "undefined"/"undefined"). This is not an error, it only means that we don't have data for it yet.

**Comment by sorccu** [comment]
We don't speak Chinese. I'm not sure what your issue is even after trying to use Google Translate. Please offer more details in English.

**Comment by WillPangZi** [comment]
Seems his ZUK Z1 device not works fine.

Referes to #436

**Comment by hehm4** [comment]
OK , Let me see，Thanks a lot!



zhule117@163.com
 
发件人： WillPang
发送时间： 2017-02-23 16:15
收件人： openstf/stf
抄送： hehm4; Author
主题： Re: [openstf/stf] 求大神赐教，zuk z1的机子，Thanks！！！ (#547)
Seems his ZUK Z1 device not works fine.
Referes to #436

**Comment by sorccu** [comment]
I think this has been fixed for quite a while now.
