### ISSUE TITLE
In the project how to make their own changes in the JS source code effective?

### ISSUE THREAD

**Issue by Bobcui001** [openstf/stf#551]
I now need to secondary development of STF, see the source code and found that the front-end procedures using Webpack package. Would like to ask you, in the project how to make their own changes in the JS source code effective?

**Comment by sorccu** [comment]
Remove the prebuilt resources and your changes will take effect. If you
have gulp installed, run `gulp clean`. If not, you can run
`./node_modules/.bin/gulp clean` to do the same with the bundled gulp.

**Comment by Bobcui001** [comment]
Ok, thanks, it seems that you are using the Webpack & Glup mode, to achieve on-demand loading and modular. Yes, I will always be concerned about this project. Wish good ~ @sorccu
