### ISSUE TITLE
storage temp s3

### ISSUE THREAD

**Issue by nianliang** [openstf/stf#555]
why code of storage-temp/index.js is require('../../units/storage/s3') and code of storage-s3/index.js is require('../../units/storage/temp')?Is there anything wrong?

**Comment by sorccu** [comment]
You're right, the files are backwards. However, since they have the right content, everything still works as long as the units are launched via the main `bin/stf` executable.

**Comment by nianliang** [comment]
yes,i get it ,thank you!
