### ISSUE TITLE
Image quality / color depth configuration in minicap

### ISSUE THREAD

**Issue by apprayadmin** [openstf/stf#556]
**What is the issue or idea you have?**
Hi there, STF is a great tool but I'm wondering if possible to configure the screen capture module (minicap?) for lower color depths. The thing is, one single device can eat up to 10-15 mbit/s bandwidth, even more if has HD screen - for debugging, you might not want to have full color palette (24-32bit) but instead, optimized bandwidth and reduced memory/cache usage may be a reasonable decision. What do you think? Is it already available maybe?

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Any

**Please provide the steps to reproduce the issue.**
N/A

**What is the expected behavior?**
N/A

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
N/A

**Please run `stf doctor` and paste the output here.**-
N/A

**Comment by sorccu** [comment]
There's an option to decrease the JPG quality in master. Other than that I personally will definitely not spend time on playing with color depths and whatever. I would perhaps accept a PR that does that, though.

STF was made for local networks where there's plenty of bandwidth available.

**Comment by PheonixS** [comment]
Where I can find the option in configuration in master branch?
Thanks!

**Comment by sorccu** [comment]
Check --help.
