### ISSUE TITLE
any tools support to type text from pc?

### ISSUE THREAD

**Issue by bbdabing** [openstf/stf#557]
is the stf has any tools support to type text from keyword of pc？just like minicap can support screen stream.

**Comment by sorccu** [comment]
They are in STFService.apk, but depending on what you want to do you can just use the built-in `input` command.

**Comment by bbdabing** [comment]
what's built-in?you mean is the adb shell input?but it's not support unicode，can i just use STFService.apk。

**Comment by sorccu** [comment]
Well our version doesn't really support unicode either. I think Appium has something you can use. I can't help you with this any further but please update the issue with your solution if you find one.
