### ISSUE TITLE
Some questions about deploying STF to actual servers.

### ISSUE THREAD

**Issue by yuancc** [openstf/stf#56]
Thanks for your great sharing and reply! I have got STF running via stf local and now I want to try deploying STF to actual servers.But I have some questions need your help.(I want to deploy the platform on two hosts,each host connected to several devices for testing,the OS of hosts is Ubuntu 15.04 )
1.Whether I need to deploy the local Requirements at every host at first (like Node.js >= 0.12,ADB properly set up ,GraphicsMagick ,RethinkDB >= 2.0.0,ZeroMQ ,Protocol Buffers,and pkg-config as stf local) before deploying STF to actual servers like DEPLOYMENT.md?
2.If I don't use Authorization method when I testing the platform,neither OAuth2.0 nor LDAP,How can  I set up the "SECRET=YOUR_SESSION_SECRET_HERE" in stf-app@.service,stf-auth@.service,stf-websocket@.service? How to deal with "AUTHKEY=YOUR_RETHINKDB_AUTH_KEY_HERE_IF_ANY" in rethinkdb-proxy-28015.service.
Thanks!

**Comment by sorccu** [comment]
If you don't have an auth key for rethinkdb, just don't set the environment variable.

Disabling auth is not possible right now, see #37. Use the mock auth if you don't have anything else.

I would suggest using the docker images because they include all the dependencies (although you'll have to set up rethinkdb separately) and you won't have to install anything separately (except RethinkDB). See [doc/DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) for details.

I would also strongly recommend running RethinkDB on another host. ADB is only required on nodes where you have devices connected. The rest of the dependencies would be good to have everywhere.

**Comment by yuancc** [comment]
Hi sorccu,thanks for your replay.I'll have a try,maybe I‘ll need to ask you for further help!

**Comment by yuancc** [comment]
Hi sorccu,when i use the command "sudo docker pull openstf/base:v1.0.1" it will show "Error while pulling image:Get https://index.docker.io/v1/repositories/openstf/base/images: net/http: TLS handshke time".

when i  create the docker image in the current directory of Dockerfile with the command "sudo docker build .",it will show "Get https://registry-1.docker.io/v1/repositories/openstf/base/tags/v1.0.1:dial tcp 54.152.161.54.443: i/o timeout".

How can i resolve the question?

**Comment by sorccu** [comment]
I think you're having some kind of network issues. Maybe something's blocking the connection?

Worst-case scenario, if you're unable to solve the connectivity issues, you can [build the base image](https://github.com/openstf/docker-openstf-base) too, with `docker build -t openstf/base:v1.0.1 .`. You should then be able to build the image in this repository.

**Comment by yuancc** [comment]
Thanks a lot! I‘m interested in this platform!But I haven't used systemd and docker before,
Now,I have create the units(rethinkdb-proxy-28015.service,adbd.service,stf-provider@.service and other files of '.service' ) under the  directory of "/etc/systemd/system",Can you describe the other implementation steps in detail?

This is the new question with docker build -t openstf/base:v1.0.1 . 
yuancc@STF:/usr/share/docker-engine/contrib/desktop-integration/gparted$ sudo docker build -t openstf/base:v1.0.1 .
Sending build context to Docker daemon 4.096 kB
Step 0 : FROM openstf/base:v1.0.1
Pulling repository docker.io/openstf/base
4f0e1fd9c617: Download complete 
83e4dde6b9cf: Download complete 
b670fb0c7ecd: Download complete 
29460ac93442: Download complete 
d2a0ecffe6fa: Download complete 
Status: Downloaded newer image for openstf/base:v1.0.1
 ---> 4f0e1fd9c617
Step 1 : RUN useradd --system       --no-create-home       --shell /usr/sbin/nologin       --home-dir /app       stf
 ---> Running in 4c1c1be06067
 ---> 401d9d32010a
Removing intermediate container 4c1c1be06067
Step 2 : ENV PATH /app/bin:$PATH
 ---> Running in c3cd0bd3a006
 ---> 8c16a2c9eee9
Removing intermediate container c3cd0bd3a006
Step 3 : WORKDIR /app
 ---> Running in 69bd52d20074
 ---> fc2dec01370e
Removing intermediate container 69bd52d20074
Step 4 : EXPOSE 3000
 ---> Running in 5c92582d4370
 ---> dc5e825e1d51
Removing intermediate container 5c92582d4370
Step 5 : COPY . /app/
 ---> 205a07eb5316
Removing intermediate container 28029e2bc23a
Step 6 : RUN export PATH=/app/node_modules/.bin:$PATH &&     npm install &&     bower install --allow-root &&     gulp build
 ---> Running in 6c247023b6a2
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /app/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/app/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c export PATH=/app/node_modules/.bin:$PATH &&     npm install &&     bower install --allow-root &&     gulp build' returned a non-zero code: 254


Sorry to bother you！

**Comment by yuancc** [comment]
I change the contents of Dockerfile "RUN export PATH=/app/node_modules/.bin:$PATH && npm install && bower install --allow-root && gulp build" to "RUN export PATH=/usr/local/lib/node_modules/.bin:$PATH && npm install && bower install --allow-root && gulp build" ,the question still exist!

**Comment by sorccu** [comment]
You have to run the docker build command from the folder where you cloned
the stf repo.

**Comment by yuancc** [comment]
Hi,sorccu,I'm sorry to bother you again.

I have created the docker image(openstf/base:v1.0.1) by the method like below：
1.$docker search openstf/base
2.$docker pull openstf/base:v1.0.1
3.$docker images,then i can see 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              93a5a17e88f4        15 hours ago        489.5 MB
<none>              <none>              8624680b8bd9        15 hours ago        489.5 MB
ctlc/ambassador     latest              cea471227545        13 days ago         186.4 MB
openstf/base        v1.0.1              4f0e1fd9c617        5 weeks ago         474.7 MB

I have create the units in the path of /etc/systemd/system
    adbd.service
    stf-provider@.service
    rethinkdb-proxy-28015.service
    stf-app@.service
    stf-auth@.service
    stf-log-rethinkdb.service
    stf-migrate.service
    stf-notify-hipchat.service
    stf-processor@.service
    stf-provider@.service
    stf-reaper.service
    stf-storage-plugin-apk@.service
    stf-storage-plugin-image@.service
    stf-storage-temp@.service
    stf-triproxy-app.service
    stf-triproxy-dev.service
    stf-websocket@.service  and ngnix.service

Then I change the configuration of nginx like DEPLOYMENT.md,
In addition to the above comes,I have installed RethinkDB separetely.

But, I don't know how to get the platform running,I tested it by the following method:
1.open a new terminal,input the command "rethinkdb" (like stf local)

2.open a new terminal,input the command "sudo docker run -d -p 80:80 openstf/base:v1.0.1",the result is "yuancc@STF:~$ sudo docker run -d -p 80:80 openstf/base:v1.0.1
e3392b09e421056c2fa7df3be715c439b858003c51783c28337b506ebff8a266
yuancc@STF:~$ "

3.input the URL(https://stf.example.org/) in my browser,it will be show"Server not found"
Maybe it's wrong,or I missed something?I want to run it on my PC at first,and then i will try deploy it on several hosts.

Can you tell me the correct and detailed steps to take the platform running? 
	
Looking forward to your reply!
Thanks!

**Comment by sorccu** [comment]
The openstf/base image does NOT include STF. It only exists so that the main build in this repo doesn't take too long. You need to pull or build openstf/stf, although the units will attempt do it for you.

The example URL does not work because it's an example URL. You need your own domain (or you can just use your IP) and then you'll have to modify the unit configs with the new URL.

You should create a separate unit for RethinkDB (preferably on another server) and expose its ports. Then you need to then modify `rethinkdb-proxy-28015.service` so that it's able to connect, and start it. Then you start the migrate unit and let it finish. Then you start the rest of the units, order is not that important but you should launch the provider last.

Sorry but I don't think I can provide anymore support with this issue, it's taking way too much time. The deployment docs are meant for advanced users who have prior experience with docker and systemd.

**Comment by yuancc** [comment]
Hi,sorccu!I have learned the basic knowledge about docker and systemd.
But I don't know the meaning of commands like "ExecStartPre=-/usr/bin/docker kill %p,docker rm %p",when I start the units(like rethinkdb-proxy-28015.service),I can check the status with the command of "$systemctl status rethinkdb-proxy-28015.service ",it will show

"root@OMTL-STF:/home/yuancc# systemctl status rethinkdb-proxy-28015.service -l
● rethinkdb-proxy-28015.service - RethinkDB proxy/28015
   Loaded: loaded (/etc/systemd/system/rethinkdb-proxy-28015.service; static; vendor preset: enabled)
   Active: active (running) since 一 2015-08-17 19:21:33 CST; 25min ago
  Process: 1639 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 1633 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)"

I can't start the unit stf-migrate.service, the status is
"root@OMTL-STF:/home/yuancc# systemctl status stf-migrate.service -l
● stf-migrate.service - STF migrate
   Loaded: loaded (/etc/systemd/system/stf-migrate.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since 一 2015-08-17 19:34:43 CST; 1min 24s ago
  Process: 8461 ExecStart=/usr/bin/docker run --rm --name %p --link rethinkdb-proxy-28015:rethinkdb openstf/stf:latest stf migrate (code=exited, status=1/FAILURE)
  Process: 8455 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 8448 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 7848 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
 Main PID: 8461 (code=exited, status=1/FAILURE)"

this kind of question will be emerge where have the command like "docker kill %p".how can i deal with it?

others:
I can find 5 images in my the list of images when i run the command "$docker images".

"root@OMTL-STF:/home/yuancc# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
openstf/stf         latest              1e2efcf0fd35        8 days ago          979.4 MB
ctlc/ambassador     latest              cea471227545        2 weeks ago         186.4 MB
openstf/base        v1.0.1              4f0e1fd9c617        5 weeks ago         474.7 MB
nginx               1.7.10              3f72b0ae3e59        5 months ago        93.43 MB
sorccu/adb          latest              37b4eb7ce7a3        13 months ago       343 MB "
and i start rethinkdb in a new terminal:"$rethinkdb"like "stf local",then i start rethinkdb-proxy-28015.service "$systemctl start rethinkdb-proxy-28015.service",then start the migrate unit "$systemctl start stf-migrate.service"but it failed!

Sorry to trouble you again.

**Comment by sorccu** [comment]
It says failure, but because the command is prefixed with -, the failure is only mentioned in the logs but doesn't prevent the unit from starting. It's normal to see it in the logs.

We just improved the deployment docs to include a sample rethinkdb.service, that might help.
