### ISSUE TITLE
Screenshots problem

### ISSUE THREAD

**Issue by liuang68** [openstf/stf#560]
Hello, @sorccu I installed newly STF code,but i found the screenshots doesn't work.can ypu help me ?
![image](https://cloud.githubusercontent.com/assets/24601692/24089954/0b27147e-0d77-11e7-99e4-f7c06fffa1a1.png)

**Comment by 0x88l** [comment]
modify lib/unit/storage/temp.js
copy another  app.get('/s/blog/:id/:name'......）

**Comment by liuang68** [comment]
@0x88l Sorry, according to what you said, I did not find temp.js in lib/unit/storage/temp.js,What can be done in detail?thx

**Comment by sorccu** [comment]
If there's a bug you've found please submit a PR. All I can say is that it
has (nearly) always worked for me.
