### ISSUE TITLE
STF Service doesn't start on Wiko LENNY 3

### ISSUE THREAD

**Issue by FelixHahn** [openstf/stf#561]
**Environment:**

- STF Version 2.3.0
- Running in Docker Container after your deployment.md
- Serveral Android Phones, Tablets and Smartwatches connected to the different device hosts in different locations
- Wiko Lenny 3 (Android 6.0) with activated USB Debugging

**What is the issue or idea you have?**

STF Service App was automatically installed on the device.
The STF Service doesn't start on the Wiko Lenny 3.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

Yes, it happes only to Wiko LENNY 3.

0123456789ABCDEF       device product:V3702AN model:LENNY3 device:V3702AN

**Please provide the steps to reproduce the issue.**

Check if any old version of the STF Services is installed on the phone. If there are any old versions than uninstall them.
Plug the phone to device host with the USB Debugging enabled on the phone
--> STF Services doesn't start on phone. The phone is not listed in the STF web front end.

**What is the expected behavior?**

After plugging the phone to the device host.
The STF Services get installed and are started automatically by the device host.
Afterwards the Smartphone is listed on the STF web front end.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Logs of the Device host:

FTL/util:lifecycle 10282 [0123456789ABCDEF] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "0123456789ABCDEF"
ERR/provider 1 [*] Device worker "0123456789ABCDEF" died with code 1
INF/provider 1 [*] Restarting device worker "0123456789ABCDEF"
INF/device:support:push 10294 [0123456789ABCDEF] Sending output to "tcp://devside.stf-server.iavgroup.local:7270"
INF/device 10294 [0123456789ABCDEF] Preparing device
INF/device:support:sub 10294 [0123456789ABCDEF] Receiving input from "tcp://devside.stf-server.iavgroup.local:7250"
INF/device:support:sub 10294 [0123456789ABCDEF] Subscribing to permanent channel "*ALL"
INF/device:support:properties 10294 [0123456789ABCDEF] Loading properties
INF/device:support:abi 10294 [0123456789ABCDEF] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 10294 [0123456789ABCDEF] Checking whether we need to install STFService
INF/device:resources:service 10294 [0123456789ABCDEF] Running version check
INF/device:resources:service 10294 [0123456789ABCDEF] STFService up to date
INF/device:plugins:service 10294 [0123456789ABCDEF] Launching agent
INF/device:plugins:service 10294 [0123456789ABCDEF] Launching service
INF/device:plugins:service 10294 [0123456789ABCDEF] Agent says: "Listening on @stfagent"
INF/device:plugins:service 10294 [0123456789ABCDEF] Agent says: "InputClient started"
FTL/device 10294 [0123456789ABCDEF] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /app/lib/units/device/plugins/service.js:101:23
From previous event:
    at /app/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 10294 [0123456789ABCDEF] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "0123456789ABCDEF"
ERR/provider 1 [*] Device worker "0123456789ABCDEF" died with code 1
INF/provider 1 [*] Restarting device worker "0123456789ABCDEF"
INF/device:support:push 10306 [0123456789ABCDEF] Sending output to "tcp://devside.stf-server.iavgroup.local:7270"
INF/device 10306 [0123456789ABCDEF] Preparing device
INF/device:support:sub 10306 [0123456789ABCDEF] Receiving input from "tcp://devside.stf-server.iavgroup.local:7250"
INF/device:support:sub 10306 [0123456789ABCDEF] Subscribing to permanent channel "*ALL"
INF/device:support:properties 10306 [0123456789ABCDEF] Loading properties
INF/device:support:abi 10306 [0123456789ABCDEF] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 10306 [0123456789ABCDEF] Checking whether we need to install STFService
INF/device:resources:service 10306 [0123456789ABCDEF] Running version check
INF/device:resources:service 10306 [0123456789ABCDEF] STFService up to date
INF/device:plugins:service 10306 [0123456789ABCDEF] Launching agent
INF/device:plugins:service 10306 [0123456789ABCDEF] Agent says: "Listening on @stfagent"
INF/device:plugins:service 10306 [0123456789ABCDEF] Launching service
INF/device:plugins:service 10306 [0123456789ABCDEF] Agent says: "InputClient started"
FTL/device 10306 [0123456789ABCDEF] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /app/lib/units/device/plugins/service.js:101:23
From previous event:
    at /app/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 10306 [0123456789ABCDEF] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "0123456789ABCDEF"
ERR/provider 1 [*] Device worker "0123456789ABCDEF" died with code 1
INF/provider 1 [*] Restarting device worker "0123456789ABCDEF"
INF/device:support:push 10318 [0123456789ABCDEF] Sending output to "tcp://devside.stf-server.iavgroup.local:7270"
INF/device 10318 [0123456789ABCDEF] Preparing device
INF/device:support:sub 10318 [0123456789ABCDEF] Receiving input from "tcp://devside.stf-server.iavgroup.local:7250"
INF/device:support:sub 10318 [0123456789ABCDEF] Subscribing to permanent channel "*ALL"
INF/device:support:properties 10318 [0123456789ABCDEF] Loading properties
INF/device:support:abi 10318 [0123456789ABCDEF] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 10318 [0123456789ABCDEF] Checking whether we need to install STFService
INF/device:resources:service 10318 [0123456789ABCDEF] Running version check
INF/device:resources:service 10318 [0123456789ABCDEF] STFService up to date
INF/device:plugins:service 10318 [0123456789ABCDEF] Launching agent
INF/device:plugins:service 10318 [0123456789ABCDEF] Agent says: "Listening on @stfagent"
INF/device:plugins:service 10318 [0123456789ABCDEF] Launching service
INF/device:plugins:service 10318 [0123456789ABCDEF] Agent says: "InputClient started"
FTL/device 10318 [0123456789ABCDEF] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /app/lib/units/device/plugins/service.js:101:23
From previous event:
    at /app/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 10318 [0123456789ABCDEF] Shutting down due to fatal error

The Log is repeating. The installation wents through fine but the service doesn't start.

**Please run `stf doctor` and paste the output here.**

Should I run the stf doctor on the device host?

Thank you for your help!

Kind regards 

Felix Hahn

**Comment by FelixHahn** [comment]
I can't find any similar settings on the Wiko phone. I will look into the topic after my holiday. I will be back next week on monday.

Thank you for your fast response

**Comment by FelixHahn** [comment]
@sorccu Sorry, the mistake was on our side.
To use the Wiko Lenny 3 with STF you must deactivate the 360 Security app (is installed by default by Wiko) and allow STF Services in Protected Apps.

For deactivating Wiko 360 Security App: 

Settings -> Apps -> 360 Security -> than deactivate App

![wikolenny3_360security](https://cloud.githubusercontent.com/assets/9655106/24393278/d025fd28-1397-11e7-9cc5-3e9007492f2b.jpg)

Allowing STF Service App in Protected App:

Settings -> Protected Apps -> Set the slider for STF Services on active

![lenny3_0123456789abcdef](https://cloud.githubusercontent.com/assets/9655106/24393216/85fa6ebe-1397-11e7-827e-b4c2abacf4ac.jpg)

After you did this settings the Wiko Lenny 3 runs fine with STF :).

**Comment by sorccu** [comment]
Interesting. Thanks for the detailed information!

**Comment by sorccu** [comment]
Also, note that since the maker has been extremely lazy and hasn't even set the USB serial number (as is evident from the value `0123456789ABCDEF`), you can only have one of these devices connected in STF since it's used as a unique key.

**Comment by FelixHahn** [comment]
Thank you for the advice. We already noticed this behaviour with several cheap phones from smaller manufacturers. This is a problem for us. Because from what I know the only way to set this serial number is to root the phone and this is no option for us. Am I right?

**Comment by sorccu** [comment]
Yeah you can't really change the serial number. If you have the skills, you could try writing a proxy that sits between stf and adb. That proxy would pretend to be adb and somehow map each device to a unique ID, possibly by making queries on the side and using the IMEI number, WIFI mac address, or just a persistent text file for the ID. That's the only way to do it right now without modifying STF.

Modifying STF is tricky since none of that information is known at the time the device is plugged in. Initially only the USB serial number is known. STF provides information in real time so it has to deal with the information it's able to access.

**Comment by FelixHahn** [comment]
Thank you :). The Proxy is a good idea. When there is time we will look into it. I will talk to Benjamin who did already the Appium Connector for us. 

Thanks again :).
