### ISSUE TITLE
stf 2.3.0 not detecting devices

### ISSUE THREAD

**Issue by mygit00** [openstf/stf#564]
Hi, I'm using the latest version of STF - 2.3.0. 
**What is the issue or idea you have?**
Devices are properly connected and detected by computer but STF is not detecting them. Note that on the same machine with an older STF version, this used to work fine. This issue started occurring only in this newer version 2.3.0

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
When I run adb devices, list of devices is showing blank.

**Please provide the steps to reproduce the issue.**
Connect the devices to computer, notice the computer has properly detected the devices

**What is the expected behavior?**
STF should also properly detect the attached devices.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
![stf-local](https://cloud.githubusercontent.com/assets/26623893/24245799/5ebb81ae-0fea-11e7-8266-a27760859ad4.png)

**Please run `stf doctor` and paste the output here.**
![stf-doctor](https://cloud.githubusercontent.com/assets/26623893/24245576/7f8a067c-0fe9-11e7-96ac-97ec07157573.png)

**Comment by sorccu** [comment]
I don't get it. The error you're seeing simply means that there's something already listening on a port, meaning that you either have two stf instances running or some other program is running there. What exactly is the issue if not that?

**Comment by mygit00** [comment]
My bad, I'm closing this issue. Actually those attached devices' USB debugging setting was not enabled, because of which the adb devices was resulting blank. 

STF is working great. Thank you.

**Comment by mygit00** [comment]
closing per above comment
