### ISSUE TITLE
Question: using minitouch through openstf

### ISSUE THREAD

**Issue by ssynix** [openstf/stf#571]
I noticed that while running openstf, I can directly connect to a device's websocket address to stream the screen. Is the same thing possible with touch interactions?

I know I can directly use minitouch, but it feels a bit too "low-level" if using it through openstf is exposed.

**Comment by sorccu** [comment]
Not really, although you could connect to the app websocket that the ui
uses for everything else. You'd have to mimic the ui though. If you want to
try that, check chrome's network inspector, select the websocket, and check
the messages that are sent.

I feel like it's probably too mich hassle. Using minitouch directly would
be easier I think.

**Comment by ssynix** [comment]
Thanks for the super fast response 😄! I'll give that a try and see if I'm better off just using minitouch.
