### ISSUE TITLE
Error while running STF locally

### ISSUE THREAD

**Issue by skumar1122** [openstf/stf#572]
**What is the issue or idea you have?**
I have pulled latest code and I am getting error when running STF locally. 
and also rethinkdb is started in another terminal.

Node version is **7.8.0**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
List of devices attached
06157df68947b219       device usb:336592896X product:zerofltexx model:SM_G920F device:zeroflte
**Please provide the steps to reproduce the issue.**
Run $stf local
Run $rethinkdb

**What is the expected behavior?**
STF should start locally

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

> MM5003604:~ skumar$ stf local
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'please-update-dependencies'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli/please.js:1:63)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
> 

**Please run `stf doctor` and paste the output here.**

> skumar$ stf doctor
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'please-update-dependencies'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli/please.js:1:63)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

**Comment by sorccu** [comment]
Seems like you did not do `npm install` after pulling the latest changes.

**Comment by skumar1122** [comment]
I am not sure what i have done right now but i am getting error when I run this 

> MM5003604:~ skumar$ npm install
> 
> > uiautomator-client@1.1.9 install /Users/skumar/node_modules/uiautomator-client
> > node ./scripts/build.js
> 
> JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
> The android command is no longer available.
> For manual SDK and AVD management, please use Android Studio.
> For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
> /Users/skumar/node_modules/uiautomator-client/scripts/build.js:177
>       throw e;
>       ^
> 
> Error: setup failed
>     at ChildProcess.createProcess.on.code (/Users/skumar/node_modules/uiautomator-client/scripts/build.js:133:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> npm WARN enoent ENOENT: no such file or directory, open '/Users/skumar/package.json'
> npm WARN skumar No description
> npm WARN skumar No repository field.
> npm WARN skumar No README data
> npm WARN skumar No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.1.9 (node_modules/uiautomator-client):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.1.9 install: `node ./scripts/build.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by sorccu** [comment]
Well, that's not STF. Can't help you with that.

**Comment by skumar1122** [comment]
Sorry, Can you reckon something here ..

> MM5003604:git skumar$ npm install -g stf
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm ERR! path /usr/local/lib/node_modules/stf
> npm ERR! code EISGIT
> npm ERR! git /usr/local/lib/node_modules/stf: Appears to be a git repo or submodule.
> npm ERR! git     /usr/local/lib/node_modules/stf
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/skumar/.npm/_logs/2017-04-11T16_05_19_363Z-debug.log

**Comment by sorccu** [comment]
No I don't think so, I'd rather fix actual issues or build new features. If you're having trouble with dependencies, consider using Linux and the docker image we provide. Other than that you have to have your environment in proper working condition, honestly it's not our responsibility to help you with that.

As a last tip I would recommend doing `rm -rf /usr/local/lib/node_modules/stf` and reinstalling. That doesn't look right at all.

**Comment by skumar1122** [comment]
@sorccu 
Much Appreciated for help! apologies for bothering.

Cheers
SK
