### ISSUE TITLE
Can I get stf in Windows 7？ Thanks a lot!

### ISSUE THREAD

**Issue by wangpengfei100** [openstf/stf#573]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Perhaps some day. None of us develops on Windows so it has the lowest
possible priority.

**Comment by codeskyblue** [comment]
Possible, but very very hard.

**Comment by denis99999** [comment]
A work arround is to install STF on a virtualization system like Virtual Box for instance !
