### ISSUE TITLE
I change some codes in /stf/res/app/menu/menu.jade, Then input "gulp clean && gulp build "   faild 

### ISSUE THREAD

**Issue by wangpengfei100** [openstf/stf#574]
First,Thanks for your great Tools! My English not so good...

I change some codes in /stf/res/app/menu/menu.jade, 
Then input "gulp clean && gulp build "  but faild ....
It show  " No gulpfile found".
What show I do to make the changed STF work?

**Comment by sorccu** [comment]
You need the git repository if you're changing things. Could be that you're modifying an installation you installed from NPM, which would not work as it doesn't include all resources.

**Comment by wangpengfei100** [comment]
Thanks!
