### ISSUE TITLE
Using " APP Upload " faild

### ISSUE THREAD

**Issue by wangpengfei100** [openstf/stf#575]
**What is the issue or idea you have?**
When I using "App Upload" a APK to my test phone, Faild.
Err Log as follow:

INF/storage:temp 2091 [*] Uploaded "aqybfq.apk" to "/tmp/upload_7c0e32f0c313b7cd0cb92d4a361a3b51"
ERR/storage:plugins:apk 2101 [*] Unable to read manifest of "38fa7aaa-164b-4b2c-b5c5-440e6e9709d7" Error: Invalid or unsupported zip format. No END header found
    at new ApkReader (/usr/local/lib/node_modules/stf/node_modules/adbkit-apkreader/lib/apkreader.js:27:17)
    at Function.ApkReader.readFile (/usr/local/lib/node_modules/stf/node_modules/adbkit-apkreader/lib/apkreader.js:16:14)
    at /usr/local/lib/node_modules/stf/lib/units/storage/plugins/apk/task/manifest.js:9:30
    at process._tickCallback (node.js:355:11)

Thanks for your reply

**Comment by sorccu** [comment]
Are you using the master branch? It has a few related fixes.

Otherwise please send the apk to me.

**Comment by wangpengfei100** [comment]
Thanks, I SOLVE the problem.
Yesterday,I change some codes to fix  "screemshot" picture not show.  Now I change back ,"App Upload" FIXED, but "screemshot" not  show  back ......
I will try to fix it ,thanks for your reply
