### ISSUE TITLE
Auto reload 

### ISSUE THREAD

**Issue by benedict-lee** [openstf/stf#576]
**What is the issue or idea you have?**
In development environment, autoreload didn't work

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
1. git clone https://github.com/openstf/stf.git
2. npm inatall
3. npm link
4. stf local
5. modify/add stf frontend codes
eg. 
res/app/components/xxx/xxx-service.js
res/app/xxx/index.js
res/app/xxx/xxx-controller.js
res/app/xxx/xxx.pug

**What is the expected behavior?**
auto reload stf server.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
no message

**Please run `stf doctor` and paste the output here.**
```
INF/util:doctor 61099 [*] OS Arch: x64
INF/util:doctor 61099 [*] OS Platform: darwin
INF/util:doctor 61099 [*] OS Platform: 15.6.0
INF/util:doctor 61099 [*] Using Node 6.10.2
INF/util:doctor 61099 [*] Using RethinkDB client 2.3.3
INF/util:doctor 61099 [*] Using ZeroMQ 4.2.0
WRN/util:doctor 61099 [*] Executable was not found
INF/util:doctor 61099 [*] GraphicsMagick 1.3.25
INF/util:doctor 61099 [*] Local ADB 1.0.36

INF/util:doctor 61099 [*] Local RethinkDB server 2.3.5
```

**Comment by sorccu** [comment]
The installation process uses prebuilds resources. You need to clean first.
Run 'gulp clean' or './node_modules/.bin/gulp clean' if you don't have it
installed.

Also there's no auto reload, only auto build. You meed to refresh manually
after changing things.

**Comment by benedict-lee** [comment]
Thanks, It's working.
