### ISSUE TITLE
STFService fails to start on some ASUS devices (Error: Not found; no service started.)

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#577]
**What is the issue or idea you have?**

This is not an issue but rather posted here for future reference.

Some ASUS devices fail to become active in the STF UI. They stay disconnected all the time.

Looking at STF logs, the following can be seen:

> Error: Not found; no service started.

Looking at logcat, the following message can be seen:

> App Op not allow to start app jp.co.cyberagent.stf/10162

This is caused by the [ASUS Auto-start Manager](https://www.asus.com/support/faq/1011266). Follow the instructions in that link to enable STFService. Everything should then work OK.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

> redacted       device usb:redacted product:WW_Phone model:ASUS_X014D device:ASUS_X014D_1

**Comment by mihaistana** [comment]
The link it's not working anymore, here you have a cached version of it [https://web.archive.org/web/20160504044651/https://www.asus.com/support/faq/1011266](url)

**Comment by oddgames-david** [comment]
Auto-start manager can be found in Settings -> Battery -> PowerMaster -> Auto-start manager
