### ISSUE TITLE
Differences between Device URL port and Remote Debug URL port

### ISSUE THREAD

**Issue by rfapo** [openstf/stf#579]
I'm trying to connect a device using 'adb connect' with the device.display.url value <"ws://ip:port"> but the device doesn't appear in the list. Then I tried to connect using the Remote Debug URL and it works. Shouldn't it be the same value in both cases?
![devicedisplayurl](https://cloud.githubusercontent.com/assets/599132/25147758/fbb846d6-244e-11e7-8a3e-f3fc51e53295.png)
![remotedebug](https://cloud.githubusercontent.com/assets/599132/25147771/0462ec78-244f-11e7-8158-d37cd9393c06.png)

**Comment by sorccu** [comment]
The device URL is for the screen (display) only and does not work with ADB. The debug URL is for ADB.
