### ISSUE TITLE
npm install stf failed

### ISSUE THREAD

**Issue by testerlife** [openstf/stf#580]
# npm-debug.log:
64933 info lifecycle basic-auth@1.1.0~install: basic-auth@1.1.0
64934 silly lifecycle basic-auth@1.1.0~install: no script for install, continuing
64935 silly install bufferutil@1.3.0 /root/node-v6.10.2-linux-x64/lib/node_modules/.staging/bufferutil-08da6e97
64936 info lifecycle bufferutil@1.3.0~install: bufferutil@1.3.0
64937 verbose lifecycle bufferutil@1.3.0~install: unsafe-perm in lifecycle false
64938 verbose lifecycle bufferutil@1.3.0~install: PATH: /root/node-v6.10.2-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bufferutil/node_modules/.bin:/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/.bin:/root/node-v6.10.2-linux-x64/lib/node_modules/.bin:/root/node-v6.10.2-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/android-sdk-linux/tools:/root/android-sdk-linux/platform-tools:/root/root/android-sdk-linux/tools:/root/root/android-sdk-linux/platform-tools:/usr/local/protobuf/bin/
64939 verbose lifecycle bufferutil@1.3.0~install: CWD: /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bufferutil
64940 silly lifecycle bufferutil@1.3.0~install: Args: [ '-c', 'node-gyp rebuild' ]
64941 info lifecycle bufferutil@1.3.0~install: Failed to exec install script
64942 verbose unlock done using /root/.npm/_locks/staging-5e8af678fb34472d.lock for /root/node-v6.10.2-linux-x64/lib/node_modules/.staging
64943 silly rollbackFailedOptional Starting
64944 silly rollbackFailedOptional Finishing
64945 silly runTopLevelLifecycles Finishing
64946 silly install printInstalled
64947 warn optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 (node_modules/stf/node_modules/bunyan/node_modules/dtrace-provider):
64948 warn optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 install: `node scripts/install.js`
64948 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY:
64949 verbose optional Failed at the dtrace-provider@0.8.1 install script 'node scripts/install.js'.
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the dtrace-provider package,
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs dtrace-provider
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls dtrace-provider
64949 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
64950 warn optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.7.1 (node_modules/stf/node_modules/dtrace-provider):
64951 warn optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.7.1 install: `node scripts/install.js`
64951 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY:
64952 verbose optional Failed at the dtrace-provider@0.7.1 install script 'node scripts/install.js'.
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the dtrace-provider package,
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs dtrace-provider
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls dtrace-provider
64952 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
64953 verbose stack Error: bufferutil@1.3.0 install: `node-gyp rebuild`
64953 verbose stack spawn ENOENT
64953 verbose stack     at ChildProcess.<anonymous> (/root/node-v6.10.2-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:33:16)
64953 verbose stack     at emitTwo (events.js:106:13)
64953 verbose stack     at ChildProcess.emit (events.js:191:7)
64953 verbose stack     at maybeClose (internal/child_process.js:886:16)
64953 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
64954 verbose pkgid bufferutil@1.3.0
64955 verbose cwd /root
64956 error Linux 4.2.0-16-generic
64957 error argv "/root/node-v6.10.2-linux-x64/bin/node" "/usr/local/bin/npm" "install" "-g" "stf"
64958 error node v6.10.2
64959 error npm  v3.10.10
64960 error file sh
64961 error code ELIFECYCLE
64962 error errno ENOENT
64963 error syscall spawn
64964 error bufferutil@1.3.0 install: `node-gyp rebuild`
64964 error spawn ENOENT
64965 error Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'.
64965 error Make sure you have the latest version of node.js and npm installed.
64965 error If you do, this is most likely a problem with the bufferutil package,
64965 error not with npm itself.
64965 error Tell the author that this fails on your system:
64965 error     node-gyp rebuild
64965 error You can get information on how to open an issue for this project with:
64965 error     npm bugs bufferutil
64965 error Or if that isn't available, you can get their info via:
64965 error     npm owner ls bufferutil
64965 error There is likely additional logging output above.
64966 verbose exit [ 1, true ]

**Comment by sorccu** [comment]
Maybe you do not have a compiler installed. I don't think we can help you
with this, it's your responsibility to get your environment working
properly. Also, running npm install as root can cause issues. Try with
another user, too.

**Comment by testerlife** [comment]
thank you . The problem has been solved

**Comment by Feliphegomez** [comment]
It should install **Python** and others files.

**Run** this in Windows **PowerShell** as **administrator:**

~~~sh
npm install --global --production windows-build-tools
~~~
