### ISSUE TITLE
stf doctor failed

### ISSUE THREAD

**Issue by testerlife** [openstf/stf#581]
root@wzl-virtual-machine:~/node-v6.10.2-linux-x64/lib/node_modules/stf/bin# ./stf doctor
/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/compiled/6.10.2/linux/x64/zmq.node
    at bindings (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by sorccu** [comment]
Did you install ZeroMQ?

**Comment by testerlife** [comment]
@sorccu 
yes installed

**Comment by sorccu** [comment]
Ok run `npm install zmq` in a random folder (like `/tmp`) and paste the output here.

**Comment by testerlife** [comment]
problem：
root@wzl-virtual-machine:~# npm install zmq

> zmq@2.15.3 install /root/node_modules/zmq
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/root/node-v6.10.2-linux-x64/bin/node" "/usr/local/bin/npm" "install" "zmq"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by sorccu** [comment]
I told you. Do not use root.

**Comment by testerlife** [comment]
oh 
wzl@wzl-virtual-machine:/root$ sudo npm install zmq
[sudo] wzl 的密码： 

> zmq@2.15.3 install /root/node_modules/zmq
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/root/node-v6.10.2-linux-x64/bin/node" "/usr/local/bin/npm" "install" "zmq"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by sorccu** [comment]
Do not use sudo, do not use root. Do not use anything that makes you uid 0.

**Comment by sorccu** [comment]
It says you do not have zeromq installed.

**Comment by testerlife** [comment]
stf@wzl-virtual-machine:/root/node-v6.10.2-linux-x64/lib/node_modules/stf/bin$ npm install zmq

> zmq@2.15.3 install /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  COPY Release/zmq.node
make: Leaving directory '/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build'
stf@2.3.0 /root/node-v6.10.2-linux-x64/lib/node_modules/stf
└── zmq@2.15.3 
**run stf doctor ：**
stf@wzl-virtual-machine:/root/node-v6.10.2-linux-x64/lib/node_modules/stf/bin$ ./stf doctor
/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/compiled/6.10.2/linux/x64/zmq.node
    at bindings (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by sorccu** [comment]
It looks ok I guess, as long as that folder has permissions set up properly
(you're still in /root so that is suspicious but it could be alright). I
would recommend deleting your whole node installation and starting from
zero now that you actually have the dependency you needed. It's not worth
the time to attempt to fix a broken install. If you're having trouble with
dependencies, use the docker image instead.

**Comment by testerlife** [comment]
# thank u now problem：
stf@wzl-virtual-machine:/root/node-v6.10.2-linux-x64/lib/node_modules/stf/bin$ ./stf doctor
INF/util:doctor 15869 [*] OS Arch: x64
INF/util:doctor 15869 [*] OS Platform: linux
INF/util:doctor 15869 [*] OS Platform: 4.2.0-16-generic
INF/util:doctor 15869 [*] Using Node 6.10.2
INF/util:doctor 15869 [*] Using RethinkDB client 2.3.3
INF/util:doctor 15869 [*] Using ZeroMQ 4.1.6
WRN/util:doctor 15869 [*] Executable was not found
INF/util:doctor 15869 [*] Local ADB 1.0.31
INF/util:doctor 15869 [*] GraphicsMagick 1.3.21
INF/util:doctor 15869 [*] Local RethinkDB server 2.3.5~0wily
/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0wily
    at new SemVer (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/root/node-v6.10.2-linux-x64/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /root/node-v6.10.2-linux-x64/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /root/node-v6.10.2-linux-x64/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by sorccu** [comment]
That's OK. It just doesn't parse the version well. It should work now if
you try.

**Comment by testerlife** [comment]
thank you
