### ISSUE TITLE
need a description how zmq message transmit?

### ISSUE THREAD

**Issue by QingyunLiu** [openstf/stf#582]
Hi @sorccu , thanks for your great works!  After read the deployment.md and the core topology, I just confused how message transmit between ZMQ's end-points, especially DEALER and DEALER.
Could you give a example in actual scene to explain it?
Sorry for my poor english, thank you again!
![zmq](https://cloud.githubusercontent.com/assets/15082338/25273300/d1af05a2-26bd-11e7-8a11-87e4ebf5db3b.png)

**Comment by sorccu** [comment]
No I'm sorry that would be too much work for me to explain everything, the
question is too broad. Please read the ZeroMQ documentation. Other than
that, we may be able to provide paid training if necessary. Or, if you have
a very specific question then it might be possible to answer that.

**Comment by QingyunLiu** [comment]
That's ok, thanks all the same : )
