### ISSUE TITLE
can I use wifi instead of connect to stf server?

### ISSUE THREAD

**Issue by dyxrdyxr** [openstf/stf#583]
When I read and test by myself, devices must connect to stf server by wire for adb connect. can I use wifi instead of connect to stf server? If I can't , can I modify stf code?how?

**Comment by sorccu** [comment]
There are multiple issues about this topic already. Use the --allow-remote option. However, ADB over WIFI is extremely, extremely slow. You'll get really bad performance out of it and there's nothing we can do about it.

**Comment by dyxrdyxr** [comment]
I got it, thanks a lot

**Comment by BlueCute** [comment]
Isn't there a way to install user control on the phone itself and control it via wifi.
L3MON has come up with something similar. Payload is installed and the phone itself is controlled through it. And it works with wifi.
