### ISSUE TITLE
APP Upload

### ISSUE THREAD

**Issue by jonatasteixeira** [openstf/stf#584]
Hello there!

I getting erros during apk instalation by interface..
I'm using the last version of the branch master.

When I try, I get the interface message: `Processing... (100%)`
<img width="493" alt="screen shot 2017-04-25 at 12 12 37 pm" src="https://cloud.githubusercontent.com/assets/124299/25393142/15fe2c42-29b1-11e7-902a-27cbfebf6775.png">

And the follow output:
```
storage:plugins:apk 70330 [*] Unable to read manifest of "b13c02f0-273b-43d3-9cf1-65064faf76f9" Error: end of central directory record signature not found
    at /Users/jaspion/workspace/stf/node_modules/yauzl/index.js:183:14
    at /Users/jaspion/workspace/stf/node_modules/yauzl/index.js:618:5
    at /Users/jaspion/workspace/stf/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
```
I tried with 3 differentes apks and 3 differents devices.
```
$ stf doctor
INF/util:doctor 70494 [*] OS Arch: x64
INF/util:doctor 70494 [*] OS Platform: darwin
INF/util:doctor 70494 [*] OS Platform: 15.4.0
INF/util:doctor 70494 [*] Using Node 7.5.0
INF/util:doctor 70494 [*] Using RethinkDB client 2.3.3
INF/util:doctor 70494 [*] Using ZeroMQ 4.2.2
WRN/util:doctor 70494 [*] Executable was not found
INF/util:doctor 70494 [*] GraphicsMagick 1.3.25
INF/util:doctor 70494 [*] ProtoBuf 3.2.0
ERR/util:doctor 70494 [*] Current ProtoBuf version is not supported, it has to be ~2
INF/util:doctor 70494 [*] Local RethinkDB server 2.3.5
```

**Comment by 0x88l** [comment]
What is the name of apk?

**Comment by sorccu** [comment]
Could be either a stream error in the poor proxy causing lost data (has happened before), or you have an exotic APK. If possible, mail the .apk to me (simo @ name of this github org .io) and I'll take a look when I have time. Or if you can post it here publicly, perhaps others can take a look as well.

**Comment by sorccu** [comment]
Closing since there's no feedback.

**Comment by bebethoi** [comment]
I am running into the same issue. I am unable to upload an APK. It shows  'Uploading...100%' and does nothing.

<img width="695" alt="Screen Shot 2019-09-04 at 4 49 36 PM" src="https://user-images.githubusercontent.com/19418538/64301471-10e1e700-cf34-11e9-9ba2-5bdf6cd850de.png">
