### ISSUE TITLE
can I add a stf server as a slave for the main stf server, both servers were linked with phones?how?

### ISSUE THREAD

**Issue by dyxrdyxr** [openstf/stf#585]
Cause one stf server can't connet too many phones or it may be done for some other reasons, I need more than one stf servers for our project.  If I run 2 stf servers like http://1.1.1.1:7100 and http://2.2.2.2:7100 , both of them are connected with some phones. 1.1.1.1 with phone A and B, 2.2.2.2 with phone C and D.
Question 1:
How can I see all the phones A , B ,C and D on one website (1.1.1.1)
Question 2:
If Question 1 was sovled , how can I operate phone A, D can do the same operation.
Thank you very much.

**Comment by sorccu** [comment]
What you're asking is exactly how STF was meant to work. See our [deployment guide](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md).

Your second question is more complex and several people have asked about it already. You can search past issues if you want to read why it's unlikely to happen for now.
