### ISSUE TITLE
Setting AUTHKEY in rethinkDB using the command mentioned in Deployment document throws error

### ISSUE THREAD

**Issue by praveen133t** [openstf/stf#590]
Setting AUTHKEY in rethinkDB using the command mentioned in Deployment document throws error

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
1. Start rethinkDB 2.3
2. go to localhost:8080
3. Enter command `r.db('rethinkdb').table('cluster_config').get('auth').update({auth_key: '12345'})`
Error message as shown below will be thrown 

```

{
"deleted": 0 ,
"errors": 1 ,
"first_error":  "It's illegal to delete rows from the `rethinkdb.cluster_config` table." ,
"inserted": 0 ,
"replaced": 0 ,
"skipped": 0 ,
"unchanged": 0
}
```

**What is the expected behavior?**

AUTHKEY should be set

Based on [this issue here](https://github.com/GoRethink/gorethink/issues/302) it looks like they updated the feature and it's not longer available
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by mirceanis** [comment]
Hi, I've encountered this error as well.
The docs are a bit outdated on this topic.

I've created a pull request for a doc update [here]
(https://github.com/openstf/stf/pull/526)

**Comment by sorccu** [comment]
Sorry about that, forgot to merge. It's done now.
