### ISSUE TITLE
Cannot Authorized/get token code from Yahoo! Gemini API

### ISSUE THREAD

**Issue by syafi1204** [openstf/stf#593]
I've been trying to pull report data from Yahoo! Gemini using API. I've created an app on YDN to get customer id and customer secret and I put oauth.datorama.com as a callback domain because I want to put the result data to datorama platform.

I've followed the instruction on https://developer.yahoo.com/gemini/ and run the php file. First, the page successfully go to the agreement page to get the data from my account, then when I clicked 'Agree', the result page is always like this
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7AA75693A4B6963C</RequestId>
<HostId>
wrwmF9SWG9jrt8gUhHmtjRHSVwsHcvMS2RZfiKF27zeDfp/PV5jd3nL2uEWH0kqBCuOk9d3fiMo=
</HostId>
</Error>

Can anyone tell me the solution for this problem? Or is there something that I did wrong?

Thanks.

**Comment by vbanthia** [comment]
How is this related to STF?

**Comment by syafi1204** [comment]
Oops. Sorry
