### ISSUE TITLE
swagger v3 incompatibilities 

### ISSUE THREAD

**Issue by kwv** [openstf/stf#594]
**What is the issue or idea you have?**
The STF api [docs](https://github.com/openstf/stf/blob/master/doc/API.md) refer to v2 of swagger-js.  `npm i swagger-js` installs v3 of swagger-js and has breaking changes.  The swagger-js migration [document](https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md) helps, but I ran into an issue that may require changes to STF's Swagger spec (& implementation?).

The STF Swagger Spec does not explicitly set `content-type` for empty POST requests.   Invoking swagger-js omits the `content-type` header for the operations where the device serial number serializes into the path. 

`client.apis.user.remoteConnectUserDeviceBySerial( { 'serial': '1234' })` 
becomes a POST against `/user/devices/1234/remoteConnect` with no body or content-type

On STF api service, the `content-type` is inferred as `application/octet-stream`, which does not conform to the swagger spec, and the request fails.   Can reproduce from swagger-js or from curl commands

swagger-js should (IMHO) follow the spec.  If the global `content-type` is specified in the `consumes` array of the swagger [spec](https://raw.githubusercontent.com/openstf/stf/master/lib/units/api/swagger/api_v1_generated.json) then swagger should use it [swagger-js issue 1022](https://github.com/swagger-api/swagger-js/issues/1022).  

That said the STF Swagger Spec (/implementation?) should be more precise and allow empty POST bodies where appropriate.  This would conform to RFC and fix the issue.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

n/a

**Please provide the steps to reproduce the issue.**
Using curl, reserve the device, and send remoteConnect with no content-type specified
```
curl -X POST --header "Content-Type: application/json" --data '{"serial":"SERIAL"}' -H "Authorization: Bearer BEARER_TOKEN " http://ENDPOINT:7100/api/v1/user/devices

{"success":true,"description":"Device successfully added"}

curl -X POST  -H "Authorization: Bearer BEARER_TOKEN " http://ENDPOINT:7100/api/v1/user/devices/SERIAL/remoteConnect

{"message":"Validation errors","errors":[{"code":"INVALID_CONTENT_TYPE","message":"Invalid Content-Type (application/octet-stream).  These are supported: application/json","path":[]}]}

```

It works if the content-type header is specified (erroneously as there is no content):
```
curl -X POST --header "Content-Type: application/json" -H "Authorization: Bearer BEARER_TOKEN" http: //ENDPOINT:7100/api/v1/user/devices/SERIAL/remoteConnect

{"success":true,"remoteConnectUrl":"ENDPOINT:7461"}
```

Swagger v3 does not expose the ability to explicitly set `content-type` on a per-request basis. 

**What is the expected behavior?**

Per [S.O. on RFC-7231](http://stackoverflow.com/a/28652339) when there is no content-type provided `application/octet-stream` may be inferred.    The STF Swagger spec should be updated to allow empty POST / default content-type

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

n/a

**Please run `stf doctor` and paste the output here.**

assuming unrelated failures:
```
CI:~ ciuser$ stf doctor
INF/util:doctor 21707 [*] OS Arch: x64
INF/util:doctor 21707 [*] OS Platform: darwin
INF/util:doctor 21707 [*] OS Platform: 16.5.0
INF/util:doctor 21707 [*] Using Node 6.10.2
INF/util:doctor 21707 [*] Using RethinkDB client 2.3.3
INF/util:doctor 21707 [*] Using ZeroMQ 4.2.2
INF/util:doctor 21707 [*] GraphicsMagick 1.3.25
INF/util:doctor 21707 [*] Local RethinkDB server 2.3.5
INF/util:doctor 21707 [*] Local ADB 1.0.39
Installed as /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb

/Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.0.39
Installed as /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb

    at new SemVer (/Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/lib/util/doctor.js:143:7
    at /Users/ciuser/.nvm/versions/node/v6.10.2/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by sorccu** [comment]
Thank you, that is an extremely good bug report. I think @vbanthia would be best equipped to handle this if he has time.

**Comment by vbanthia** [comment]
Will fix this next weekend. Thanks for reporting.

**Comment by vbanthia** [comment]
*Copying comment from [here](https://github.com/openstf/stf/pull/601#issuecomment-305354613), so that other users don't get confused.*

> I will still suggest to use swagger-client@2.x.x instead of 3.x.x since they are making lots of breaking changes in their own implementation not just because of OpenAPI specs. Also, I do not think we will be supporting OpenAPI v3 anytime soon since v2 is working totally fine as for now and we don't have any plan to extend OpenSTF API anytime soon.

**Comment by ricardo-valtierra** [comment]
Hi, I've already installed the swagger-client@3.1.1 but I want to change to the older version. I'm pretty new at this, how can i do it? Thanks a lot in advance

**Comment by vbanthia** [comment]
npm install swagger-client@2.1.31

If you are not comfortable with NodeJS, you can also try shell script example, https://github.com/openstf/stf/blob/master/doc/API.md#using-shell
