### ISSUE TITLE
Running Multiple Providers role with single App role

### ISSUE THREAD

**Issue by saurabhmistry18** [openstf/stf#596]
I am successfully running stf local and stf local --public-ip commands to view and control my android devices using a raspberry pi. What I plan to do is have such multiple Raspberry Pis connected to a central server such that now I can access all my devices from anywhere and not just my local IP. I have checked the Deployment.md files. However can I use multiple Providers and still connect to STF such that post login I can view all the *x* number of devices connected over *n* number of Raspberry Pis. What I intend to achieve is have multiple such Raspberry Pis sitting at different locations which connect to a central server for access from anywhere. Can this really be achieved using the STF Deployment strategy?

**Comment by sorccu** [comment]
That is exactly what it does.

**Comment by saurabhmistry18** [comment]
This would work where I have all my android devices connected to a single Raspberry Pi. What if I have a single android device connected to each Raspberry Pi and now I want to access them centrally? What all services should I be deploying on the Raspberry Pi and what should I be running on the server?

**Comment by sorccu** [comment]
I meant that the deployment is explicitly designed so that you can even
have 1 device per machine if you like.

The deployment guide tells you what you need and where.
