### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lishuai0214** [openstf/stf#597]
I have experienced this error many times, it caused the websocket to exit, what's reason for this?

INF/util:datautil 1 [*] Device database does not have an entry for "123456789ABCD" (model "R7t"/"R7t"). This is not an error, it only means that we don't have data for it yet.
INF/util:datautil 1 [*] Device database does not have an entry for "123456789ABCD" (model "R7t"/"R7t"). This is not an error, it only means that we don't have data for it yet.
INF/util:datautil 1 [*] Device database does not have an entry for "123456789ABCD" (model "R7t"/"R7t"). This is not an error, it only means that we don't have data for it yet.
INF/util:datautil 1 [*] Device database does not have an entry for "123456789ABCD" (model "R7t"/"R7t"). This is not an error, it only means that we don't have data for it yet.
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Maximum call stack size exceeded
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at Buffer.slice (buffer.js:811:10)
    at fromString (buffer.js:204:21)
    at Function.Buffer.from (buffer.js:99:12)
    at new Buffer (buffer.js:80:17)
    at Sender.frameAndSend (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:166:14)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:126:12
    at Sender.applyExtensions (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:287:5)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:120:10
    at Sender.flush (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:268:3)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:270:10
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:127:7
    at Sender.applyExtensions (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:287:5)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:120:10
    at Sender.flush (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:268:3)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:270:10
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:127:7
    at Sender.applyExtensions (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:287:5)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:120:10
    at Sender.flush (/app/node_modules/engine.io/node_modules/ws/lib/Sender.js:268:3)
    at /app/node_modules/engine.io/node_modules/ws/lib/Sender.js:270:10

**Comment by sorccu** [comment]
That's not an error, it's there purely for information purposes. I've now removed the message because everyone thinks it's an error for some reason.

Unfortunately that stack trace is not very useful. Please describe what exactly you are doing when that error happens.

**Comment by lishuai0214** [comment]
when stf run several days or several weeks, this error occurs, I know it is there for information purposes, but it does lead the websocket exited many times, I guess there is a buffer to small, I don't know which one

**Comment by lishuai0214** [comment]
@sorccuI, I finally found this is a bug in older versions of websocket, It's just a coincidence when it appear together with datautil's log, is there any plan to upgrade websocket to a newer version? This is the origin bug of websocket, https://github.com/websockets/ws/issues/758

**Comment by sorccu** [comment]
Nice. Have you tried upgrading the package in your own installation yet?

**Comment by lishuai0214** [comment]
Yeah, I had upgrade socket.io to 2.0.2 which depends on engine.io@3.1.0, and engine.io@3.1.0 depends on ws@2.3.1, It worked fine for several days, but I'm not sure if there will be problems a few weeks later.

**Comment by sorccu** [comment]
Updated it master.
