### ISSUE TITLE
Can't connect to devices

### ISSUE THREAD

**Issue by BGolis** [openstf/stf#598]
Hi,

I am trying to set up an STF-Server using your Deployment-doc. I can log in, but there are no devices shown. Doesn't matter which device I try to connect. In addition after some time the screen on the stf-dashboard shows "Disconnected"

stf local works just fine.

Following I have the stf-providers log.

> INF/device:plugins:touch 25 [03157df3694e4d1f] Touch origin is top left
INF/device:plugins:touch 25 [03157df3694e4d1f] Requesting touch consumer to start
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Reading minitouch banner
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Type B touch device sec_touchscreen (4095x4095 with 10 contacts) detected on /dev/input/event1 (score 2100)"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "binding socket: Address already in use"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Unable to start server on minitouch"
WRN/device:plugins:touch 25 [03157df3694e4d1f] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Reading minitouch banner
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Type B touch device sec_touchscreen (4095x4095 with 10 contacts) detected on /dev/input/event1 (score 2100)"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "binding socket: Address already in use"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Unable to start server on minitouch"
WRN/device:plugins:touch 25 [03157df3694e4d1f] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/provider 1 [*] Providing 0 of 1 device(s); waiting for INF/device:plugins:touch 25 [03157df3694e4d1f] Touch origin is top left
INF/device:plugins:touch 25 [03157df3694e4d1f] Requesting touch consumer to start
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Reading minitouch banner
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Type B touch device sec_touchscreen (4095x4095 with 10 contacts) detected on /dev/input/event1 (score 2100)"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "binding socket: Address already in use"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Unable to start server on minitouch"
WRN/device:plugins:touch 25 [03157df3694e4d1f] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Reading minitouch banner
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Type B touch device sec_touchscreen (4095x4095 with 10 contacts) detected on /dev/input/event1 (score 2100)"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "binding socket: Address already in use"
INF/device:plugins:touch 25 [03157df3694e4d1f] minitouch says: "Unable to start server on minitouch"
WRN/device:plugins:touch 25 [03157df3694e4d1f] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Launching screen service
INF/device:plugins:touch 25 [03157df3694e4d1f] Connecting to minitouch service
INF/provider 1 [*] Providing 0 of 1 device(s); waiting for "03157df3694e4d1f"
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Ending minitouch I/O as a last resort
FTL/device 25 [03157df3694e4d1f] Setup had an error TimeoutError: operation timed out
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
FTL/util:lifecycle 25 [03157df3694e4d1f] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "03157df3694e4d1f"
ERR/provider 1 [*] Device worker "03157df3694e4d1f" died with code 1
INF/provider 1 [*] Restarting device worker "03157df3694e4d1f"
INF/device:support:push 37 [03157df3694e4d1f] Sending output to "tcp://172.17.0.1:7270"
INF/device 37 [03157df3694e4d1f] Preparing device
INF/device:support:sub 37 [03157df3694e4d1f] Receiving input from "tcp://172.17.0.1:7250"
INF/device:support:sub 37 [03157df3694e4d1f] Subscribing to permanent channel "*ALL"
INF/provider 1 [*] Providing 0 of 1 device(s); waiting for "03157df3694e4d1f"
"03157df3694e4d1f"
INF/device:plugins:touch 25 [03157df3694e4d1f] Disconnecting from minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Stopping minitouch service
INF/device:plugins:touch 25 [03157df3694e4d1f] Ending minitouch I/O as a last resort
FTL/device 25 [03157df3694e4d1f] Setup had an error TimeoutError: operation timed out
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
FTL/util:lifecycle 25 [03157df3694e4d1f] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "03157df3694e4d1f"
ERR/provider 1 [*] Device worker "03157df3694e4d1f" died with code 1
INF/provider 1 [*] Restarting device worker "03157df3694e4d1f"
INF/device:support:push 37 [03157df3694e4d1f] Sending output to "tcp://172.17.0.1:7270"
INF/device 37 [03157df3694e4d1f] Preparing device
INF/device:support:sub 37 [03157df3694e4d1f] Receiving input from "tcp://172.17.0.1:7250"
INF/device:support:sub 37 [03157df3694e4d1f] Subscribing to permanent channel "*ALL"
INF/provider 1 [*] Providing 0 of 1 device(s); waiting for "03157df3694e4d1f"

What might be the problem here?

**Comment by sorccu** [comment]
Well, since there's this: `minitouch says: "binding socket: Address already in use"`, I'd say you may have more than one copy of STF running at the same time.

Also, please don't remove the issue template. You should have said which device you're having this issue with, but didn't because you removed the template. We need that information or we can't/won't do anything.

**Comment by BGolis** [comment]
Ok, sorry for removing the template. The devices in question are a Samsung A5, Samsung S6 and Sony Z1c.

I realized I've been running two instances of the provider.

Now I still cannot see my devices in the dashboard, though the provider says it is there:

> INF/provider 1 [*] Subscribing to permanent channel "IZHDwa0WR36+wRjTY+xEOw=="
INF/provider 1 [*] Sending output to "tcp://172.17.0.1:7270"
INF/provider 1 [*] Receiving input from "tcp://172.17.0.1:7250"
INF/provider 1 [*] Tracking devices
INF/provider 1 [*] Found device "03157df3694e4d1f" (offline)
INF/provider 1 [*] Registered device "03157df3694e4d1f"
INF/provider 1 [*] Providing all 0 of 1 device(s); ignoring "03157df3694e4d1f"
INF/provider 1 [*] Lost device "03157df3694e4d1f" (offline)
INF/provider 1 [*] Found device "03157df3694e4d1f" (offline)
INF/provider 1 [*] Registered device "03157df3694e4d1f"
INF/provider 1 [*] Providing all 0 of 1 device(s); ignoring "03157df3694e4d1f"
INF/provider 1 [*] Lost device "03157df3694e4d1f" (offline)
INF/provider 1 [*] Found device "03157df3694e4d1f" (offline)
INF/provider 1 [*] Registered device "03157df3694e4d1f"
INF/provider 1 [*] Device "03157df3694e4d1f" is now "device" (was "offline")
INF/device:support:push 14 [03157df3694e4d1f] Sending output to "tcp://172.17.0.1:7270"
INF/device 14 [03157df3694e4d1f] Preparing device
INF/device:support:sub 14 [03157df3694e4d1f] Receiving input from "tcp://172.17.0.1:7250"
INF/device:support:sub 14 [03157df3694e4d1f] Subscribing to permanent channel "*ALL"
INF/device:support:properties 14 [03157df3694e4d1f] Loading properties
INF/device:support:sdk 14 [03157df3694e4d1f] Supports SDK 23
INF/device:support:abi 14 [03157df3694e4d1f] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:minicap 14 [03157df3694e4d1f] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 14 [03157df3694e4d1f] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-23/minicap.so" as "/data/local/tmp/minicap.so"
INF/device:resources:service 14 [03157df3694e4d1f] Checking whether we need to install STFService
INF/device:resources:service 14 [03157df3694e4d1f] Running version check
INF/device:resources:service 14 [03157df3694e4d1f] STFService up to date
INF/device:plugins:service 14 [03157df3694e4d1f] Launching agent
INF/device:plugins:service 14 [03157df3694e4d1f] Agent says: "Listening on @stfagent"
INF/device:plugins:service 14 [03157df3694e4d1f] Launching service
INF/device:plugins:service 14 [03157df3694e4d1f] Agent says: "InputClient started"

The reapers logs say:

> stf@stf-1:~$ sudo docker logs stf-reaper
INF/reaper 1 [dev] Subscribing to permanent channel "*ALL"
INF/reaper 1 [dev] Reaping devices with no heartbeat
INF/db 1 [dev] Connecting to 172.17.0.6:28015
INF/reaper 1 [dev] Receiving input from "tcp://172.17.0.1:7150"
INF/reaper 1 [dev] Sending output to "tcp://172.17.0.1:7270"
INF/reaper 1 [dev] Device "03157df3694e4d1f" is present
INF/reaper 1 [dev] Reaping device "03157df3694e4d1f" due to heartbeat timeout
INF/reaper 1 [dev] Device "03157df3694e4d1f" is present
INF/reaper 1 [dev] Device "03157df3694e4d1f" is present

**Comment by sorccu** [comment]
Logs look OK to me. Closing since this issue is fairly old.
