### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by lucker6666** [openstf/stf#6]
ForbiddenError: invalid csrf token
    at verifytoken (/app/node_modules/csurf/index.js:269:11)
    at csrf (/app/node_modules/csurf/index.js:97:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/app/node_modules/body-parser/lib/types/json.js:107:37)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at /app/lib/units/app/middleware/auth.js:36:13
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:489:31)

met this problems when i test it in my environment. adb works and the whole log was attached.

root@ubuntu:/app# adb devices
List of devices attached
00445e524f8c5907	device

INF/device:support:sub 545 [00445e524f8c5907] Subscribing to permanent channel "*ALL"
INF/device:support:properties 545 [00445e524f8c5907] Loading properties
INF/device:support:abi 545 [00445e524f8c5907] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 545 [00445e524f8c5907] Checking whether we need to install STFService
INF/device:resources:service 545 [00445e524f8c5907] Running version check
INF/device:resources:service 545 [00445e524f8c5907] STFService up to date
INF/device:plugins:service 545 [00445e524f8c5907] Launching agent
INF/device:plugins:service 545 [00445e524f8c5907] Launching service
INF/device:plugins:service 545 [00445e524f8c5907] Agent says: "Listening on port 1090"
INF/device:plugins:service 545 [00445e524f8c5907] Agent says: "InputClient started"
INF/device:plugins:display 545 [00445e524f8c5907] Reading display info
INF/device:plugins:phone 545 [00445e524f8c5907] Fetching phone info
INF/device:plugins:identity 545 [00445e524f8c5907] Solving identity
INF/device:plugins:solo 545 [00445e524f8c5907] Subscribing to permanent channel "S+KScTlq18iysOfuoUm6iN5WyIc="
INF/device:plugins:screen:stream 545 [00445e524f8c5907] Starting WebSocket server on port 7400
INF/device:plugins:browser 545 [00445e524f8c5907] Loading browser list
INF/device:plugins:browser 545 [00445e524f8c5907] Updating browser list
WRN/device:plugins:data 545 [00445e524f8c5907] Unable to find device data { serial: '00445e524f8c5907',
  platform: 'Android',
  manufacturer: 'LGE',
  operator: null,
  model: 'Nexus 4',
  version: '5.0',
  abi: 'armeabi-v7a',
  sdk: '21',
  product: 'occam',
  display:
   { id: 0,
     width: 768,
     height: 1280,
     xdpi: 319.7900085449219,
     ydpi: 318.7449951171875,
     fps: 60,
     density: 2,
     rotation: 0,
     secure: true,
     size: 4.679082154320592,
     url: 'ws://localhost:7400' },
  phone: { imei: '353918051433593', network: 'UNKNOWN' } }
INF/device:plugins:touch 545 [00445e524f8c5907] Touch origin is top left
INF/device:plugins:touch 545 [00445e524f8c5907] Requesting touch consumer to start
INF/device:plugins:touch 545 [00445e524f8c5907] Launching screen service
INF/device:plugins:touch 545 [00445e524f8c5907] Connecting to minitouch service
INF/device:plugins:touch 545 [00445e524f8c5907] minitouch says: "Type B touch device touch_dev (1535x2559 with 10 contacts) detected on /dev/input/event2 (score 1100)"
INF/device:plugins:touch 545 [00445e524f8c5907] Reading minitouch banner
INF/device:plugins:touch 545 [00445e524f8c5907] minitouch says: "Connection established"
INF/device:plugins:forward 545 [00445e524f8c5907] Launching reverse port forwarding service
INF/device:plugins:forward 545 [00445e524f8c5907] Connecting to reverse port forwarding service
INF/device:plugins:connect 545 [00445e524f8c5907] Listening on port 7401
INF/device 545 [00445e524f8c5907] Fully operational
INF/provider 487 [*] Providing all 1 device(s)

**Comment by sorccu** [comment]
Hi,

Could you show me the command you used to launch STF (e.g. `stf local`)? Looks like the log cuts off a bit. I would also like to know which OS and browser you're using.

The CSRF token is sent over inside a cookie. Is it possible that you may be blocking the cookie?

**Comment by lucker6666** [comment]
Hi Sorccu,

i used the docker images openstf/stf to run as below,

docker run -t -i --privileged -v /dev/bus/usb:/dev/bus/usb -u root -p 7100:7100 openstf/stf /bin/bash

then i installed the rethinkdb/adb then run rethinkdb/stf local.  after that using firefox to open localhost:7100.

then i can see a disconnecting issue but i am not sure why?

Liang

**Comment by lucker6666** [comment]
Hi Sorccu,

it works well on a Mac environemnt (no docker), thanks so much for open it. 

Liang

**Comment by gupiao** [comment]
met same problem when I login to stf page
