### ISSUE TITLE
triproxy -- pub and sub

### ISSUE THREAD

**Issue by daring123** [openstf/stf#600]
I read the STF source Code.
In triproxy/index.js, I know it publish  message  to all  subscribers. But, how the subscriber get the message owned by it .
For example, when I tap device A on the STF website,  triproxy  publish 'tap' to all devices. Device A and device B both subscribe 'tap' infomation. however, device A handle it , device not handle it . how STF do this?
Thanks.I don't know if you can understand me. My English is not very well.

**Comment by sorccu** [comment]
Publishers and subscribers only push/sub to certain channels. There's a unique channel for each device, each group (set of devices controlled by a user at once) and all devices. When you tap, the message is sent to a specific device's channel. Other device workers never see the message.

**Comment by daring123** [comment]
Ok.
New question.I can understand the unique channel. I read ZeroMQ. The Pub/Sub example is as follow:
Publisher  pubber.js
`// pubber.js
var zmq = require('zeromq')
  , sock = zmq.socket('pub');

sock.bindSync('tcp://127.0.0.1:3000');
console.log('Publisher bound to port 3000');

setInterval(function(){
  console.log('sending a multipart message envelope');
  sock.send(['kitty cats', 'meow!']);
}, 500);`
Subscriber: subber.js
`
// subber.js
var zmq = require('zeromq')
  , sock = zmq.socket('sub');

sock.connect('tcp://127.0.0.1:3000');
sock.subscribe('kitty cats');
console.log('Subscriber connected to port 3000');

sock.on('message', function(topic, message) {
  console.log('received a message related to:', topic, 'containing message:', message);
});
`
In the  subber.js,  `sock.subscribe('kitty cats');` the subscriber  subscribes the channel named kitty cats. However,  in  /stf/lib/units/device/support/sub.js,  which I think every device has it own sub socket through this file,does not has the similar code .The publisher send data through the special channel , however,the subscriber doesn't subscribe the special channel. Is something  I missed?

**Comment by vbanthia** [comment]
Device subscribes to its own channel here, https://github.com/openstf/stf/blob/master/lib/units/device/plugins/solo.js#L28

Just look for `sub.subscribe` under device directory, you will know all the channels which device is subscribing.

**Comment by daring123** [comment]
I known. Thanks

**Comment by daring123** [comment]
One more question.You start two 'triproxys' through the command

```
INF/util:procutil 40934 [*] Forking "/Users/sheranjun/Code/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 40934 [*] Forking "/Users/sheranjun/Code/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
```

When I tap device A on the STF website, the flow is as follow:
![image](https://cloud.githubusercontent.com/assets/5986074/26661140/8774d1f4-46ae-11e7-8c0c-9ac38829a338.png)

Here is my question. Why STF start 'app001' and 'dev 001' two 'triproxys' ? . If just start one 'triproxy', what's wrong with it?

**Comment by sorccu** [comment]
App side triproxy takes messages from the web UI and passes them to the devices (through processors and the device side triproxy). The device side triproxy takes messages from the devices and passes them to the app side (via processors and app side triproxy).

**Comment by daring123** [comment]
Ok.Thanks very much.
