### ISSUE TITLE
Garbled stf local Chinsese output

### ISSUE THREAD

**Issue by woliuzhilan** [openstf/stf#606]
Hi, I have some problems with Jenkins job garbled output.  
Set Jenkins encoding uft-8 ,before installing stf plugin,the encoding of output is normal.  
After installing stf plugin, It has trouble with the console.

before installing stf plugin

![1496643065 1](https://cloud.githubusercontent.com/assets/29189610/26772662/733081c2-49f9-11e7-957e-0c0769fb0418.jpg)

After installing stf plugin

![1496643499](https://cloud.githubusercontent.com/assets/29189610/26772780/2ce52294-49fa-11e7-84f6-0f9ee4768b98.jpg)

![Uploading 1496643499.jpg…]()

**Comment by sorccu** [comment]
Please ask the plugin author. I would try using UTF-8 as your character set, though.
