### ISSUE TITLE
Running Monkey interrupts

### ISSUE THREAD

**Issue by woliuzhilan** [openstf/stf#607]
Hi,  an other issue.  
I use STF to execute monkey, set 10 hours, and collect logs at the same time. But 2.5 hours later, the execution was interrupted. What's the reason, please?

**Comment by sorccu** [comment]
Impossible to tell, you've given almost no details. It could be a timeout, though. Try setting a longer `--group-timeout`.

**Comment by woliuzhilan** [comment]
I visit the devices by STF, at Shell, enter the Monkey command: "ADB shell monkey -p com.huajiao.camera -s -v -v -v 1000 --throttle 500 --pct-touch 10 --pct-motion 10 --pct-trackball 10 --pct-nav 10 --pct-majornav 10 --pct-syskeys 1 --pct-appswitch 1 --pct-anyevent 1 --ignore-crashes --ignore-security-exceptions --kill-process-after-error --monitor-native-crashes 100000"

At the same time, locally connect the device, enter under the CMD: "ADB -s 10.16.42.11:11193 logcat -v time >D:/toushijing.txt" to collect the log
Two hours later, the execution was interrupted

**Comment by sorccu** [comment]
Oh. The web UI isn't really meant to be used for several hours, I don't think that works well. No idea though, I've never tried doing that. I would use the `adb connect` command instead, and then run monkey over that. You should also increase `--group-timeout` to be longer than 10 hours.

**Comment by woliuzhilan** [comment]
we've specified group-timeout when start stf provider using docker container.
we do:


/usr/bin/docker run --rm \
  --name %p-%i \
  --net host   \
  openstf/stf  \
  stf provider \
    --name "%H/%i"                              \
    --connect-sub tcp://server:7250  \
    --connect-push tcp://server:7270 \
    --storage-url http://server      \
    --public-ip server                 \
    --min-port=11000 \
    --max-port=12000 \
    --heartbeat-interval 20000 \
    --group-timeout 36000
    --screen-ws-url-pattern "ws://server/d/floor4/<%= serial %>/<%= publicPort %>/"



Is this correct operation?

**Comment by woliuzhilan** [comment]
Hi,We have set the correct parameters

sysctl -w net.ipv4.tcp_keepalive_intvl=75
sysctl -w net.ipv4.tcp_keepalive_probes=9
sysctl -w net.ipv4.tcp_keepalive_time=75000
sysctl -p

The problem has been solved

Thank you for your help

**Comment by sorccu** [comment]
Thanks for following up with a solution! I'm not sure if it would have helped, but there's also `ZMQ_TCP_KEEPALIVE` and `ZMQ_TCP_KEEPALIVE_IDLE` that you could have tried. See https://github.com/openstf/stf/blob/461ec81c9ed3a149bd31906b1fc4546e95fee592/lib/util/zmqutil.js
