### ISSUE TITLE
How to use the Automation feature available in the STF GUI ?

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#610]
Please, do you have some samples illustrating the using of this feature ?

**Comment by sorccu** [comment]
Check some of the other repositories for examples. Maybe stf-appium-example.

**Comment by denis99999** [comment]
I talk about the 'Automation' tab in the GUI ?

**Comment by sorccu** [comment]
No that's different.

**Comment by denis99999** [comment]
The appium example uses the RESTful API to connect to the device, and then runs the test, I experimented that yet and it is great, but I don't see where the 'Automation' window of the device under control is used in this use case, this is why I asked the question. In this 'Automation' window, there is the 'Store account' box with "Sign-in" button etc. but I don't know what it means ?

**Comment by sorccu** [comment]
It's a completely different thing. Not related.

**Comment by denis99999** [comment]
I agree with you, so what means 'Automation' window and how to use it ?

**Comment by sorccu** [comment]
It's mostly useless right now.

**Comment by denis99999** [comment]
Thanks.
