### ISSUE TITLE
Using adb while running automation

### ISSUE THREAD

**Issue by ekftjq** [openstf/stf#618]
Hello,

I'm using openSTF to run automated tests for my android app.
I was wondering if it is possible to have adb commands within my automation code to run them remotely in STF.
For example, I want to run adb logcat for every test failures.
I can connect adb remotely, but I was wondering if I can run adb remotely within the automation code.

Thanks!

**Comment by mirceanis** [comment]
It's not really a job for STF, but you can get logcat while testing on
devices connected through STF.

While connected through STF, devices behave almost as though they are
attached to your PC.

Getting logcat during tests is a job for your testing framework.
I get the most out of instrumentation tests using the [Spoon runner](
http://square.github.io/spoon/)

I hope this answers your query

**Comment by thinkhy** [comment]
You can extend device component. I've implement a similar function to send all the logcat entries to Graylog based on ElasticSearch.

**Comment by sorccu** [comment]
Good answer by @mirceanis! Closing.
