### ISSUE TITLE
Can we generate one url for one device so that it will show only single device not all devices?

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#620]

**Comment by sorccu** [comment]
No not right now. Plus even if you could, users could still access the
device list by changing the URL?

**Comment by suvansh-dev** [comment]
**Plus even if you could** means there is a possibility?

**Comment by suvansh-dev** [comment]
You are right changing the url will show whole of the stuff.

**Comment by gunta** [comment]
If you want to implement this properly, it would require to implement first an user-specific permissions system.

**Comment by suvansh-dev** [comment]
ok thanks but what after that?

**Comment by gunta** [comment]
After having a permissions system, assigning which user can see which device should be doable from the database at least. This will take effort and we don't have plans to do this right now, but contributions are welcome.

**Comment by suvansh-dev** [comment]
ok sir, i will try to do this, if you found anything else that can help me to achieve this then please comment over here. Thanks!

**Comment by suvansh-dev** [comment]
One thing more what kind of user-specific permission system i should make, any suggestions please?
