### ISSUE TITLE
openstf disconnects when disconnecting network from device

### ISSUE THREAD

**Issue by ekftjq** [openstf/stf#621]
Hi,

I'm running some Android automation with Appium remotely using openstf.
One problem I am having is, when I try to disconnect all network (eg, go to airplane mode),
I realized that openstf will also disconnect.

Does anyone know a way I can get my device to have no network, but have openstf connected?

Thanks.

**Comment by sorccu** [comment]
STF works fine in airplane mode. Are you perhaps using `adb tcpip`?

**Comment by ekftjq** [comment]
I am able to use STF in airplane mode.
But when I go from Non-airplane mode -> Airplane mode, STF connection also disconnects.
If it is not a STF issue, maybe it's a Appium issue.
I'm using Appium Driver to disconnect from all networks, and maybe it's happens because of how Appium executes this.

Has anyone tried using Appium and disconnecting from all networks?

**Comment by viktors89** [comment]
Are you running the Appium tests on the same machine that hosts STF? I had STF online while running some Appium tests of my own (not related), and at some points STF decided to disconnect as well, I think there might be some kind of conflict between both servers when they're up.

**Comment by sorccu** [comment]
Closing this as no evidence or examples have been provided.
