### ISSUE TITLE
How to uninstall openstf from ubuntu?

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#625]
Hi,
Is there any command like:
    
     sudo apt purge openstf

to uninstall openstf from Ubuntu 16.04 or how can i uninstall openstf from ubuntu completely?

**Comment by sorccu** [comment]
That depends entirely on how you installed it. Therefore it's your
responsibility to know how to remove it.

**Comment by suvansh-dev** [comment]
I have done it by using the following command: 

               curl -s https://gist.githubusercontent.com/MiteshShah/62cd0923b9068a927dae/raw/STF | sudo bash
Nothing else i have used to install it.

**Comment by sorccu** [comment]
You can read the script and do the opposite of what it does. You can also
ask the person who provided that script, however they'll likely say the
same thing.

I would recommend using docker containers for an easily removable, isolated
installation.

**Comment by suvansh-dev** [comment]
Here is the script:

#!/bin/bash

# Error handling
function OwnError()
{
	echo -e "[ `date` ] $(tput setaf 1)$@$(tput sgr0)"
	exit $2
}

# Repository for rethinkdb
echo "Setup Repository For Rethinkdb, Please Wait..."
source /etc/lsb-release \
&& echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" > /etc/apt/sources.list.d/rethinkdb.list \
&& wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add - \
|| OwnError "Unable to setup rethinkdb repository, exit status = " $?

# Install wget and curl
echo "Executing: apt-get update, Please wait..."
apt-get update \
|| OwnError "Unable to execute apt-get update command, exit status = " $?

echo "Installing required packages, Please wait..."
apt-get -y install wget curl git rethinkdb android-tools-adb python autoconf automake libtool build-essential ninja-build libzmq3-dev libprotobuf-dev git graphicsmagick \
|| OwnError "Unable to install required packages, exit status = " $?

echo "Donwloading Node.js, Please Wait..."
cd /tmp && \
wget -c https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz \
|| OwnError "Unable to download Node.js, exit status = " $?

echo "Installing Node.js, Please Wait..."
tar xzf node-v*.tar.gz && \
rm node-v*.tar.gz && \
cd node-v* && \
export CXX="g++ -Wno-unused-local-typedefs" && \
./configure --ninja && \
make && \
make install && \
rm -rf /tmp/node-v* && \
cd /tmp && \
/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install \
|| OwnError "Unable to install Node.js, exit status = " $?

echo "Installing Bower, Please Wait..."
npm install -g bower \
|| OwnError "Unable to install Bower, exit status = " $?

echo "Installing ZeroMQ, Please wait..."
cd /opt
wget http://download.zeromq.org/zeromq-4.1.2.tar.gz \
&& tar -zxvf zeromq-4.1.2.tar.gz \
&& cd zeromq-4.1.2 \
&& ./configure --without-libsodium \
&& make \
&& make install \
|| OwnError "Unable to install ZeroMQ, exit status = " $?

echo "Setup Protocol Buffers, Please wait..."
cd /opt \
&& git clone https://github.com/google/protobuf.git \
&& cd protobuf \
&& ./autogen.sh \
&& ./configure \
&& make \
&& make install \
|| OwnError "Unable to Setup Protocol Buffers, exit status = " $?

echo "Installing STF, Please wait..."
npm install -g stf \
|| OwnError "Unable to Installing STF, exit status = " $?
view raw

**Comment by sorccu** [comment]
Read the script and do the opposite of what it does. It's you who must do it, I will not help you because it's a waste of my time.

**Comment by suvansh-dev** [comment]
Done :)
