### ISSUE TITLE
stf provider as slave machine, cannot provide phones

### ISSUE THREAD

**Issue by dyxrdyxr** [openstf/stf#627]
I have two server, both mac mini. server A run stf local --public-ip x.x.x.x --allow-remote 
server B has 2 phones linked to it, and run 
stf provider --connect-sub tcp:// x.x.x.x:7250  --connect-push tcp:// x.x.x.x:7270  --storage-url http:// x.x.x.x:7100  --public-ip  x.x.x.x --min-port=35000  --max-port=40000  --heartbeat-interval 20000
but B result is：
INF/provider 10745 [*] Subscribing to permanent channel "qnSu3UvKTmeZsyf9XXld5g=="
INF/provider 10745 [*] Sending output to "tcp://x.x.x.x:7270"
INF/provider 10745 [*] Receiving input from "tcp://x.x.x.x:7250"
INF/provider 10745 [*] Tracking devices
INF/provider 10748 [*] Found device "ENU7N15B12014604" (device)
INF/provider 10748 [*] Found device "69edb8c0" (device)
INF/provider 10748 [*] Providing all 0 of 2 device(s); ignoring "ENU7N15B12014604", "69edb8c0"

why？

**Comment by sorccu** [comment]
Pretty sure it's unable to connect to your other server. After devices are found, a request is made to the other server which then needs to reply. If there's no response, it might look like that.

**Comment by dyxrdyxr** [comment]
so do you mean - tcp:// x.x.x.x:7250 or  tcp:// x.x.x.x:7270 dosn't reply .
should I appoint the sub/push port for server B

**Comment by sorccu** [comment]
It can be that the address is wrong, or that there's a firewall on the other machine. Unfortunately I have no time to help you with that, so please try to figure it out and post your solution once you find it.

**Comment by ysxAAA** [comment]
did u fix it ? can u tell the solution?

**Comment by vip68** [comment]
can you tell me how to solution?help!

**Comment by thinkhy** [comment]
@vip68 @ysxAAA Refer to #989 , hope this would be helpful.

**Comment by jon2kx** [comment]
> @vip68 @ysxAAA Refer to #989 , hope this would be helpful.

This is not the same issue; the device IDs are unique.

**Comment by rounakcodes** [comment]
> Pretty sure it's unable to connect to your other server. After devices are found, a request is made to the other server which then needs to reply. If there's no response, it might look like that.

This helped. 
I used `netstat -atnp` on the triproxy machines.
I found that it was not listening on the ports specified in the docker compose file. 
I added `network_mode: host` and it worked.
