### ISSUE TITLE
Can't launch STF / Semver / "Identifier 'options' has already been declared"

### ISSUE THREAD

**Issue by jguedon** [openstf/stf#630]
Hi,

When I'm trying to run **stf local**, the error is  "Child process had an error ExitError : Exit code "1" at ChildProcess.<anonymous>" with procutil.js.

When I'm trying **stf doctor** I've got an invalid version from semver of "Invalid Version : 2.3.5~0 jessie"

Does someone have the same error ? How can I fix it ? Should I remove everything and start all over again ?

**Comment by sorccu** [comment]
Use the master branch.

**Comment by jguedon** [comment]
the master branch of stf ?

**Comment by sorccu** [comment]
Yes..
