### ISSUE TITLE
STF disconnecting when starting adb daemon

### ISSUE THREAD

**Issue by ekftjq** [openstf/stf#631]
Hi,

I'm trying to install an apk to my device connected to STF.
However, when I have STF running and do "adb install -r <filename>",
I get disconnected from STF when I get "* daemon started successfully *"

My guess is that by trying to install a file to device, I'm killing the adb server connection, which is also killing my STF connection.
Is there anyway to solve this?

**Comment by sorccu** [comment]
Does anything else work? Like `adb shell` for example?

Usually that problem occurs when you are connecting from an older or newer ADB client to an ADB server that's a different version. However, if your ADB server is running locally, that shouldn't really happen.

I think you'll need to give more details. For example:

* Where is the adb server running?
* Does the adb server run inside a docker container?
* Where is `adb install -r` running?
* How did you install ADB?
* How did you connect the device to your ADB?

**Comment by sorccu** [comment]
Closing since no new information has been presented, and this doesn't seem to be an issue with STF anyway.
