### ISSUE TITLE
Devices at "automation" status are listed in random positions in details view

### ISSUE THREAD

**Issue by thinkhy** [openstf/stf#633]
As subject, devices at "automation" status can't be listed in static order. 

Seems it's due to the status of "automation"  missed in compare function in `res/app/device-list/column/device-column-service.js` .

```javascript
      compare: (function() {
         var order = {
           using: 10
          , available: 20
          , busy: 30
          , ready: 40
          , preparing: 50
          , unauthorized: 60
          , offline: 70
          , present: 80
          , absent: 90
        }
```

**Comment by vbanthia** [comment]
https://github.com/openstf/stf/commit/cc5d7580c23dce1fd4526974370fc3a5c76c866d should fix this issue. 

Thanks
