### ISSUE TITLE
How to get sound from the microphone of the mobile device(android,apple,etc) on which we are running openstf in any browser?

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#634]
Hi,
The question can be a bit confusing, sorry for that. But the problem is when i run openstf on any browser then it is still using the hardware(microphone,camera,etc) of the physical device connected with server not of my device on which i am running openstf. Now please tell me how to access the hardware of the device on which i am running openstf?

**Comment by sorccu** [comment]
Right now you cannot.

**Comment by suvansh-dev** [comment]
So there are not any plugin's for that? Is there any way by which i can make it manually?

**Comment by sorccu** [comment]
No. You would have to figure it out yourself.

**Comment by suvansh-dev** [comment]
So sweet of you, thanks
