### ISSUE TITLE
centos  have something problem ,gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/node-v8.1.2-linux-x64/lib/node_modules/stf/node_modules/zmq/build' ,can you help me 

### ISSUE THREAD

**Issue by nennhui** [openstf/stf#637]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Use nvm to install node. All package managers suck at installing node.

**Comment by nennhui** [comment]
thanks ，this problem is slove . npm use " --unsafe-perm" can slove

**Comment by sorccu** [comment]
Yes, that works sometimes but occasionally it doesn't (we've seen some packages fail to build in the past). Either way I would recommend `nvm`.

**Comment by anti-k-camino** [comment]
Thanks a lot.That saved my night.
