### ISSUE TITLE
Can the lastest version of STF support Android7.0? Why I don't see the minicap and minitouch floder In vendor at master branch?Looking forward to your answer,Thanks!

### ISSUE THREAD

**Issue by Crazyerick** [openstf/stf#638]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
It works fine. Use the master branch, though.

**Comment by Crazyerick** [comment]
But why I don't see the minicap and minitouch floder In vendor at master branch?It doesn't matter?

**Comment by sorccu** [comment]
They're now in separate packages, minicap-prebuilt and minitouch-prebuilt,
which are dependencies in package.json.

**Comment by Crazyerick** [comment]
Ok，Thanks for your answer!
