### ISSUE TITLE
some problems when docker build

### ISSUE THREAD

**Issue by dyxrdyxr** [openstf/stf#640]
I modify some code, and then build docker image myself.
when I run sudo docker build -t stf . , some problems happen.
![2017-07-03 11 23 33](https://user-images.githubusercontent.com/27947461/27777052-14baa060-5fe2-11e7-9437-eec1ad29d5f3.png)

**Comment by sorccu** [comment]
That doesn't look right. Perhaps it's your modifications that are causing the issue, as the `node-buc` package doesn't exist (or at least it isn't public).
