### ISSUE TITLE
can i connect virtual devices with openstf?

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#641]
Hi,
Can we connect virtual devices created in virtualbox,vmware with openstf?

**Comment by sorccu** [comment]
Some have managed to do it, but I've never done it. Either way it's not a supported use case. Try searching for older issues about this same thing.

**Comment by strong-code** [comment]
For people that come across this via google or something in the future, see this issue for information on connecting virtual devices to STF: https://github.com/openstf/stf/issues/453#issuecomment-256832772

**Comment by suvansh-dev** [comment]
Hi,
Here i am sharing the details to connect AVD(Android virtual devices) with openStf. I will just tell what i did because i have no idea what is the cause of that black screen issue or any other problem.

**Hardware details of the pc:**
Processor: Intel® Core™ i3-4130 CPU @ 3.40GHz × 4 
Graphics: Intel® Haswell 
 OS type: 64 bit

**Operating System:**
 OS: Ubuntu  16.04LTS

**Android Studio AVD details:**

Just make any AVD  x86(kitkat 4.4,marshmallow 6.0) works fine  but not of ABI "armeabi-v7a" and  let the settings be as by default.
Please don't change anything especially in the OpenGl or any hardware settings. But you can give the RAM and storage size as much as you need.

Note:  If you already a STF user then you don't need to read further.

**Source for installation of STF :** 

https://miteshshah.github.io/sysadmin/how-to-setup-smartphone-test-farm-stf/

or you can directly run this command from terminal(Press ctrl+alt+T to open terminal on ubuntu): 

**$ curl -s https://gist.githubusercontent.com/MiteshShah/62cd0923b9068a927dae/raw/STF | sudo bash**

But i will recommend you to visit the link first.

**Starting stf on localhost:**

1. Open terminal and run the following command:
                                   $ sudo rethinkdb

2. Open another terminal and the run this command:
                                 $ sudo stf local
    but if you want to access stf on another computers connecting on same network then you can just run this command:
                              $ sudo stf local --public-ip 192.168.x.x

Here 192.168.x.x is the ip address of your computer connecting on that network, its different for every computer, you can get this ip address from:
            System settings> Network>Wireless or wired(see in left side) > name_of_network>then click on arrow on right side if the name> there in details you will see IPv4 address>Just copy/paste it next to --public-ip .
There are other ways too of getting this IPv4 address.
Now just run the above command as per your need.

**Using STF:**
Open any browser and type : 127.0.0.1:7100 for sudo stf local
                                                192.168.x.x:7100 for sudo stf local --public-ip 192.168.x.x

**Starting AVD:**

 Open Android studio>Click on AVD manager icon(Just below Window)>Start the AVD from Actions(that green play button).

**Back to browser**
Now open the browser and see in the **Devices** , there you must see something like "x86 .... " device, now open the device and its done.


Note:
If by any means your installation gets failed and during re-installation you get some "**protobuf**" error then you have to manually delete the protobuf folder and the location of protobuf in my case was: 
             computer>opt>protobuf
and then begin the installation again.
