### ISSUE TITLE
stf-log-rethinkdb.service failed to store messages in rethinkdb

### ISSUE THREAD

**Issue by gauravraval** [openstf/stf#642]
Tried rethinkdb in local and docker env. No messages are coming in logs table

Steps: Start stf ( by following https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) and stf-log-rethinkdb.service 
Also tried stf local and stf log-rethinkdb --connect-sub tcp://127.0.0.1:7150

Expected: logs should come to rethinkdb

no error or warning in stf local output

stf doctor output:
```log
INF/cli:doctor 62523 [*] OS Arch: x64
INF/cli:doctor 62523 [*] OS Platform: darwin
INF/cli:doctor 62523 [*] OS Platform: 16.6.0
INF/cli:doctor 62523 [*] Using Node 7.10.0
INF/cli:doctor 62523 [*] Using ZeroMQ 4.2.2
INF/cli:doctor 62523 [*] Using GraphicsMagick 1.3.25
INF/cli:doctor 62523 [*] Using ADB 1.0.39
INF/cli:doctor 62523 [*] Using ProtoBuf 3.3.0
INF/cli:doctor 62523 [*] Using RethinkDB 2.3.5
```

**Comment by sorccu** [comment]
So does the unit output anything? Check `journalctl -u stf-log-rethinkdb`.

Note that I would recommend a third party logging service that watches journal logs instead. The rethinkdb logger can miss messages if it dies briefly, or obviously if the socket dies.

**Comment by gauravraval** [comment]
Unit output is there but log level seems to have problem. (refer last line in blow logs). in older code, log level is defined / honored correctly  (e.g. INF/log-db 1 [*] Listening for **USAGE (or higher)** level log messages)
Current log: 
``` log
Jul 05 09:50:23 localhost systemd[1]: Started STF RethinkDB log recorder.
Jul 05 09:50:24 localhost docker[2427]: INF/log-db 1 [*] Subscribing to permanent channel "*ALL"
Jul 05 09:50:24 localhost docker[2427]: INF/log-db 1 [*] Listening for undefined (or higher) level log messages
```

**Comment by sorccu** [comment]
That looks like a bug (it says undefined). I'll check it a bit later.

**Comment by sorccu** [comment]
```
bin/stf log-rethinkdb --connect-sub tcp://127.0.0.1:7150
INF/log-db 21542 [*] Subscribing to permanent channel "*ALL"
INF/log-db 21542 [*] Listening for IMP (or higher) level log messages
```

Seems to work fine with latest master, at least.

**Comment by gauravraval** [comment]
Working with port 7111 (on local) and priority from 1 to 7. Port 7150 didn't work on local setup.
