### ISSUE TITLE
Connecting to 172.17.0.2:28015 is not successful

### ISSUE THREAD

**Issue by bhajojo** [openstf/stf#644]
I am running this 2 commands inside Docker terminal to Setup STP 

docker run --name some-rethink -v "C:/STF/RethinkDB/data" -p 28015:28015 rethinkdb
docker run --link some-rethink:rethinkdb -p 7100:7100 openstf/stf:latest stf local

first Command run successfully and generates logs as below 
$ docker run --name some-rethink -v "C:/STF/RethinkDB/data" -p 28015:28015 reth
inkdb
Unable to find image 'rethinkdb:latest' locally
latest: Pulling from library/rethinkdb
9f0706ba7422: Pull complete
13cff7bd7d5f: Pull complete
2f7f87e28358: Pull complete
4f5c608387ab: Pull complete
0168e87b5569: Pull complete
Digest: sha256:e752a5624ab4c0724d1c2c5201e09c8d88de290bafd85f026ddb53cc21a31717
Status: Downloaded newer image for rethinkdb:latest
Recursively removing directory /data/rethinkdb_data/tmp
Initializing directory /data/rethinkdb_data
Running rethinkdb 2.3.5~0jessie (GCC 4.9.2)...
Running on Linux 4.4.59-boot2docker x86_64
Loading data from directory /data/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (avail
able memory: 785 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 172.17.0.2
Listening on driver addresses: 127.0.0.1, 172.17.0.2
Listening on http addresses: 127.0.0.1, 172.17.0.2
Server ready, "0772e140b102_j2j" 9174cf42-c618-40eb-8dac-fc76c80fe826
warn: Some RethinkDB data on this server has been placed into swap memory. This
may impact performance.

2nd Command generates following logs 
Unable to find image 'openstf/stf:latest' locally
latest: Pulling from openstf/stf
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
a8a00db89a00: Pull complete
eefd4bde42f3: Pull complete
cd3668a0e1bf: Pull complete
223d989df2e2: Pull complete
fa36956c56f3: Pull complete
Digest: sha256:8f2588bf654323198d2344774d247044044611b102490fd71d18c1324f5c697d
Status: Downloaded newer image for openstf/stf:latest
INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"
INF/db 10 [*] Connecting to 172.17.0.2:28015
INF/db:setup 10 [*] Database "stf" created
INF/db:setup 10 [*] Table "users" created
INF/db:setup 10 [*] Index "users"."adbKeys" created
INF/db:setup 10 [*] Waiting for index "users"."adbKeys"
INF/db:setup 10 [*] Index "users"."adbKeys" is ready
INF/db:setup 10 [*] Table "vncauth" created
INF/db:setup 10 [*] Index "vncauth"."response" created
INF/db:setup 10 [*] Waiting for index "vncauth"."response"
INF/db:setup 10 [*] Table "accessTokens" created
INF/db:setup 10 [*] Table "logs" created
INF/db:setup 10 [*] Table "devices" created
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" created
INF/db:setup 10 [*] Index "accessTokens"."email" created
INF/db:setup 10 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 10 [*] Waiting for index "accessTokens"."email"
INF/db:setup 10 [*] Index "devices"."owner" created
INF/db:setup 10 [*] Waiting for index "devices"."owner"
INF/db:setup 10 [*] Index "devices"."present" created
INF/db:setup 10 [*] Waiting for index "devices"."present"
INF/db:setup 10 [*] Index "devices"."providerChannel" created
INF/db:setup 10 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 10 [*] Index "accessTokens"."email" is ready
INF/db:setup 10 [*] Index "devices"."owner" is ready
INF/db:setup 10 [*] Index "vncauth"."response" is ready
INF/db:setup 10 [*] Index "devices"."present" is ready
INF/db:setup 10 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://1
27.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:711
3"
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://1
27.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:711
6"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc001 --connect-app-de
aler tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc002 --connect-app-de
aler tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tc
p://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1 [*] Forking "/app/lib/cli provider --name 280c78dcf572 --min
-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp
://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http:/
/localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800
"
INF/util:procutil 1 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kut
e kittykat --app-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli app --port 7105 --secret kute kitt
ykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhos
t:7110/"
INF/util:procutil 1 [*] Forking "/app/lib/cli api --port 7106 --secret kute kitt
ykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1 [*] Forking "/app/lib/cli websocket --port 7110 --secret kut
e kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:71
11 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-temp --port 7102"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 -
-storage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --s
torage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http:
//localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7
106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/
 --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http
://localhost:7104/"
INF/triproxy 16 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 16 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 17 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 16 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/triproxy 17 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 17 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/poorxy 89 [*] Listening on port 7100
INF/reaper 40 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 40 [reaper001] Reaping devices with no heartbeat
INF/db 29 [*] Connecting to 172.17.0.2:28015
INF/db 23 [*] Connecting to 172.17.0.2:28015
INF/db 40 [reaper001] Connecting to 172.17.0.2:28015
INF/reaper 40 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 40 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/processor 29 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 29 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/processor 23 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 23 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/storage:plugins:image 77 [*] Listening on port 7103
INF/auth-mock 47 [*] Listening on port 7120
INF/storage:plugins:apk 83 [*] Listening on port 7104
INF/storage:temp 76 [*] Listening on port 7102
INF/provider 41 [*] Subscribing to permanent channel "VJyocYsmRCKaB7cY+XWrGQ=="
INF/provider 41 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 41 [*] Receiving input from "tcp://127.0.0.1:7114"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
INF/app 58 [*] Using pre-built resources
INF/app 58 [*] Listening on port 7105
INF/db 58 [*] Connecting to 172.17.0.2:28015
INF/websocket 65 [*] Subscribing to permanent channel "*ALL"
INF/websocket 65 [*] Listening on port 7110
INF/db 65 [*] Connecting to 172.17.0.2:28015
INF/websocket 65 [*] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 65 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/api 59 [*] Subscribing to permanent channel "*ALL"
INF/api 59 [*] Listening on port 7106
INF/api 59 [*] Sending output to "tcp://127.0.0.1:7113"
INF/api 59 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/db 59 [*] Connecting to 172.17.0.2:28015

**Please run `stf doctor` and paste the output here.**
when I run stf doctor , I get following exception 

Error: Cannot find module 'C:\UserlibPath\AppData\Roaming\npm\node_modules\st
f\bin\stf'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Please help me to resolve this issue

**Comment by sorccu** [comment]
The stf image does not include adb. There's a separate docker image for
that. Check out the deployment guide.

**Comment by bhajojo** [comment]
Hi  ,

I have tried to run adb container seperately by  using this command
docker run -d --privileged -v /dev/bus/usb:/dev/bus/usb --name abdb sorccu/adb

still I an getting the same exception


$ docker run --link some-rethink:rethinkdb -p 7100:7100 openstf/stf:latest stf
local
Unable to find image 'openstf/stf:latest' locally
latest: Pulling from openstf/stf
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
a8a00db89a00: Pull complete
eefd4bde42f3: Pull complete
cd3668a0e1bf: Pull complete
223d989df2e2: Pull complete
fa36956c56f3: Pull complete
Digest: sha256:8f2588bf654323198d2344774d247044044611b102490fd71d18c1324f5c697d
Status: Downloaded newer image for openstf/stf:latest
INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"
INF/db 10 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/db:setup 10 [*] Database "stf" already exists
INF/db:setup 10 [*] Table "users" already exists
INF/db:setup 10 [*] Table "accessTokens" already exists
INF/db:setup 10 [*] Table "vncauth" already exists
INF/db:setup 10 [*] Table "devices" already exists
INF/db:setup 10 [*] Table "logs" already exists
INF/db:setup 10 [*] Index "users"."adbKeys" already exists
INF/db:setup 10 [*] Index "accessTokens"."email" already exists
INF/db:setup 10 [*] Index "vncauth"."response" already exists
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 10 [*] Waiting for index "users"."adbKeys"
INF/db:setup 10 [*] Waiting for index "accessTokens"."email"
INF/db:setup 10 [*] Waiting for index "vncauth"."response"
INF/db:setup 10 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 10 [*] Index "devices"."owner" already exists
INF/db:setup 10 [*] Index "devices"."present" already exists
INF/db:setup 10 [*] Index "devices"."providerChannel" already exists
INF/db:setup 10 [*] Index "users"."adbKeys" is ready
INF/db:setup 10 [*] Index "accessTokens"."email" is ready
INF/db:setup 10 [*] Waiting for index "devices"."owner"
INF/db:setup 10 [*] Waiting for index "devices"."present"
INF/db:setup 10 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 10 [*] Index "vncauth"."response" is ready
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 10 [*] Index "devices"."owner" is ready
INF/db:setup 10 [*] Index "devices"."present" is ready
INF/db:setup 10 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://1
27.0.0.1:7111<http://27.0.0.1:7111> --bind-dealer tcp://127.0.0.1:7112<http://127.0.0.1:7112> --bind-pull tcp://127.0.0.1:711<http://127.0.0.1:711>
3"
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://1
27.0.0.1:7114<http://27.0.0.1:7114> --bind-dealer tcp://127.0.0.1:7115<http://127.0.0.1:7115> --bind-pull tcp://127.0.0.1:711<http://127.0.0.1:711>
6"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc001 --connect-app-de
aler tcp://127.0.0.1:7112<http://127.0.0.1:7112> --connect-dev-dealer tcp://127.0.0.1:7115<http://127.0.0.1:7115>"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc002 --connect-app-de
aler tcp://127.0.0.1:7112<http://127.0.0.1:7112> --connect-dev-dealer tcp://127.0.0.1:7115<http://127.0.0.1:7115>"
INF/util:procutil 1 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tc
p://127.0.0.1:7116<http://127.0.0.1:7116> --connect-sub tcp://127.0.0.1:7111<http://127.0.0.1:7111>"
INF/util:procutil 1 [*] Forking "/app/lib/cli provider --name 2f30d2f4a13b --min
-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114<http://127.0.0.1:7114> --connect-push tcp
://127.0.0.1:7116<http://127.0.0.1:7116> --group-timeout 900 --public-ip localhost --storage-url http:/
/localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800
"
INF/util:procutil 1 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kut
e kittykat --app-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli app --port 7105 --secret kute kitt
ykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhos
t:7110/"
INF/util:procutil 1 [*] Forking "/app/lib/cli api --port 7106 --secret kute kitt
ykat --connect-push tcp://127.0.0.1:7113<http://127.0.0.1:7113> --connect-sub tcp://127.0.0.1:7111<http://127.0.0.1:7111>"
INF/util:procutil 1 [*] Forking "/app/lib/cli websocket --port 7110 --secret kut
e kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:71<http://127.0.0.1:71>
11 --connect-push tcp://127.0.0.1:7113<http://127.0.0.1:7113>"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-temp --port 7102"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 -
-storage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --s
torage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http:
//localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7
106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/
 --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http
://localhost:7104/"
INF/triproxy 16 [app001] PUB socket bound on tcp://127.0.0.1:7111<http://127.0.0.1:7111>
INF/triproxy 16 [app001] DEALER socket bound on tcp://127.0.0.1:7112<http://127.0.0.1:7112>
INF/triproxy 22 [dev001] PUB socket bound on tcp://127.0.0.1:7114<http://127.0.0.1:7114>
INF/triproxy 16 [app001] PULL socket bound on tcp://127.0.0.1:7113<http://127.0.0.1:7113>
INF/triproxy 22 [dev001] DEALER socket bound on tcp://127.0.0.1:7115<http://127.0.0.1:7115>
INF/triproxy 22 [dev001] PULL socket bound on tcp://127.0.0.1:7116<http://127.0.0.1:7116>
INF/poorxy 84 [*] Listening on port 7100
INF/reaper 35 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 35 [reaper001] Reaping devices with no heartbeat
INF/db 23 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/db 35 [reaper001] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/db 29 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/reaper 35 [reaper001] Receiving input from "tcp://127.0.0.1:7111<http://127.0.0.1:7111>"
INF/reaper 35 [reaper001] Sending output to "tcp://127.0.0.1:7116<http://127.0.0.1:7116>"
INF/processor 23 [proc001] App dealer connected to "tcp://127.0.0.1:7112<http://127.0.0.1:7112>"
INF/processor 23 [proc001] Device dealer connected to "tcp://127.0.0.1:7115<http://127.0.0.1:7115>"
INF/processor 29 [proc002] App dealer connected to "tcp://127.0.0.1:7112<http://127.0.0.1:7112>"
INF/processor 29 [proc002] Device dealer connected to "tcp://127.0.0.1:7115<http://127.0.0.1:7115>"
INF/storage:plugins:image 77 [*] Listening on port 7103
INF/auth-mock 47 [*] Listening on port 7120
INF/storage:plugins:apk 83 [*] Listening on port 7104
INF/storage:temp 71 [*] Listening on port 7102
INF/provider 36 [*] Subscribing to permanent channel "EjJpPvuITGamvu7Atz+y/w=="
INF/provider 36 [*] Sending output to "tcp://127.0.0.1:7116<http://127.0.0.1:7116>"
INF/provider 36 [*] Receiving input from "tcp://127.0.0.1:7114<http://127.0.0.1:7114>"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
INF/app 53 [*] Using pre-built resources
INF/app 53 [*] Listening on port 7105
INF/db 53 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/websocket 70 [*] Subscribing to permanent channel "*ALL"
INF/websocket 70 [*] Listening on port 7110
INF/db 70 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>
INF/websocket 70 [*] Sending output to "tcp://127.0.0.1:7113<http://127.0.0.1:7113>"
INF/websocket 70 [*] Receiving input from "tcp://127.0.0.1:7111<http://127.0.0.1:7111>"
INF/api 59 [*] Subscribing to permanent channel "*ALL"
INF/api 59 [*] Listening on port 7106
INF/api 59 [*] Sending output to "tcp://127.0.0.1:7113<http://127.0.0.1:7113>"
INF/api 59 [*] Receiving input from "tcp://127.0.0.1:7111<http://127.0.0.1:7111>"
INF/db 59 [*] Connecting to 172.17.0.3:28015<http://172.17.0.3:28015>


On Mon, Jul 10, 2017 at 11:41 AM, Simo Kinnunen <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #644<https://github.com/openstf/stf/issues/644>.

**Comment by rahul0698** [comment]
hi,
I am trying to deploy stf but all containers are UP except the containers which are trying to connect to 127.0.0.1:28015 are exited. All those are showing this error(please see the attached image)

 ```
INF/db 1 [*] Connecting to 127.0.0.1:28015
INF/db 1 [*] Unable to connect to 127.0.0.1:28015
FTL/db 1 [*] No hosts left to try
FTL/util:lifecycle 1 [*] Shutting down due to fatal error
```
result of ``` sudo docker ps -a ```

![docker_ps1](https://user-images.githubusercontent.com/20282504/28657382-81338974-72c4-11e7-9873-84636fa21026.png)
the shell script that I am using to automate the deployment is [https://github.com/thinkhy/deploy-stf-docker/blob/master/deploy_stf.sh](url) 

The browser screenshot witch error in console is 
![chrome_console2](https://user-images.githubusercontent.com/20282504/28657447-d90dafbc-72c4-11e7-880f-6d420aa55376.png)
![firefox_console2](https://user-images.githubusercontent.com/20282504/28657458-e26e0534-72c4-11e7-9b21-ce526be3bff0.png)

any help will be much appreciated. I am close to deployment. Not able to figure out how to resolve this issue.

Thanks in advance.

**Comment by zhouzxiang** [comment]
@rahul0698 I also have the same problem. Do you have a solution to this problem? Thank you
