### ISSUE TITLE
Websocket exception while using --allow-remote  --public -ip option with stf local docker image 

### ISSUE THREAD

**Issue by bhajojo** [openstf/stf#649]
Hi All,

I am getting websocket exception  while running the docker image while selecting allow remote and public ip option 

but when  i run the image without these options like public-ip  , I am able to run STF successfully without any exception 

I have gone through other similar  issue on github , the solution mentioned was that the "configuration was wrong " if the configuration is wrong how is it possible to connect to the device without using public -ip option

Also in some issues it was mentioned that the websocket should also connect to 7100 port , but in the cases  where STF was working successfully(without public -ip options). websocket was connected to 7110 port only.

I am trying to figure out in the repository , where exactly this connection is being established  . Please help me out with this issue 

Thanks and Regards,

**Comment by sorccu** [comment]
While I agree that "your configuration is wrong" is vague, we simply don't have time to help with general configuration issues unless you provide all the necessary details by yourself. It takes a lot of time if we have to ask for those one by one.

For example, when you created this issue, you decided to remove the issue template. So now I would have to spend a few minutes asking you to provide those details instead of being able to help you directly. In this case, it would have been particularly useful if you had provided the exact commands you used, and the full output of those commands. Otherwise you're sort of expecting me or someone else to simply keep trying various random combinations, which is a huge waste of time.

Please try to proactively provide as much detail as possible. It increases the chances of someone willing to look into your issue.

**Comment by bhajojo** [comment]
Please find the steps along with the Logs 

executed command :1
bharatjoshi$ docker run -d --privileged --net host -v /dev/bus/usb:/dev/bus/usb --name abdb sorccu/adb

Logs
337488050e200c435235c91aa2b5cf47a3e99f25bbc25e0e9ae103d628d48377

executed command :2 
docker run --net host --name some-rethink -v "/c/STF/RethinkDB:/data" rethinkdb

Logs: 
Recursively removing directory /data/rethinkdb_data/tmp
Initializing directory /data/rethinkdb_data
Running rethinkdb 2.3.5~0jessie (GCC 4.9.2)...
Running on Linux 4.4.66-boot2docker x86_64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 172.17.0.1, 10.0.2.15, 192.168.99.100, ::1, fe80::a00:27ff:fe35:af5d%4, fe80::a00:27ff:feba:fff5%3
Listening on driver addresses: 127.0.0.1, 172.17.0.1, 10.0.2.15, 192.168.99.100, ::1, fe80::a00:27ff:fe35:af5d%4, fe80::a00:27ff:feba:fff5%3
Listening on http addresses: 127.0.0.1, 172.17.0.1, 10.0.2.15, 192.168.99.100, ::1, fe80::a00:27ff:fe35:af5d%4, fe80::a00:27ff:feba:fff5%3
Server ready, "default_l8r" d75a238c-d201-4729-a71b-863223204d0f

executed Command: 3
docker run --net host openstf/stf:latest stf local --allow-remote --public-ip 10.83.12.78

Logs: INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"
INF/db 10 [*] Connecting to 127.0.0.1:28015
INF/db:setup 10 [*] Database "stf" created
INF/db:setup 10 [*] Table "users" created
INF/db:setup 10 [*] Table "accessTokens" created
INF/db:setup 10 [*] Table "vncauth" created
INF/db:setup 10 [*] Table "devices" created
INF/db:setup 10 [*] Table "logs" created
INF/db:setup 10 [*] Index "users"."adbKeys" created
INF/db:setup 10 [*] Index "accessTokens"."email" created
INF/db:setup 10 [*] Index "vncauth"."response" created
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" created
INF/db:setup 10 [*] Index "devices"."owner" created
INF/db:setup 10 [*] Index "devices"."present" created
INF/db:setup 10 [*] Waiting for index "users"."adbKeys"
INF/db:setup 10 [*] Waiting for index "accessTokens"."email"
INF/db:setup 10 [*] Waiting for index "vncauth"."response"
INF/db:setup 10 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 10 [*] Waiting for index "devices"."owner"
INF/db:setup 10 [*] Waiting for index "devices"."present"
INF/db:setup 10 [*] Index "devices"."providerChannel" created
INF/db:setup 10 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 10 [*] Index "users"."adbKeys" is ready
INF/db:setup 10 [*] Index "accessTokens"."email" is ready
INF/db:setup 10 [*] Index "vncauth"."response" is ready
INF/db:setup 10 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 10 [*] Index "devices"."owner" is ready
INF/db:setup 10 [*] Index "devices"."present" is ready
INF/db:setup 10 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 1 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1 [*] Forking "/app/lib/cli provider --name default --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.83.12.78 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --allow-remote"
INF/util:procutil 1 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://10.83.12.78:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://10.83.12.78:7100/auth/mock/ --websocket-url http://10.83.12.78:7110/"
INF/util:procutil 1 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 1 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-temp --port 7102"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 1 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 17 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 16 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 17 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 17 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/triproxy 16 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 16 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/db 23 [*] Connecting to 127.0.0.1:28015
INF/db 29 [*] Connecting to 127.0.0.1:28015
INF/processor 29 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 29 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/processor 23 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 23 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/reaper 35 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 35 [reaper001] Reaping devices with no heartbeat
INF/db 35 [reaper001] Connecting to 127.0.0.1:28015
INF/reaper 35 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 35 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/poorxy 79 [*] Listening on port 7100
INF/provider 36 [*] Subscribing to permanent channel "//wsYk8jSVO5Np5Ia/TKew=="
INF/provider 36 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 36 [*] Receiving input from "tcp://127.0.0.1:7114"
INF/provider 36 [*] Tracking devices
INF/auth-mock 42 [*] Listening on port 7120
INF/storage:temp 66 [*] Listening on port 7102
INF/storage:plugins:image 72 [*] Listening on port 7103
INF/websocket 60 [*] Subscribing to permanent channel "*ALL"
INF/websocket 60 [*] Listening on port 7110
INF/db 60 [*] Connecting to 127.0.0.1:28015
INF/websocket 60 [*] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 60 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/storage:plugins:apk 78 [*] Listening on port 7104
INF/app 53 [*] Using pre-built resources
INF/app 53 [*] Listening on port 7105
INF/db 53 [*] Connecting to 127.0.0.1:28015
INF/api 54 [*] Subscribing to permanent channel "*ALL"
INF/api 54 [*] Listening on port 7106
INF/api 54 [*] Sending output to "tcp://127.0.0.1:7113"
INF/api 54 [*] Receiving input from "tcp://127.0.0.1:7111"
INF/db 54 [*] Connecting to 127.0.0.1:28015
INF/provider 36 [*] Found device "2bd2eca7" (offline)
INF/provider 36 [*] Registered device "2bd2eca7"
INF/reaper 35 [reaper001] Device "2bd2eca7" is present
INF/provider 36 [*] Device "2bd2eca7" is now "device" (was "offline")
INF/device:support:push 120 [2bd2eca7] Sending output to "tcp://127.0.0.1:7116"
INF/device 120 [2bd2eca7] Preparing device
INF/device:support:sub 120 [2bd2eca7] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 120 [2bd2eca7] Subscribing to permanent channel "*ALL"
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/provider 36 [*] Providing 0 of 1 device(s); waiting for "2bd2eca7"
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:adb 120 [2bd2eca7] Waiting for boot to complete
INF/device:support:properties 120 [2bd2eca7] Loading properties
INF/device:support:sdk 120 [2bd2eca7] Supports SDK 22
INF/device:support:abi 120 [2bd2eca7] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:minicap 120 [2bd2eca7] Installing "/app/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/bin/minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 120 [2bd2eca7] Installing "/app/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-22/minicap.so" as "/data/local/tmp/minicap.so"
INF/device:resources:service 120 [2bd2eca7] Checking whether we need to install STFService
INF/device:resources:service 120 [2bd2eca7] Running version check
INF/device:resources:service 120 [2bd2eca7] STFService up to date
INF/device:plugins:service 120 [2bd2eca7] Launching agent
INF/provider 36 [*] Providing 0 of 1 device(s); waiting for "2bd2eca7"
INF/device:plugins:service 120 [2bd2eca7] Launching service
INF/device:plugins:service 120 [2bd2eca7] Agent says: "Listening on @stfagent"
INF/device:plugins:service 120 [2bd2eca7] Agent says: "InputClient started"
INF/device:plugins:display 120 [2bd2eca7] Reading display info
INF/device:plugins:phone 120 [2bd2eca7] Fetching phone info
INF/device:plugins:identity 120 [2bd2eca7] Solving identity
INF/device:plugins:solo 120 [2bd2eca7] Subscribing to permanent channel "jMSB9mdwadB/o0mgJ1E4fgzDn6E="
INF/device:plugins:screen:stream 120 [2bd2eca7] Starting WebSocket server on port 7400
INF/device:resources:minitouch 120 [2bd2eca7] Installing "/app/node_modules/minitouch-prebuilt/prebuilt/armeabi-v7a/bin/minitouch" as "/data/local/tmp/minitouch"
WRN/device:plugins:data 120 [2bd2eca7] Unable to find device data { serial: '2bd2eca7',
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  operator: ',',
  model: 'SM-E700H',
  version: '5.1.1',
  abi: 'armeabi-v7a',
  sdk: '22',
  product: 'e73gxx',
  display: 
   { id: 0,
     width: 720,
     height: 1280,
     xdpi: 268.9410095214844,
     ydpi: 266.4909973144531,
     fps: 60,
     density: 2,
     rotation: 0,
     secure: true,
     size: 5.498873422694838,
     url: 'ws://10.83.12.78:7400' },
  phone: { imei: '358185060538227', network: 'UNKNOWN' } }
INF/device:plugins:touch 120 [2bd2eca7] Touch origin is top left
INF/device:plugins:touch 120 [2bd2eca7] Requesting touch consumer to start
INF/device:plugins:touch 120 [2bd2eca7] Launching screen service
INF/device:plugins:touch 120 [2bd2eca7] Connecting to minitouch service
INF/device:plugins:touch 120 [2bd2eca7] minitouch says: "WARNING: linker: /data/local/tmp/minitouch: unused DT entry: type 0x6ffffffe arg 0x8c8"
INF/device:plugins:touch 120 [2bd2eca7] minitouch says: "WARNING: linker: /data/local/tmp/minitouch: unused DT entry: type 0x6fffffff arg 0x1"
INF/device:plugins:touch 120 [2bd2eca7] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 120 [2bd2eca7] minitouch says: "Type B touch device sec_touchscreen (720x1280 with 10 contacts) detected on /dev/input/event2 (score 2109)"
INF/device:plugins:touch 120 [2bd2eca7] Reading minitouch banner
INF/device:plugins:touch 120 [2bd2eca7] minitouch says: "Connection established"
INF/device:plugins:vnc 120 [2bd2eca7] Starting VNC server on port 7402
INF/device:plugins:browser 120 [2bd2eca7] Loading browser list
INF/device:plugins:browser 120 [2bd2eca7] Updating browser list
INF/device:plugins:mute 120 [2bd2eca7] Will not mute master volume during use
INF/device:resources:minirev 120 [2bd2eca7] Installing "/app/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
INF/device:plugins:forward 120 [2bd2eca7] Launching reverse port forwarding service
INF/device:plugins:forward 120 [2bd2eca7] Connecting to reverse port forwarding service
INF/device:plugins:connect 120 [2bd2eca7] Listening on port 7401
INF/device 120 [2bd2eca7] Fully operational
INF/provider 36 [*] Providing all 1 device(s)

**Comment by bhajojo** [comment]
Hi ,

I have added the logs and the commands

On 17-Jul-2017 19:35, "Simo Kinnunen" <notifications@github.com<mailto:notifications@github.com>> wrote:

While I agree that "your configuration is wrong" is vague, we simply don't have time to help with general configuration issues unless you provide all the necessary details by yourself. It takes a lot of time if we have to ask for those one by one.

For example, when you created this issue, you decided to remove the issue template. So now I would have to spend a few minutes asking you to provide those details instead of being able to help you directly. In this case, it would have been particularly useful if you had provided the exact commands you used, and the full output of those commands. Otherwise you're sort of expecting me or someone else to simply keep trying various random combinations, which is a huge waste of time.

Please try to proactively provide as much detail as possible. It increases the chances of someone willing to look into your issue.

**Comment by bhajojo** [comment]
I have got the workaround to the websocket issue 

Solution: We need to add the port which is appearing in the websocket exception to the  Port forwarding rules of the vm used 

It will  start working . Closing this issue now
