### ISSUE TITLE
Unable to connect to 127.0.0.1:28015

### ISSUE THREAD

**Issue by yuancc** [openstf/stf#65]
I start rethinkdb as default configure in new terminal with command "rethinkdb",then start the unit "rethinkdb-proxy-28015.service".

Then I start the unit "stf-app@3100.service",it can running at first,but it will  failed after a while, I have tried it like the following method.How can I deal with it?

# docker run openstf/stf:latest stf app --port 3000 --secret 123456 --auth-url 10.240.154.173:7100 --websocket-url 10.240.154.173:7100
INF/app 1 [*] Using pre-built resources
INF/app 1 [*] Listening on port 3000
INF/db 1 [*] Connecting to 127.0.0.1:28015
INF/db 1 [*] Unable to connect to 127.0.0.1:28015
FTL/db 1 [*] No hosts left to try
FTL/util:lifecycle 1 [*] Shutting down due to fatal error

**Comment by sorccu** [comment]
Hi,

You forgot the `--link` option. See https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md.

**Comment by yuancc** [comment]
It will also failed if I start the stf-app@3100.service with the command "systemctl start stf-app@3100.service ". The question maybe the docker's IP can not link the expose port of rethinkdb if add the --link option (172.17.0.179:28015--->127.0.0.1:28015),I don't know how to deal with it. (if i don't use --link option,it will connecting to 127.0.0.1.:28015)

Then I try to start Like following:

# docker run --link rethinkdb-proxy-28015:rethinkdb -e "SECRET=123456" -p 127.0.0.1:3100:3000 openstf/stf:latest stf app --port 3000 --secret 123456 --auth-url 10.240.154.173:7100 --websocket-url 10.240.154.173:7100
INF/app 1 [*] Using pre-built resources
INF/app 1 [*] Listening on port 3000
INF/db 1 [*] Connecting to 172.17.0.179:28015
INF/db 1 [*] Unable to connect to 172.17.0.179:28015
FTL/db 1 [*] No hosts left to try
FTL/util:lifecycle 1 [*] Shutting down due to fatal error

**Comment by vbanthia** [comment]
Try this. Start rethinkdb using --bind all
```
rethinkdb --bind all
```

**Comment by yuancc** [comment]
Thanks,I have tried it,but it doesn't work. Now i want to ask another question,should i have to install nginx separately in my host? I have pulled the docker image of nginx:1.7.10,Should i have to create the file of nginx.conf by myself and deploy it like https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md? how to create the file like cert.pem cert.key dhparam.pem?

**Comment by sorccu** [comment]
Hi,

Sorry but that's beyond the scope of STF and the resources we have right
now. The deployment guide is meant for those who are already familiar with
the software we use, or otherwise able to adapt the instructions to their
system.

Note though that you don't have to set up https if creating the certs is
too much trouble.

**Comment by yuancc** [comment]
Oh,i see,thanks.
It's means that i must deploy the platform of STF by myself if i want to run it on real servers,the file https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md just a reference. There are a lot of things I should to change or create in my way.It will not work if i deploy it just like the description of DEPLOYMENT .

thanks again, I will learn it by my best.

**Comment by sorccu** [comment]
I can guarantee that the instructions work as long as you know how you're
supposed to use them, since the system we use is identical except for a few
configuration options. So I know that it works, but I can't really help if
you or someone else can't get it running, because that would take way more
time than I can afford :)

**Comment by yuancc** [comment]
thanks a lot,I'm trying ! sorry to trouble you !
