### ISSUE TITLE
Issues while running STF built from source

### ISSUE THREAD

**Issue by thuanpv** [openstf/stf#651]
Hello,
I followed this tutorial (https://gist.github.com/yasuyk/bbaa28568c497d95ff92566efc4ecc3c) and successfully installed openstf (STF version 2.0.0) on a machine running Ubuntu 14.04 64-bit. It works very well -- I can login to the system and interact with my real device.

Since I want to modify the STF a bit, I have tried to build it from source by skipping the 7th step in the tutorial and running "sudo npm install" and "sudo npm link" from STF source folder; however I face the following issues
1. If I compile the newest version of STF from source, there are some compilation errors which seem to be relevant to the NPM version (my NPM version is 1.3.10) 
2. I think the first problem is because the newest version of STF is v3.0.0 while the installed dependencies are for STF v2.0.0 so I tried to checkout the commit for STF 2.0.0 (5a2af57fc5aafeedcbc5e6e215fdd0d609e4cf84). Using this revision, I compiled the code successfully without any errors. However, when I run "stf local" and try to access the front-end at 127.0.0.1:7100, I got a blank page -- no login screen. I checked the STF output and saw several errors while building app and web_modules (as attached).
[stf_output_error.txt](https://github.com/openstf/stf/files/1159464/stf_output_error.txt)

I also tried to run "stf doctor" and following is the output. It seems that the Node version is too old.

INF/util:doctor 8173 [*] OS Arch: x64
INF/util:doctor 8173 [*] OS Platform: linux
INF/util:doctor 8173 [*] OS Platform: 4.4.0-31-generic
INF/util:doctor 8173 [*] Using Node 0.10.25
ERR/util:doctor 8173 [*] Current Node version is not supported, it has to be >= 4.2
INF/util:doctor 8173 [*] Using RethinkDB client 2.3.3
INF/util:doctor 8173 [*] Using ZeroMQ 4.1.2
INF/util:doctor 8173 [*] Local ADB 1.0.31
INF/util:doctor 8173 [*] Local RethinkDB server 2.3.6~0trusty

/home/ubuntu/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 2.3.6~0trusty
    at new SemVer (/home/ubuntu/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/home/ubuntu/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/home/ubuntu/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/home/ubuntu/stf/lib/util/doctor.js:13:15)
    at /home/ubuntu/stf/lib/util/doctor.js:95:7
    at /home/ubuntu/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

Have you faced similar issues and successfully resolved them? Your suggestion would be really appreciated.
Thanks,
Thuan

**Comment by sorccu** [comment]
Your node is incredibly ancient. We haven't supported that version for years.

**Comment by thuanpv** [comment]
Thanks for your prompt reply. I have tried to setup newest version of OpenSTF on another machine running Ubuntu 16.04 and faced similar issues. Following is the output of "stf doctor" and attached file is the error log when I run "stf local".

INF/cli:doctor 7328 [*] OS Arch: x64
INF/cli:doctor 7328 [*] OS Platform: linux
INF/cli:doctor 7328 [*] OS Platform: 4.8.0-36-generic
INF/cli:doctor 7328 [*] Using Node 6.11.0
INF/cli:doctor 7328 [*] Using ZeroMQ 4.1.4
INF/cli:doctor 7328 [*] Using RethinkDB 2.3.6~0xenial
INF/cli:doctor 7328 [*] Using GraphicsMagick 1.3.23
INF/cli:doctor 7328 [*] Using ProtoBuf 3.2.0
ERR/cli:doctor 7328 [*] ADB version cannot be detected
Regarding the issue with ADB version, my ADB version is 1.0.39. I don't know why stf doctor cannot detect it.
[error_log_stf2.3.0.txt](https://github.com/openstf/stf/files/1161215/error_log_stf2.3.0.txt)

**Comment by thuanpv** [comment]
PS. If I install STF using npm (by running "sudo npm install -g stf"), I get this error while starting stf local

Cannot find module './../../../webpack.config'
FTL/cli:local 9298 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

If I install webpack by running "sudo npm install webpack", I get the following warnings and the problem of missing webpack.config is still unresolved.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

**Comment by thuanpv** [comment]
Now, it works :) I think it did not work because bower and gulp were not there. After installing the two packages and run 2 commands "npm install" (without sudo, and without -g) and "sudo npm link" the system works well.

**Comment by sorccu** [comment]
Glad you were able to get it working, though I'd advice against using `sudo` anyway.
