### ISSUE TITLE
Multiple providers in one machine

### ISSUE THREAD

**Issue by guggas** [openstf/stf#653]
**What is the issue or idea you have?**
I want to have multiple providers in the same machine, filtering the devices that connect to each provider by USB port, that is, if some device gets connected to a range of ports, it will be served by provider X.

In the "Deployment" documentation one can find the following:
"_Note that you cannot have more than one provider unit running on the same host, as they would compete over which one gets to control the devices. In the future we might add a negotiation protocol to allow for relatively seamless upgrades._"

My question is, in order to prevent which provider gets control over the devices, a configuration file could be used in order to force a certain provider to access only the intended range of ports.

This would allow for different devices to show in frontend with different tags, ultimately allowing for finer control over them.

**Comment by sorccu** [comment]
Ok as a disclaimer I don't think that's a very good idea, and we definitely provide support that, but it is possible with some effort.

If you run `stf provider --help`, you should be able to see that if you give it a list of serial numbers, it'll ignore all other devices. So, in theory, you could have both `stf provider 0123456` and `stf provider 7890123` running at the same time. Make sure to give them non-conflicting port ranges, though.

Note that I've never actually tried that myself, but in theory it should work.

**Comment by guggas** [comment]
I got confused, `Usage: provider [options] [serial...]` this serial is related to the device, and not the USB port, right?
We should have a service that gets the serial numbers of the devices connected to the ports we need and then send these serial numbers to the provider at start-up. something along those lines?

**Comment by sorccu** [comment]
Yes you would need to know the serials and then spawn a provider for each (or however you want to split them).
