### ISSUE TITLE
Huawei P9 lite is wiped after disconnection for inactivity

### ISSUE THREAD

**Issue by risinek** [openstf/stf#655]
When I work on Huawei P9 lite, it gets occassionally wiped after I get disconnected from device for inactivity (I guess it's becouse of inactivity).. It gets wiped to the state when I start using the device..
Is this some kind of secure feature in development, or is this a bug?

I will attach logs after it happens again

**Comment by sorccu** [comment]
Do you mean that applications you installed get deleted?

**Comment by risinek** [comment]
Yep, that's exactly what I mean

**Comment by sorccu** [comment]
Use the --no-cleanup option if you don't want that.

**Comment by risinek** [comment]
Ok thanks, didn't know about this feature.. It works just on some devices.. On Samsung Galaxy devices this does not work
Anyway thanks for clear this out.. 👍
