### ISSUE TITLE
Swagger documentation is broken

### ISSUE THREAD

**Issue by thasegaw** [openstf/stf#656]
https://vbanthia.github.io/angular-swagger-ui/

<img width="500" alt="smartphone_test_farm_api" src="https://user-images.githubusercontent.com/8136032/28580291-02b5aee0-719a-11e7-8740-43cd9a8c9179.png">

**Comment by thinkhy** [comment]
I attempt to load lib/units/api/swagger/api_v1.yml  with [swagger editor](https://github.com/swagger-api/swagger-editor), everything goes well. Which swagger parser did you use?

**Comment by thasegaw** [comment]
This error has occurred in document page. 
https://github.com/openstf/stf/blob/master/doc/API.md

<img width="984" alt="stf_api_md_at_master_ _openstf_stf" src="https://user-images.githubusercontent.com/8136032/28768636-5d59af54-7613-11e7-922e-743cf9f3f219.png">

**Comment by vbanthia** [comment]
Fixed in https://github.com/openstf/stf/commit/707482fa3b17a966b6727dba7ea5de9fba1ac40c
