### ISSUE TITLE
Access STF from external network?

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#657]
Hi,
Currently i am launching STF as ........ 
sudo stf local 

or 

sudo stf local --public-ip ipaddress

But what to do if i want to access it from any external network? Currently i write my local pc address to make it available over the local network but what to do if users from external network want to access it? Please help!

**Comment by sorccu** [comment]
It's possible but completely up to you to decide how you want to do it. We don't really provide any help with that, though you can search through old issues for past answers.
