### ISSUE TITLE
Sometimes when I plug/unplug devices, STF devices' restart

### ISSUE THREAD

**Issue by viktors89** [openstf/stf#659]
Hello there!

**What is the issue or idea you have?**
Recently we bought a Mac Mini and I migrated STF from our Mac to the Mac Mini. Everything's working well, but there's this issue that I don't know why happens.

The problem is that sometimes when I plug/unplug a phone, it seems like openstf's devices all unplugged and they restart connecting again.

**Please provide the steps to reproduce the issue.**
With STF running, just plug/unplug some devices and it will eventually happening.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

NF/provider 14788 [*] Providing all 14 of 16 device(s); ignoring "CB5A1XN5M8", "0f680bfc"
IMP/device:plugins:service 25307 [04d86162a2438995] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25307 [04d86162a2438995] Launching service
IMP/device:plugins:service 25307 [04d86162a2438995] Service connection ended, attempting to relaunch
INF/device:plugins:service 25307 [04d86162a2438995] Launching service
INF/provider 14788 [*] Lost device "04d86162a2438995" (device)
INF/provider 14788 [*] Shutting down device worker "04d86162a2438995"
INF/provider 14788 [*] Cleaning up device worker "04d86162a2438995"
INF/provider 14788 [*] Gracefully killing device worker "04d86162a2438995"
WRN/device:plugins:touch 25307 [04d86162a2438995] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25307 [04d86162a2438995] Disconnecting from minitouch service
FTL/util:lifecycle 25307 [04d86162a2438995] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25307 [04d86162a2438995] Shutting down due to fatal error
INF/provider 14788 [*] Device worker "04d86162a2438995" has retired
IMP/device:plugins:service 25298 [5B17000411] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25298 [5B17000411] Launching service
IMP/device:plugins:service 25294 [ZX1D22B4MV] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25294 [ZX1D22B4MV] Launching service
IMP/device:plugins:service 25298 [5B17000411] Service connection ended, attempting to relaunch
INF/device:plugins:service 25298 [5B17000411] Launching service
IMP/device:plugins:service 25294 [ZX1D22B4MV] Service connection ended, attempting to relaunch
WRN/device:plugins:touch 25298 [5B17000411] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:service 25294 [ZX1D22B4MV] Launching service
INF/device:plugins:touch 25298 [5B17000411] Disconnecting from minitouch service
WRN/device:plugins:touch 25294 [ZX1D22B4MV] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25294 [ZX1D22B4MV] Disconnecting from minitouch service
IMP/device:plugins:service 25295 [RB042046] Agent connection ended, attempting to relaunch
IMP/device:plugins:service 25300 [0e32a002f1645052] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25295 [RB042046] Launching service
IMP/device:plugins:service 25302 [aa9443f6] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25300 [0e32a002f1645052] Launching service
INF/device:plugins:service 25302 [aa9443f6] Launching service
IMP/device:plugins:service 25303 [FC047636] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25303 [FC047636] Launching service
IMP/device:plugins:service 25302 [aa9443f6] Service connection ended, attempting to relaunch
INF/device:plugins:service 25302 [aa9443f6] Launching service
IMP/device:plugins:service 25295 [RB042046] Service connection ended, attempting to relaunch
INF/device:plugins:service 25295 [RB042046] Launching service
IMP/device:plugins:service 25300 [0e32a002f164IMP/device:plugins:service 25299 [d6656b6a] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25299 [d6656b6a] Launching service
IMP/device:plugins:service 25299 [d6656b6a] Service connection ended, attempting to relaunch
INF/device:plugins:service 25299 [d6656b6a] Launching service
IMP/device:plugins:service 25308 [CB5A2AGTZ3] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25308 [CB5A2AGTZ3] Launching service
WRN/device:plugins:touch 25299 [d6656b6a] Shell keeping minitouch running ended unexpectedly
IMP/device:plugins:service 25308 [CB5A2AGTZ3] Service connection ended, attempting to relaunch
INF/device:plugins:service 25308 [CB5A2AGTZ3] Launching service
INF/device:plugins:touch 25299 [d6656b6a] Disconnecting from minitouch service
WRN/device:plugins:touch 25308 [CB5A2AGTZ3] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25308 [CB5A2AGTZ3] Disconnecting from minitouch service
5052] Service connection ended, attempting to relaunch
IMP/device:plugins:service 25305 [06157df6612b5c22] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25305 [06157df6612b5c22] Launching service
INF/device:plugins:service 25300 [0e32a002f1645052] Launching service
IMP/device:plugins:service 25305 [06157df6612b5c22] Service connection ended, attempting to relaunch
INFWRN/device:plugins:touch 25295 [RB042046] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25295 [RB042046] Disconnecting from minitouch service
IMP/device:plugins:service 25297 [a3a14ab9] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25297 [a3a14ab9] Launching service
IMP/device:plugins:service 25301 [565347b5] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25301 [565347b5] Launching service
IMP/device:plugins:service 25306 [013e689795773670] Agent connection ended, attempting to relaunch
INF/device:plugins:service 25306 [013e689795773670] Launching service
IMP/device:plugins:service 25297 [a3a14ab9] Service connection ended, attempting to relaunch
IMP/device:plugins:service 25301 [565347b5] Service connection ended, attempting to relaunch
INF/device:plugins:service 25301 [565347b5] Launching service
IMPINF/device:plugins:service 25297 [a3a14ab9] Launching service
/device:plugins:service 25306 [013e689795773670] Service connection ended, attempting to relaunch
WRN/device:plugins:touch 25297 [a3a14ab9] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:service 25306 [013e689795773670] Launching service
9m/device:plugins:service 25305 [06157df6612b5c22] Launching service
IMP/device:plugins:service 25296 [52006836bede3287] Agent connection ended, attempting to relaunch
INF/device:plugins:touch 25297 [a3a14ab9] Disconnecting from minitouch service
INF/device:plugins:service 25296 [52006836bede3287] Launching service
WRN/device:plugins:touch 25305 [06157df6612b5c22] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25305 [06157df6612b5c22] Disconnecting from minitouch service
IMP/device:plugins:service 25296 [52006836bede3287] Service connection ended, attempting to relaunch
IMP/device:plugins:service 25303 [FC047636] Service connection ended, attempting to relaunch
INF/device:plugins:service 25303 [FC047636] LaunchinWRN/device:plugins:touch 25306 [013e689795773670] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25306 [013e689795773670] Disconnecting from minitouch service
WRN/device:plugins:touch 25300 [0e32a002f1645052] Shell keeping minitouch running ended unexpectedly
g service
INF/device:plugins:touch 25300 [0e32a002f1645052] Disconnecting from minitouch service
WRN/device:plugins:touch 25303 [FC047636] Shell keeping minitouch running ended unexpectedly
WRN/device:plugins:touch 25302 [aa9443f6] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 25302 [aa9443f6] Disconnecting from minitouch service
INF/device:plugins:touch 25303 [FC047636] Disconnecting from minitouch service
INF/device:plugins:service 25296 [52006836bede3287] Launching service
FTL/util:lifecycle 25302 [aa9443f6] Forward shell ended; we shall share its fate
WRN/device:plugins:touch 25296 [52006836bede3287] Shell keeping minitouch running ended unexpectedly
FTL/util:lifecycle 25305 [06157df6612b5c22] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25302 [aa9443f6] Shutting down due to fatal error
FTL/util:lifecycle 25305 [06157df6612b5c22] Shutting down due to fatal error
INF/device:plugins:touch 25296 [52006836bede3287] Disconnecting from minitouch service
WRN/device:plugins:touch 25301 [565347b5] Shell keeping minitouch running ended unexpectedly
FTL/util:lifecycle 25295 [RB042046] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25295 [RB042046] Shutting down due to fatal error
INF/device:plugins:touch 25301 [565347b5] Disconnecting from minitouch service
FTL/util:lifecycle 25296 [52006836bede3287] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25296 [52006836bede3287] Shutting down due to fatal error
FTL/util:lifecycle 25301 [565347b5] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25301 [565347b5] Shutting down due to fatal error
INF/provider 14788 [*] Device "CB5A2AGTZ3" is now "offline" (was "device")
INF/provider 14788 [*] Device "013e689795773670" is now "offline" (was "device")
INF/provider 14788 [*] Device "06157df6612b5c22" is now "offline" (was "device")
FTL/util:lifecycle 25308 [CB5A2AGTZ3] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25308 [CB5A2AGTZ3] Shutting down due to fatal error
FTL/util:lifecycle 25297 [a3a14ab9] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25294 [ZX1D22B4MV] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25294 [ZX1D22B4MV] Shutting down due to fatal error
FTL/util:lifecycle 25297 [a3a14ab9] Shutting down due to fatal error
FTL/util:lifecycle 25298 [5B17000411] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25298 [5B17000411] Shutting down due to fatal error
INF/provider 14788 [*] Device "aa9443f6" is now "offline" (was "device")
INF/provider 14788 [*] Device "d6656b6a" is now "offline" (was "device")
INF/provider 14788 [*] Device "FC047636" is now "offline" (was "device")
INF/provider 14788 [*] Device "a3a14ab9" is now "offline" (was "device")
INF/provider 14788 [*] Device "565347b5" is now "offline" (was "device")
INF/provider 14788 [*] Device "52006836bede3287" is now "offline" (was "device")
INF/provider 14788 [*] Device "0e32a002f1645052" is now "offline" (was "device")
INF/provider 14788 [*] Device "RB042046" is now "offline" (was "device")
INF/provider 14788 [*] Device "ZX1D22B4MV" is now "offline" (was "device")
INF/provider 14788 [*] Lost device "5B17000411" (device)
INF/provider 14788 [*] Shutting down device worker "5B17000411"
INF/provider 14788 [*] Lost device "0f680bfc" (offline)
INF/provider 14788 [*] Lost device "CB5A1XN5M8" (offline)
INF/provider 14788 [*] Lost device "ZX1D22B4MV" (offline)
INF/provider 14788 [*] Shutting down device worker "ZX1D22B4MV"
INF/provider 14788 [*] Cleaning up device worker "aa9443f6"
INF/provider 14788 [*] Cleaning up device worker "06157df6612b5c22"
FTL/util:lifecycle 25299 [d6656b6a] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25299 [d6656b6a] Shutting down due to fatal error
FTL/util:lifecycle 25303 [FC047636] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25306 [013e689795773670] Forward shell ended; we shall share its fate
FTL/util:lifecycle 25303 [FC047636] Shutting down due to fatal error
FTL/util:lifecycle 25306 [013e689795773670] Shutting down due to fatal error
INF/provider 14788 [*] Cleaning up device worker "5B17000411"
INF/provider 14788 [*] Cleaning up device worker "ZX1D22B4MV"
INF/provider 14788 [*] Lost device "0e32a002f1645052" (offline)
FTL/util:lifecycle 25300 [0e32a002f1645052] Forward shell ended; we shall share its fate
INF/provider 14788 [*] Shutting down device worker "0e32a002f1645052"
FTL/util:lifecycle 25300 [0e32a002f1645052] Shutting down due to fatal error
INF/provider 14788 [*] Lost device "RB042046" (offline)
INF/provider 14788 [*] Shutting down device worker "RB042046"
INF/provider 14788 [*] Lost device "FC047636" (offline)
INF/provider 14788 [*] Shutting down device worker "FC047636"
INF/provider 14788 [*] Lost device "aa9443f6" (offline)
INF/provider 14788 [*] Shutting down device worker "aa9443f6"
INF/provider 14788 [*] Lost device "d6656b6a" (offline)
INF/provider 14788 [*] Shutting down device worker "d6656b6a"
INF/provider 14788 [*] Lost device "CB5A2AGTZ3" (offline)
INF/provider 14788 [*] Shutting down device worker "CB5A2AGTZ3"
INF/provider 14788 [*] Lost device "06157df6612b5c22" (offline)
INF/provider 14788 [*] Shutting down device worker "06157df6612b5c22"
INF/provider 14788 [*] Lost device "52006836bede3287" (offline)
INF/provider 14788 [*] Shutting down device worker "52006836bede3287"
INF/provider 14788 [*] Lost device "013e689795773670" (offline)
INF/provider 14788 [*] Shutting down device worker "013e689795773670"
INF/provider 14788 [*] Lost device "a3a14ab9" (offline)
INF/provider 14788 [*] Shutting down device worker "a3a14ab9"
INF/provider 14788 [*] Lost device "565347b5" (offline)
INF/provider 14788 [*] Shutting down device worker "565347b5"
INF/provider 14788 [*] Cleaning up device worker "RB042046"
INF/provider 14788 [*] Cleaning up device worker "52006836bede3287"
INF/provider 14788 [*] Cleaning up device worker "a3a14ab9"
INF/provider 14788 [*] Cleaning up device worker "565347b5"
INF/provider 14788 [*] Cleaning up device worker "CB5A2AGTZ3"
INF/provider 14788 [*] Cleaning up device worker "d6656b6a"
INF/provider 14788 [*] Cleaning up device worker "013e689795773670"
INF/provider 14788 [*] Cleaning up device worker "FC047636"
INF/provider 14788 [*] Gracefully killing device worker "5B17000411"
INF/provider 14788 [*] Gracefully killing device worker "ZX1D22B4MV"
INF/provider 14788 [*] Cleaning up device worker "0e32a002f1645052"
INF/provider 14788 [*] Gracefully killing device worker "0e32a002f1645052"
INF/provider 14788 [*] Found device "ZX1D22B4MV" (offline)
INF/provider 14788 [*] Found device "RB042046" (offline)
INF/reaper 14787 [reaper001] Device "ZX1D22B4MV" is present
INF/provider 14788 [*] Registered device "ZX1D22B4MV"
INF/provider 14788 [*] Device "ZX1D22B4MV" is now "unauthorized" (was "offline")
INF/provider 14788 [*] Device "ZX1D22B4MV" is now "device" (was "unauthorized")
INF/reaper 14787 [reaper001] Device "RB042046" is present
INF/provider 14788 [*] Registered device "RB042046"
INF/provider 14788 [*] Device "RB042046" is now "device" (was "offline")
INF/provider 14788 [*] Found device "52006836bede3287" (offline)
INF/provider 14788 [*] Found device "0f680bfc" (offline)
INF/provider 14788 [*] Found device "06157df6612b5c22" (offline)
INF/provider 14788 [*] Found device "0e32a002f1645052" (offline)
INF/provider 14788 [*] Found device "a3a14ab9" (offline)
INF/provider 14788 [*] Found device "565347b5" (offline)
INF/provider 14788 [*] Found device "d6656b6a" (offline)
INF/provider 14788 [*] Found device "5B17000411" (offline)
INF/provider 14788 [*] Found device "04d86162a2438995" (offline)
INF/provider 14788 [*] Found device "CB5A1XN5M8" (offline)
INF/provider 14788 [*] Found device "FC047636" (offline)
INF/reaper 14787 [reaper001] Device "52006836bede3287" is present
INF/provider 14788 [*] Registered device `"52006836bede3287"

**Please run `stf doctor` and paste the output here.**

INF/util:doctor 25376 [*] OS Arch: x64
INF/util:doctor 25376 [*] OS Platform: darwin
INF/util:doctor 25376 [*] OS Platform: 16.4.0
INF/util:doctor 25376 [*] Using Node 8.2.1
INF/util:doctor 25376 [*] Using RethinkDB client 2.3.3
INF/util:doctor 25376 [*] Using ZeroMQ 4.2.2
INF/util:doctor 25376 [*] GraphicsMagick 1.3.26
INF/util:doctor 25376 [*] Local ADB 1.0.39
Installed as /usr/local/bin/adb

/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.0.39
Installed as /usr/local/bin/adb

    at new SemVer (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1100:15)
    at Function.satisfies (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1149:16)
    at unsupportedVersion (/usr/local/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:143:7
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)

**Comment by sorccu** [comment]
We do not support Macs in production. They're a pain and and a waste of
everyone's time.

**Comment by viktors89** [comment]
Thanks for the reply @sorccu 
I will see if I can get a linux!

**Comment by sorccu** [comment]
As mentioned earlier this is a common issue on Macs when you have a large (usually 8+) number of devices connected. Either get more Macs or switch to Linux and the PCIe card we recommend. Closing.
