### ISSUE TITLE
Some guidelines in order to use devices remotely

### ISSUE THREAD

**Issue by kalw** [openstf/stf#66]
Hi there,

Is there any way or clues on how to continue to manage devices once USB removed ?

-- 
Regis A. Despres

**Comment by sorccu** [comment]
Can you clarify what kind of guidance you're looking for?

**Comment by kalw** [comment]
Hey,

Thanks for the prompt answer. I'm looking for a way to configure adb into stf in order to join device wirelessly =)


-- 
Regis A. Despres

**Comment by jonalmeida** [comment]
@kawl STF recognizes devices via adb (e.g. `adb devices`) so you can try something like [adb over wifi][1] to setup your device, and then `adb connect [ip_address]` with your local device IP. 

I'm personally using [WiFi ADB - Debug Over Air][2].

[1]: http://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp
[2]: https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en

**Comment by kalw** [comment]
Thanks for the tip.

I finally get my device to be recognized.
