### ISSUE TITLE
There's a problem that deploying by docker on windows10

### ISSUE THREAD

**Issue by darkmanno6** [openstf/stf#660]
I hava cloned the stf.git and deployed the stf by command ```docker build -t stf:0.0.1 .```in th stf git directory.
When I deploy and build successfully , then I run it by the command ```docker run -it stf:0.0.1```.
However , it shows the error message:
> docker run -it stf:0.0.1
> /usr/bin/env: 'node\r': No such file or directory

It can't be executed successfully. 
Could you help solving the problem?
Thx.

**Comment by sorccu** [comment]
I'm sorry but we have absolutely no time to help with Windows issues. If you use Windows, you're on your own. Perhaps you could try a Linux virtual machine?

**Comment by darkmanno6** [comment]
I have soveld this problem. because the file stf is dos filefomat.
Solution:
install dos2unix , and insert the command ```dos2unix /app/bin/stf && \ ``` before ```cd /app && \```
