### ISSUE TITLE
Accessing `serial and `publicPort` outside the scope.

### ISSUE THREAD

**Issue by 45minutepromise** [openstf/stf#662]
**What is the issue or idea you have?**
I know you don't support any question apart from the scope.
I want to understand how do you get the serial and port information after running the provider, are these a kind of environment variable, I am trying to make it as a pod in the k8s.
Since there is no direct way to provide `--screen-ws-url-pattern "wss://stf.example.org/d/%i/<%= serial %>/<%= publicPort %>/"` apart from environment variable, I don't see any environment variable exposed for `serial` and `publicPort`.

Also, Since I am using an ingress to bind all the services, I am still a bit confused with provider being being a part of ingress.

Any suggestion will be appreciated, Thanks!

**Comment by 45minutepromise** [comment]
@sorccu @vbanthia Any suggestion here guys?

**Comment by sorccu** [comment]
I'm not 100% sure what you're asking but I think you believe that you're
supposed to replace those values. It's a pattern (or template), you're
supposed to leave it like that. The values are variables that are passed to
the template.

**Comment by 45minutepromise** [comment]
@sorccu
I currently have 2 issues:
- If I hard code the serial number for provider, then only it gets registered and starts to provide, but fails at the websocket connection.`failed: Error during WebSocket handshake: Unexpected response code: 400`, I still have an operable greyed out screen.
- If I give the provider any other name apart from serial number of device - it just gets filtered out.

**Comment by sorccu** [comment]
Well that seems like some sort of a configuration issue then.

**Comment by 45minutepromise** [comment]
And this happens only in the case of creating it as a replication controller in k8s If I make provider  as a daemon service on the machine, it provides correctly - 'That's why I am trying to understand, how I can get this in k8s'

**Comment by sorccu** [comment]
Ok, I've never deployed STF on kubernetes so I can't really help you with
that.

You could try posting the exact config and units you're using here. Perhaps
someone will spot something.

**Comment by sorccu** [comment]
Closing as requested information has not been provided.
