### ISSUE TITLE
Is it possible to run a test on a number of devices at the same time?

### ISSUE THREAD

**Issue by ricardo-valtierra** [openstf/stf#663]
First of all, thank you for your great software.
It has been a really great source of help, and I'm looking for an option to install the same APK and run the same test on a group of selected devices from the STF panel. Is there a way to do this?

Thanks in advance.

**Comment by sorccu** [comment]
That would be a task for other software. STF only provides remote access to
devices; it doesn't run any tests.

**Comment by ricardo-valtierra** [comment]
Ok, Thank You.

Now I've been trying to use STF API to install an APK on several devices simultaneously,  but unsuccessfully. Is there any kind of tutorial for this?

Thanks in advance

**Comment by sorccu** [comment]
Either set up and use your own domain name or use an IP address.
