### ISSUE TITLE
Showing 'Disconnected' when i access the device other than stf hosted machine 

### ISSUE THREAD

**Issue by mrajendrac** [openstf/stf#665]
Hi All,

I able to setup the STF successfully on my mini MAC and able to access it from local host. I am facing the issue when i am trying to connect the STF from other machine using the stf hosted machine IP, it is always showing 'DisConnected' popup even though the device is plugged in and the device is ready to use.

Regards,
RajendraC

**Comment by thinkhy** [comment]
Did you add command arguments --pubic-ip and --allow-remote when you started STF locally?

 `stf local --public-ip  YOUR_PUBLIC_IP  --poorxy-port 80 --allow-remote`

Or you can check your network panel in your browser and identify which URL is not accessible.
