### ISSUE TITLE
Cannot access OpenSTF inside a LAN

### ISSUE THREAD

**Issue by thuanpv** [openstf/stf#666]
Hello,
I successfully setup OpenSTF on a machine following the installation guide at https://github.com/openstf/stf. I can use OpenSTF on this machine by accessing 127.0.0.1:7100 using mock authentication. However, when I try to access the device test farm from another machine on the same network (by typing IP_ADDRESS:7100 where IP_ADDRESS is the address of the machine on which OpenSTF has been installed), I get the error message "This site can't be reached" and on the URL bar of the web browser I see this URL "localhost:7100/auth/mock".
I would like to get some suggestion on configuring OpenSTF so it is accessible from other machines on the same network.
Thanks,
Thuan

**Comment by sorccu** [comment]
Sounds like you've misconfigured it, you should have used the `--public-ip` option to let STF know which IP you'd like to use.

**Comment by thuanpv** [comment]
Oh, my bad. It works now. Thank you very much for your prompt reply.

**Comment by sorccu** [comment]
Good!
