### ISSUE TITLE
stf local --public-ip XXXXXXXX --allow-remote &  

### ISSUE THREAD

**Issue by sgjeff** [openstf/stf#669]
ERROR in ./res/app/app.js
Module not found: Error: Cannot resolve module 'angular-route' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app
 @ ./res/app/app.js 3:2-26

ERROR in ./res/auth/mock/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-route' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/auth/mock/scripts
 @ ./res/auth/mock/scripts/entry.js 5:2-26

ERROR in ./res/auth/ldap/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-route' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/auth/ldap/scripts
 @ ./res/auth/ldap/scripts/entry.js 5:2-26

ERROR in ./res/app/app.js
Module not found: Error: Cannot resolve module 'angular-touch' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app
 @ ./res/app/app.js 4:2-26

ERROR in ./res/auth/mock/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-touch' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/auth/mock/scripts
 @ ./res/auth/mock/scripts/entry.js 6:2-26

ERROR in ./res/auth/ldap/scripts/entry.js
Module not found: Error: Cannot resolve module 'angular-touch' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/auth/ldap/scripts
 @ ./res/auth/ldap/scripts/entry.js 6:2-26

ERROR in ./res/web_modules/gettext/index.js
Module not found: Error: Cannot resolve module 'angular-gettext' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/gettext
 @ ./res/web_modules/gettext/index.js 1:0-26

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'bootstrap/dist/css/bootstrap.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 1:0-43

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'components-font-awesome/css/font-awesome.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 5:0-55

ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'font-lato-2-subset' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 7:0-29

ERROR in ./res/web_modules/angular-hotkeys/index.js
Module not found: Error: Cannot resolve module 'angular-hotkeys/build/hotkeys.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-hotkeys
 @ ./res/web_modules/angular-hotkeys/index.js 1:0-44

ERROR in ./res/web_modules/angular-hotkeys/index.js
Module not found: Error: Cannot resolve module 'angular-hotkeys/build/hotkeys.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-hotkeys
 @ ./res/web_modules/angular-hotkeys/index.js 3:0-43

ERROR in ./res/web_modules/ui-bootstrap/index.js
Module not found: Error: Cannot resolve module 'angular-bootstrap/ui-bootstrap-tpls' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/ui-bootstrap
 @ ./res/web_modules/ui-bootstrap/index.js 1:0-53

ERROR in ./res/web_modules/angular-borderlayout/index.js
Module not found: Error: Cannot resolve module 'angular-borderlayout/src/borderLayout.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-borderlayout
 @ ./res/web_modules/angular-borderlayout/index.js 1:0-51

ERROR in ./res/web_modules/angular-borderlayout/index.js
Module not found: Error: Cannot resolve module 'angular-borderlayout/src/borderLayout.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-borderlayout
 @ ./res/web_modules/angular-borderlayout/index.js 2:0-52

ERROR in ./res/web_modules/angular-xeditable/index.js
Module not found: Error: Cannot resolve module 'angular-xeditable/dist/js/xeditable.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-xeditable
 @ ./res/web_modules/angular-xeditable/index.js 1:0-49

ERROR in ./res/web_modules/angular-xeditable/index.js
Module not found: Error: Cannot resolve module 'angular-xeditable/dist/css/xeditable.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-xeditable
 @ ./res/web_modules/angular-xeditable/index.js 2:0-51

ERROR in ./res/app/components/stf/device/device-service.js
Module not found: Error: Cannot resolve module 'oboe' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/device
 @ ./res/app/components/stf/device/device-service.js 1:11-26

ERROR in ./res/app/control-panes/dashboard/clipboard/index.js
Module not found: Error: Cannot resolve module 'angular-elastic' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/control-panes/dashboard/clipboard
 @ ./res/app/control-panes/dashboard/clipboard/index.js 3:0-26

ERROR in ./res/app/components/stf/common-ui/notifications/index.js
Module not found: Error: Cannot resolve module 'angular-animate' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/common-ui/notifications
 @ ./res/app/components/stf/common-ui/notifications/index.js 1:0-26

ERROR in ./res/app/components/stf/common-ui/table/index.js
Module not found: Error: Cannot resolve module 'ng-table/dist/ng-table' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/common-ui/table
 @ ./res/app/components/stf/common-ui/table/index.js 2:0-40

ERROR in ./res/app/components/stf/common-ui/enable-autofill/index.js
Module not found: Error: Cannot resolve module 'angular-cookies' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/common-ui/enable-autofill
 @ ./res/app/components/stf/common-ui/enable-autofill/index.js 1:0-26

ERROR in ./res/web_modules/ng-context-menu/index.js
Module not found: Error: Cannot resolve module 'ng-context-menu/dist/ng-context-menu' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/ng-context-menu
 @ ./res/web_modules/ng-context-menu/index.js 1:0-47

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/rect.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 3:0-29

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/packer.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 4:0-31

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/item.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 5:0-29

ERROR in ./res/app/components/stf/angular-packery/index.js
Module not found: Error: Cannot resolve module 'packery/js/packery.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/angular-packery
 @ ./res/app/components/stf/angular-packery/index.js 6:14-46

ERROR in ./res/app/settings/general/local/index.js
Module not found: Error: Cannot resolve module 'angular-bootstrap/ui-bootstrap-tpls' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/settings/general/local
 @ ./res/app/settings/general/local/index.js 1:0-28

ERROR in ./res/web_modules/ng-file-upload/index.js
Module not found: Error: Cannot resolve module 'ng-file-upload/angular-file-upload-shim' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/ng-file-upload
 @ ./res/web_modules/ng-file-upload/index.js 1:0-50

ERROR in ./res/web_modules/ng-file-upload/index.js
Module not found: Error: Cannot resolve module 'ng-file-upload/angular-file-upload' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/ng-file-upload
 @ ./res/web_modules/ng-file-upload/index.js 2:0-45

ERROR in ./res/app/components/stf/logcat/logcat-service.js
Module not found: Error: Cannot resolve module 'underscore.string/index' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/logcat
 @ ./res/app/components/stf/logcat/logcat-service.js 2:9-37

ERROR in ./res/web_modules/angular-growl/index.js
Module not found: Error: Cannot resolve module 'angular-growl-v2/build/angular-growl.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-growl
 @ ./res/web_modules/angular-growl/index.js 1:0-50

ERROR in ./res/app/components/stf/common-ui/modals/fatal-message/index.js
Module not found: Error: Cannot resolve module 'angular-route' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/common-ui/modals/fatal-message
 @ ./res/app/components/stf/common-ui/modals/fatal-message/index.js 1:0-24

ERROR in ./res/web_modules/angular-ladda/index.js
Module not found: Error: Cannot resolve module 'angular-ladda/src/angular-ladda' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/angular-ladda
 @ ./res/web_modules/angular-ladda/index.js 3:0-42

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'jquery' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 1:0-17

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'd3' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 3:0-13

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'epoch/dist/css/epoch.min.css' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 4:0-39

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'epoch/dist/js/epoch.min.js' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 5:0-37

ERROR in ./res/web_modules/epoch/index.js
Module not found: Error: Cannot resolve module 'ng-epoch' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/web_modules/epoch
 @ ./res/web_modules/epoch/index.js 6:0-19

ERROR in ./res/app/components/stf/angular-draggabilly/index.js
Module not found: Error: Cannot resolve module 'draggabilly' in /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/res/app/components/stf/angular-draggabilly
 @ ./res/app/components/stf/angular-draggabilly/index.js 1:18-40
ERR/middleware:webpack 3979 [*] Bundle has errors
INF/webpack:config 3979 [*] Build progress 100% (complete)

**Comment by sorccu** [comment]
Can't really help you with this because it's an installation issue. However, I've just released v3.0.0 on NPM, so perhaps installing that would work better.

**Comment by mheins** [comment]
I'm having a similar issue, have you discovered the source of the problem?
