### ISSUE TITLE
what's mean of  code 1

### ISSUE THREAD

**Issue by sgjeff** [openstf/stf#670]
ryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
FTL/util:lifecycle 11076 [A02AECPB2E3T4] Shutting down due to fatal error
INF/provider 10924 [*] Cleaning up device worker "A02AECPB2E3T4"
# **ERR/provider 10924 [*] Device worker "A02AECPB2E3T4" died with code 1**
INF/provider 10924 [*] Restarting device worker "A02AECPB2E3T4"

**Comment by sorccu** [comment]
You haven't posted the actual error, which is above those lines.

**Comment by sgjeff** [comment]
FTL/device 14370 [A02AECPB2E3T4] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
FTL/util:lifecycle 14370 [A02AECPB2E3T4] Shutting down due to fatal error
INF/provider 12986 [*] Cleaning up device worker "A02AECPB2E3T4"
ERR/provider 12986 [*] Device worker "A02AECPB2E3T4" died with code 1



Do you know YunOS？The error on YunOS by Alibaba.

**Comment by sorccu** [comment]
Sounds like you have the same issue as some other devices. It's a setting.
Look for the issue about adding Xiaomi devices to STF. Use that and the
linked issues as a guide for finding the auto-start setting. Then update us
when you know.

**Comment by sgjeff** [comment]
I found a solution.The error on YunOS by Alibaba,Use the following steps:

adb uninstall jp.co.cyberagent.stf 
adb install d:/xxx/STFService.apk 
adb shell am start -n jp.co.cyberagent.stf/.IdentityActivity
adb shell am startservice  -n jp.co.cyberagent.stf/.Service
