### ISSUE TITLE
Version 3.0.0 not available on docker hub

### ISSUE THREAD

**Issue by koral--** [openstf/stf#672]
**What is the issue or idea you have?**
Version 3.0.0 is not released to docker hub, latest update was about a month ago: https://hub.docker.com/r/openstf/stf/ while on GitHub releases page or npm there is v 3.0.0 published 5 days ago.

**Please provide the steps to reproduce the issue.**
Go to https://hub.docker.com/r/openstf/stf/tags/

**What is the expected behavior?**
Version 3.0.0 is available on docker hub.

**Comment by vbanthia** [comment]
Looks like dockerhub build trigger is not working. Will trigger manually for now.

**Comment by vbanthia** [comment]
You can find both `latest` & `v3.0.0` image on docker hub. Somehow, automatic build trigger was off and because of that images were not building. It should be fine now. 

Thanks for reporting.
