### ISSUE TITLE
Orientation issue: landscape not work

### ISSUE THREAD

**Issue by zoejiang2015** [openstf/stf#676]
**What is the issue or idea you have?**
I have set up stf and connect to devices successfully.  But on the device control page: the landscape icon is not working for me. 

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Right now I have tried 3 devices, nexus4, galaxy s4, galaxy s5, the landscape not work for all of them

**Please provide the steps to reproduce the issue.**
Select one device on the devices list, then on detail page click on landscape icon. Device is still portrait.

**What is the expected behavior?**
Device screen should change to Landscape.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
No error shows up. or on browser debug panel, nothing shows up.

**Please run `stf doctor` and paste the output here.**

**Comment by zoejiang2015** [comment]
Hi sorccu,

thank you for your quit comment.  but it's not working for me. any idea about it? 

**stf doctor** result: 
INF/cli:doctor 35364 [*] OS Arch: x64
INF/cli:doctor 35364 [*] OS Platform: darwin
INF/cli:doctor 35364 [*] OS Platform: 14.5.0
INF/cli:doctor 35364 [*] Using Node 6.10.1
INF/cli:doctor 35364 [*] Using ZeroMQ 4.2.2
INF/cli:doctor 35364 [*] Using RethinkDB 2.3.6
INF/cli:doctor 35364 [*] Using GraphicsMagick 1.3.26
INF/cli:doctor 35364 [*] Using ADB 1.0.39
INF/cli:doctor 35364 [*] Using ProtoBuf 3.3.2

**Comment by sorccu** [comment]
What is the exact command you use to start stf

**Comment by zoejiang2015** [comment]
I tried this two: 
> stf local --public-ip 10.2.21.145  --allow-remote --lock-rotation;
> stf local --lock-rotation

**Comment by sorccu** [comment]
It should work. It has always worked on samsung devices, too.

Start from the assumption that it works. Then, try changing your
environment in various ways (e.g. use a different browser) and see if
anything changes.

**Comment by zoejiang2015** [comment]
It fixed today. I really don't know what's wrong. Yesterday I tried various browsers and update my node version, but didn't work.   Anyway, really appreciate your help, sorccu.

**Comment by Rabusek** [comment]
I think I know what could be the issue here - I had similiar situation, thinking what could be wron, in the end it turned out... S8 is not supporting landscape mode on home screen. I noticed that when I opened the browser and the rotation suddenly changed.

Hope that helps someone with similiar problem :)
