### ISSUE TITLE
USB devices randomly disconnecting themselves every few seconds

### ISSUE THREAD

**Issue by Rabusek** [openstf/stf#677]
**What is the issue or idea you have?**
USB devices randomly disconnecting themselves

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
No matter the devices, it was working well on 3-4 devices, then suddenly when I plugged two more it started to constantly restart - even unplugging the other ones does not fix the issue

**Please provide the steps to reproduce the issue.**
1. Plug 3-4 devices
2. Start STF
3. Plug two more

**What is the expected behavior?**
They should work

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
https://pastebin.com/fj02PxEy

**Please run `stf doctor` and paste the output here.**
N/A, using docker, and while doing that it throws errors that are unrelated (like "adb is missing" while I'm able to fully use the devices)

![chrome_2017-08-17_13-02-20](https://user-images.githubusercontent.com/10826482/29409579-30f853c4-834d-11e7-86e3-1bfd7f219ff8.png)
![chrome_2017-08-17_13-02-09](https://user-images.githubusercontent.com/10826482/29409578-30f7c364-834d-11e7-813b-e916f88bda7b.png)

**Comment by sorccu** [comment]
This is in the README. Hardware issues are no joke. Get better hardware.

**Comment by Rabusek** [comment]
I bought hardware specifically following the README. G4560 (so newest gen CPU) and B250M motherboard, along with SSD and 8gb of rams. Also top-end usb hubs, active, powered from power outlet.

**Comment by sorccu** [comment]
And what's the exact model of the hub?

**Comment by Rabusek** [comment]
http://www.tp-link.com.pl/products/details/cat-5688_UH700.html - UH700 TP Link, you can't even get a more expensive one in here. Also, I've been playing with STF a year or two ago, and it worked up to 10 devices on mac (!), so should work here too I guess?

One more thing - I'm still waiting for the StarTech usb controller, but I think 6 devices should not restart themselves

**Comment by sorccu** [comment]
That hub is no good. It comes with a power adapter that's able to provide
12V*2A=24W. Even if the hub supported battery charging spec 1.1 or 1.2, a
device may use up to 5V*1.5A=7.5W, though usually 1A would be closer. As
you can see it's impossible for the hub to provide enough power. In the
manual, it even says: For best performance, the connected devices should
not exceed a combined current of 8A for UH720 (5A for UH700).


It's also highly unlikely that the hub actually supports BC, so even in
that sense it's just no good. Even ignoring the total output issue, it may
be unable to provide enough power for even a single power hungry device.


It's not about the price... it's about specs. You should return the hub or
throw it away.

**Comment by Rabusek** [comment]
@sorccu big thanks for this support that you didn't even had to provide - I have a few of those hubs already unfortunately (they did work with mac up to 12 devices), so for now I'll just plug less devices per hub and then import the pluggable from US.

Thanks!

**Comment by sorccu** [comment]
That's the thing with USB hardware issues - sometimes things work for a while but aren't stable long term. I'm not sure where you're located but you should have other options than buying from the US, see http://plugable.com/products/usb2-hub7bc/. Also, it doesn't have to be that exact hub, but it needs to have similar specs.

Do note that you could also have issues with your other components. Right now the hub is the only component that's obviously bad but who knows? Having the latest and greatest isn't necessarily a guarantee of anything either - older Intel processors used to have enough resources to support 50+ phones connected simultaneously, but now you're limited to 8-12 without a PCIE card. It's a huge pain honestly as soon as you try to connect more devices than an average consumer would.

Your motherboard could also have a USB chipset that has quirks in Linux. That's why it would be best to get the PCIE card to minimize the variables. And again, note that there are differences between PCIE cards, you have to choose one with the right specs.

**Comment by Rabusek** [comment]
Sure, but who has the resources to test out all the USB Hubs and usb extension cards out there? ;) You guys (or just you?) did a great job handpicking two best options for both hubs and extension cards. 

My StarTech PCIe card should arrive next week, and I just ordered the pluggable usb 2.0 hub, so hopefully it'll sort out at least those problems I face now.

Thanks!

**Comment by Rabusek** [comment]
Just in case someone has similiar issue - I was making a research what's wrong with UH700/720. Turns out, for some reason, in some cases, it tends to restart every 30 seconds (rough estimate of how often my devices were kicked off stf):

https://ubuntuforums.org/showthread.php?t=2201564

Removing extension cord should help. Also, it's basically 4 port device with... another hub plugged into one of its ports. Nice engineering TP-Link ;)

**Comment by Rabusek** [comment]
One (really) last tip, that could help someone - I wasn't able to fix the 3.0 ports, BUT, after turning off ALL USB options in bios and, using powertop, in tunables, selecting autosupsend as "bad" resolved the issue completely. Even with the mentioned hubs, I was able to connect 24 devices (3x7 + 3 ports) and everything is super stable.

![2017-08-21_00-49-53](https://user-images.githubusercontent.com/10826482/29499140-b5606574-860a-11e7-9a57-a364c6f58eca.png)

**Comment by sorccu** [comment]
Yes, BIOS settings can help sometimes. However, the settings themselves
depend heavily on the motherboard and they can be labelled in various ways,
or more commonly not be present at all. We will therefore under no
circumstance provide BIOS advice as that would be a complete nightmare.

However, if you have the skills to look into the settings by yourself, then
it can sometimes work out. Glad you found a way.

Do keep in mind that the stability could only be temporary, though.

**Comment by Rabusek** [comment]
@sorccu sure, that's why I'm setting up the proper USB controller and using the pluggable hub, which is much more capable, for more power consuming devices (like tablets and bigger phones). I've left this info here also in case someone will have similiar problem - so you can always reroute him (or he can find this in google or STF issues listing)

**Comment by C14427818** [comment]
Hi I am using this hub https://shop.okluge.de/icy-box-ib-hub1703-qc3-7-port-usb-3.0-hub-mit-3x-laden.html?sPartner=adwords&gclid=EAIaIQobChMIk8HBvtXO3gIVEpSyCh3v0A-DEAQYBSABEgKdrPD_BwE. I am testing the phones with appium and after 3 or for tests the phones disconnect. Wondering if it is this hub. Cheers.

**Comment by entomber** [comment]
Thank you @Rabusek.  I had a somewhat similar issue with the Plugable USB3-HUB7BC.  All connected devices would disconnect and reconnect every few minutes.  Disabling autosuspend resolved it for me.

**Comment by direc85** [comment]
> One (really) last tip, that could help someone - I wasn't able to fix the 3.0 ports, BUT, after (...) using powertop, in tunables, selecting autosupsend as "bad" resolved the issue completely.

Thank you so much!

I'm trying to flash my Sony Xperia XA2 Ultra and having used `powertop` the device *does not* disconnect after I run `flashboot devices`. I'm going to spread this tip, thanks again!

**Comment by Rabusek** [comment]
Glad it still helps someone after 3 years! That reminds me i need to set my STF up again after i moved out 2 times since 2017.

**Comment by Wokir** [comment]
Hello everyone. I have 2 questions about connecting multiple android devices to a PC at the same time. 
1. Can 20, 30 or more devices be connected to a PC via Wi-Fi and identified by adb? If so, please tell me the way.
2. If the wireless connection does not work out how to solve the problem for me using USB hubs. What active USB hubs will solve the problem of unstable connection of devices to a PC? 
If I need to configure the system, please explain me how to do it. Thanks in advance.
