### ISSUE TITLE
domain in auth-url, websocket-url, and --app-url useless

### ISSUE THREAD

**Issue by lishuai0214** [openstf/stf#678]
I I find that auth-url, websocket-url, and --app-url useless in STF, the browser knows which domain it visit STF from, if we give a fixed domain , accessing the **same** STF from **two** domains is very difficult, I think we can just give /auth/mock/ instead of https://stf.example.org/auth/mock/

**Comment by sorccu** [comment]
They might not have the same domain. Additionally, there may be cases where
you do not have an HTTP request to take the values from.

Either way this is very unlikely to change unless someone provides a pull
request for it.
