### ISSUE TITLE
Wherefrom the STF is getting device info like OS, SDK version etc?

### ISSUE THREAD

**Issue by risinek** [openstf/stf#679]
Hi, 
I'm trying to customize the STF to our internal needs, and I need to fetch more details about device and show it in device detail.. But I can't figure out, wherefrom the STF is getting the informations like OS, SDK, Platform, HW details? Do I need to customize the mobile app STF, so it will send those informations, or can it be done from STF app without altering mobile app codes?

**Comment by sorccu** [comment]
Your question is too broad. You need to ask something more specific.

There is no single source. Some are provided by the APK whereas some just
taken off of 'adb shell getprop'.

**Comment by risinek** [comment]
'adb shell getprop' is what I'm looking for, but I can't find it in STF codes anywhere to modify it to my needs

**Comment by sorccu** [comment]
Search for getProperties.

**Comment by risinek** [comment]
Ok, thanks for you help.. Anyway I was not able to figure out, how to alter the adb shell command to return Knox SDK version.. 
This is the command I want to use `adb shell getprop net.knox.shareddevice.version`

**Comment by sorccu** [comment]
I can't help you with that. If you can't figure out how to retrieve that
property, you'll probably also need help in figuring out how to store it in
the database and how to display it in the UI, which would be way too time
consuming.

I would recommend trying to change existing version field first. Just
replace it with that property. Once you gain some confidence with that,
perhaps you'll be able to find a way to add the rest of the properties, too.

**Comment by risinek** [comment]
Yep, thats what I thought, just wanted to be sure, there is no easy way to do it 👍  Thanks a lot..
