### ISSUE TITLE
How to deal with the file of 'nginx.conf' and nginx.service? Who can give  me a hand,thanks.

### ISSUE THREAD

**Issue by yuancc** [openstf/stf#68]
Thanks for the great sharing. I have tried to deploy it on real servers for several days,but now I meet a question, I can not take it work when I input the URL in my browser,there will nothing(Unable to connect) I think there is something wrong in the file of 'nginx.conf'.

1. I create the the file of '/srv/nginx/nginx.conf' by myself,and I have pulled the docker image of nginx:1.7.10

2. I have started all of the units active(running), I used my host's IP (10.240.154.173:7100)instead of https://stf.example.org/ in all of the units and the file 'nginx.conf'. 

3. I don't know how to create certs,so I can't use the https , I have commented some codes in the '/srv/nginx/nginx.conf' about https.

4. I have changed the code like ' server 192.168.255.100:3100 max_fails=0;'to ' server 10.240.154.173:3100 max_fails=0;'

5. It will be change to 10.240.154.173:7100 if I input 10.240.154.173:80 in  browser,it can shows the nginx.conf have worked.But why there is nothing in 10.240.154.173:7100?
6. The rest of the file '/srv/nginx/nginx.conf'is like doc/DEPLOYMENT.md .Then the nginx.service delete the code like
ConditionPathExists=/srv/ssl/stf.example.org.crt
ConditionPathExists=/srv/ssl/stf.example.org.key
ConditionPathExists=/srv/ssl/dhparam.pem
and
  -v /srv/ssl/stf.example.org.crt:/etc/nginx/ssl/cert.pem:ro \
  -v /srv/ssl/stf.example.org.key:/etc/nginx/ssl/cert.key:ro \
  -v /srv/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro \

7. Now I can see the change of RethinkDB from 'localhost:8080' if I link devices to host.

Who can tell me how to do it? Thanks.

**Comment by sorccu** [comment]
Sorry for the late response. The deployment docs unfortunately had many mistakes (see #76 if interested) and were updated a while ago to be more complete. Closing this ticket for now.
