### ISSUE TITLE
android 8.0 phone cannot run ，help，please！

### ISSUE THREAD

**Issue by hzy729** [openstf/stf#680]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Not supported yet. There is already an issue about Android O. Do not make duplicates.
