### ISSUE TITLE
cannot debug remotely

### ISSUE THREAD

**Issue by FuningChen** [openstf/stf#681]
**What is the issue or idea you have?**
I want to control my devices on a computer with STF while the devices are connected to another computer.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Nope. It happens all the time maybe cause I have made some mistakes.

**Please provide the steps to reproduce the issue.**
There are two computers running CentOS 7, A's IP is 172.17.11.111 and B's is 172.17.11.112.
1. A runs `stf local --public-ip 172.17.11.111 --allow-remote`
2. A runs 
`stf provider --name localhost.localdomain --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 172.17.11.111 --storage-url http://localhost:7100/--vnc-initial-size 600x800 --allow-remote`

**What is the expected behavior?**
A can see the devices remotely which are connected to B.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
There are no errors or warnings, but it last with "INF/provider 8656 [*] Tracking devices" and then have no response.

**Please run `stf doctor` and paste the output here.**
INF/cli:doctor 8799 [*] OS Arch: x64
INF/cli:doctor 8799 [*] OS Platform: linux
INF/cli:doctor 8799 [*] OS Platform: 3.10.0-514.26.2.el7.x86_64
INF/cli:doctor 8799 [*] Using Node 6.11.2
INF/cli:doctor 8799 [*] Using ZeroMQ 4.1.2
INF/cli:doctor 8799 [*] Using RethinkDB 2.3.6
INF/cli:doctor 8799 [*] Using ADB 1.0.39
INF/cli:doctor 8799 [*] Using ProtoBuf 3.3.0
INF/cli:doctor 8799 [*] Using GraphicsMagick 1.3.25

**Thanks for your attention!**

**Comment by FuningChen** [comment]
It seems that the problem is because multiple providers, but how can I solve this problem?
If I only run the second code, I cannot access the STF web and the browser only says "unable to connect".

**Comment by sorccu** [comment]
First of all stf local is for development only, but assuming you run the
provider on another machine, it should work. Your connect-sub and
connect-push options should point to the machine where stf is running, not
localhost. Your storage url is wrong, too. Also, I believe you mislabelled
your commands, but just to be sure I'll just say that you cannot have stf
local and stf provider running on the same machine.

I would suggest you look at the deployment guide for ideas, though you'll
have to do things a bit differently if you insist on using stf local.

In general, we do not help with configuration issues, so please try very
hard to get it running by yourself and only as a last resort ask us.

**Comment by FuningChen** [comment]
Thank you for replying so fast. But there are still something I feel confused.

I corrected my codes and run the provider where stf is running, but the problem is still unsolved.
Should I run something on the computer that the devices are connected and why I still cannot open 172.17.11.112(IP of the computer running stf):7100 for I think my stf have well-configured?

**Comment by sorccu** [comment]
Keep trying. Like I said I don't usually help with configuration issues
because it would likely waste an hour or more of my life. Use the
deployment guide as a rough guide for figuring out what options you want to
use.

**Comment by FuningChen** [comment]
OK. Thank you all the same.

**Comment by FuningChen** [comment]
Now I only run the code below
`stf provider --name localhost.localdomain --min-port 7400 --max-port 7700 --connect-sub tcp://172.17.11.112:7114 --connect-push tcp://172.17.11.112:7116 --group-timeout 900 --public-ip 172.17.11.112 --storage-url http://172.17.11.112:7100/ --adb-host 172.17.11.111 --adb-port 5037 --vnc-initial-size 600x800 --allow-remote`

and it gave me the error
**Unhandled rejection Error: connect EHOSTUNREACH 172.17.11.111:5037**
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

What's the matter with TCP?

**Comment by sorccu** [comment]
While that can be made to work, you should almost never use --adb-host and
--adb-port unless you know 100% what you're doing. It's not the way the
system was meant to operate.
