### ISSUE TITLE
ERR/cli:doctor 3046 [*] Unexpected error checking ZeroMQ: Error: Module version mismatch. Expected 48, got 47.

### ISSUE THREAD

**Issue by yuzhidi** [openstf/stf#683]
brew upgrade zmq
Error: zmq 4.2.2 already installed
$ ./bin/stf doctor
INF/cli:doctor 3046 [*] OS Arch: x64
INF/cli:doctor 3046 [*] OS Platform: darwin
INF/cli:doctor 3046 [*] OS Platform: 16.7.0
INF/cli:doctor 3046 [*] Using Node 6.9.4
ERR/cli:doctor 3046 [*] Unexpected error checking ZeroMQ: Error: Module version mismatch. Expected 48, got 47.
INF/cli:doctor 3046 [*] Using RethinkDB 2.3.6
INF/cli:doctor 3046 [*] Using GraphicsMagick 1.3.25
INF/cli:doctor 3046 [*] Using ProtoBuf 3.2.0
INF/cli:doctor 3046 [*] Using ADB 1.0.39

**Comment by yuzhidi** [comment]
I do not know what is wrong

**Comment by vbanthia** [comment]
Delete `node_modules` folder and reinstall dependencies with `npm install`

**Comment by yuzhidi** [comment]
thx,
