### ISSUE TITLE
What is the maximum devices can connect to 1 openSTF host?

### ISSUE THREAD

**Issue by TuHuynhVan** [openstf/stf#684]
I read to this: https://github.com/openstf/stf#recommended-hardware

But I'm not sure we have information about maximum device connected to that recommended hardware.

Please help me to confirm that.
Thank @sorccu so much!

**Comment by sorccu** [comment]
Please do not mention me directly. Someone rlse might answer.

The limit depends entirely on your hardware. It can be as low as 8 unless
you get the PCIE card.

**Comment by TuHuynhVan** [comment]
Thank you for your answer!
