### ISSUE TITLE
npm update , build jpegturbo fail, libtool: unrecognized option `-static'

### ISSUE THREAD

**Issue by yuzhidi** [openstf/stf#685]
CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/transupp.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatadst-tj.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatasrc-tj.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/simd/jsimd_x86_64.o
  LIBTOOL-STATIC Release/libjpeg-turbo.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libjpeg-turbo.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/stf/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/stf/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/stf/node_modules/jpeg-turbo/lib/binding/node-v48-darwin-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=/Users/stf/node_modules/jpeg-turbo/lib/binding/node-v48-darwin-x64

------------
$ which libtool
/usr/local/bin/libtool

libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sorccu** [comment]
Seems that you have the GNU `libtool` installed on OS X. You should probably use the `libtool` that comes with Xcode instead. It should be located in `/usr/bin/libtool` which should forward it to `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool` or similar.

**Comment by tavurth** [comment]
First I had the homebrew libtool installed, which does not accept the `-static` parameter.

```
brew unlink libtool
Unlinking /usr/local/Cellar/libtool/2.4.6_1... 20 symlinks removed
```

Next I had an auto-generated `libtool` at my `/usr/local/bin/libtool`

```
$ which libtool
/usr/local/bin/libtool

$ rm -rf /usr/local/bin/libtool
$ which libtool
/usr/bin/libtool
```

Compiling `node-sass` now works correctly.

**Comment by greenzeal** [comment]
@tavurth thanks man! it worked also for building through command line xcode

**Comment by thijstriemstra** [comment]
If you don't want to delete any files, and potentially mess up your system, temporarily switch to the `/usr/bin/libtool` and install your package:

```
$ export PATH=/usr/bin/:$PATH
$ npm install node-opus -D
```

**Comment by olowoseun** [comment]
Had a similar experience while trying to install a Gatsby starter theme. Apparently, I have MAMP installed on my MacOS Mojave which had the lib tool installed here /Applications/MAMP/Library/bin/libtool. So the only thing I had to do differently from the steps above was just to replace $ rm -rf /usr/local/bin/libtool with $ rm -rf /Applications/MAMP/Library/bin/libtool

**Comment by andlrc** [comment]
A quick hack could be to change your environment variable PATH, something like this might do the trick:

```
PATH="/usr/bin:$PATH" npm ...
```

or 

```
PATH="/usr/bin:$PATH" yarn ...
```
