### ISSUE TITLE
Device Control link redirecting to device list page

### ISSUE THREAD

**Issue by bisena** [openstf/stf#687]
**Whenever I click on a web link to a device for ex:  http://x.x.x.x:7100/auth/mock/#!%2Fcontrol%2Fxxxxxxxx it asks me for Name and Email Id and once I enter I am taken to Device list page rather that that particular device control screen. Am I using wrong link to access device or is it a bug?**

**Comment by sorccu** [comment]
That's the way it works right now.

**Comment by sorccu** [comment]
For now, this behavior won't change, though we may accept a PR.
