### ISSUE TITLE
stf-processor can not start, and Could not connect to 172.17.0.2:28015, operation timed out,help me

### ISSUE THREAD

**Issue by 1102592040** [openstf/stf#688]
stf-processor can not start ,  flowing
![image](https://user-images.githubusercontent.com/31344510/29717563-338dc9e8-89e2-11e7-8d35-ac15e9cd6ab7.png)
logs  ， flowing
![image](https://user-images.githubusercontent.com/31344510/29717492-f1f14f96-89e1-11e7-92ac-306942d4b29f.png)
command ， flowing
![image](https://user-images.githubusercontent.com/31344510/29717595-52518f90-89e2-11e7-99e5-658823cc23c2.png)
![image](https://user-images.githubusercontent.com/31344510/29717626-6262101c-89e2-11e7-87f3-4c574da3cf3d.png)
![image](https://user-images.githubusercontent.com/31344510/29717642-6fdeb7fe-89e2-11e7-8597-e316bd622f70.png)

everything i have try，but it not success ，please help me，thank you

**Comment by sorccu** [comment]
Like it says, it's unable to reach your rethinkdb.

**Comment by 1102592040** [comment]
@sorccu 
thank you your replay
i have a problem about  “SECRET=YOUR_SESSION_SECRET_HERE”，What value should I assign to it？is it the same as "AUTHKEY"，or I'm defining myself？

**Comment by sorccu** [comment]
Please follow the deployment guide. It's a secret that only you know.
