### ISSUE TITLE
While using" SCREEN_JPEG_QUALITY" variable STF boot stuck on "Connecting to 127.0.0.1:28015"

### ISSUE THREAD

**Issue by Rabusek** [openstf/stf#690]
**What is the issue or idea you have?**
While using SCREEN_JPEG_QUALITY variable STF boot process stops on 
INF/db 17225 [*] Connecting to 127.0.0.1:28015
(pressumably DB connection)

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
N/A, devices do not load.

**Please provide the steps to reproduce the issue.**
1. Start STF with ie. 
./stf local screen-jpeg-quality 40 
or 
./launcher local --public-ip 192.168.1.83 STF_LOCAL_SCREEN_JPEG_QUALITY 40

**What is the expected behavior?**
screen_jpeg_quality variable should be set to 40 and STF should boot

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
Nope, no errors. If an instance was running without the variable, devices will load, but they will not show anything on screen, and after a short while will be kicked out
INF/reaper 17201 [reaper001] Reaping device "ce011711a418990e01" due to heartbeat timeout
INF/reaper 17201 [reaper001] Reaping device "a285daa5" due to heartbeat timeout
INF/reaper 17201 [reaper001] Reaping device "LGV700db999815" due to heartbeat timeout
INF/reaper 17201 [reaper001] Reaping device "cd1753ee" due to heartbeat timeout
INF/reaper 17201 [reaper001] Reaping device "e7572a5c" due to heartbeat timeout

**Workaround**
I simply edited out stf/lib/cli/provider/index.js and stf/lib/cli/device/index.js files adding proper values.

**Attachment**
Loading with and without the variable.
![2017-08-27_19-50-47](https://user-images.githubusercontent.com/10826482/29752574-11298326-8b61-11e7-99bf-039558a2e8a5.gif)

**Comment by sorccu** [comment]
You're using the option and environment variable incorrectly.
