### ISSUE TITLE
User authentication to access the devices.

### ISSUE THREAD

**Issue by mrajendrac** [openstf/stf#691]
Hi Team,

I have successfully configured STF in my MAC mini and able to access it remotely, however when i access it remotely it is asking only the username and email id. I do not see any authentication.

Could you please some one guide me how to give access to the devices using authentication, it would be great if you can point me to some examples.

Thanks in advance
RajendraC

**Comment by sorccu** [comment]
See the deployment guide. Other than that, we don't have time to provide more assistance.
