### ISSUE TITLE
Continuously trying to connect to an emulator which does not exist

### ISSUE THREAD

**Issue by PanteonAdmin** [openstf/stf#695]
Hello,

First of all, thanks for your good work.

We have a small problem: It is continuously tries to connect an emulator which does not exist. 

> NF/provider 16748 [*] Lost device "emulator-5564" (offline)
INF/provider 16748 [*] Found device "emulator-5564" (offline)
INF/provider 16748 [*] Registered device "emulator-5564"
INF/reaper 16747 [reaper001] Device "emulator-5564" is present
INF/provider 16748 [*] Lost device "emulator-5564" (offline)
INF/provider 16748 [*] Found device "emulator-5564" (offline)
INF/reaper 16747 [reaper001] Device "emulator-5564" is present
INF/provider 16748 [*] Registered device "emulator-5564"
INF/provider 16748 [*] Lost device "emulator-5564" (offline)
INF/provider 16748 [*] Found device "emulator-5564" (offline)
INF/reaper 16747 [reaper001] Device "emulator-5564" is present
INF/provider 16748 [*] Registered device "emulator-5564"
INF/provider 16748 [*] Lost device "emulator-5564" (offline)
INF/provider 16748 [*] Found device "emulator-5564" (offline)
INF/reaper 16747 [reaper001] Device "emulator-5564" is present
INF/provider 16748 [*] Registered device "emulator-5564"

..... loops like that...

I tried to remove this device from rethinkdb but it did not change anything.

$ adb devices -l
List of devices attached
f069fef20351a313       device usb:2174976X product:gts28vewifixx model:SM_T713 device:gts28vewifi
52036d10ec4ea3f9       device usb:2166784X product:j7xeltetur model:SM_J710FQ device:j7xelte

$ stf doctor
INF/cli:doctor 16808 [*] OS Arch: x64
INF/cli:doctor 16808 [*] OS Platform: darwin
INF/cli:doctor 16808 [*] OS Platform: 16.7.0
INF/cli:doctor 16808 [*] Using Node 8.4.0
INF/cli:doctor 16808 [*] Using ZeroMQ 4.2.2
INF/cli:doctor 16808 [*] Using RethinkDB 2.3.6
INF/cli:doctor 16808 [*] Using GraphicsMagick 1.3.26
INF/cli:doctor 16808 [*] Using ProtoBuf 3.4.0
INF/cli:doctor 16808 [*] Using ADB 1.0.39

**Comment by sorccu** [comment]
STF grts that information from ADB. So ADB thinks that you have an emulator there - perhaps you really do? Can't really do anything about that right now, though there's a pull request that allows you to exclude devices.
