### ISSUE TITLE
The version of "bluebird" in STF 3.1 is not consistent with that in adbkit-apkreader 2.1.2

### ISSUE THREAD

**Issue by thinkhy** [openstf/stf#696]
For the latest version of STF(3.1), the package.json shows bluebird is 2.10.1:

        **"bluebird": "^2.10.1",**
        "adbkit-apkreader": "^2.1.2"

In the modlue of "adbkit-apkreader 2.1.2", it shows bluebird has been upgraded to 3.4.7:

          "dependencies": {
              **"bluebird": "^3.4.7",**
              "debug": "~0.7.4",
              "yauzl": "^2.7.0"
          },

So after deploying the STF v3.1, the problem was encountered when trying to install APK package:
        
        ERR/storage:plugins:apk 13930 [*] Unable to read manifest of "4f92bf05-283e-40d9-850e-d80eca3deec2" 
       **TypeError: Promise.fromCallback is not a function**
          at ApkReader._open (/Users/song/work/stf/node_modules/adbkit-apkreader/lib/apkreader.js:24:22)
          at ApkReader.usingFileStream (/Users/song/work/stf/node_modules/adbkit-apkreader/lib/apkreader.js:66:19)
         at ApkReader.usingFile (/Users/song/work/stf/node_modules/adbkit-apkreader/lib/apkreader.js:34:19)
         at ApkReader.readManifest (/Users/song/work/stf/node_modules/adbkit-apkreader/lib/apkreader.js:102:19)
         at /Users/song/work/stf/lib/units/storage/plugins/apk/task/manifest.js:5:19
         From previous event:
            at module.exports (/Users/song/work/stf/lib/units/storage/plugins/apk/task/manifest.js:4:36)
            at runCallback (timers.js:672:20)
            at tryOnImmediate (timers.js:645:5)
            at processImmediate [as _immediateCallback] (timers.js:617:5)
            ... ...

Seems the function of "fromCallback is introduced in 3.x version of bluebird, so STF modules which still depends on bluebird 2.x can not work.

Also I attempted to upgrad bluebird to 3.x for STF 3.1, but still hit the problem in lifecycle related function:

     resolver.promise.cancellable is not a function ...

It's because [Cancellation](http://bluebirdjs.com/docs/api/cancellation.html) has been redesigned for bluebird 3.x. The symptom is that the program gets stuck with the message: "INF/util:lifecycle 15277 [*] Winding down for graceful exit"

**Comment by sorccu** [comment]
Did you use yarn or npm to install the dependencies?

**Comment by thinkhy** [comment]
Yes, I tried to use 'npm install' and 'npm link' to install the dependencies, also tried to upgrade bluebird manually with the command "npm install bluebird@3.4.7"

**Comment by sorccu** [comment]
So, the stf repository is still supposed to use v2 (v3 won't work), and adbkit-apkreader should be using v3. I'm not sure why but it sounds like you only have one version installed. What does your `node_modules/adbkit-apkreader/node_modules/bluebird/package.json` look like?

**Comment by thinkhy** [comment]
Initially the directory `node_modules/adbkit-apkreader/node_modules/bluebird/ was not existed.  I issued command `npm install bluebird@3.4.7` to install bluebird v3 manually. Now thing goes well and I can install apk through STF UI. 
Thanks!

BTW,  is there any plan to upgrade  bluebird or  use native Promise interface in STF itself?

**Comment by sorccu** [comment]
It would be great if we could upgrade, however we rely too much on cancellation and progression which are both deprecated.

**Comment by sorccu** [comment]
So I'm not sure what exactly happened here but I've just done a full reinstall of my modules and can confirm that `node_modules/adbkit-apkreader/node_modules/bluebird/package.json` was there, and the version was 3.5.0. `node_modules/bluebird/package.json` was 2.11.0. Everything should be fine.

**Comment by thinkhy** [comment]
It might be a env problem. I did following steps in my dev env on Macbook:
   1. Merge the code of v3.1.0 with my customized code based on 2.1
   2. Issue the command "cnpm install" (cnpm is using private npm registry from taobao.com)
   3. Open web page of STF and encounter the problem caused by incompatible bluebird version
   4. try to issue the command "npm install" to update modules using official npm registry, the problem still occurs, the dir `node_modules/adbkit-apkreader/node_modules/bluebird/package.json` can't be located 
   5. issue the command "cd node_modules/adbkit-apkreader/&&cnpm install bluebird@3.4.7" to install bluebird v3 for apkreader manually.  Then the problem resolved.
