### ISSUE TITLE
STF Public  

### ISSUE THREAD

**Issue by tares003** [openstf/stf#700]
Hi guys, any support would be appreciated as I am new. I have spent hours and hours searching but I couldn't find anything. Hopeless! I want to  make publicly access-able so they can use the Public IP address access the STF.

I have tried port forwarding on my router but it redirects top local ip (192.168.1.9:7100) but I want make publicly access able . When I type in the public IP with the port (x.x.x.x:7100) it directs me to (http://localhost:7100/auth/mock/). I have also tried to NGrok still the same. 

Any help would be appreciated.

Thank you all.

**Comment by vbanthia** [comment]
As mentioned in the [README](https://github.com/openstf/stf#running)
> If you want to access STF from other machines, you can add the --public-ip option for quick testing.
>```bash
>stf local --public-ip <your_internal_network_ip_here>
>```

**Comment by tares003** [comment]
@vbanthia it only works internal network not outside, I have opened the ports from 7000-25000. <your_internal_network_ip_here>
should this be the public ip or internal IP.

**Comment by sorccu** [comment]
Do the real deployment then, as specified in the deployment guide. If you
set it up correctly you can access the system from a public address.

**Comment by OKNoah** [comment]
> Do the real deployment then, as specified in the deployment guide. If you set it up correctly you can access the system from a public address.
> […](#)

I'd thank you for specifics on this board answer.
