### ISSUE TITLE
Integrity checksum failed in npm install

### ISSUE THREAD

**Issue by yangguang0405** [openstf/stf#704]
**What is the issue or idea you have?**
I got the following error when running npm.

npm ERR! code EINTEGRITY
npm ERR! sha1-yPxiAcf0DdCJQbh8CFdnOGpnmsw= integrity checksum failed when using sha1: wanted sha1-yPxiAcf0DdCJQbh8CFdnOGpnmsw= but got sha1-QqerEPTFvpQj+/AS9PGovYNfNL4=. (212467 bytes)

I'm running Ubuntu 16.04 with node v8.4.0 and npm  v5.3.0. Here're more details from npm log:

21563 verbose Linux 4.10.0-28-generic
21564 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
21565 verbose node v8.4.0
21566 verbose npm  v5.3.0
21567 error code EINTEGRITY
21568 error sha1-yPxiAcf0DdCJQbh8CFdnOGpnmsw= integrity checksum failed when using sha1: wanted sha1-yPxiAcf0DdCJQbh8CFdnOGpnmsw= but got sha1-QqerEPTFvpQj+/AS9PGovYNfNL4=. (212467 bytes)
21569 verbose exit [ 1, true ]

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

1. git clone https://github.com/openstf/stf.git
2. cd stf
3. npm install

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Nothing in your logs points to this being an STF issue.

**Comment by yangguang0405** [comment]
Yes, this is an issue from npm. I got this fix by clearing npm's cache.
