### ISSUE TITLE
Unable to start stf local. Getting Error Message.

### ISSUE THREAD

**Issue by prasb** [openstf/stf#705]
When i enter stf local after installation.
 I get the following error message. I have pasted full logs below this error message. 

Logs:-

INF/db 2888 [*] Connecting to 127.0.0.1:28015
/usr/local/lib/node_modules/stf/lib/cli websocket

Options:
  -h, --help          Show help.                                       [boolean]
  -V, --version       Show version.                                    [boolean]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to.
                                                              [array] [required]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.
                                                              [array] [required]
  --port, -p          The port to bind to.              [number] [default: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.                       [string] [required]
  --ssid, -i          The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --storage-url, -r   URL to the storage unit.               [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

**/usr/local/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
Use of const in strict mode.
FTL/cli:local 2863 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
/usr/local/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
Use of const in strict mode.
FTL/cli:local 2863 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)**

_Pasting the Full Logs here._
[sudo] password for tauser: 
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli migrate"
INF/db 2866 [*] Connecting to 127.0.0.1:28015
INF/db:setup 2866 [*] Database "stf" already exists
INF/db:setup 2866 [*] Table "users" already exists
INF/db:setup 2866 [*] Table "accessTokens" already exists
INF/db:setup 2866 [*] Table "vncauth" already exists
INF/db:setup 2866 [*] Table "devices" already exists
INF/db:setup 2866 [*] Table "logs" already exists
INF/db:setup 2866 [*] Index "users"."adbKeys" already exists
INF/db:setup 2866 [*] Index "accessTokens"."email" already exists
INF/db:setup 2866 [*] Index "vncauth"."response" already exists
INF/db:setup 2866 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 2866 [*] Index "devices"."owner" already exists
INF/db:setup 2866 [*] Index "devices"."present" already exists
INF/db:setup 2866 [*] Waiting for index "users"."adbKeys"
INF/db:setup 2866 [*] Waiting for index "accessTokens"."email"
INF/db:setup 2866 [*] Waiting for index "vncauth"."response"
INF/db:setup 2866 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 2866 [*] Waiting for index "devices"."owner"
INF/db:setup 2866 [*] Waiting for index "devices"."present"
INF/db:setup 2866 [*] Index "devices"."providerChannel" already exists
INF/db:setup 2866 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 2866 [*] Index "users"."adbKeys" is ready
INF/db:setup 2866 [*] Index "accessTokens"."email" is ready
INF/db:setup 2866 [*] Index "devices"."owner" is ready
INF/db:setup 2866 [*] Index "devices"."present" is ready
INF/db:setup 2866 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 2866 [*] Index "vncauth"."response" is ready
INF/db:setup 2866 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli provider --name tauser-VirtualBox --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-temp --port 7102"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 2863 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 2870 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 2870 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 2870 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/triproxy 2869 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 2869 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 2869 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/db 2873 [*] Connecting to 127.0.0.1:28015
INF/db 2876 [*] Connecting to 127.0.0.1:28015
INF/processor 2873 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 2873 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/reaper 2879 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 2879 [reaper001] Reaping devices with no heartbeat
INF/db 2879 [reaper001] Connecting to 127.0.0.1:28015
INF/processor 2876 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 2876 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/reaper 2879 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/poorxy 2906 [*] Listening on port 7100
INF/reaper 2879 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/provider 2882 [*] Subscribing to permanent channel "MnGATzy6TuqbnPcT3Q8XZQ=="
INF/provider 2882 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 2882 [*] Receiving input from "tcp://127.0.0.1:7114"
INF/provider 2882 [*] Tracking devices
INF/auth-mock 2885 [*] Listening on port 7120
INF/storage:plugins:image 2900 [*] Listening on port 7103
INF/storage:plugins:apk 2903 [*] Listening on port 7104
INF/storage:temp 2897 [*] Listening on port 7102
INF/app 2888 [*] Using pre-built resources
INF/app 2888 [*] Listening on port 7105
INF/db 2888 [*] Connecting to 127.0.0.1:28015
/usr/local/lib/node_modules/stf/lib/cli websocket

Options:
  -h, --help          Show help.                                       [boolean]
  -V, --version       Show version.                                    [boolean]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to.
                                                              [array] [required]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.
                                                              [array] [required]
  --port, -p          The port to bind to.              [number] [default: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.                       [string] [required]
  --ssid, -i          The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --storage-url, -r   URL to the storage unit.               [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

/usr/local/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
Use of const in strict mode.
FTL/cli:local 2863 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
INF/cli:local 2863 [*] Shutting down all child processes
INF/util:lifecycle 2869 [app001] Winding down for graceful exit
INF/util:lifecycle 2870 [dev001] Winding down for graceful exit
INF/util:lifecycle 2873 [proc001] Winding down for graceful exit
INF/util:lifecycle 2879 [reaper001] Winding down for graceful exit
WRN/db 2879 [reaper001] Connection closed
INF/util:lifecycle 2876 [proc002] Winding down for graceful exit
INF/util:lifecycle 2882 [*] Winding down for graceful exit
WRN/db 2873 [proc001] Connection closed
INF/util:lifecycle 2885 [*] Winding down for graceful exit
INF/auth-mock 2885 [*] Waiting for client connections to end
INF/util:lifecycle 2888 [*] Winding down for graceful exit

Also I have sudo rethinkdb and started rethinkdb server as well.

tauser@tauser-VirtualBox:~$ sudo rethinkdb
[sudo] password for tauser: 
Running rethinkdb 2.3.6~0xenial (GCC 5.3.1)...
Running on Linux 4.10.0-33-generic x86_64
Loading data from directory /home/tauser/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on driver addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on http addresses: 127.0.0.1, 127.0.1.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "tauser_VirtualBox_g0p" 814aecfb-3052-494c-9c2e-15869a1d5c6e

Machine Details :+1: 
1) Ubuntu 16.04
2) 4GB RAM.

Regards,
Prasanna B

**Comment by sorccu** [comment]
Sounds like your Node.js may be too old. You should have ran `stf doctor` and posted the results here.

**Comment by prasb** [comment]
Hi Sorccu,

Many thanks for your quick reply. I have updated nodejs version. PFB the results. but got different error.

tauser@tauser-VirtualBox:~$ ^C
tauser@tauser-VirtualBox:~$ stf doctor
INF/cli:doctor 2590 [*] OS Arch: x64
INF/cli:doctor 2590 [*] OS Platform: linux
INF/cli:doctor 2590 [*] OS Platform: 4.10.0-33-generic
INF/cli:doctor 2590 [*] Using Node 6.11.3
**ERR/cli:doctor 2590 [*] Unexpected error checking ZeroMQ: Error: Module version mismatch. Expected 48, got 14.**
INF/cli:doctor 2590 [*] Using RethinkDB 2.3.6~0xenial
INF/cli:doctor 2590 [*] Using ProtoBuf 3.4.0
INF/cli:doctor 2590 [*] Using ADB 1.0.32
INF/cli:doctor 2590 [*] Using GraphicsMagick 1.3.23



**Stf local logs**  
Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Module version mismatch. Expected 48, got 14.
FTL/cli:local 2487 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
INF/cli:local 2487 [*] Shutting down all child processes

**Comment by sorccu** [comment]
Uninstall STF and reinstall. Some of the native modules are stuck at the older version you were using before.

**Comment by prasb** [comment]
Thanks Sorccu,

I did a fresh install of STF. Got following error.

Installing STF, Please wait...
/usr/local/bin/stf -> /usr/local/lib/node_modules/stf/bin/stf

> dtrace-provider@0.8.5 install /usr/local/lib/node_modules/stf/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.7.1 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node scripts/install.js


> uws@0.14.5 install /usr/local/lib/node_modules/stf/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> bufferutil@1.3.0 install /usr/local/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/bufferutil/build'

> jpeg-turbo@0.4.0 install /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/build'
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_0 Release/obj/gen/jfdctflt-sse-64.o
/bin/sh: 1: yasm: not found
deps/jpeg-turbo.target.mk:10: recipe for target 'Release/obj/gen/jfdctflt-sse-64.o' failed
make: *** [Release/obj/gen/jfdctflt-sse-64.o] Error 127
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-33-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node --module_name=jpegturbo --module_path=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.10.0-33-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp" "install" **"--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
node-pre-gyp ERR! node -v v6.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node --module_name=jpegturbo --module_path=/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64' (1)
/usr/local/lib
`-- (empty)

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "stf"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10**
npm ERR! code ELIFECYCLE

npm ERR! jpeg-turbo@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpeg-turbo@0.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jpeg-turbo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jpeg-turbo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jpeg-turbo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/protobuf/npm-debug.log
npm ERR! code 1

Following below installation steps as mentioned in the git hub document:-

https://gist.github.com/prasb/458878000d05ae72c0906e7fa4f28708

**Comment by sorccu** [comment]
Just follow the README. You're missing dependencies again. Please stop wasting my time.
