### ISSUE TITLE
How to get the screen of a remote device as a detached window ?

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#706]
It is not an issue but just a question.

I'm using the RestFul API to remote connect to a device and once connected to it I would like to know if there is a way to get its screen as a detached window, that is it means without to login to the OpenSTF GUI ?

I saw that properties returned for each device contain a "display" section with a web socket url value inside, is it possible to use it to reach my goal ?

At provider side, I also saw in log file that a VNC server is started, is it possible to interact with it using a VNC client ?

Thanks.

**Comment by sorccu** [comment]
1. Not really, there kind of is but it doesn't work like that, the user
must be logged in already.
2. Yes if you are willing to write your own rendering code. You can look at
the STF source as an example. We will not help with that, however.
3. Yes and no, it's functional but the client side is unfinished. The steps
you must take to make it work are fairly advanced, I'd rather you didn't
try unless you're very confident in your skills.

**Comment by denis99999** [comment]
Thanks for your answer
