### ISSUE TITLE
npm link throw nine-bootstrap "Module not found" exception

### ISSUE THREAD

**Issue by iqianxing** [openstf/stf#708]
run ```npm link``` cause an exception in console, error log as follow:
```ERROR in ./res/web_modules/nine-bootstrap/index.js
Module not found: Error: Cannot resolve module 'nine-bootstrap/nine-bootstrap.sass' in D:\Projects\stf_orig\res\web_modules\nine-bootstrap
 @ ./res/web_modules/nine-bootstrap/index.js 3:0-45```

**Comment by iqianxing** [comment]
1. I compile nine-bootstrap.sass by node-sass first;
2. Modify the nine-bootstrap index.js:  
``` javascript
// require('nine-bootstrap/nine-bootstrap.sass')
require('nine-bootstrap/nine-bootstrap.css')
```
3. npm link;
4. Run stf;
5. Open the stf on my chrome browser, the font-color on my page is white?

**Comment by iqianxing** [comment]
![screenshot](https://user-images.githubusercontent.com/2938263/30373346-95afb926-98b3-11e7-85c2-845d1c673570.jpg)

**Comment by sorccu** [comment]
Don't compile it by hand, try to figure out why the require is not working
instead.

**Comment by iqianxing** [comment]
I have resolved this problem by rebuilding node-sass. Thank you @sorccu

**Comment by sorccu** [comment]
Good!
