### ISSUE TITLE
Sending an artifact containing apk from GitLab to STF connected devices

### ISSUE THREAD

**Issue by akarsh** [openstf/stf#710]
I want to send the artifact containing apk file
e.g. https://gitlab.com/sakarsh/gitlab-ci-android/-/jobs/31736597/artifacts/download
to STF connected devices.

I went through the wiki and readme in the repository to find out "how the apk file is installed from stf"; but i was not able to find any material.

My initial search through the repository, i found that STF uses an install service
https://github.com/openstf/stf/blob/916d8f751512091aaba6f4ca312d82fbad2dd8b0/lib/units/device/resources/service.js 
to install the apk file.

I worked on small JS projects; so it was hard for me to figure out. what was happening in the file.

Help is appreciated in solving it.

**Comment by hram** [comment]
adb install <apk file path>

**Comment by akarsh** [comment]
@hram 
adb install apk file; is the command line approach. But i want to use the api from stf.
As, i did not understand how stf does it.
![screen shot 2017-09-14 at 10 17 27](https://user-images.githubusercontent.com/845598/30419296-22d9f9c4-9936-11e7-8ecb-1a39a09dd1a6.png)

**Comment by akarsh** [comment]
After some search around openstf repositories. I found the [adbkit](https://github.com/openstf/adbkit) repository fits for my purpose. I am able to understand now how to install an apk file via api.
I will write a tutorial repository on how to use it.

**Comment by hram** [comment]
And this one uses "adb shell pm install APK_FILE" command
I dont understand what wrong with "adb install APK_FILE" ?

**Comment by akarsh** [comment]
You can check my tutorial repository based on adbkit
https://github.com/akarsh/adkit-install-apk-tutorial

I want to install the APK file via URL of the artifact. The adbkit is used
by stf.
