### ISSUE TITLE
Will a server can connect up to a number of mobile phones?

### ISSUE THREAD

**Issue by weikejia** [openstf/stf#717]
Will a server can connect up to a number of mobile phones? USB connected to more than one phone, the USB interface is not enough bandwidth how to solve? In the use of the process, often a mobile phone dropped, what is a good way?

Is there any recommended server model?

**Comment by weikejia** [comment]
How many phones can be connected to a server

**Comment by sorccu** [comment]
Impossible to say, depends on your hardware. Read the README.

**Comment by weikejia** [comment]
Is there a reference value? For example, you increase the use of what configuration, up to the number of mobile phones can support?
thank~

**Comment by sorccu** [comment]
Read the README...
