### ISSUE TITLE
Deploying the STF Docker container

### ISSUE THREAD

**Issue by stephenchinnadorai** [openstf/stf#72]
Would it be possible to get a little more guidance on how to deploy the Docker container for STF provided on Docker Hub? Is it as simple as entering the container and running `npm install -g stf` followed by all the usual commands for installing/building STF in a manual installation, or is there more to it?

Also, is it recommended that RethinkDB is run in a linked Docker container?

**Comment by sorccu** [comment]
Have you seen https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md?
