### ISSUE TITLE
Not able to OnePlusOne 3T to STF in Ubuntu 16.04.1

### ISSUE THREAD

**Issue by pavankumarh14** [openstf/stf#720]
**Not able to OnePlusOne 3T to STF in Ubuntu 16.04.1**

**Attached error in STF output**

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/22715147/30775804-a8e7df7a-a0b8-11e7-9b7a-8f30b3abc31b.png">

**Comment by sorccu** [comment]
You’re using an old version of STF.

**Comment by pavankumarh14** [comment]
@sorccu 
We are using the latest stf version "3.1.0"
Attached screen shot
<img width="533" alt="image" src="https://user-images.githubusercontent.com/22715147/30795342-be70f736-a1ea-11e7-8a50-796ef3543d81.png">

Any help would be appreciated .  Its working fine on MAC with the same version of STF "3.1.0"

**Comment by sorccu** [comment]
I guarantee you're either using an old version or a modified version. The paths in your log screenshot show `stf/vendor/minicap`. That path has not existed for 11 months. You should be seeing `stf/node_modules/minicap-prebuilt` instead.
