### ISSUE TITLE
"Stop using" device cause minimising top activity application

### ISSUE THREAD

**Issue by pwicherski** [openstf/stf#722]
Somehow connected to: #346 #242 
**What is the issue or idea you have?**

I've checked cli.js file and didn't found any flag that would be helpful.
When the session is closed ("stop using" option) for each device, the application which is on the top activity is closed (minimised).

Is there something that I've missed, flag or any other way to leave the application on the top after closing device session?

The case I'm thinking about:
Automated tests are running on the device (for example Espresso). While this is happening I would like to lookup on the device to check if everything is ok. But when I'm leaving the session ("stop using" option) the application is closed (minimised).

I would like that application to be still on top activity then I leave the device session to let the tests run without interruption.

**Comment by sorccu** [comment]
This is because the user could have left something unwanted open that doesn’t let the screen sleep, which is extremely bad for long term battery life.

**Comment by pwicherski** [comment]
Sure. understand. Any clue what can I do about it?
Any suggestion where I should lookup to make a PR with a new flag for example?

**Comment by sorccu** [comment]
It's currently being done [here](https://github.com/openstf/stf/blob/445cfcf0bc025346bcfefae663fcd987285ade85/lib/units/device/plugins/group.js#L106) if that helps.

**Comment by pwicherski** [comment]
Will you guys be ok with a new PR with a new flag to turn this off?

**Comment by sorccu** [comment]
Sure, please submit the PR!

**Comment by sorccu** [comment]
Note that we may or may not need changes but please go ahead.

**Comment by thinkhy** [comment]
I would like to have automation testcase running on device connected with API, so the device is in "automation" status and would not be timedout.
