### ISSUE TITLE
Setting up OpenSTF with HTTPS

### ISSUE THREAD

**Issue by thuanpv** [openstf/stf#724]
I am trying to setup OpenSTF to make it work over HTTPS. However, once I type in the URL https://127.0.0.1:7100 I receive the error message "This site can't be reached". My OpenSTF setup works fine with HTTP.

Anyone has successfully setup OpenSTF with HTTPS? Is there any option to switch between HTTP and HTTPS support? If there is no such option and I need to modify OpenSTF to make it work, could you please give me some guidance -- which component(s) need to be changed and how?
Many thanks

**Comment by sorccu** [comment]
It works fine. You’re supposed to do HTTPS via nginx. STF itself doesn’t and should not know anything about that. The deployment guide gives you some pointers.
