### ISSUE TITLE
Notes content was deleted after restart the STF host

### ISSUE THREAD

**Issue by TuHuynhVan** [openstf/stf#727]
Notes content was deleted after restart the STF host.
I used STF model local.

Did I miss something from configuration note?

**Comment by sorccu** [comment]
Did you perhaps start rethinkdb in a different folder than originally?

**Comment by TuHuynhVan** [comment]
Thanks @sorccu for your quick response. Let me scan through the steps I did to see whether I did that.

**Comment by sorccu** [comment]
Closing as there's no feedback. I will say however that this should not happen, but if it does, it's probably something RethinkDB-related. For example, it's possible for the database to get corrupt, though in that case RethinkDB would usually refuse to start at all.
