### ISSUE TITLE
Xiaomi phone mix 2 resolution adaptation problem

### ISSUE THREAD

**Issue by chunyuong** [openstf/stf#733]
Xiaomi mix 2 resolution is 2160x1080 pixels, the virtual status bar can not be displayed on stf. But Samsung S8 resolution is 2960x1440 pixels, the virtual status bar can be displayed properly.
This is Xiaomi mix2's screenshot on stf:
![image](https://user-images.githubusercontent.com/26139195/31701348-6a5331e4-b402-11e7-87a7-3cc7a687fdcd.png)

This is  Xiaomi mix2's correct screenshot:
![image](https://user-images.githubusercontent.com/26139195/31701427-ec8b30bc-b402-11e7-8a5c-7e288628f8bf.png)

**Comment by sorccu** [comment]
This is a problem that I can't fix without having the device here with me. If possible, please consider asking your company to donate one of those devices (a used one is fine) or donate funds to purchase one.

**Comment by thinkhy** [comment]
Xiao Mix2 is a popular full-screen phone in China. I can get a new device this weekend, will try to debug this problem or provide one for @sorccu to remote-debug this problem.

**Comment by sorccu** [comment]
Somewhat ironically, I hate working on devices remotely while debugging STF. The point of STF is to allow interaction that's as real as possible. I can't really tell what "real" is if I've never even seen the device myself. That combined with painfully slow SSH is usually super annoying and easily takes 3x as long as just having the device on hand would.

Based on the screenshot though, I guess that the Android API STFService uses to retrieve the display size was modified by Xiaomi to not include the software buttons. This could be verified by trying to run minicap with manually modified parameters and seeing if the buttons are actually there. I'm thinking they probably are, but are just cropped out.

**Comment by thinkhy** [comment]
Remote control STF can't used to remote debug itself, from this point of view, STF is not self-host :-)
I get used to using TeamView to do remote debugging, but it's indeed painful to connect across countries, network delays can't be tolerated.

Thanks for your hints, this weekend I will verify if XiaoMi Mix2 crops out the actual size of screen.

**Comment by thinkhy** [comment]
@sorccu The culprit is the absolute height of the available display size retrieved by STFService, related code can be found in /android/view/DisplayInfo.java:

```java
    private void getMetricsWithSize(DisplayMetrics outMetrics, CompatibilityInfo compatInfo,
            Configuration configuration, int width, int height) {
        outMetrics.densityDpi = outMetrics.noncompatDensityDpi = logicalDensityDpi;
        outMetrics.density = outMetrics.noncompatDensity =
                logicalDensityDpi * DisplayMetrics.DENSITY_DEFAULT_SCALE;
        outMetrics.scaledDensity = outMetrics.noncompatScaledDensity = outMetrics.density;
        outMetrics.xdpi = outMetrics.noncompatXdpi = physicalXDpi;
        outMetrics.ydpi = outMetrics.noncompatYdpi = physicalYDpi;

        width = (configuration != null
                && configuration.screenWidthDp != Configuration.SCREEN_WIDTH_DP_UNDEFINED)
                ? (int)((configuration.screenWidthDp * outMetrics.density) + 0.5f) : width;
        height = (configuration != null
                && configuration.screenHeightDp != Configuration.SCREEN_HEIGHT_DP_UNDEFINED)
                ? (int)((configuration.screenHeightDp * outMetrics.density) + 0.5f) : height;

        outMetrics.noncompatWidthPixels  = outMetrics.widthPixels = width;
        outMetrics.noncompatHeightPixels = outMetrics.heightPixels = height;

        if (!compatInfo.equals(CompatibilityInfo.DEFAULT_COMPATIBILITY_INFO)) {
            compatInfo.applyToDisplayMetrics(outMetrics);
        }
    }
```
Width x height retrieved in above code is 1080x1980, but the actual resolution rate is 1080x2160. 

Fortunately the shell command "wm size" can output the correct value:

```
chiron:/data/local/tmp $ wm size
Physical size: 1080x2160
```

So I wrote some code to workaround this problem:

  * Add a new function getResolution in lib/util/devutil.js

```javascript

// get window size (resolution)
devutil.getResolution = function(adb, serial) {
  return new Promise(function(resolve, reject) {
    client.shell(serial, "wm size").timeout(2 * 1000)
      .then(function processAdbOutput(output) {
        var content = ""
        var resolver = Promise.defer()

        function processData(data) {
          content += data
        }

        function errorListener(err) {
          resolver.reject(err)
        }

        function endListener() {
          var res = /(\d+)x(\d+)/.exec(content)
          if (res === null)
            reject("Can't find valid resolution rate")
          else {
            resolve({width: res[1], height: res[2]})  // get matched group
          }
        }

        output.on('data', processData)
        output.on('error', errorListener)
        output.on('end', endListener)

        return resolver.promise.finally(function () {
          output.removeListener('data', processData)
          output.removeListener('error', errorListener)
          output.removeListener('end', endListener)
        })
      })
  })
}

```
  * Invoke devutil.getResolution to get screen size in lib/units/device/plugins/service.js  
 
```javascript
    plugin.getDisplay = function(id) {
      return Promise.join(runServiceCommand(
          apk.wire.MessageType.GET_DISPLAY
        , new apk.wire.GetDisplayRequest(id)
        ), devutil.getResolution(
          adb
        , options.serial)
        )
        .timeout(10000)
        .then(function(data, resolution) {
          var response = apk.wire.GetDisplayResponse.decode(data)

          if (response.success) {
            return {
              id: id
            //, width: response.width
            //, height: response.height
            , width: resolution.width
            , height: resolution.height
            , xdpi: response.xdpi
            , ydpi: response.ydpi
            , fps: response.fps
            , density: response.density
            , rotation: response.rotation
            , secure: response.secure
            , size: Math.sqrt(
                Math.pow(response.width / response.xdpi, 2) +
                Math.pow(response.height / response.ydpi, 2)
              )
            }
          }
          throw new Error('Unable to retrieve display information')
        })
    }
```
Til now STF can support XiaoMi Mix2 perfectly.

![image](https://user-images.githubusercontent.com/140176/31861458-2dc294ce-b6f3-11e7-8f21-d35e9035f6d2.png)

**Comment by sorccu** [comment]
Interesting but I would prefer not calling `wm size` if possible, because there's no guarantee that the output format will be the same on all devices (including ancient ones), and it would be a huge pain to collect enough data to verify whether that's the case or not. It's also not entirely clear whether the value is affected by rotation or not. I'm hoping that there might be another Java method that returns real values...

**Comment by sorccu** [comment]
Btw there's a small bug in the `getResolution` you posted, it uses both `Promise.defer()` and `new Promise()`. The cleanup is tied on the deferred promise but it never gets resolved.

**Comment by thinkhy** [comment]
@sorccu Thank you for reviewing my code! I will fix the bug soon. I've applied the code for almost 90 devices covering 20 brands(Android 4.2~8.0), it works well.

BTW, this week I will contact engineer in XiaoMi to discuss about the issue ...

**Comment by sorccu** [comment]
Alternatively, https://github.com/openstf/minicap/issues/93 might be one way. More crash prone in theory, though.

**Comment by thinkhy** [comment]
OK, I will look into openstf/minicap#93 after work. Seems to introduce more code changes.

**Comment by sorccu** [comment]
Related to #464, the LG V10 has an issue with both `wm size` and `minicap -i`. They both return  1440x2720, which includes the "second screen" at the top of the main screen. Using the full size with minicap results in a black area at the bottom of the screen image and even worse touch coordinates. The public Java API returns 1440x2560, which displays the correct screen area (though the touch coordinate issue is obviously still there).

**Comment by linzhaoqin** [comment]
Xiaomi has [a blog](https://dev.mi.com/console/doc/detail?pId=1160) about this issue, which is written in Chinese. 

It's fine if you don't know Chinese. The solution is to declare the maximum aspect ratio larger than 2.0. Here is the [documentation](https://developer.android.com/guide/practices/screens_support.html#MaxAspectRatio) about how to declare the maximum aspect ratio written by Android team.

I hope it helps.

**Comment by sorccu** [comment]
Well I can’t try it out. @thinkhy?

**Comment by thinkhy** [comment]
@sorccu  I will try it tonight. Thanks @linzhaoqin from XiaoMi.

**Comment by thinkhy** [comment]
@sorccu The problem has been resolved perfectly after adding meta-data below as @linzhaoqin mentioned:

```
<application android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:persistent="true">

      **<meta-data android:name="android.max_aspect"
        android:value="3.0" />**

```

Added two debug log in lib/units/device/plugins/service.js:

```
    plugin.getDisplay = function(id) {
      return runServiceCommand(
          apk.wire.MessageType.GET_DISPLAY
        , new apk.wire.GetDisplayRequest(id)
        )
        .timeout(10000)
        .then(function(data) {
          var response = apk.wire.GetDisplayResponse.decode(data)
          console.log("+++++++++++++ width:", response.width)
          console.log("+++++++++++++ height:", response.height)
```
Then run STF and connect with the Mix2 device, the output is as expected

```
INF/device:plugins:service 28623 [c4700512] Agent says: "InputClient started"
INF/device:plugins:display 28623 [c4700512] Reading display info
+++++++++++++ width: 1080
+++++++++++++ height: 2160
```

Thanks

**Comment by thinkhy** [comment]
@sorccu Can you please merge the code change(AndroidManifest.xml) for full-screen devices into STFService.apk?   Thanks

**Comment by sorccu** [comment]
Sorry I can’t yet - it will be at least another week till I have free time again. Tough times.

**Comment by thinkhy** [comment]
OK, take your time. Please ping me if we need to test the new feature on Chinese brands devices.

**Comment by lishuai0214** [comment]
I met the same problem recently. I guess some manufacturers force return an error resolution because they want the virtual button to be shown forever and not covered by other apps, I think getting resolution from adb command is a good solution.

**Comment by sorccu** [comment]
I've made the change. Can you try master now?

**Comment by thinkhy** [comment]
I've tried the master of STFService.apk, which works very well. Thanks.
