### ISSUE TITLE
How to change 'Location'

### ISSUE THREAD

**Issue by glolsh** [openstf/stf#734]
3.1.0

**What is the issue or idea you have?**
I changed hostname of machine. 
I cleared rethinkdb data, but Location still shown old hostname.
I want to update 'Location'

**Comment by sorccu** [comment]
If you're using `stf local`, use the `--provider` option to set the name. It's supposed to be a descriptive value that tells you where the provider is located, but you can choose whatever.

**Comment by glolsh** [comment]
@sorccu thank you. So if hostname is changed - there is no way to "update" it, only to set manually?

**Comment by sorccu** [comment]
Start stf again with the option you want, then refresh your browser. I’m not 100% sure but it should show up.

**Comment by jachstet-sea** [comment]
You could modify the data in the database directly?

**Comment by glolsh** [comment]
Thanks, issue is resolved.
