### ISSUE TITLE
Bad filtering of Battery Level and Battery Temp

### ISSUE THREAD

**Issue by lukzeg** [openstf/stf#735]
**Description:**
During filtering devices via Battery Level or Battery Temp filer, I noticed, that results for query like:
batteryLevel: > 20

Did not return Android devices passing this criteria. The same issue I observed when I tried to filter devices using this query:
 batteryTemp: >20

STF source code checkout with : d5ab5fd83d2e9a1dab2c61dc42b0ba999a6dbb1a

**Steps to reproduce**
A)
Insert in  input tag with name="deviceFilter" this query:
batteryLevel: >50

**What is the expected behavior?**
We should expect to see only devices which battery level is bigger then 50%. But we see only devices, which body contains 50%.

B)
Insert in  input tag with name="deviceFilter" this query:
batteryTemp: <40

**What is the expected behavior?**
We should expect to see only devices which battery temp is lower then 40°C. But we see only devices, which body contains 40.

**Investigation**:
The problem is mostly connected with using text filtering for both of params: Battery Level and Battery Temp. 
stf/res/app/device-list/column/device-column-service.js: ln340

As we can see both of params are marked as TextCell. To parse them as values we might to add additional extra checking in :
stf/res/app/device-list/column/device-column-service.js: ln340

to parse those data properly by adding this part:
  , filter: function(item, filter) {
      if ( options.title == "Battery Level" || options.title == "Battery Temp" ) {
        //Exception in TextCell. We want to filter after integer values for two columns, Battery Level and Battery Temp
        var remove_unit_character = ''
        switch (options.title){
        case "Battery Level":
          remove_unit_character = "%"
          break
        case "Battery Temp":
          remove_unit_character = "°C"
          break
        }

        var parsed_value = parseInt((options.value(item)).replace(remove_unit_character,''))

        return filterOps[filter.op || '='](
            parsed_value
          , Number(filter.query)
        )
      }
      else{
        return filterIgnoreCase(options.value(item), filter.query)
      }
    }

**Comment by sorccu** [comment]
Interesting. I don’t think we want to hardcode column names but perhaps this should be fixed by maybe introducing a new column type. I’m just happy that someone is actually using the search function :)

May I ask you how many devices you have connected to the system? Sounds like you may have quite a few.

**Comment by lukzeg** [comment]
Hi @sorccu ,

Not to many, only 5, but I thinking about adding few more devices to my environment. I'm just playing around in different locations. I think about adding one more thing , which I'm missing in your framework. 

It will be cool to have possibilities to compute few filters queries for instance:
batteryLevel:>20 AND sdk:>20 AND name: Nexus 5

But I would like to do it everything by baby steps. The fix for filtering I added in PR:
https://github.com/openstf/stf/pull/736
