### ISSUE TITLE
Is it possible install STF services in one host, ADBD-s in other hosts?

### ISSUE THREAD

**Issue by armdev** [openstf/stf#737]
Hello, 

Is it possible to have 3 Servers with installed ADBD and connected devices, and having one main OpenSTF host which is connect to 3 hosts and collect data from ADB ports?
If yes, could you please provide minimum configuration (give multiple adb IP addresses to STF provider. )

Thanks,

**Comment by sorccu** [comment]
That is exactly how STF was meant to run. Read the deployment docs. They may be a bit complex but that's all the help we provide right now.

**Comment by sorccu** [comment]
Actually not exactly. STF does not connect to multiple adb servers. You can run pieces (units) of STF on many machines, and bundle them together into a single UI, which is what the deployment docs are for.

**Comment by armdev** [comment]
Many thanks
