### ISSUE TITLE
"Automation" option does nothing?

### ISSUE THREAD

**Issue by Rup1** [openstf/stf#742]
When I click the "Automation" tab, it asks for my "Store" login (I'm assuming this means my Google Play Store login?). But when I click sign in nothing happens. What is this supposed to do?
![2017-10-27 03 29 29](https://user-images.githubusercontent.com/15389183/32092565-2107143a-bac7-11e7-9f1a-be9fc30a1189.gif)

**Comment by sorccu** [comment]
It never worked reliably, and it hasn't been updated for newer Android versions. Don't use it. It's because it's not possible to add accounts without system permissions, so we tried to do it by emulating UI actions. 

Removing accounts works though.
