### ISSUE TITLE
How touch events are handled after the touch plugin

### ISSUE THREAD

**Issue by thuanpv** [openstf/stf#743]
Hi all,
I can control the flow of the code to handle touch events from its device control pane to the touch plugin (stf/lib/units/device/plugins/touch/index.js). Basically, the frontend calls functions in control-service.js and control-service.js subsequently sends Websocket requests to websocket service. After that, the websocket service creates TouchXYZMessages and passes them to touch service for handling.  However, I don't know how the touch plugin interacts with the real device -- I suspect that eventually, STF needs to send some ADB commands to the device to simulate the events however I cannot find that code.
Could someone please help me on that?
Many thanks

**Comment by sorccu** [comment]
It's in the README, minitouch. Then check out the minitouch README after that.
