### ISSUE TITLE
Where i can find logs for server?

### ISSUE THREAD

**Issue by mrPsycho** [openstf/stf#746]
Hello! 
I'was able to start your amazing app on docker, on remote server...
but, something differs from local machine and i get "500 Internal server error" and on login page i see only this: "**Server error. Check log output.**"

I tried to connect to stf-auth image (`docker exec -i -t stf-auth-3200 /bin/bash`), but i don't see any logs.
is it there a way to get more details?

**Comment by sorccu** [comment]
‘docker logs’ or alternatively journalctl may be more useful if you’re on a systemd machine.

**Comment by mrPsycho** [comment]
poor me. 
thanks!
