### ISSUE TITLE
How to deal with Wi-Fi signal interference?

### ISSUE THREAD

**Issue by kingname** [openstf/stf#747]
**What is the issue or idea you have?**

My phone use 2.4G route to connect router. And if there are more than 15 phones connect to the same Wi-Fi hot point at the same time, then none of the phone can connect to the internet. Because of the signal interference of Wi-Fi

So can you suggest me some method to solve the interference?

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

No, It happen to all phone if there are more than 15 phones.

**Please provide the steps to reproduce the issue.**

Connect more 15 phones to the same Wi-Fi hot point.

**What is the expected behavior?**

All phone should have connected to the internet.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

No Error, Because it is out of stf's business.

**Please run `stf doctor` and paste the output here.**

None

**Comment by sorccu** [comment]
Get a better wifi router, that shouldn’t be an issue at all. Make sure you don’t put the phones in a rack or some other metallic enclosure though, the signal gets pretty bad there. Choose a good channel manually, too.

Also, you can run STF on multiple machines and have them in separate locations if necessary.

**Comment by kingname** [comment]
Thanks for your reply. But in fact I have to setup a cluster in the size of 10000 android phones. So routers make no sense. I have to deal with the signal interference of electromagnetic wave.

**Comment by vbanthia** [comment]
If your are thinking about that scale, this might help you. 

https://code.facebook.com/posts/300815046928882/the-mobile-device-lab-at-the-prineville-data-center/

**Comment by sorccu** [comment]
I’m sure you already know but we can’t help you design that. You should hire an expert at that scale, certainly sounds like you could afford it at least :) Keep it mind that we are merely unpaid contributors to an open source project. We can therefore only afford to spend a very limited time per issue, which isn’t enough to research a massive task like this.

I can only say that STF itself should function fine at that scale, though obviously you’ll need to run it on quite a few machines, and hardware choices are critically important.

I would be interested in hearing on your progress, though.

**Comment by kingname** [comment]
Thanks @sorccu I will do it myself. But can you tell me wether your scale of phone cluster can be handled only by a good router?

**Comment by sorccu** [comment]
We had 99% of the phones on LTE, because that was important to us.

**Comment by kingname** [comment]
Ok Got, LTE is a really excellent solution. But in my country, Phone number must be bound with everyone's ID Card, and every person could have at most 5 Phone number, that is b***s**t.

**Comment by sorccu** [comment]
I’m sure you can get it working with WIFI, but you’ll have to be very careful when positioning the routers and devices. If you have the space, try splitting the devices into multiple locations.

**Comment by kingname** [comment]
Sure. Thanks again.
