### ISSUE TITLE
Device Icons are being displayed as default icons

### ISSUE THREAD

**Issue by yogesh8394** [openstf/stf#748]
Hi,
I am using STF for a while now, but i have observed that for most of the devices it shows the default image. Only in case of Nexus 6P i was able to get the proper device image.
Can any one help me with how to make the desired changes in order to get the specific device image properly.

**Comment by sorccu** [comment]
Fork STF and replace the stf-device-db module with your own. It's too much work for us to keep it up to date.

**Comment by yogesh8394** [comment]
Thanks for the quick response Simo Kinnunen. I have already forked the STF but how can we make changes to the node modules directory stf-device-db module and rebuild it in order to get the updated images of the devices. I tried doing it but in vain. So can you please suggest some way to do it.

**Comment by sorccu** [comment]
Fork the module and change the version to a github url or publish under a different name.
