### ISSUE TITLE
Connection to device unstable

### ISSUE THREAD

**Issue by notauser1** [openstf/stf#750]
I have been trying to use STF to connect to my Android. I am able to connect, sometimes for a few minutes and sometimes only a few seconds. Following are system specs and log output.

PC OS: Ubuntu 16.04 (lxde desktop) 64 bit
PC Browser: Firefox 56 64 bit
Mobile Device: Nexus 6
Mobile OS: 7.1

STF version: 3.1.0
Nodejs version: 7.10.1
ADB version: 1.0.32

Connection is made using a 32' MonoPrice extender USB cable. I have tried with and without a powered USB hub (on the phone side). The hub does not seem to make a difference.

Log output:
INF/provider 6740 [*] Device "ZX1G223ZGH" is now "device" (was "offline")
INF/device:support:push 11287 [ZX1G223ZGH] Sending output to "tcp://127.0.0.1:7116"
INF/device 11287 [ZX1G223ZGH] Preparing device
INF/device:support:sub 11287 [ZX1G223ZGH] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 11287 [ZX1G223ZGH] Subscribing to permanent channel "*ALL"
INF/device:support:properties 11287 [ZX1G223ZGH] Loading properties
INF/device:support:sdk 11287 [ZX1G223ZGH] Supports SDK 25
INF/device:support:abi 11287 [ZX1G223ZGH] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:minicap 11287 [ZX1G223ZGH] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/bin/minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 11287 [ZX1G223ZGH] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-25/minicap.so" as "/data/local/tmp/minicap.so"
INF/device:resources:service 11287 [ZX1G223ZGH] Checking whether we need to install STFService
INF/device:resources:service 11287 [ZX1G223ZGH] Running version check
INF/device:resources:service 11287 [ZX1G223ZGH] STFService up to date
INF/device:plugins:service 11287 [ZX1G223ZGH] Launching agent
INF/device:plugins:service 11287 [ZX1G223ZGH] Agent says: "Listening on @stfagent"
INF/device:plugins:service 11287 [ZX1G223ZGH] Launching service
INF/device:plugins:service 11287 [ZX1G223ZGH] Agent says: "InputClient started"
INF/device:plugins:display 11287 [ZX1G223ZGH] Reading display info
INF/device:plugins:phone 11287 [ZX1G223ZGH] Fetching phone info
INF/device:plugins:identity 11287 [ZX1G223ZGH] Solving identity
INF/device:plugins:solo 11287 [ZX1G223ZGH] Subscribing to permanent channel "VhffyrV0m5bF7RcK4H8AFlXpG84="
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Starting WebSocket server on port 7508
INF/device:resources:minitouch 11287 [ZX1G223ZGH] Installing "/usr/lib/node_modules/stf/node_modules/minitouch-prebuilt/prebuilt/armeabi-v7a/bin/minitouch" as "/data/local/tmp/minitouch"
INF/device:plugins:touch 11287 [ZX1G223ZGH] Touch origin is top left
INF/device:plugins:touch 11287 [ZX1G223ZGH] Requesting touch consumer to start
INF/device:plugins:touch 11287 [ZX1G223ZGH] Launching screen service
INF/device:plugins:touch 11287 [ZX1G223ZGH] Connecting to minitouch service
INF/device:plugins:touch 11287 [ZX1G223ZGH] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 11287 [ZX1G223ZGH] minitouch says: "Type B touch device atmel_mxt_ts (1439x2559 with 16 contacts) detected on /dev/input/event0 (score 2115)"
INF/device:plugins:touch 11287 [ZX1G223ZGH] minitouch says: "Note: hard-limiting maximum number of contacts to 10"
INF/device:plugins:touch 11287 [ZX1G223ZGH] Reading minitouch banner
INF/device:plugins:touch 11287 [ZX1G223ZGH] minitouch says: "Connection established"
INF/device:plugins:vnc 11287 [ZX1G223ZGH] Starting VNC server on port 7510
INF/device:plugins:browser 11287 [ZX1G223ZGH] Loading browser list
INF/device:plugins:browser 11287 [ZX1G223ZGH] Updating browser list
WRN/device:plugins:browser 11287 [ZX1G223ZGH] Unmapped browser "mobi.mgeek.TunnyBrowser"
WRN/device:plugins:browser 11287 [ZX1G223ZGH] Unmapped browser "org.mozilla.focus"
INF/device:plugins:mute 11287 [ZX1G223ZGH] Will not mute master volume during use
INF/device:resources:minirev 11287 [ZX1G223ZGH] Installing "/usr/lib/node_modules/stf/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
INF/device:plugins:forward 11287 [ZX1G223ZGH] Launching reverse port forwarding service
INF/device:plugins:forward 11287 [ZX1G223ZGH] Connecting to reverse port forwarding service
INF/device:plugins:connect 11287 [ZX1G223ZGH] Listening on port 7509
INF/device 11287 [ZX1G223ZGH] Fully operational
INF/provider 6740 [*] Providing all 1 device(s)
IMP/device:plugins:group 11287 [ZX1G223ZGH] Now owned by "none@none.none"
INF/device:plugins:group 11287 [ZX1G223ZGH] Subscribing to group channel "fpX1QyxcQEau01p3AJNnrA=="
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Setting frame producer projection to 922x922
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Requesting frame producer to start
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Launching screen service
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "PID: 5314"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: Using projection 1440x2560@519x922/0"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:241) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:244) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:251) Creating virtual display"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:257) Creating buffer queue"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:262) Creating CPU consumer"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:266) Creating frame waiter"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:270) Publishing virtual display"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (external/MY_minicap/src/minicap_25.cpp:287) Found 7.1 Developer Preview SurfaceComposerClient::setDisplaySurface"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Connecting to minicap service
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder"
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] Reading minicap banner
INF/device:plugins:screen:stream 11287 [ZX1G223ZGH] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
IMP/device:plugins:connect 11287 [ZX1G223ZGH] Remote Connect Started for device "ZX1G223ZGH" at "localhost:7509"
IMP/device:plugins:service 11287 [ZX1G223ZGH] Agent connection ended, attempting to relaunch
INF/device:plugins:service 11287 [ZX1G223ZGH] Launching service
INF/provider 6740 [*] Lost device "ZX1G223ZGH" (device)
INF/provider 6740 [*] Shutting down device worker "ZX1G223ZGH"
INF/provider 6740 [*] Cleaning up device worker "ZX1G223ZGH"
INF/provider 6740 [*] Gracefully killing device worker "ZX1G223ZGH"
IMP/device:plugins:service 11287 [ZX1G223ZGH] Service connection ended, attempting to relaunch
INF/device:plugins:service 11287 [ZX1G223ZGH] Launching service
WRN/device:plugins:touch 11287 [ZX1G223ZGH] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 11287 [ZX1G223ZGH] Disconnecting from minitouch service
FTL/util:lifecycle 11287 [ZX1G223ZGH] Forward shell ended; we shall share its fate
FTL/util:lifecycle 11287 [ZX1G223ZGH] Shutting down due to fatal error
INF/provider 6740 [*] Device worker "ZX1G223ZGH" has retired
INF/provider 6740 [*] Found device "ZX1G223ZGH" (offline)
INF/reaper 6734 [reaper001] Device "ZX1G223ZGH" is present
INF/provider 6740 [*] Registered device "ZX1G223ZGH"
INF/provider 6740 [*] Lost device "ZX1G223ZGH" (offline)
INF/provider 6740 [*] Found device "ZX1G223ZGH" (offline)
INF/reaper 6734 [reaper001] Device "ZX1G223ZGH" is present
INF/provider 6740 [*] Registered device "ZX1G223ZGH"
INF/provider 6740 [*] Lost device "ZX1G223ZGH" (offline)
INF/provider 6740 [*] Found device "ZX1G223ZGH" (offline)
INF/reaper 6734 [reaper001] Device "ZX1G223ZGH" is present
INF/provider 6740 [*] Registered device "ZX1G223ZGH"
INF/provider 6740 [*] Lost device "ZX1G223ZGH" (offline)
INF/provider 6740 [*] Found device "ZX1G223ZGH" (offline)
INF/reaper 6734 [reaper001] Device "ZX1G223ZGH" is present
INF/provider 6740 [*] Registered device "ZX1G223ZGH"
INF/provider 6740 [*] Lost device "ZX1G223ZGH" (offline)

The application will keep looping from Registered/Lost/Found until the usb cable unplugged and plugged back in. Any help is greatly appreciated. I am fairly new to nodejs so if there is something I am missing, please let me know.

Thanks

**Comment by sorccu** [comment]
Hardware issue, can’t do anything about it. Read the README for recommendations. Avoid very long cables.

**Comment by sorccu** [comment]
You should also describe your hardware. Preferably exact model numbers. Not all powered hubs are equal, in fact very few are any good.

**Comment by notauser1** [comment]
I will see what I can find on the hub. When you say it is a 'Hardware issue', can you be more specific? Do you suspect that it is USB/hub related or some other device issue? What is the longest recommended USB cord? I see the one mentioned in the README is only 1.5'.

**Comment by notauser1** [comment]
Sorry, I forgot to mention the phone batt, is only at 33%. Might things work better if the phone has a full charge?

**Comment by sorccu** [comment]
It's a waste of my time to speculate too much, however if you see a device toggle between "device" and "offline" state, it's 99% guaranteed to be a hardware issue. Can't help.

It might become more stable once it's charged, but it might not. Sounds like your hub is unable to provide enough power to it. Read the README.

**Comment by notauser1** [comment]
Thank you for the follow up. I am not trying to achieve stellar performance from the remote device. I have my home office in the basement and do not get cell service in the dungeon. With the help of a BT head set and your UI (using --allow-remote and wifi), I am able to make/receive calls and text messages remotely. 

By trade, I am a certified Penetration Tester so there is a definite possibility of using this solution when performing mobile device testing.  

Thanks again for your help and all of your hard work providing this FOSS solution.

Regards
