### ISSUE TITLE
FTL Error No hosts left to try when run `stf local --public-ip xxxx`

### ISSUE THREAD

**Issue by cuhavp** [openstf/stf#752]
INF/util:procutil 8798 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli migrate"
INF/db 8799 [*] Connecting to 127.0.0.1:28015
INF/db 8799 [*] Unable to connect to 127.0.0.1:28015
FTL/db 8799 [*] No hosts left to try
FTL/util:lifecycle 8799 [*] Shutting down due to fatal error

/usr/local/lib/node_modules/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by sorccu** [comment]
You probably don’t have rethinkdb running. Read the README.

**Comment by cuhavp** [comment]
I tried command `rethinkdb&` but show error log: irectory 'rethinkdb_data' is already in use, perhaps another instance of rethinkdb is using it.

**Comment by sorccu** [comment]
Sounds like you’re doing something wrong. Try rebooting if you can’t figure out what’s causing that.

**Comment by remy-burney-pf** [comment]
Not having rethinkdb running was my issue, thanks !
Ideally a more friendly message would be great.
