### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by pinotao** [openstf/stf#754]
**What is the issue or idea you have?**
run  stf local   failed 
`ERR/cli:doctor 4007 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:`
`Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/9.1.0/darwin/x64/zmq.node
../stf/lib/cli triproxy [name]`

**Please provide the steps to reproduce the issue.**
brew installed , node v9.0.1 installed  , npm  5.5.1 installed
> brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config     
  **done**
> sudo npm install -g stf       
 **done**
> rethinkdb
 **done**
> stf local 
 **exception**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
`chendongtaodeMacBook-Pro:zmq chendongtao$ stf local
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli migrate"
INF/db 4017 [*] Connecting to 127.0.0.1:28015
INF/db:setup 4017 [*] Database "stf" already exists
INF/db:setup 4017 [*] Table "users" already exists
INF/db:setup 4017 [*] Table "accessTokens" already exists
INF/db:setup 4017 [*] Table "vncauth" already exists
INF/db:setup 4017 [*] Table "devices" already exists
INF/db:setup 4017 [*] Table "logs" already exists
INF/db:setup 4017 [*] Index "users"."adbKeys" already exists
INF/db:setup 4017 [*] Index "accessTokens"."email" already exists
INF/db:setup 4017 [*] Index "vncauth"."response" already exists
INF/db:setup 4017 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 4017 [*] Waiting for index "users"."adbKeys"
INF/db:setup 4017 [*] Waiting for index "accessTokens"."email"
INF/db:setup 4017 [*] Waiting for index "vncauth"."response"
INF/db:setup 4017 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 4017 [*] Index "devices"."owner" already exists
INF/db:setup 4017 [*] Index "devices"."present" already exists
INF/db:setup 4017 [*] Index "devices"."providerChannel" already exists
INF/db:setup 4017 [*] Waiting for index "devices"."owner"
INF/db:setup 4017 [*] Waiting for index "devices"."present"
INF/db:setup 4017 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 4017 [*] Index "users"."adbKeys" is ready
INF/db:setup 4017 [*] Index "accessTokens"."email" is ready
INF/db:setup 4017 [*] Index "vncauth"."response" is ready
INF/db:setup 4017 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 4017 [*] Index "devices"."owner" is ready
INF/db:setup 4017 [*] Index "devices"."present" is ready
INF/db:setup 4017 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli provider --name chendongtaodeMacBook-Pro.local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-temp --port 7102"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 4016 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
../stf/lib/cli triproxy [name]

选项：
  -h, --help         Show help.                                           [布尔]
  -V, --version      Show version.                                        [布尔]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                               [字符串] [默认值: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                               [字符串] [默认值: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                               [字符串] [默认值: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                             [字符串] [默认值: "chendongtaodeMacBook-Pro.local"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/9.1.0/darwin/x64/zmq.node
../stf/lib/cli triproxy [name]

选项：
  -h, --help         Show help.                                           [布尔]
  -V, --version      Show version.                                        [布尔]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                               [字符串] [默认值: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                               [字符串] [默认值: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                               [字符串] [默认值: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                             [字符串] [默认值: "chendongtaodeMacBook-Pro.local"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (FTL/cli:local 4016 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
INF/cli:local 4016 [*] Shutting down all child processes
e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/9.1.0/darwin/x64/zmq.node
`

**Please run `stf doctor` and paste the output here.**
`chendongtaodeMacBook-Pro:zmq chendongtao$ stf doctor
INF/cli:doctor 4007 [*] OS Arch: x64
INF/cli:doctor 4007 [*] OS Platform: darwin
INF/cli:doctor 4007 [*] OS Platform: 16.7.0
INF/cli:doctor 4007 [*] Using Node 9.1.0
ERR/cli:doctor 4007 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/9.1.0/darwin/x64/zmq.node
INF/cli:doctor 4007 [*] Using GraphicsMagick 1.3.26
INF/cli:doctor 4007 [*] Using ProtoBuf 3.4.0
INF/cli:doctor 4007 [*] Using ADB 1.0.39
INF/cli:doctor 4007 [*] Using RethinkDB 2.3.6`

**Comment by pinotao** [comment]
I try #250 and #420 solution . but didn't work

**Comment by sorccu** [comment]
Perhaps there were errors when you ran `npm install`? If `rm -rf node_modules && npm install` doesn't work, usually you're either missing a dependency (read the README) or you're missing a complete build environment (like perhaps python 2.7 or a c++ compiler).

**Comment by sorccu** [comment]
Ah... actually, it's more likely because you're using `sudo`. Sometimes, some modules refuse to build if you're root.

I would recommend installing and setting up node via `NVM`, which avoids the usual permission issues. You should **never** have to use `sudo` when running `node` or `npm`. Installing node from a package manager is the worst thing you can do, pretty much. If you're sure you want to do that anyway, you're on your own. However, perhaps https://docs.npmjs.com/getting-started/fixing-npm-permissions might help.

**Comment by pinotao** [comment]
@sorccu  what about handle  run  `stf doctor ` causes the exception after finish  install zpm .

`chendongtaodeMacBook-Pro:zmq chendongtao$ stf doctor
INF/cli:doctor 4542 [*] OS Arch: x64
INF/cli:doctor 4542 [*] OS Platform: darwin
INF/cli:doctor 4542 [*] OS Platform: 16.7.0
INF/cli:doctor 4542 [*] Using Node 9.1.0
ERR/cli:doctor 4542 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/9.1.0/darwin/x64/zmq.node
INF/cli:doctor 4542 [*] Using GraphicsMagick 1.3.26
INF/cli:doctor 4542 [*] Using ADB 1.0.39
INF/cli:doctor 4542 [*] Using ProtoBuf 3.4.0
INF/cli:doctor 4542 [*] Using RethinkDB 2.3.6`

**Comment by sorccu** [comment]
It’s not a magician. Your installation is broken. Do what I said.

**Comment by pinotao** [comment]
I try  reinstall  zeromq with  libsodium  and reinstall stf 。finish this issue

```
brew uninstall zeromq
brew install zeromq --with-libsodium

npm uninstall -g stf 
npm install -g stf
```
you can close the issue
