### ISSUE TITLE
Using Bearer token key for authentication

### ISSUE THREAD

**Issue by thuanpv** [openstf/stf#755]
Hi,
Has anyone tried to authenticate the STF app using the Bearer token key generated by Settings->Keys section? (https://github.com/openstf/stf/blob/master/doc/API.md)

I found the thread #311 helpful (https://github.com/openstf/stf/issues/311) however it requires many settings:

```
export OAUTH_AUTHORIZATION_URL="https://accounts.google.com/o/oauth2/v2/auth"
export OAUTH_TOKEN_URL="https://www.googleapis.com/oauth2/v4/token"
export OAUTH_USERINFO_URL="https://www.googleapis.com/oauth2/v3/userinfo"
export OAUTH_CLIENT_ID="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.apps.googleusercontent.com"
export OAUTH_CLIENT_SECRET="BBBBBBBBBBBBBBBBBBBBBBBB"
export OAUTH_CALLBACK_URL="http://localhost:7100/auth/oauth/callback"
export OAUTH_SCOPE="openid email"

# Now you can just run stf local without the annoying auth options.
stf local --auth-type oauth
```

I am wondering whether I can simplify these settings to make my Bearer token work. My setup has only one user and I don't want to use the mock authentication.

Appreciate your help!

**Comment by vbanthia** [comment]
You are misunderstanding between Bearer Token authentication & oauth authentication here.

Bearer Token authentication is only for accessing REST API. And you can only create these token from STF UI. For browser authentication you will have to use one of the auth which STF provide such as `oauth`, `ldap`, `saml2` etc.

If you think setting up oauth is too much work and you want some minimal security, you can use `basic-auth` instead.  Refer this: https://github.com/openstf/stf/pull/254

**Comment by thuanpv** [comment]
Thank you vabanthia for your explanation. In fact, I did successfully use OAUTH using Google credentials. My issue is that I embed OpenSTF in another app which already has one layer of authentication so I want something simple that allows all users who can login my app successfully can use OpenSTF without the second layer of authentication -- only one account is needed for my app and I can pass the login information in command line, no login screen is needed. I will look into #254 to see whether it can help.

**Comment by thuanpv** [comment]
I tried #254 but it seems that it not what I need. I would need to modify STF myself to disable the login screen (one default user only) or synchronize two authentication layers so that STF authentication layer can use user credentials from my app's login information. 

Many thanks for your support!

**Comment by srohit13** [comment]
@sorccu  : We have set up the Open STF server without Docker settings and we are able to access the STF successfully need your help to understand how we can we limit the access for specified users as we are currently able to access easily through any user name /email id, but we need to provide only access to selected email ids, can you help for the same.
