### ISSUE TITLE
"screen-jpeg-quality" option not available in stf local mode ?

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#761]
Why the `screen-jpeg-quality` option is not available in stf local mode while it is available in stf provider mode ?

**Comment by sorccu** [comment]
1. stf local is for development only, so it doesn’t need to expose all options
2. you can still use an environment variable to set it if you need to.

**Comment by denis99999** [comment]
Shame on me it was obvious :-)
Thanks !
