### ISSUE TITLE
HUAWEI mate 10 devices cannot display full screen

### ISSUE THREAD

**Issue by zhaozhenlei** [openstf/stf#765]
my new huawei mate10 device with  2160x1080 pixels, which  is  a zero bezel huawei product named ALP-AL00 , shows a Non -full screen display on our stf just as my screenshot bellow . and I cannot swipe or click on the screen button either.
BTW: No setting changed after i got my device,except openning USB  debug 
screenshot on stf:
![image](https://user-images.githubusercontent.com/28615244/33362378-2d4121cc-d517-11e7-9d67-01c16989bf7f.png)

**Comment by zhaozhenlei** [comment]
I wanna to konw why this issue happened ?  and how to get full-sceen display? thx

**Comment by sorccu** [comment]
Probably it doesn't render at full resolution by default. Perhaps it upscales a lower resolution image? Check your settings and change the resolution to see if that makes a difference.

Also, run 'adb shell dumpsys window' and 'adb shell wm size' before changing anything and paste the output here.

To fully resolve this issue I'd need to have one of those devices, but I don't. Feel free to donate one if possible.

**Comment by zhaozhenlei** [comment]
···
run 'adb shell dumpsys window',  I found nothing about mDisplayId
run 'adb shell wm size', it shows just like below:
![image](https://user-images.githubusercontent.com/28615244/33369441-95135654-d52f-11e7-8c24-60d86e2567f6.png)

···

**Comment by sorccu** [comment]
I don't think I asked you to grep by anything? Anyway wm size confirms that it's running at a lower resolution by default. You can make it work in STF by changing the resolution in settings. Other than that, I can take a look if someone sends me that device.

**Comment by zhaozhenlei** [comment]
Aha! Here at last, the answer to my question: setting-> Dispaly->Screen resolution, change default setting from FHD to WQHD,then everything goes well on STF !!
![image](https://user-images.githubusercontent.com/28615244/33429297-35b1a4ee-d607-11e7-9916-9ede30d2a708.png)
