### ISSUE TITLE
My Android machine have no Mobile interface  for connect PC，I have to use "adb connect 192.168.2.1:5555" to debug it , how can I connect to STF ??

### ISSUE THREAD

**Issue by cooldeaaap1** [openstf/stf#769]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Use the --allow--remote option. Note that ADB over WIFI is much, much slower than a regular USB connection, so don’t be surprised if the performance is poor.

**Comment by cooldeaaap1** [comment]
Thanks for your reply，but my STF service have no way  connect with the Android Machine ..  Where to use  "allow-remote"?

**Comment by sorccu** [comment]
Start STF with that option, then run adb connect to add the device to your local adb. STF will then see it.
