### ISSUE TITLE
Device worker died with code 1

### ISSUE THREAD

**Issue by prutapptic** [openstf/stf#78]
Hello,
I'm using STF to control a set of many Android devices. Sometimes I can plug 6 devices without problem, and sometimes when I plug those 6 same devices, some devices stay disconnected after a connection attempt.

Here is the error message in the shell:

INF/provider 83795 [*] Cleaning up device worker "HT4AGJT04584"
ERR/provider 83795 [*] Device worker "HT4AGJT04584" died with code 1
INF/provider 83795 [*] Restarting device worker "HT4AGJT04584"
  error: missing required argument `--screen-port'

I got this message when I try to plug our Nexus 9 tab in Android 5.0.1.

Here are some info about the plugged device: 

add device 1: /dev/input/event0
  bus:      0000
  vendor    0000
  product   0003
  version   2002
  name:     "synaptics_dsx"
  location: "synaptics_dsx/touch_input"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_WAKEUP
    ABS (0003): ABS_MT_SLOT           : value 0, min 0, max 9, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MAJOR    : value 0, min 0, max 47, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MINOR    : value 0, min 0, max 47, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_X     : value 0, min 0, max 3072, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_Y     : value 0, min 0, max 2304, fuzz 0, flat 0, resolution 0
                ABS_MT_TRACKING_ID    : value 0, min 0, max 65535, fuzz 0, flat 0, resolution 0
                ABS_MT_PRESSURE       : value 0, min 0, max 255, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT
add device 2: /dev/input/event3
  bus:      0019
  vendor    0001
  product   0001
  version   0100
  name:     "gpio-keys.6"
  location: "gpio-keys/input0"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_VOLUMEDOWN        KEY_VOLUMEUP          KEY_POWER
  input props:
    <none>
add device 3: /dev/input/event2
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "h2w headset"
  location: ""
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_END               KEY_MUTE              KEY_VOLUMEDOWN        KEY_VOLUMEUP
                KEY_NEXTSONG          KEY_PLAYPAUSE         KEY_PREVIOUSSONG      KEY_REWIND
                KEY_FASTFORWARD       KEY_MEDIA             KEY_SEND              KEY_VOICECOMMAND
  input props:
    <none>
add device 4: /dev/input/event1
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "CwMcuSensor"
  location: ""
  id:       ""
  version:  1.0.1
  events:
    SW  (0005): SW_LID                SW_CAMERA_LENS_COVER*
  input props:
    <none>

There is no problem with the Nexus 6 - 5.0.1.
Edit: Now, the same problem appears with the Nexus 6 - 5.0.1.
Thanks for your help guys ;-)

**Comment by sorccu** [comment]
You have a crappy USB host controller and/or USB hub if you're using one. It's disconnecting so much that STF runs out of ports and fails to even put them back into the pool. That's a bug, but even if we fixed it your system wouldn't be usable. If you're using a hub you're most likely just going to have to throw it away, it's worthless. I recommend reading the troubleshooting section in our README and possible our hardware recommendations, too.

We've seen the problem before when some guys scavenged random parts from their dead PCs and tried to put a provider there. USB is NOT easy once you have more than a few devices connected.

**Comment by sorccu** [comment]
And it could also be caused by crappy USB cables. Just go through the troubleshooting section, we have encountered every single issue listed there.

**Comment by Bobcui001** [comment]
Unfortunately, I met the same problem with you. Has now been fixed. I suggest you install the latest 'jpeg-turbo' package. And make sure other packages are up to date. I wish good luck
