### ISSUE TITLE
I Have 4 mac mini has install STF already, but I want to centralizer into one, Please let me know if i can config like it with STF?

### ISSUE THREAD

**Issue by cuhavp** [openstf/stf#780]

**Comment by sorccu** [comment]
The only configuration we support is in the [deployment guide](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). You can do something similar with `stf local` on one machine and `stf provider` on other machines, but we won't help with that.

**Comment by cuhavp** [comment]
Thanks @sorccu
