### ISSUE TITLE
Could not start stf local --public-ip <>

### ISSUE THREAD

**Issue by cuhavp** [openstf/stf#781]
Could not locate the bindings file. Tried:
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/out/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/out/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/default/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/compiled/8.1.2/darwin/x64/zmq.node
Could not locate the bindings file. Tried:
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/out/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/Debug/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/out/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/Release/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/build/default/zmq.node
 → /Users/misfit/Documents/ADBKIT/stf/node_modules/zmq/compiled/8.1.2/darwin/x64/zmq.node
2017-12-28T03:47:15.856Z FTL/cli:local 7184 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/misfit/Documents/ADBKIT/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
2017-12-28T03:47:15.856Z INF/cli:local 7184 [*] Shutting down all child processes

**Comment by sorccu** [comment]
Please search the older issues for a solution. This has been posted a lot.
