### ISSUE TITLE
Display market device names

### ISSUE THREAD

**Issue by koral--** [openstf/stf#786]
Currently our device list displayed by STF looks like this:
![image](https://user-images.githubusercontent.com/3340954/34461934-c3399cba-ee38-11e7-9263-7c7271e0e7b1.png)

Some devices have unfriendly names like XT1032 and C6603 however, their market names are Moto G and Xperia Z respectively. It will be nice feature to include those market names in STF UI.

There is an official list of Android devices maintained by Google: https://support.google.com/googleplay/answer/1727131?hl=en and there are Android libraries which map model names to market names e.g.: https://github.com/jaredrummler/AndroidDeviceNames or https://github.com/tslamic/AndroidDeviceNames

**Comment by sorccu** [comment]
We’ve been thinking of perhaps providing a paid API with full STF integration for automatically retrieving the device name, image and possibly some other details. This way companies would have a way of supporting the project while getting something back. They’d also get a normal invoice which is handy for tax purposes. At the same time, the service would only be of cosmetic value, so no one would be forced to use the service.

Would something like that be of interest to you?

**Comment by koral--** [comment]
What is approx. price and what else will be included (if any)?
