### ISSUE TITLE
Back、Menu and Home key have no response in Vivo X9?

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#787]
Dear,
        Back、Menu and Home key have no response in Vivo X9, but it work normally in other mobile phones。

<img width="402" alt="dingtalk20180103112403" src="https://user-images.githubusercontent.com/26616673/34508299-b352307c-f078-11e7-9ab0-e7f6c7cfa166.png">

**Comment by sorccu** [comment]
Thanks. Let’s keep this issue open, perhaps someone will figure it out. Personally I don’t have that device so I’m not able to look into it. If someone wants to donate one perhaps we can move a bit faster.

**Comment by zhangpeng23796** [comment]
Dear,
      I wan't debug on Vivo X9, i has read code in "/Users/zhj/Api/stf/res/app/control-panes/device-control/device-control-key-directive.js",as follow:

![image](https://user-images.githubusercontent.com/26616673/34550125-446a0a5a-f149-11e7-8751-9cab4979435d.png)

could you tell me which code can response after " scope.control.keyUp(key)"?

**Comment by thinkhy** [comment]
I have Vivo X9 and Vivo X9 plus on my STF cluster, which both work very well.  You may need to enable "click simulation" (模拟点击) on your developer options.

**Comment by zhangpeng23796** [comment]
@thinkhy ,thanks. I have solve the problem

**Comment by thinkhy** [comment]
You're welcome.
