### ISSUE TITLE
I want to modify front-end UI for our developers

### ISSUE THREAD

**Issue by jihunim** [openstf/stf#788]
I want to modify front-end UI and maybe contribute.

What I want to do:
> Change device selection page to checkbox style
> Add button which executes "install Android application to all of chosen devices".
> Add button which executes "run instrumentation test using gradle command".

However, I don't know how to build this project. I also don't know which front-end framework did you use.

Could you guide me a little bit?

**Comment by sorccu** [comment]
Sorry we can’t provide generic guidance, it’s too time consuming. What I would recommend is that you just read the source code a bit and have a go at implementing it yourself. If you run into a more specific issue, then ask again about that issue.
