### ISSUE TITLE
login for ldap

### ISSUE THREAD

**Issue by zhn3431223** [openstf/stf#793]
![image](https://user-images.githubusercontent.com/25398776/34927845-45ca4d7a-f9f4-11e7-9bce-544128d6f03a.png)

![image](https://user-images.githubusercontent.com/25398776/34927859-653d8f1e-f9f4-11e7-99c3-593e88312814.png)

**Comment by thinkhy** [comment]
@zhn3431223  It should be due to incorrect options. Please update the issue if you have resolved the problem. Thanks.

**Comment by zhn3431223** [comment]
![image](https://user-images.githubusercontent.com/25398776/34968905-11bde0f6-faa7-11e7-8aa0-a7eb2099104f.png)

I have solved this problem in this way。

**Comment by thinkhy** [comment]
Thanks for your sharing.  Close out.

**Comment by thinkhy** [comment]
Thanks for your sharing.  Close out.
