### ISSUE TITLE
is there any plan to change stf from B/S to C/S?

### ISSUE THREAD

**Issue by tasktinkle** [openstf/stf#797]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
No unless we can come up with a business model. We definitely would not be able to handle the increased number of support requests otherwise.
