### ISSUE TITLE
TPS650: Setup had an error TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vagabond1-1983** [openstf/stf#804]
Hi guys,
When I run stf in docker env and try to connect android device in USB mode, I get the error below. Could anyone support this? Thanks a lot.

Device info:
MODEL: TPS650
VERSION: 5.1.1 (SDK 22)

error message in output
2018-02-02T07:41:30.564Z FTL/device 12139 [17088013200005] Setup had an error TypeError: Cannot read property 'length' of undefined
    at devutil.makeIdentity (/app/lib/util/devutil.js:113:28)
    at solve (/app/lib/units/device/plugins/util/identity.js:15:30)
    at /app/lib/units/device/plugins/util/identity.js:21:12
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by sorccu** [comment]
Run `adb shell getprop` and paste the full output here.

**Comment by vagabond1-1983** [comment]
Thanks @sorccu
[UserVolumeLabel]: [RockChips]
[camera2.portability.force_api]: [1]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.dexopt-flags]: [m=y]
[dalvik.vm.heapgrowthlimit]: [192m]
[dalvik.vm.heapmaxfree]: [8m]
[dalvik.vm.heapminfree]: [512k]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [16m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [div]
[dalvik.vm.jniopts]: [warnonly]
[dalvik.vm.lockprof.threshold]: [500]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[debug.force_rtl]: [0]
[debug.nfc.fw_download]: [false]
[debug.nfc.se]: [false]
[dev.bootcomplete]: [1]
[dhcp.eth0.pid]: [566]
[dhcp.eth0.reason]: [PREINIT]
[dhcp.eth0.result]: []
[dhcp.wlan0.dns1]: [192.168.137.1]
[dhcp.wlan0.dns2]: []
[dhcp.wlan0.dns3]: []
[dhcp.wlan0.dns4]: []
[dhcp.wlan0.domain]: [mshome.net]
[dhcp.wlan0.gateway]: [192.168.137.1]
[dhcp.wlan0.ipaddress]: [192.168.137.91]
[dhcp.wlan0.leasetime]: [604800]
[dhcp.wlan0.mask]: [255.255.255.0]
[dhcp.wlan0.mtu]: []
[dhcp.wlan0.pid]: [7759]
[dhcp.wlan0.reason]: [RENEW]
[dhcp.wlan0.result]: [ok]
[dhcp.wlan0.server]: [192.168.137.1]
[dhcp.wlan0.vendorInfo]: []
[drm.service.enabled]: [false]
[gsm.current.phone-type]: [1]
[gsm.network.type]: [Unknown]
[gsm.operator.alpha]: []
[gsm.operator.iso-country]: []
[gsm.operator.isroaming]: [false]
[gsm.operator.numeric]: []
[gsm.sim.operator.alpha]: []
[gsm.sim.operator.iso-country]: []
[gsm.sim.operator.numeric]: []
[gsm.sim.state]: [NOT_READY]
[gsm.version.ril-impl]: [SIMCOM_RIL51_20170412]
[init.svc.adbd]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.console]: [running]
[init.svc.daemonsu]: [running]
[init.svc.debuggerd]: [running]
[init.svc.dhcpcd_eth0]: [stopped]
[init.svc.dhcpcd_wlan0]: [running]
[init.svc.displayd]: [running]
[init.svc.drm]: [running]
[init.svc.drmservice]: [stopped]
[init.svc.flash_recovery]: [stopped]
[init.svc.healthd]: [running]
[init.svc.installd]: [running]
[init.svc.keystore]: [running]
[init.svc.lmkd]: [running]
[init.svc.logd]: [running]
[init.svc.media]: [running]
[init.svc.netd]: [running]
[init.svc.ril-daemon]: [running]
[init.svc.rtw_suppl_con]: [running]
[init.svc.sdcard]: [stopping]
[init.svc.servicemanager]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.telpo-st-setup]: [stopped]
[init.svc.tplcdinit]: [stopped]
[init.svc.ueventd]: [running]
[init.svc.vold]: [running]
[init.svc.zygote]: [running]
[keyguard.no_require_sim]: [true]
[media.sink.audio]: []
[net.bt.name]: [Android]
[net.change]: [net.dns1]
[net.dns1]: [192.168.137.1]
[net.hostname]: [android-7b6487cb19eecc2c]
[net.qtaguid_enabled]: [1]
[net.tcp.default_init_rwnd]: [60]
[persist.logd.size]: []
[persist.service.bdroid.bdaddr]: [22:22:1d:d6:44:39]
[persist.sys.country]: [CN]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.first_booting]: [false]
[persist.sys.language]: [zh]
[persist.sys.overscan.aux]: [overscan 100,100,100,100]
[persist.sys.overscan.main]: [overscan 100,100,100,100]
[persist.sys.preinstalled]: [1]
[persist.sys.profiler_ms]: [0]
[persist.sys.strictmode.visual]: [false]
[persist.sys.timezone]: [Asia/Shanghai]
[persist.sys.usb.config]: [mass_storage,adb]
[persist.tegra.nvmmlite]: [1]
[ril.function.dataonly]: [1]
[rild.simcom.gps]: [1]
[rild.simcom.stk]: [0]
[rild.simcom.ussd]: [0]
[ro.adb.secure]: [0]
[ro.allow.mock.location]: [0]
[ro.audio.monitorOrientation]: [true]
[ro.baseband]: [unknown]
[ro.board.platform]: [rk3288]
[ro.boot.console]: [ttyS2]
[ro.boot.hardware]: [rk30board]
[ro.boot.mode]: [emmc]
[ro.boot.selinux]: [permissive]
[ro.boot.serialno]: [17088013200005]
[ro.bootloader]: [unknown]
[ro.bootmode]: [emmc]
[ro.bt.bdaddr_path]: [/data/misc/bluetoothd/bt_addr]
[ro.build.characteristics]: [tablet]
[ro.build.date.utc]: [1502859194]
[ro.build.date]: [Wed Aug 16 12:53:14 HKT 2017]
[ro.build.description]: [rk3288-userdebug 5.1.1 LMY49F eng.luorf.20170816.125105 test-keys]
[ro.build.display.id]: [TPS650_ALL_V1.0.1_20170816]
[ro.build.fingerprint]: [Android/rk3288/rk3288:5.1.1/LMY49F/luorf08161252:userdebug/test-keys]
[ro.build.flavor]: [rk3288-userdebug]
[ro.build.host]: [ubuntu]
[ro.build.id]: [LMY49F]
[ro.build.product]: [rk3288]
[ro.build.tags]: [test-keys]
[ro.build.type]: [userdebug]
[ro.build.user]: [luorf]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [eng.luorf.20170816.125105]
[ro.build.version.release]: [5.1.1]
[ro.build.version.sdk]: [22]
[ro.build.version.security_patch]: [2016-03-01]
[ro.carrier]: [unknown]
[ro.com.android.dataroaming]: [true]
[ro.com.android.dateformat]: [MM-dd-yyyy]
[ro.config.alarm_alert]: [Alarm_Classic.ogg]
[ro.config.enable.remotecontrol]: [false]
[ro.config.notification_sound]: [pixiedust.ogg]
[ro.config.ringtone]: [Ring_Synth_04.ogg]
[ro.crypto.state]: [unencrypted]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [1]
[ro.default.size]: [100]
[ro.enable_boot_charger_mode]: [0]
[ro.factory.hasGPS]: [false]
[ro.factory.hasUMS]: [true]
[ro.factory.storage_suppntfs]: [true]
[ro.factory.tool]: [0]
[ro.factory.without_battery]: [false]
[ro.factorytest]: [0]
[ro.hardware]: [rk30board]
[ro.htg.force]: [1]
[ro.internal.model]: [TPS650]
[ro.kernel.android.checkjni]: [0]
[ro.nfc.port]: [I2C]
[ro.opengles.version]: [196609]
[ro.product.board]: [rk30sdk]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.device]: [TPS650]
[ro.product.locale.language]: [zh]
[ro.product.locale.region]: [CN]
[ro.product.manufacturer]: [rockchip]
[ro.product.model]: [TPS650]
[ro.product.name]: [TPS650]
[ro.product.ota.host]: [www.rockchip.com:2300]
[ro.product.usbfactory]: [rockchip_usb]
[ro.product.version]: [1.0.1]
[ro.radio.platform]: [ALL]
[ro.revision]: [0]
[ro.ril.ecclist]: [112,911]
[ro.rk.LowBatteryBrightness]: [false]
[ro.rk.MassStorage]: [false]
[ro.rk.bt_enable]: [true]
[ro.rk.cpu]: [rk3288v2]
[ro.rk.cpu_min_freq]: [126000
]
[ro.rk.def_brightness]: [200]
[ro.rk.homepage_base]: [http://www.google.com/webhp?client={CID}&amp;source=android-home]
[ro.rk.install_non_market_apps]: [false]
[ro.rk.screenoff_time]: [-1]
[ro.rk.screenshot_enable]: [true]
[ro.rk.soc]: [rk3288]
[ro.rk.systembar.tabletUI]: [false]
[ro.rk.systembar.voiceicon]: [true]
[ro.rksdk.version]: [RK30_ANDROID5.1.1-SDK-v1.00.00]
[ro.runtime.firstboot]: [1517551015475]
[ro.secure]: [0]
[ro.serialno]: [17088013200005]
[ro.sf.fakerotation]: [false]
[ro.sf.hwrotation]: [0]
[ro.sf.lcd_density]: [160]
[ro.simcomril.version]: [simcom_ril5x_20170412]
[ro.target.product]: [tablet]
[ro.tether.denied]: [false]
[ro.wifi.channels]: []
[ro.zygote]: [zygote32]
[selinux.reload_policy]: [1]
[service.adb.tcp.port]: [5555]
[service.bootanim.exit]: [1]
[sf.power.control]: [2073600]
[sys.ID.mID]: [4]
[sys.boot_completed]: [1]
[sys.display.oritation]: [0]
[sys.ggralloc.version]: [1.0.2]
[sys.ggsurflgr.version]: [1.000]
[sys.ghwc.version]: [2.067-3288MID]
[sys.gmali.version]: [r6p0-02rel0-13-11@0]
[sys.grga.version]: [2.000]
[sys.hwc.compose_policy]: [0]
[sys.hwc.htg]: [true]
[sys.pms.finishscan]: [true]
[sys.resolution.changed]: [false]
[sys.rkadb.root]: [0]
[sys.settings_system_version]: [302]
[sys.sysctl.extra_free_kbytes]: [12294]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.underUmsMode.enable]: [false]
[sys.usb.config]: [mass_storage,adb]
[sys.usb.state]: [mass_storage,adb]
[sys.usb.umsavailible]: [true]
[sys.wallpaper.rgb565]: [0]
[sys_graphic.cam_camboard.ver]: [0.13.0]
[sys_graphic.cam_hal.ver]: [1.54.13]
[sys_graphic.cam_isi.ver]: [0.10.0]
[sys_graphic.cam_libisp.ver]: [1.39.0]
[sys_graphic.cam_trace]: [0]
[testing.mediascanner.skiplist]: [/mnt/internal_sd/Android/]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
[wifi.supplicant_scan_interval]: [15]
[wlan.driver.status]: [ok]

**Comment by sorccu** [comment]
I guess it’s because there’s no SIM card support.

**Comment by vagabond1-1983** [comment]
Ok, I see. Thanks for the info.

**Comment by sorccu** [comment]
Nah we can fix that. But not sure when. Maybe try changing the code yourself?

**Comment by thinkhy** [comment]
Seems the field 'ro.product.brand' is missing  in the output of "adb shell getprop", so the line 113 of devutil.js failed:

```
 if (model.substr(0, brand.length) === brand) {
```

@sorccu For this case, can we add a default brand name 'unkown' as below?

```
 var brand = properties['ro.product.brand']||'unknown'
```

**Comment by vagabond1-1983** [comment]
Thanks @thinkhy  @sorccu 
I will try for your suggestion. Please let me know if you have new patch for the issue.

**Comment by sorccu** [comment]
@thinkhy I think `'unknown'` should be at the presentation layer, not in the actual data that we collect. Anyway since we're not actually storing the brand, I don't think it needs to have a fallback value - perhaps just change:

https://github.com/openstf/stf/blob/2dac3d1bbd1ef1974a1c22a10941c5739711928e/lib/util/devutil.js#L113

Into:

```
if (brand && model.substr(0, brand.length) === brand) {
```

That should work. Though this particular device might have other issues as well.

**Comment by sorccu** [comment]
@vagabond1-1983 maybe now? Try latest master.

**Comment by vagabond1-1983** [comment]
That would be great @sorccu . Would you update openstf/stf docker image too? I build stf environment in that way.

**Comment by thinkhy** [comment]
@sorccu your fix would be better, we don't need to assign a fallback value to brand which will not be presented on web UI.

**Comment by sorccu** [comment]
I think this was fixed already.

**Comment by sorccu** [comment]
Nevermind, sorry for the spam. Wrong search term.
