### ISSUE TITLE
Create normal documentation step by step how to install and don't waste people time!

### ISSUE THREAD

**Issue by Oksana098** [openstf/stf#805]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Please do not use our software.
