### ISSUE TITLE
STF credentials

### ISSUE THREAD

**Issue by maciejkamela** [openstf/stf#811]
I try to run stf on localhost and it worked till now, for some reason when I hit stf local and go to the localhost:7100 it redirect me to the http://localhost:7100/auth/mock/ which require some username/pwd.
When I check devices list (adb devices) I see my devices connected. What is the issue here?What creds I am supposed to use?

**Comment by sorccu** [comment]
It does not ask for a password. It asks for your name and email address. You can enter anything you want.

**Comment by chigarow** [comment]
hey guys, just want to ask, is there any way to use credentials for login?
