### ISSUE TITLE
Why IPhone picture in https://openstf.io/ ?

### ISSUE THREAD

**Issue by leojiang** [openstf/stf#812]
Hi there, 
Actually this is not a issue for the project, it's about the webpage of openstf.
I noticed in https://openstf.io/, 'feature' section, you guys used a phone picture.
But why the picture looks so much like a IPhone ?
Could you please replace it with a real android device picture?

![image](https://user-images.githubusercontent.com/939583/36521901-6888a3cc-17d4-11e8-96cb-0fca575e6024.png)

**Comment by sorccu** [comment]
It says it right below the image... you can even control an Android phone from an iPhone if you like. In that picture STF is being used from an iPhone. That's all.

**Comment by leojiang** [comment]
Cool, thanks!
