### ISSUE TITLE
Why choose nodejs to implement it

### ISSUE THREAD

**Issue by kateliublack** [openstf/stf#815]
hello, I'm working on a project that based on the github project,so l'm learning the stf code recently.Thank you for sharing.It’s amazing that it displays the phone screen fluently .  I haven‘t used nodejs before that，so  I have a question that why you choose nodejs to implement it? What’s the nodejs‘s advantage？

**Comment by sorccu** [comment]
It’s what we wanted to use at the time and Rust didn’t exist yet. Simple as that. Now I would use Rust :)

**Comment by codeskyblue** [comment]
thanks for answer.
