### ISSUE TITLE
How can i know how many providers  running, is there any tools?

### ISSUE THREAD

**Issue by ericlin-ICT** [openstf/stf#817]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

Hi, 

How can i know how many providers running through any tools? And is there any administrator pages that we can see some system information?

Thanks very much.

**Comment by sorccu** [comment]
Hmmm no not really. You’d have to look at the devices list and see that all devices from a provider are offline. Give each provider a unique easy to remember name.

Or you can query rethinkdb but I don’t have time to help with that. You’d query all devices that have present: false.

**Comment by ericlin-ICT** [comment]
thanks

**Comment by ericlin-ICT** [comment]
thanks

**Comment by thinkhy** [comment]
@sorccu I've implemented a page to show all the provider info in a tab view of settings page. I can submit a PR if this is a common requirement.

**Comment by sorccu** [comment]
Nice but I’ve had very little time to review recently, and I don’t have a multi provider setup available to me right now. Please submit it but also include screenshots if possible (censor private information with black boxes or whatever). Maybe @vbanthia can then also comment on it.

**Comment by vbanthia** [comment]
@thinkhy

I will look into it. Please send PR.
