### ISSUE TITLE
Smartphones are lost and can no longer be found unless restarting the provider service in production mode 

### ISSUE THREAD

**Issue by David-gulu** [openstf/stf#818]
Hi, there

I have read through the deployment document and deployed OpenSTF in production mode, with (app & database role) and the provider role deployed on two separated servers. One server ran the app.service, app-auth.service and other necessary services according to the deployment document  ,
and the other server only ran the provider service and adbd service. The deployment was base on docker.

At  the beginning, the overall system worked properly, yet , if we just left the connected phones there with no one using them after a specific period of time (seems to be 40 mins) , then a problem occured.  When we clicked the "use" button,  the screen monitoring part on the webpage turned out to be gray and we were not able to do anything to such phones, including checking status infos of them.  We tried to replug these devices, and found that they were offline on the webpage whereas connected when checking using "adb devices" (status device). 

To best of our knowledge, we have tried everything we can  and find out that the problem will not disappear unless we restart the provider container.  

This problem is not happen on a specific device. We've also checked the logs of the provider container and found no difference between  the problem occured and not.

the stf doctor output at the provider is 

2018-03-05T09:51:50.533Z INF/cli:doctor 155 [*] OS Arch: x64
2018-03-05T09:51:50.534Z INF/cli:doctor 155 [*] OS Platform: linux
2018-03-05T09:51:50.535Z INF/cli:doctor 155 [*] OS Platform: 3.10.0-514.el7.x86_64
2018-03-05T09:51:50.535Z INF/cli:doctor 155 [*] Using Node 6.11.2
2018-03-05T09:51:50.570Z INF/cli:doctor 155 [*] Using ZeroMQ 4.1.4
2018-03-05T09:51:50.585Z ERR/cli:doctor 155 [*] RethinkDB is not installed (`rethinkdb` is missing)
2018-03-05T09:51:50.585Z ERR/cli:doctor 155 [*] ProtoBuf is not installed (`protoc` is missing)
2018-03-05T09:51:50.585Z ERR/cli:doctor 155 [*] ADB is not installed (`adb` is missing)
2018-03-05T09:51:50.956Z INF/cli:doctor 155 [*] Using GraphicsMagick 1.3.23

When the problem occured,  the statues of the adb container was up, together with the provider container. Can you please do us a favor to  help solve the problem?

yours, 

David

**Comment by sorccu** [comment]
Sounds like you’re hitting #100.

**Comment by David-gulu** [comment]
Thanks for your advice. We will check and feedback.

**Comment by David-gulu** [comment]
We checked #100, #104, #342, and #528 and finally solved the problem according to #342， by adding 

-e "ZMQ_TCP_KEEPALIVE=1" 
-e "ZMQ_TCP_KEEPALIVE_IDLE=300" 
to the below unit-files
stf-triproxy-app
stf-triproxy-dev
stf-websocket
stf-provider@
stf-processor@

the smartphones were kept idle for about 2 hours and still connectable.   A little advice here is to update the DEPLOYMENT.md and thus can help more people to avoid encountering such problem. Thank you very much. closing.
