### ISSUE TITLE
screen white when connected 6 devices

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#82]
Hi, my stf works very well with two devices connected
but when i add more devices ( now i have 6 devices connected )
i find some devices hard to be ready and when they are ready , i connect them, the screen is white
i really do not know why
does anyone have ideas about this?

**Comment by jonalmeida** [comment]
Your USB controllers are probably aren't supplying enough power to all your devices. Consider getting a powered USB hub (see the FAQ section for more details about this).

**Comment by channingbreeze** [comment]
thank you for your answer
i find the device record in rethinkdb , the ready is false , does this means that the device is unable to use?
when i plug it off and plug in again , sometimes it is ok
so it is wierd

**Comment by sorccu** [comment]
The hardware guide exists for a reason. Once you scale past just a few devices, you WILL run into problems unless you know what you're doing. At the very least, get a powered USB hub (with enough power! Most powered USB hubs are actually only able to support 3-4 devices simultaneously). If you are in China, I would recommend the ORICO brand. Our recommended hub is essential a rebrand of an ORICO USB 2.0 hub with BC 1.2 support. For example, [this hub](http://www.aliexpress.com/store/product/2014-New-Design-ORICO-BH7-U3-BK-ABS-7-Ports-USB3-0-BC1-2-Charging-HUB/105327_2026659970.html) should be OK. You should have more options on Chinese sites, though.
