### ISSUE TITLE
Android P

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#822]
# Android P

This is a tracking issue for Android P support.

### Current status

Not working. Requires:

- [ ] openstf/minicap#118
- [ ] openstf/STFService.apk#25

**Comment by kennethzhu** [comment]
Expecting the great project to support Android P...

**Comment by hzy729** [comment]
When can support Android P?

**Comment by sorccu** [comment]
Read the linked issues.

**Comment by thinkhy** [comment]
Update this issue with openstf/STFService.apk#25

**Comment by sorccu** [comment]
Done as of v3.4.0.
