### ISSUE TITLE
Not able to execute ZMQ_TCP_KEEPALIVE for my application. 

### ISSUE THREAD

**Issue by sanshaw1** [openstf/stf#833]
I have an application that uses ZMQ Pub-Sub Model. I have an algorithm in my sub side that if the socket remains idle for 40 seconds it should disconnect and reconnect again. Now, I want to remove this algorithm. Instead i want to use TCP KeepAlive Packets so that my socket does not remain idle  and thus my sub does not disconnect and connect frequently. 
Please find my code below:

zmq_socket_t socket;
socket = zmq_socket(_zmq_context, ZMQ_PUB);

int tcp_keepalive = 1, tcp_keepalive_idle = 25;

 if(zmq_setsockopt(socket, ZMQ_TCP_KEEPALIVE, &tcp_keepalive, sizeof(tcp_keepalive))) {
        INFO(0, "sanjay keepalive error -err %d", tcp_keepalive);
        return NULL;
    }
    else
    {
        INFO(0, "keepalive set -noerr %d", tcp_keepalive);
    }

    if(zmq_setsockopt(socket, ZMQ_TCP_KEEPALIVE_IDLE, &tcp_keepalive_idle, sizeof(tcp_keepalive_idle))) 
    {
        INFO(0, "keepalive idle error -err %d", tcp_keepalive_idle);
        return NULL;
    }
    else
    {
        INFO(0, "idle set -noerr %d", tcp_keepalive_idle);
    }
  if (zmq_bind(socket, urlp)) {
        ERR(0, "zmq_bind(PUB): %s", ERRNO);
        FREE(urlp);
        return NULL;
    }

Please help me on this ??  I am not able to achieve my target. Am i missing anything?

**Comment by sorccu** [comment]
Is this related to STF?

**Comment by sanshaw1** [comment]
No its not related to STF.

**Comment by sorccu** [comment]
Please ask ZeroM people then.
