### ISSUE TITLE
Ability to connect to PC in LAN from another subnetwork

### ISSUE THREAD

**Issue by gadgadskiy** [openstf/stf#835]
Hi!
I've set up stf locally on PC (Ubuntu 16.04) with connected Android device and it works well. `stf doctor` answers all is OK.
Now I'm trying to re-run stf with remote access from another PC (Windows 10)

Ubuntu network is
inet addr: 10.62.10.16
mask: 255.255.255.0
Windows network is
inet addr: 10.62.24.90
mask: 255.255.254.0
I'm starting `stf local --public-ip 10.62.24.90` on Ubuntu PC and going to `http://10.62.10.16:7100` on Windows. But this link redirects me onto `http://10.62.24.90:7100/auth/mock/` with message "This site can’t be reached"

Tell me please, is there ability to use stf from another local subnetwork? Or maybe did I some errors during its set up?

**Comment by sorccu** [comment]
You should use the IP your clients see for that option. Or, do a full deployment and replace the load balancer with whatever you please. We don’t help with network config issues because it takes ages and the end it’s your network.

**Comment by gadgadskiy** [comment]
Clients can see each other.

> do a full deployment
do you mean this [DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md)?

**Comment by luoshangyu** [comment]
where is `--allow-remote true`?

**Comment by gadgadskiy** [comment]
Thanks, I've forgot about it.
