### ISSUE TITLE
Connect to display websocket out of STF

### ISSUE THREAD

**Issue by hursevich** [openstf/stf#843]
Hey, we've integrated STF into our QA infrastructure and I'd like to stream STF device display to webpage out of STF, is there any limitation (cross-origin or smth) for getting screen images by wss://<public>/d/<private>/<udid>/<port>?

**Comment by sorccu** [comment]
You can do it. It is not good from a security point of view but there are almost no checks whatsoever. Just connect and it should work.

**Comment by ElanCao** [comment]
> You can do it. It is not good from a security point of view but there are almost no checks whatsoever. Just connect and it should work.

Hi , i'm trying to do this. i can connect ws via a local html file with js, but if i use URL.createObjectURL(blob), i always got a "blob://null/guid", can you please help?
