### ISSUE TITLE
No results when running the command "adb -s 10.167.44.71:7401 shell ps "  on Android 8.0

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#845]
When I run the command "adb -s 10.167.44.71:7401 shell ps "  on Android 8.0, there is no result for pids.
 
![image](https://user-images.githubusercontent.com/26616673/38286511-597f79b6-37f8-11e8-838f-3e2044661144.png)

But if I run the command "adb -s 10.167.44.71:7401 shell ps "  on Android 8.0 without stf, the result is ok.
![image](https://user-images.githubusercontent.com/26616673/38286664-12ddc6f6-37f9-11e8-9106-a0c45ccc5091.png)

And,"adb -s 10.167.44.71:* shell ps "  on Android 7.0,Android6.0,Android5.0, is there some problems on Android8.0？

**Comment by sorccu** [comment]
Maybe this is related to #806?

**Comment by sorccu** [comment]
Closed in favor of #806.
