### ISSUE TITLE
When I link my device and look at the information on the web page, there is no CPU and memory information . Why is that?

### ISSUE THREAD

**Issue by EvilOlivia** [openstf/stf#849]
![image](https://user-images.githubusercontent.com/23339100/38464844-d5dfb89e-3b46-11e8-84bf-534bea079194.png)

**Comment by sorccu** [comment]
Our device database hasn’t been updated for a long time because it’s a lot of work. You can fork the project and create your own device database if needed. Check out stf-device-db.

**Comment by thinkhy** [comment]
@sorccu some CPU and Memory info can be retrieved from filesystem /proc, we may need a PR for this feature ...

**Comment by sorccu** [comment]
Yes but we might not want to do that. There are entire apps, both free and paid, dedicated to displaying this information (and others like RAM/ROM). I feel like it could be an entire open source project by itself :)

I have nothing against a PR though. But most likely the functionality would like in a separate repo anyway.
