### ISSUE TITLE
OpenSTF integration with Apache webserver

### ISSUE THREAD

**Issue by sdvroot** [openstf/stf#851]
Hi, I am install latest version of OpenSTF without docker...

Please tell what web-server using by default where is necessary files? I want to configuring it with Apache server, maybe you have some ready documentation about it?

**Comment by sorccu** [comment]
While it's possible to use Apache, we don't support it. Please understand that it's a lot of work to support an open source project, so we have to limit the scope somehow. We recommend nginx. If you want to use something else you're on your own.
