### ISSUE TITLE
Installation error：JavaScript heap out of memory

### ISSUE THREAD

**Issue by liuhao-121** [openstf/stf#855]
**What is the issue or idea you have?**
Follow the steps to install, an error occurs when you finally install STF
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
<--- Last few GCs --->

[31404:0x28396b0]  1115108 ms: Mark-sweep 1257.0 (1820.7) -> 1257.0 (1820.7) MB, 748.9 / 0.0 ms  allocation failure GC in old space requested
[31404:0x28396b0]  1116145 ms: Mark-sweep 1257.0 (1820.7) -> 1257.0 (1768.2) MB, 1037.0 / 0.0 ms  last resort GC in old space requested
[31404:0x28396b0]  1117158 ms: Mark-sweep 1257.0 (1768.2) -> 1257.0 (1746.7) MB, 1013.8 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x209416da57c1 <JSObject>
    1: eaccesFallback [/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:~412] [pc=0x3595fefbf73c](this=0xdf835d8c211 <JSGlobal Object>)
    2: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:132] [bytecode=0x1acba325e2f1 offset=52](this=0xdf835d8c211 <JSGlobal Object>,err=0x2a88cfe6fad1 <Error map = 0x1501d2b84e59>,created=0x9089dd82201 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node-gyp]
 2: 0x11f127c [node-gyp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node-gyp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node-gyp]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node-gyp]
 6: 0xdf1d33 [node-gyp]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node-gyp]
 8: 0x3595fee842fd
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/data/.npm/_logs/2018-04-18T07_38_03_323Z-debug.log

**Please run `stf doctor` and paste the output here.**

**Comment by liuhao-121** [comment]
@sorccu  please help me thanks!

**Comment by liuhao-121** [comment]
node version is 8.11.1

**Comment by sorccu** [comment]
Can't help you with that. It's an issue with your environment. Maybe you ran out of memory during the build.

**Comment by liuhao-121** [comment]
@sorccu  I don't have this issue with nodejs version 0.x.x, but 0.x.x does not meet the requirements; using the >6.9 version will have this problem, do not know how to solve
