### ISSUE TITLE
Touch point doesn't match between the touch on STF Control and the touch on Real Device.

### ISSUE THREAD

**Issue by luoshangyu** [openstf/stf#858]
Touch point doesn't match between the touch on STF Control and the touch on Real Device.
Please see the bellow picture, mobile is OPPO R15.

Any solution? @sorccu 

![touchpoint](https://user-images.githubusercontent.com/7412385/39171852-9725b872-47d2-11e8-95d8-10835424ae37.png)

**Comment by sorccu** [comment]
Check the [CHANGELOG](https://github.com/openstf/stf/blob/master/CHANGELOG.md). Maybe that Mi Mix 2 fix also fixes your device. Try building master.

**Comment by luoshangyu** [comment]
@sorccu thank you S.K. for the reply, I'll try if it was fixed. Once I've done, will update result here.

**Comment by luoshangyu** [comment]
@sorccu thanks sk，looks working fine.
