### ISSUE TITLE
Calling Syrup functions from another class

### ISSUE THREAD

**Issue by UncertainSpin** [openstf/stf#860]
Hello,

I am attempting to make some modifications to OpenSTF and am encountering some issues when trying to interact between classes. This appears to be due to STF-Syrup's dependency injection blocking functions from an external scope. 

In short, I would like to be able to reference functions in _bar.js_ (Uses Syrup) FROM _foo.js_ (Does not use Syrup). I can successfully require and assign _bar.js_, but instead of a typical class object, I receive a SerialSyrup object that util.inspect shows is constructed like this:

```
SerialSyrup {
  options: {},
  body: [Function],
  dependencies:
   [ SerialSyrup {
       options: {},
       body: [Function],
       dependencies: [],
       resolved: null } ],
  resolved: null }
```
  
Every attempt to reference functions that exist within the "module.exports" block of _bar.js_ fails with "...is not a function" when called from _foo.js_ . Is there a way I can reach inside this block, other than totally refactoring _foo.js_ to be a Syrup module and importing _bar.js_ as a dependency?

PS: Reposting from [/openstf/stf-syrup](https://github.com/openstf/stf-syrup/issues/3), as that issue page appears dead.

**Comment by sorccu** [comment]
Show your code.

**Comment by lenosze** [comment]
Same issue here. Attempting to modify the packages auto-cleanup to be scheduled every few days. For that I've written a simple cron that injects cleanup.js. 

```
module.exports = syrup.serial()
  .dependency(require('./cleanup'))
  .define(function(options, cleanup) {
    return {
      uninstallPackagesCron: function() {
        nodeSchedule.scheduleJob(CLEANUP_EVERY_SUNDAY, function() {
          log.info('Cleanup job launched')
          // *logic here*
        })
      }
    }
  })
```
Cron is then required in app/index.js with the server startup
```
var cleanupCron = require('./../device/plugins/cleanupCron')
```
And what I get from logging the cleanupCron is the whole SerialSyrup object with no way to reach the uninstallPackagesCron function
```
 SerialSyrup {
  options: {},
  body: [Function],
  dependencies: 
   [ SerialSyrup {
       options: {},
       body: [Function],
       dependencies: [Array],
       resolved: null } ],
  resolved: null }
```

**Comment by sorccu** [comment]
Look at https://github.com/openstf/stf/blob/master/lib/units/device/index.js. You’re not supposed to be able to require and use it directly. You have to call .consume() which then actually runs the function and returns the a promise that resolves with the result.
