### ISSUE TITLE
Do this openstf can control all mobile in once?

### ISSUE THREAD

**Issue by zeroyjk** [openstf/stf#861]
I have some question do this openstf can control 1 process in all mobile?

For example:
If i have 50 phone number with the some model and the position of apps placement are the same position on display.. But I want to control only 1 phone and others will follow the same flow... can it do that?

**Comment by sorccu** [comment]
Yes and no, but in practice no. You can search for past issues to find our previous responses.

**Comment by zeroyjk** [comment]
Can you give me some clue..

**Comment by sorccu** [comment]
Search past issues. But like I said don’t expect too much.
