### ISSUE TITLE
How can STF show the devices that is connected by ip:host?

### ISSUE THREAD

**Issue by yoyo-sincerely** [openstf/stf#864]
hello,guys!!!
It's my first time to use STF to manager mobile phone, STF show devices normality when I connect devices by usb, but STF can not show the devices when I connect devices by ip:port.
I connect devices with this command:
```
adb connect <host>[:<port>]
```
Is there a way to show the devices connected by ip:port ?

**Comment by sorccu** [comment]
`--allow-remote` though it isn't ideal - search past issues for details. It might be very slow.
