### ISSUE TITLE
Does "Remote Debug" support user authentication?

### ISSUE THREAD

**Issue by David-gulu** [openstf/stf#867]
hi, there

we are now deploying STF and it worked out fine. 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/37066792/39609325-bb84af70-4f7a-11e8-870f-b05821fb3609.png">

As the above figure shows,  we want to figure it out that whether remote debugging support user authentication or not ? If not, does it mean that after copying the public key, by just typing "**adb connect IP:port**" provided by the figure, a user can connect the smartphone remotely without any authentication even if they are not logging in STF and are not occupying any device?

yours, 
David

**Comment by sorccu** [comment]
It verifies the user’s adb key. If you have access to an adb key that has been added to the system, you can get in. Otherwise you cannot, though as always there may be bugs.
