### ISSUE TITLE
how to listen to  mousewheel event and make the device scroll

### ISSUE THREAD

**Issue by qingranfjj** [openstf/stf#870]
our users have a urgent needs that when the mouse wheeling ,the device can scroll too.
In the screen-directive.js code ,i have add some code like the following, when mousewheel, it can execute  function _onWheel ,  but i dont know how to simulated sliding event to the device in_onWheel, can someone give a idea

 element[0].addEventListener('mousewheel',_onWheel,false)
        function _onWheel(e) {
            console.log(e)
            console.log('mousewheel')
            // control.touchMove(nextSeq(), 0, 0.5423280423280423, 0.45351473922902497, 0                                                                              .5)
            // control.touchCommit(nextSeq())
            // control.touchMove(nextSeq(), 0, 0.5423280423280423, 0.4444444444444444, 0.                                                                              5)
            // control.touchCommit(nextSeq())
            // control.touchMove(nextSeq(), 0, 0.5423280423280423, 0.40816326530612246, 0                                                                              .5)
            // control.touchCommit(nextSeq())
            mouseMoveListener(e)
        }

**Comment by sorccu** [comment]
I don't think it'll work very well but you have the rough idea. You're missing touch down and touch up, though. They're required. You may also need to delay some of the events so that they're not sent all at once.
