### ISSUE TITLE
How to support android 8.1.0 system?

### ISSUE THREAD

**Issue by HeartIsBeat** [openstf/stf#872]
**What is the issue or idea you have?**
STF can't connect Huawei P20
to get /arm64-v8a/lib/android-8.1.0 or arm64-v8a/lib/android-27 and so on.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
yes
![image](https://user-images.githubusercontent.com/20472976/40154576-8e83d5f4-59c1-11e8-8b88-bf8717afefef.png)

**Please provide the steps to reproduce the issue.**
Huawei P20,  android system 8.1.0

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/20472976/40154557-7158a7f2-59c1-11e8-955d-93e1e9165c8c.png)
Other android system 8.0.0 is ok.
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**
stf version 3.1.0

**Comment by sorccu** [comment]
Either your installation is broken or you are using an old version.
