### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by oleg-webdev** [openstf/stf#873]
Reproduce steps:
- I have downloaded latest build of stf
- then npm install obviously
- successfully run rethinkdb
- then stf local.
- able to see my phone json info in console:
- tried to reach http://localhost:7100/ - server is running, but I gon whiste screen of death.
- open console and see:
`Uncaught Error: Cannot find module "!!../../../node_modules/css-loader/index.js!../../../node_modules/sass-loader/index.js!./nine-bootstrap.scss"`
Tried:
1) installed sass-loader and css-loader globally
2) npm rebuild node-sass
Any ideas?
Thank you!

**Comment by ccsunsun** [comment]
I have the same problem, can share how you solve it?

**Comment by xiaozhi1995** [comment]
I've also met the problem. How did you last it? Thank you.

**Comment by Wing-Li-oceanwing** [comment]
I have this problem,please help me, tks!

**Comment by Huanxin-leolil** [comment]
Hi, how to fix it?  Met the same problem !

**Comment by Huanxin-leolil** [comment]
> Hi, how to fix it? Met the same problem !

It's work for me 

after `installed sass-loader and css-loader globally , npm rebuild node-sass`
need to run `npm link` again !

**Comment by Wing-Li-oceanwing** [comment]
Thank you very much!
