### ISSUE TITLE
Will STF release the device automatically during Automation ?

### ISSUE THREAD

**Issue by KiThoSivaPrakash** [openstf/stf#881]
I am using a Device in STF, for running automation cases. lets say that the automation script will take around 40 minutes to complete its execution on mobile device and i have set the idle time as 30 minutes. So during the execution of automation cases, will the STF consider that device as idle and release the device from the user before the completion of automation script ?

**Comment by vbanthia** [comment]
Yes, STF will consider device idle if you are not using it from STF UI. Will suggest to use longer timeout while using device through API and once automation is complete, release the device using release API.

**Comment by KiThoSivaPrakash** [comment]
@vbanthia : Thanks for the response and solution

**Comment by yxcSini** [comment]
@vbanthia Can you tell me how to set the longer timout? I met the same problem

**Comment by vbanthia** [comment]
To set timeout while using API, check following:

https://github.com/openstf/stf/blob/master/doc/API.md#post-userdevices
