### ISSUE TITLE
We need to login repeatly while using domain name and LDAP

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#884]
I use follow common start stf, it is ok while accessing with ip(eg.http://192.168.1.16:7100), I login once，then I no need to login. But while accessing with domain name(eg.http://phone.tecent.com), I need to login while using http://phone.tecent.com. Please help me!!!
stf local --public-ip='本机IP' --auth-type ldap --auth-options '["--ldap-url","$LDAP SERVER URI", "--ldap-bind-dn","$LDAP BIND DN","--ldap-search-dn","$LDAP BASE DN", "--ldap-bind-credentials","$LDAP BIND DN PWD", "--ldap-search-class","user", "--ldap-search-field", "mail"]'

**Comment by sorccu** [comment]
I'm not sure whate exactly you mean, does it work for a while and then log you out?

If it doesn't work at all, then perhaps you're using the wrong `--public-ip` option. Even though the option is called `--public-ip`, you should use whatever ip or hostname you're using to access STF. Perhaps you should specify `--public-ip phone.tecent.com` instead of an IP address.

**Comment by sorccu** [comment]
Actually I think my comment is wrong. I meant you should make sure to use the correct `--app-url`. Use the proper hostname here. You won't be able to access from both the IP address and the hostname at the same time, though.

**Comment by zhangpeng23796** [comment]
Now i use follow command：
stf local --public-ip='10.167.33.154'  --group-timeout 900 --allow-remote --auth-type ldap --auth-options '["--ldap-url","ldap://ldap.corpautohome.com:389","--ldap-bind-dn","CN=dealerapp,OU=业务帐号,OU=Autohomestaff,DC=corp,DC=autohome,DC=inc","--ldap-search-dn","OU=Autohomestaff,DC=corp,DC=autohome,DC=inc", "--ldap-bind-credentials","Xfmhjy@2019", "--ldap-search-class","user", "--ldap-search-field", "mail"]'

I want to access by http://phone.stf.com/#!/devices, but in fact the url is http://10.167.33.154/#!/devices, what can i do?

**Comment by sorccu** [comment]
Even though the option is called —public-ip, you can give it a hostname. Just use whatever address you want.

Also, you should check out the deployment guide.

**Comment by zhangpeng23796** [comment]
In fact i have tried as follow,but there is error:
stf local --public-ip='dev.phonebus.corpautohome.com'  --group-timeout 900 --allow-remote --auth-type ldap --auth-options '["--ldap-url","ldap://ldap.corpautohome.com:389","--ldap-bind-dn","CN=dealerapp,OU=业务帐号,OU=Autohomestaff,DC=corp,DC=autohome,DC=inc","--ldap-search-dn","OU=Autohomestaff,DC=corp,DC=autohome,DC=inc", "--ldap-bind-credentials","Xfmhjy@2019", "--ldap-search-class","user", "--ldap-search-field", "mail"]'

![image](https://user-images.githubusercontent.com/26616673/44500656-423a9c80-a6bc-11e8-90aa-52d45ff96cd6.png)


I think i can't use 'dev.phonebus.corpautohome.com'  to replace '10.167.3.124',because the domain is parsed.

![image](https://user-images.githubusercontent.com/26616673/44500820-0a802480-a6bd-11e8-9ea0-bf459c9c0efe.png)

**Comment by sorccu** [comment]
Show the error you get in the Chrome developer tools.

**Comment by zhangpeng23796** [comment]
![image](https://user-images.githubusercontent.com/26616673/44502280-62ba2500-a6c3-11e8-803a-556bc4341a49.png)

**Comment by sorccu** [comment]
Maybe you need to forward that port? I would really recommend doing a proper deployment instead of using `stf local`.
