### ISSUE TITLE
[Docker] How to setup the provider in different machine?

### ISSUE THREAD

**Issue by goswings** [openstf/stf#885]
For example:
**Server 1:** 
[Docker] 3 container
1. docker run -d --name rethinkdb -v /srv/rethinkdb:/data --net host rethinkdb rethinkdb --bind all --cache-size 8192 --http-port 8090
2. docker run -d --name adbd --privileged -v /dev/bus/usb:/dev/bus/usb --net host sorccu/adb:latest
3. docker run -d --name stf --net host openstf/stf stf local --public-ip 192.168.1.100

**Server 2:**
[Docker] 2 container
1. docker run -d --name adbd --privileged -v /dev/bus/usb:/dev/bus/usb --net host sorccu/adb:latest

> got the mobile devices

2. docker run -d --name stf --net host openstf/stf stf provider --name STF-VM --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 20000 --public-ip 192.168.1.100 --storage-url http://192.168.1.100:7100/

> Cannot see the device in 192.168.1.100:7100
anyone can help on this?

**Comment by sorccu** [comment]
Doesn’t seem like your connect-sub/push are correct. They should refer to the other server.

**Comment by goswings** [comment]
fixed the issue.

**Comment by insan-jati** [comment]
Hello @goswings, could you please help to elaborate how you fixed this issue? Thank you..

**Comment by HesionBlack** [comment]
Hello @goswings, could you please help to elaborate how you fixed this issue? Thank you..
