### ISSUE TITLE
steup STF for ubuntu

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#889]
**What is the issue or idea you have?**
Hey guys, i am new to this and trying to install stf on ubuntu using google cloud, but due to some reason or other i couldn't get it done, there are like different types of errors thrown up everytime. So i just wanna ask is there any setup guide for ubuntu 16.04 and any ports and firewall setting that i need to add. Thanks, below is just one of the many errors i get during installation.
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
p WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/stf/node_modules/dtrace-provider/.node-gyp/8.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/stf/node_modules/dtrace-provider/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/stf/node_modules/dtrace-provider/.node-gyp/8.11.3"

**Comment by sorccu** [comment]
I would recommend using NVM to install node. You’ll avoid all those permission issues.

**Comment by habeebshk** [comment]
Hey sorccu, thanks
I got it installed

**Comment by thatsk** [comment]
while installing stf

**Comment by thatsk** [comment]
if we are using nvm node-pre-gyp gets error not found and when we are officially installing node and node-pre-gyp then permission error gets occured please let me know what the resolution

**Comment by sorccu** [comment]
Use NVM. You’ll avoid all that trouble.
