### ISSUE TITLE
How to connect the devices to openstf running on docker.

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#892]
**What is the issue or idea you have?**
I am running stf on docker using a GCP, i am not sure how to connect the devices to it,any help in this matter would be great help.
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by Immanuel-Codoid** [comment]
Hi @habeebshk , I face this same issue, I connected my device to my laptop and run STF on docker desktop, I'm able to see all the service running in the docker. When I launched my localhost I'm able to see the STF UI but the connected device is not displayed in UI.

`adb devices -l`:
List of devices attached
6f152707               device product:OnePlusNordCE_IND model:EB2101 device:OnePlusNordCE transport_id:1

`stf local` & `stf doctor`:
Error: Cannot find module

Can you please tell me if you see any issue in my execution?. If you need more details please let me know. I'm happy to share
Thanks in advance
