### ISSUE TITLE
how to Keep the data when tab switch

### ISSUE THREAD

**Issue by sunshine4me** [openstf/stf#893]
When I use the screenshots and then change other tabs，how to Keep the data when tab switch？
I dont want my screenshots loss。

**Comment by sorccu** [comment]
Unfortunately that's not possible right now, screenshots are not stored anywhere. I think there may be a pull request or an issue with a usable patch if you search past issues. Other than that you'd have to create the functionality yourself.

**Comment by sunshine4me** [comment]
@sorccu screenshot file is not less，it's on the server，my point is the tab change will destroy screenshots controller。Is there a simple way to keep this controller data?
