### ISSUE TITLE
Browser chooser missing Chrome Dev

### ISSUE THREAD

**Issue by paulirish** [openstf/stf#9]
It was only added to play store a few months ago so no big deal.

APK is `com.chrome.dev`
https://play.google.com/store/apps/details?id=com.chrome.dev

(btw Googlers have access to com.chrome.canary too, but it's not public yet)

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/39191/8641359/ab9273bc-28c8-11e5-928b-df33529b2ea4.png)

**Comment by sorccu** [comment]
Thanks, I'll add it in a few hours. If you can provide an icon for `com.chrome.canary`, I can add it too even though the app itself is not public.

**Comment by paulirish** [comment]
canary icon: https://lh5.ggpht.com/7tY2G7vVx_XEkNFdx--CxConvVstBCNWZ3vMs9pWcn63UPvdsUGSvvItB4Vyudf2ww=w300-rw
