### ISSUE TITLE
can stf run on android?

### ISSUE THREAD

**Issue by larsonzhong** [openstf/stf#904]
can stf run on android? if not ,why?has anyone done this? 
I want use tablet （Android） control several devices . i still have no idea.

**Comment by gounthar** [comment]
I could be wrong, but I think porting stf to Android could prove as difficult as porting Linux to your tablet.
A Raspberry Pi 3B+ is not the recommended platform, but it works for me. At $35, you can't go wrong...

**Comment by sorccu** [comment]
I don't think that's a good idea. You can use the STF UI on a tablet, though, if that's what you want. Otherwise, if you want to run the whole STF, you can try but I don't think it'll be worth the effort.
