### ISSUE TITLE
I have download STF project. Now I am using IDE visual studio code. When I am making any changes, after building its not reflecting in UI.  So any thing I have to change while building the project like if the project is using require js ,then in index.* we have to point like given below  <script src =”lib/require/require.js” data-min =“app/main ”> And after that we have to point it to build generated file. Actually i am new to these technology.

### ISSUE THREAD

**Issue by Manjuy** [openstf/stf#909]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
When you install STF, it builds a new resource cache. You have to clear the cache first if you change something. Run:

‘./node_modules/.bin/gulp clean’

Then try again.

**Comment by Manjuy** [comment]
Thank you   Simo Kinnunen ,I think thanks word is very less now.


*Best Regards*

*Manju Yadav*

**Comment by Manjuy** [comment]
Hi  Simo Kinnunen,

*will it work for IOS?*

Best Regards
*Manju Yadav*
