### ISSUE TITLE
do not want to provide all devices on my pc

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#91]
Hi, sorry to bother you again!
I have 4 devices on my pc and i just want to provide two to stf.
i tried to run provider serial1 serial2 , provider [serial1 serial2], provider serial1, serial2 and so on , but none works
is there a way to do this or i have to run two provider like , provider serial1 , provider serial2.
i just want to run one provider and provide two devices
thank you

**Comment by sorccu** [comment]
There was a bug. If you build from master now, it should work with `stf local serial1 serial2`.
