### ISSUE TITLE
browser.apps only include some browser

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#920]
V3.1.0
**What is the issue or idea you have?**
browser.apps only include some browser, example my phone has installed Firefox,Chrome,UC Browser,QQ Browser,System Browser, but only Firefox and System Browser are visible.
![image](https://user-images.githubusercontent.com/26616673/43186647-e2f26c54-9021-11e8-9c7b-6e7b0226d441.png)

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Every devices.

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Please submit a pull request to https://github.com/openstf/stf-browser-db.

You should see the application bundle ID in STF's log output. IIRC, it should say something like "Unmapped browser ..."
