### ISSUE TITLE
How to change resolution

### ISSUE THREAD

**Issue by numbqq** [openstf/stf#925]
Does it possible to change the minicap resolution via web browser?

And how can I get the FPS?

Thanks.

**Comment by sorccu** [comment]
Currently the only way is to resize your browser window. A smaller window will use a smaller resolution.

You can't see FPS. Besides, it wouldn't be very useful. For example, on a static screen where nothing changes, minicap may update the screen once per minute (when the time changes in the top bar).

**Comment by numbqq** [comment]
Hello @sorccu,
> You can't see FPS.

According to the README feature `Refresh speed can reach 30-40 FPS depending on specs and Android version.` About why I want to see the FPS is that I found the operation is not smooth when I set the minicap resolution to `1920*1080`, so I want to see what's the real FPS. Does there is any way to get it?

Thanks.

**Comment by sorccu** [comment]
Full HD isn't going to reach that number. There's a reason why we request a smaller resolution.

You can only measure FPS if you have something running that updates the screen at 60 FPS, like perhaps a game. The value we have in there is a manual estimate from a long time ago. There is no live FPS display.

**Comment by numbqq** [comment]
Hello @sorccu,

Thanks for your answer.

> Full HD isn't going to reach that number. There's a reason why we request a smaller resolution.

Can you kindly tell me what is the limitation of this? Bandwidth?(I think it is enough.) , minicap or something else?

Thanks.
