### ISSUE TITLE
Could you tell me which is the method to take screenshot?

### ISSUE THREAD

**Issue by waitshang** [openstf/stf#929]
I know stf uses minicap to cast screen and take screenshot. 
![qq 20180810143847](https://user-images.githubusercontent.com/11643284/43942844-1bbe7e9c-9cac-11e8-909a-1c5fb2dac5b8.png)
Could you tell me the way? Shells or codes are OK. Thanks a lot.

**Comment by sorccu** [comment]
See `adb shell /data/local/tmp/minicap -h`. You want the `-s` option.

**Comment by waitshang** [comment]
@sorccu While the stf is casting a phone's screen. Can `adb shell /data/local/tmp/minicap -s` works together correctly?

**Comment by sorccu** [comment]
It should, since that's what STF does.

**Comment by waitshang** [comment]
@sorccu Thanks a lot. I appreciate it.
