### ISSUE TITLE
Support - Declarative Jenkinsfile

### ISSUE THREAD

**Issue by cs-leandro-lourenco** [openstf/stf#932]
Hello everyone!

I few time ago, I've installed OpenSTF in our environment and we are using Multi-stage project. Now I started to config our CI with Jenkinsfile, and looking for a way to lock the OpenSTF using my pipeline, but after a research, I doesn't found any config. Is there a config to use OpenSTF with Jenkinsfile or is that not available yet?

Thanks guys!

**Comment by thinkhy** [comment]
I don't think it's necessary to define such a Jenkins config file to communicate with STF. You can utilize the function of STF by invoking [RestAPI](https://github.com/openstf/stf/blob/master/doc/API.md).

**Comment by cs-leandro-lourenco** [comment]
Tks @thinkhy !
