### ISSUE TITLE
[Question]Does stf support only one stf server with multiple PC and Devices? 

### ISSUE THREAD

**Issue by tobecrazy** [openstf/stf#933]
I have setup stf with latest version, it running well . 
## Version: stf 3.4.0
# What is the issue or idea you have? 
I have two pc to connect different Android devices , one is A (MAC Mini), another is B(MAC Min).
STF is running on PC A, is this possible devices which is connect to PC B  can be manage by STF running on PC A? How to configure it ?
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
adb devices works and list all the devices.

**Comment by sorccu** [comment]
See the deployment guide, linked in the readme.
