### ISSUE TITLE
how to upload images to android device's /sdcard/Pictures path?

### ISSUE THREAD

**Issue by tkoyat** [openstf/stf#942]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sorccu** [comment]
The only way right now would be to `adb connect` to the device  first and then use `adb push` to transfer the image to the desired location. We did originally have plans to add drag&drop image upload to the UI, but that's not being worked on anymore.
