### ISSUE TITLE
remote location there is some lag in stf.

### ISSUE THREAD

**Issue by pkkumar83** [openstf/stf#945]
Hi Team,

we have stf application hosted its working fine in our environment, but the remote users are facing some lag, like navigation, response is slow, we think its might be the issue from the network, but other than that,can we do anything in stf side.

**Comment by sorccu** [comment]
STF was not built for that scenario. Unfortunately there is not much you can do aside from trying to optimize your connectivity. You can modify the STF code to enforce a maximum screen size and/or JPG quality, and some people have also limited the frame rate. Doing all of these will help considerably, but it'll never be totally smooth.

**Comment by thinkhy** [comment]
@pkkumar83 Agreed with Simo. You can do some optimization for STF, but the perf may not  improved as you desire.  We did some experiments, results show smoothness of remote-operation is mostly up to out/in network bandwidth.
