### ISSUE TITLE
Keep use status when `stop using`

### ISSUE THREAD

**Issue by vus520** [openstf/stf#949]
When i have `stop using`, device will remove app, hide using app and go to home page.

after add `--no-cleanup` still go to home page(not sure if not remove apps), is there anyway to disable     cleanup feature and keep using app stay.

;)

**Comment by sorccu** [comment]
Check --help and the changelog, there’s an option there you’ll prob want to use

**Comment by vus520** [comment]
i'm sure, i added `--no-cleanup` when start stf local, but that will hide app anyway.

**Comment by sorccu** [comment]
No... you want the --no-screen-reset option
