### ISSUE TITLE
Android 6 Developer Preview 3 Error

### ISSUE THREAD

**Issue by ahmetkocu** [openstf/stf#95]
Hi,  
I try to connect Nexus 5 Android 6 Dev Prev 3 device to stf but getting some errors repeatedly. How can I fix this problem.

Thanks.

LOG:

"
FTL/device 19726 [0718fd5a0059c7ce] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:89:15)
FTL/util:lifecycle 19726 [0718fd5a0059c7ce] Shutting down due to fatal error
INF/provider 19595 [*] Cleaning up device worker "0718fd5a0059c7ce"
ERR/provider 19595 [*] Device worker "0718fd5a0059c7ce" died with code 1
INF/provider 19595 [*] Restarting device worker "0718fd5a0059c7ce"
INF/device:support:push 19729 [0718fd5a0059c7ce] Sending output to "tcp://127.0.0.1:7116"
INF/device 19729 [0718fd5a0059c7ce] Preparing device
INF/device:support:sub 19729 [0718fd5a0059c7ce] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 19729 [0718fd5a0059c7ce] Subscribing to permanent channel "*ALL"
INF/device:support:properties 19729 [0718fd5a0059c7ce] Loading properties
INF/device:support:abi 19729 [0718fd5a0059c7ce] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 19729 [0718fd5a0059c7ce] Checking whether we need to install STFService
INF/device:resources:service 19729 [0718fd5a0059c7ce] Running version check
INF/device:resources:service 19729 [0718fd5a0059c7ce] STFService up to date
INF/device:plugins:service 19729 [0718fd5a0059c7ce] Launching agent
FTL/device 19727 [0718fd5a0059c7ce] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:89:15)
FTL/util:lifecycle 19727 [0718fd5a0059c7ce] Shutting down due to fatal error
INF/provider 19595 [*] Cleaning up device worker "0718fd5a0059c7ce"
ERR/provider 19595 [*] Device worker "0718fd5a0059c7ce" died with code 1
INF/provider 19595 [*] Restarting device worker "0718fd5a0059c7ce"
INF/device:support:push 19730 [0718fd5a0059c7ce] Sending output to "tcp://127.0.0.1:7116"
INF/device 19730 [0718fd5a0059c7ce] Preparing device
INF/device:support:sub 19730 [0718fd5a0059c7ce] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 19730 [0718fd5a0059c7ce] Subscribing to permanent channel "*ALL"
INF/device:support:properties 19730 [0718fd5a0059c7ce] Loading properties
INF/device:support:abi 19730 [0718fd5a0059c7ce] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 19730 [0718fd5a0059c7ce] Checking whether we need to install STFService
INF/device:resources:service 19730 [0718fd5a0059c7ce] Running version check
INF/device:resources:service 19730 [0718fd5a0059c7ce] STFService up to date
INF/device:plugins:service 19730 [0718fd5a0059c7ce] Launching agent
INF/provider 19595 [*] Providing 2 of 2 device(s); waiting for "0718fd5a0059c7ce"

**Comment by sorccu** [comment]
You have to build and install the latest master. NPM has not been updated yet.

**Comment by ahmetkocu** [comment]
ok, try this way and work

thanks

I want to ask one more question, can we add genymotion or emulator to this system.

**Comment by sorccu** [comment]
I know that at least emulators don't work, since they don't expose any linux touch devices. It should be doable but we haven't really focused on that. Not planned currently unless someone convinces us.
