### ISSUE TITLE
npm install -g stf gives errors 

### ISSUE THREAD

**Issue by PariKdm** [openstf/stf#950]
**What is the issue or idea you have?**
node version - v10.10.0
npm version - 6.4.1

staff-169:OpenSTF prachi.salunke$ sudo npm install -g stf
npm WARN deprecated @slack/client@3.16.0: v3.x and lower are no longer supported. see migration guide: https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
/usr/local/bin/stf -> /usr/local/lib/node_modules/stf/bin/stf

> dtrace-provider@0.8.7 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1086
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:1086:25)
    at startup (internal/bootstrap/node.js:265:32)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

> bufferutil@1.3.0 install /usr/local/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.7 (node_modules/stf/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.7 install: `node-gyp rebuild || node suppress-error.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prachi.salunke/.npm/_logs/2018-09-11T04_06_09_462Z-debug.log

**Please provide the steps to reproduce the issue.**
1. Downloaded stf-master
2. Installed the given dependencies sucessfully 
brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config
3. brew install node ( done and successful )
    node version - v10.10.0
    npm version - 6.4.1
4. npm install -g stf , give above error , unable to install dependencies of stf 
5. As a result,  " npm link "  also shows same error
6. Screenshots attached for reference
![screen shot 2018-09-10 at 7 08 21 pm](https://user-images.githubusercontent.com/43161035/45337958-55ef6980-b5bd-11e8-843a-ced89bd42ba1.png)

**Comment by sorccu** [comment]
Don’t use sudo. Use nvm instead and you won’t need it.

Also, use node 8.x for now.

**Comment by hsafari** [comment]
Hello Sorccu. Is it possible to have a reference procedure/steps that works for Ubuntu 18.04? I have been trying to install STF but several errors I have got; trying to figure them out. It will be helpful for many people who want to use STF in the new Ubuntu for the first time.

**Comment by hsafari** [comment]
never mind. I finally was able to install FTF in Ubuntu 18.04 on this environment:
2018-09-14T23:23:26.464Z INF/cli:doctor 27473 [*] OS Arch: x64
2018-09-14T23:23:26.466Z INF/cli:doctor 27473 [*] OS Platform: linux
2018-09-14T23:23:26.466Z INF/cli:doctor 27473 [*] OS Platform: 4.15.0-34-generic
2018-09-14T23:23:26.466Z INF/cli:doctor 27473 [*] Using Node 6.9.1
2018-09-14T23:23:26.486Z INF/cli:doctor 27473 [*] Using ZeroMQ 4.2.1
2018-09-14T23:23:26.501Z INF/cli:doctor 27473 [*] Using RethinkDB 2.3.6~0xenial
2018-09-14T23:23:26.501Z INF/cli:doctor 27473 [*] Using GraphicsMagick 1.3.28
2018-09-14T23:23:26.501Z INF/cli:doctor 27473 [*] Using ProtoBuf 3.2.0
2018-09-14T23:23:26.502Z INF/cli:doctor 27473 [*] Using ADB 1.0.36

RethinkDB gave me hard time but worked eventually.

**Comment by jhonsuicide** [comment]
> Don’t use sudo. Use nvm instead and you won’t need it.
> 
> Also, use node 8.x for now.

hi @sorccu  i tried use node 8.x, but stil got error configure
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.0.0-23-generic
gyp ERR! command "/home/jhonsuicide/.nvm/versions/node/v8.11.3/bin/node" "/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/stf/node_modules/dtrace-provider
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> bufferutil@1.3.0 install /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.0.0-23-generic
gyp ERR! command "/home/jhonsuicide/.nvm/versions/node/v8.11.3/bin/node" "/home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jhonsuicide/.nvm/versions/node/v8.11.3/lib/node_modules/stf/node_modules/bufferutil
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

need your advice
