### ISSUE TITLE
Help!Help!Help!Apk install fail with docker and nginx

### ISSUE THREAD

**Issue by zhangpeng23796** [openstf/stf#955]
**What is the issue or idea you have?**

I have deploy stf with Docker and nginx,but there is error while installing apk, other funciton is ok.
![image](https://user-images.githubusercontent.com/26616673/45748629-e839e200-bc3b-11e8-8ea3-03522ddb9e6c.png)

![image](https://user-images.githubusercontent.com/26616673/45748987-e886ad00-bc3c-11e8-8d93-7fc569166411.png)

the dockers status:
![image](https://user-images.githubusercontent.com/26616673/45748654-00a9fc80-bc3c-11e8-86e2-9e88772cc304.png)

the nginx config as follow:
daemon off;
worker_processes 4;

events {
  worker_connections 1024;
}

http {
  upstream stf_app {
    server 10.168.66.18:3100 max_fails=0;
  }

  upstream stf_auth {
    server 10.168.66.18:3200 max_fails=0;
  }

  upstream stf_storage_apk {
    server 10.168.66.18:3300 max_fails=0;
  }

  upstream stf_storage_image {
    server 10.168.66.18:3400 max_fails=0;
  }

  upstream stf_storage {
    server 10.168.66.18:3500 max_fails=0;
  }

  upstream stf_websocket {
    server 10.168.66.18:3600 max_fails=0;
  }

  upstream stf_api {
    server 10.168.66.18:3700 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }

  map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }

  server {
    listen 80;
    server_name stf.test;
    keepalive_timeout 70;
    root /dev/null;

    resolver 127.0.0.1 valid=300s;
    resolver_timeout 10s;

    # Handle stf-provider@floor4.service
    location ~ "^/d/floor4/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.168.66.18:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ "^/d/agent/([^/]+)/(?<port>[0-9]{5})/$" {
    proxy_pass http://10.167.3.148:$port/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    }    

    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }

    location /api/ {
      proxy_pass http://stf_api/api/;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

    location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }
  }
}

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
Need to see the logs of the storage-plugin-apk unit.

**Comment by zhangpeng23796** [comment]
Thanks！ I have solved the problem，because the domain is parsed wrong

**Comment by sorccu** [comment]
Please submit a pull request or issue to adbkit-apkreader if it’s something that meeds to be fixed. If possible also provide the .apk file.
