### ISSUE TITLE
STF 3.4.0 ARMv7 Docker image

### ISSUE THREAD

**Issue by deg0nz** [openstf/stf#956]
Hi,

will there be an official docker build for version 3.4.0 on ARM soon?
Or should we consider building it ourselves?

Thanks an greetings

**Comment by petemyron** [comment]
Is there a way we can help on this? I think I read that you've got this setup to automagically build.

**Comment by sorccu** [comment]
The build server (on Scaleway) keeps dying every now and then. Sometimes it’s an easy fix, but often the entire disk is corrupt and the builder needs to be reimaged. I could perhaps start doing weekly builds at home, though. Eventually it’ll likely break my disks as well, though.

I believe since perhaps last year it’s now relatively easy to build docker images for ARM on x86 as well. If someone could figure out the way to do that, that would be the best and most reliable long term solution.

**Comment by gounthar** [comment]
I am building Docker images for ARM thanks to Shippable. I push them to Dockerhub without any problem.
If you have the set of commands needed to build it on Scaleway, I can maybe use that to start it on Shippable.

**Comment by codeskyblue** [comment]
It is also possible to build armv7 docker image on travis. example <https://github.com/codeskyblue/gohttpserver/blob/master/docker/Dockerfile.armhf>

**Comment by gounthar** [comment]
Really? I thought it could be done on Travis with qemu or with images including qemu, and not natively.
@codeskyblue, could you please elaborate on this? That's good news for me.
Thanks!

**Comment by petemyron** [comment]
Yeah, this isn't pleasant on a raspberry pi; ~1.5 hours to build after changing the source image from `alpine:3.5` to `arm32v6/alpine:3.8` (there's no v7). I'll look into cross-compiling.

Can the provider unit be separated? That's really the only part we use on ARM.

**Comment by petemyron** [comment]
there are now ARM VMs on AWS, so I might try that out for this. They're *much* faster than a pi, obv...

**Comment by gounthar** [comment]
For sure. But can this be automated with GitHub?

**Comment by gounthar** [comment]
I have built the image from the Dockerfile in docker/armv7l thanks to Shippable. It is now there: https://hub.docker.com/r/gounthar/stf-armv7l/ .
I haven't been able to run the `mkimage-alpine.sh` beforehands though.
So I guess my image is not complete. What is this script supposed to do?
Thanks.

**Comment by gounthar** [comment]
It looks like I have a problem with my image, as I get:

```bash
itouch-just-one-touch/prebuilt/armeabi-v7a/bin/minitouch, /app/node_modules/minitouch-just-one-touch/prebuilt/armeabi/bin/minitouch
```

Could you please let me know what I forgot @sorccu ? Thanks.

**Comment by phatpaul** [comment]
@gounthar please describe how you fixed the error 

I just get this error over-and-over again:
```
openstf | 2019-03-21T14:35:01.106Z FTL/device 259 [HGAGLT6Z] Setup had an error Error: At least one of these paths should exist: /app/node_modules/minitouch-just-one-touch/prebuilt/arm64-v8a/bin/minitouch, /app/node_modules/minitouch-just-one-touch/prebuilt/armeabi-v7a/bin/minitouch, /app/node_modules/minitouch-just-one-touch/prebuilt/armeabi/bin/minitouch
openstf |     at Object.module.exports.requiredMatch (/app/lib/util/pathutil.js:33:9)
openstf |     at /app/lib/units/device/resources/minitouch.js:21:23
openstf |     at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
openstf |     at /app/node_modules/stf-syrup/lib/serial.js:43:33
openstf |     at tryCatch1 (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
openstf |     at Promise$_callHandler [as _callHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
openstf |     at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
openstf |     at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
openstf |     at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
openstf |     at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
openstf |     at Async$consumeFunctionBuffer (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
openstf |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
openstf |     at process._tickCallback (internal/process/next_tick.js:104:9)
openstf | 2019-03-21T14:35:01.114Z FTL/util:lifecycle 259 [HGAGLT6Z] Shutting down due to fatal error
openstf | 2019-03-21T14:35:01.166Z INF/provider 22 [*] Cleaning up device worker "HGAGLT6Z"
openstf | 2019-03-21T14:35:01.169Z ERR/provider 22 [*] Device worker "HGAGLT6Z" died with code 1
openstf | 2019-03-21T14:35:01.169Z INF/provider 22 [*] Restarting device worker "HGAGLT6Z"
```

**Comment by koral--** [comment]
Closing this since new dockerfiles were added: https://github.com/openstf/stf/pull/1174
Please fill a new issue if you encounter some problems.

**Comment by cartoonboy1989** [comment]
@phatpaul  I met same issue like you mentioned above. Have you got an solution to solve that problem??

**Comment by phatpaul** [comment]
I have been using: https://github.com/phatpaul/openstf-arm7-docker
Which is working for me on RPi 3.  Let me know if it works for you.
