### ISSUE TITLE
Multiple stf-triproxy-dev.service on a single host

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#959]
**What is the issue or idea you have?**
I am deploying STF using the official guide and am trying to setup multiple stf-triproxies-dev. I can do the first one with no problems and while do the second one i get an error saying that the Address already in use.
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
Here is  the First STF-triproxy-dev
``` docker run -d --name triproxy-dev-1  --net host  openstf/stf  stf triproxy dev  STF_TRIPROXY_BIND_PUB "tcp://<ip-1>:7250"  STF_TRIPROXY_BIND_DEALER "tcp://<ip-1>7260" STF_TRIPROXY_BIND_PULL "tcp://<ip-1>:7270"```
and my second stf-triproxy-dev was 
``` docker run -d --name triproxy-dev-2  --net host  openstf/stf  stf triproxy dev  STF_TRIPROXY_BIND_PUB "tcp://<ip-2>:7250"  STF_TRIPROXY_BIND_DEALER "tcp://<ip-2>7260" STF_TRIPROXY_BIND_PULL "tcp://<ip-2>:7270"```
**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
bin/stf triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                               [string] [default: "openstf-nyc"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use

And also please let me know if my question is clear enough

**Comment by sorccu** [comment]
You need to use different ports. Then, specify multiple `--connect-push` and `--connect-sub` on the provider. ZeroMQ will handle everything.
