### ISSUE TITLE
Cannot install application in production setup

### ISSUE THREAD

**Issue by vbanthia** [openstf/stf#96]
Hello, I am facing some problem in installing apk files in production setup. Since, it is working perfectly with ``` stf local ``` , so most probably the problem is some where in my setup. I tried debugging it but could not figure out. Hope someone can help me out.

So, the problem starts with nginx responding with 502(Bad gateway) on uploading apk file. Below is the screenshot.

![stf-error-screenshot](https://cloud.githubusercontent.com/assets/7875161/10214662/56a25594-6855-11e5-83b5-70ff2a9bb3d3.png)

![manifest_end_point](https://cloud.githubusercontent.com/assets/7875161/10214664/5a3c7c2a-6855-11e5-81d5-76c6055d1299.png)

This is my stf-storage-temp@3500 same as Deployment.md

```
[Unit]
Description=STF temp storage
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  -v /mnt/storage:/data \
  -p %i:3000 \
  openstf/stf:latest \
  stf storage-temp --port 3000 \
    --save-dir /data
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```

I tried checking into containers /data folder but there was nothing inside. apk file was inside /tmp folder inside

```bash
[stf@enigma ~]$ docker exec -it stf-storage-temp-3500 /bin/bash
stf@af7372510bb1:/app$ ls /data
stf@af7372510bb1:/app$ ls /tmp/
upload_53e55f6c6b2b1b5f6ae57356df2807be
```

I tried to explore code but could not find where this --save-dir option is being used. [storage-temp unit](https://github.com/openstf/stf/blob/master/lib/units/storage/temp.js) is not using it

I can provide more information and logs. Please have a look!

**Comment by sorccu** [comment]
Because you're getting a HTTP 502 error, it means that your request arrived to nginx, but it was unable to connect the backend server. The backend server in this case being `stf-storage-plugin-apk`. Either your nginx.conf is wrong, or you don't don't have `stf-storage-plugin-apk@.service` running.

**Comment by vbanthia** [comment]
I checked my backend servers, they are running fine.

This is nginx error log for that 502 response

```
*469 upstream prematurely closed connection while reading response header from upstream, client: 172.23.57.87, server: stf.example.org, request: "GET /s/apk/04a9f9cb-1bc1-41c7-aac3-8b0068337a74/service-release-20150916113424690.apk/manifest HTTP/1.1", upstream: "http://10.33.85.12:3300/s/apk/04a9f9cb-1bc1-41c7-aac3-8b0068337a74/service-release-20150916113424690.apk/manifest", host: "stf.example.org", referrer: "http://stf.example.org/"
```

In case, backend server are down, nginx will raise connection refused error

```
connect() failed (111: Connection refused) while connecting to upstream,
```

and this is the log from stf-storage-plugin-apk server

```
[stf@enigma ~]$ docker logs stf-storage-plugin-apk-3300
INF/storage:plugins:apk 1 [*] Listening on port 3000
```

BTW, ```/data (--save-dir)``` directory of stf-storage-temp container is empty. And also host's ```/mnt/storage``` directory is also empty. I am trying to find out which part of code responsible for copying uploaded files from ```/tmp``` directory to ```/data (--save-dir)``` directory. Can you help me with that?

**Comment by sorccu** [comment]
Looks like you forgot to replace the storage URL somewhere. It's trying to connect to `stf.example.org`.

All command line options are in `lib/cli.js`. The `--save-dir` command line argument translates to the saveDir option in JS code. But it doesn't look like you are having problems with the upload. It seems to me it's uploading just fine, but then when it tries to access the manifest via the apk plugin you hit that error.

**Comment by vbanthia** [comment]
Sorry to mention this before, my storage url is okay, I just changed the log in order to hide private domain.

Same thought for uploading, because I can see the uploaded apk file inside tmp folder of container. I also think problem is with ```/s/apk/:id/:name/manifest``` endpoint. I tried hitting plugin-apk server directly this is what I got.

```
 wget http://stf.mydomain.org:3300/s/apk/da5f9fb2-7552-457b-8fd8-6a72aa3ca647/service-release-20150916113424690.apk
--2015-10-01 16:53:46--  http://stf.mydomain.org:3300/s/apk/da5f9fb2-7552-457b-8fd8-6a72aa3ca647/service-release-20150916113424690.apk
Resolving stf.mydomain.org... 10.33.85.12
Connecting to stf.mydomain.org|10.33.85.12|:3300... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-10-01 16:53:47--  (try: 2)  http://stf.mydomain.org:3300/s/apk/da5f9fb2-7552-457b-8fd8-6a72aa3ca647/release-20150916113424690.apk
Connecting to stf.mydomain.org|10.33.85.12|:3300... failed: Connection refused.
Resolving stf.mydomain.org... 10.33.85.12
Connecting to stf.mydomain.org|10.33.85.12|:3300... failed: Connection refused.
```

Can you tell me one thing, while getting apk or image files from storage server. From which location storage server get these files? ```/data``` or ```/tmp```

**Comment by vbanthia** [comment]
The problem was with --storage-url. stf-storage-plugin-apk container was not able to resolve the domain for storage-url thats why server was crashing. And systemd was restarting it again. 

Using ``` -e DEBUG=express:*``` helped in debugging.

**Comment by mcloudfarm** [comment]
@vbanthia hello how did you solve the problem?
