### ISSUE TITLE
Timeout issue when sitting idle after occupied device

### ISSUE THREAD

**Issue by ranukumar93** [openstf/stf#960]
Hi Sir,
I am getting an issue of timeout when I occupied any of the devices and sit idle for some time. My device automatically gets released and the state of the device is changed from busy to available. It is happening randomly.

So I was wondering if there is any such setting or functionality inbuilt which is automatically releasing the device when it remains in idle state or is it a bug. Our users are quite happy with OpenSTF but the experienced could be great if we can figure our solution for it. We would appreciate any type of hint or suggestion in this regard.

**Comment by sorccu** [comment]
See --group--timeout
