### ISSUE TITLE
chinese characters donot support

### ISSUE THREAD

**Issue by JusTomm** [openstf/stf#968]
if the apk has chinese characters, then upload the apk ,then stf is breakdown, like "中文.apk"or"我是中文.apk"

**Comment by thinkhy** [comment]
It's a known issue, root cause is storage component doesn't support filename containing Chinese character. A workaround is to convert filename to MD5.

**Comment by JusTomm** [comment]
> It's a known issue, root cause is storage component doesn't support filename containing Chinese character. A workaround is to convert filename to MD5.

how？

**Comment by JusTomm** [comment]
> It's a known issue, root cause is storage component doesn't support filename containing Chinese character. A workaround is to convert filename to MD5.

thanks，but how to convert?

**Comment by thinkhy** [comment]
You need to add some code to convert it to MD5. We may  need a PR for this issue ...
