### ISSUE TITLE
'Failed to authenticate to ...' error with ADB connect command (ADB version 1.0.40 4986621) 

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#973]
**What is the issue or idea you have?**
Using the latest version of ADB (`1.0.40 4986621`), the `adb connect` command return an error like `Failed to authenticate to 10.193.14.128:15005`, although the device has been well connected, it is confirmed by running `adb devices -l `and `adb shell` commands, so it is not a blocking issue.

Note this error message does not appear while connecting directly to a device configured with a `adb tcpip 5555` command, neither with lower version of ADB.

At `stf-provider` side, the ADB version is 1.0.36 but a I made also a test with an 1.0.40 version and the issue remains.

So, it seems the problem is perhaps located at `stf-provider` side using `adbkit`.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
no device specific, but ADB specific from `1.0.40 4986621` version.

**Please provide the steps to reproduce the issue.**
see above.

**What is the expected behavior?**
ADB should return a message like `connected to 10.193.14.128:15005`

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
No, just an info message like `New remote ADB connection from ::ffff:10.193.14.11`

**Please run `stf doctor` and paste the output here.**
```
debian@debian:~/stf-master$ stf doctor
2018-10-29T09:40:24.221Z INF/cli:doctor 7077 [*] OS Arch: x64
2018-10-29T09:40:24.224Z INF/cli:doctor 7077 [*] OS Platform: linux
2018-10-29T09:40:24.224Z INF/cli:doctor 7077 [*] OS Platform: 3.16.0-4-amd64
2018-10-29T09:40:24.225Z INF/cli:doctor 7077 [*] Using Node 8.9.3
2018-10-29T09:40:24.240Z INF/cli:doctor 7077 [*] Using ZeroMQ 4.0.5
2018-10-29T09:40:24.252Z INF/cli:doctor 7077 [*] Using ADB 1.0.36
2018-10-29T09:40:24.253Z ERR/cli:doctor 7077 [*] ProtoBuf is not installed (`protoc` is missing)
2018-10-29T09:40:24.269Z INF/cli:doctor 7077 [*] Using GraphicsMagick 1.3.20
2018-10-29T09:40:24.323Z INF/cli:doctor 7077 [*] Using RethinkDB 2.3.6~0jessie
debian@debian:~/stf-master$
```

**Comment by chagasaway** [comment]
+1

**Comment by tangdongchu** [comment]
+1

**Comment by zademaxfield** [comment]
+1

**Comment by koral--** [comment]
Please don't post comments with "+1" only or similar. It won't speed up fixing.
You can upvote this issue by adding reaction at the bottom of the first post.

**Comment by djcm75** [comment]
Hi 
I use stf api inside a docker container to access devices connected on aother system.
The same docker image and api code works on production environment but fails on local environment
I get this response back from stf "success":true,"remoteConnectUrl":"192.168.187.109:7409"
followed by this line failed to authenticate to 192.168.187.109:7409
The user account associated with the container is root.

Please advise a fix

**Comment by djcm75** [comment]
Hi
I am facing the same issue, please see the attached logs

adb I 12-03 06:09:47   297   297 auth.cpp:473] Calling send_auth_response
adb I 12-03 06:09:47   297   297 auth.cpp:440] Calling send_auth_publickey
adb I 12-03 06:09:48   297   297 adb.cpp:145] 10.30.2.188:7401: offline
adb server killed by remote request
adb I 12-03 06:09:51   297   297 transport.cpp:337] BlockingConnectionAdapter(10.30.2.188:7401): stopping
adb I 12-03 06:09:51   297   446 transport.cpp:285] 10.30.2.188:7401: read failed: Success
adb I 12-03 06:09:51   297   297 transport.cpp:355] BlockingConnectionAdapter(10.30.2.188:7401): stopped
--- adb starting (pid 530) ---
adb I 12-03 06:11:10   530   530 main.cpp:56] Android Debug Bridge version 1.0.40
adb I 12-03 06:11:10   530   530 main.cpp:56] Version 4986621
adb I 12-03 06:11:10   530   530 main.cpp:56] Installed as /opt/android-sdk/platform-tools/adb
adb I 12-03 06:11:10   530   530 main.cpp:56] 
adb I 12-03 06:11:10   530   530 auth.cpp:421] adb_auth_init...
adb I 12-03 06:11:10   530   530 auth.cpp:174] read_key_file '/root/.android/adbkey'...
adb I 12-03 06:11:10   530   530 auth.cpp:396] adb_auth_inotify_init...
adb I 12-03 06:11:16   530   543 transport.cpp:281] 10.30.2.188:7409: read thread spawning
adb I 12-03 06:11:16   530   544 transport.cpp:294] 10.30.2.188:7409: write thread spawning
adb I 12-03 06:11:16   530   530 auth.cpp:473] Calling send_auth_response
adb I 12-03 06:11:16   530   530 auth.cpp:440] Calling send_auth_publickey
adb I 12-03 06:11:16   530   530 adb.cpp:145] 10.30.2.188:7409: offline

**Comment by likezjuisee** [comment]
Hi,
i am facing the same issue, what can i do to solve it?

**Comment by jlvandusen** [comment]
adb connect 192.168.1.214
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to authenticate to 192.168.1.214:5555

adb connect 192.168.1.214
already connected to 192.168.1.214:5555

adb devices
List of devices attached
192.168.1.214:5555      unauthorized

**Comment by vjmaiky** [comment]
any updates on this topic? any solutions? i;m inthe situatia that on my macbook pro i can connect to them using Android Debug Bridge version 1.0.40 Version 4797878, and from other mac minis i get failed to connect/authenticate....

**Comment by sorccu** [comment]
I took a brief look a few weeks ago. It seems that adbkit itself is fine, if used by itself everything works well. The issue seems to be that the auth handler in STF rejects the client die to the device already being in use, even if it wasn’t. Seems like events like autojoin may be firing in an i correct order. I was not able to look into it further yet.

**Comment by vjmaiky** [comment]
if i close the active screen share and i do adb connect to it's ip..it works..

**Comment by djcm75** [comment]
I solved it by downgrading adb to ver 1.0.39 if I use version 1.0.40 I constantly get the error message. Simply downgrading solved the problem

**Comment by vjmaiky** [comment]
how did you downgraded adb?

**Comment by knallaf** [comment]
Downgrading adb to v.1.0.39 fixed the problem for me too. Attached, please find the adb file for Linux (extracted from docker container sorccu/adb). 
[adb.zip](https://github.com/openstf/stf/files/2851400/adb.zip)

**Comment by knallaf** [comment]
Downgrading adb to v.1.0.39 fixed the problem for me too. Attached, adb file for Linux (extracted from docker container sorccu/adb).
[adb.zip](https://github.com/openstf/stf/files/2851400/adb.zip)

**Comment by koral--** [comment]
It seems that there is no need to downgrade ADB nor apply any workaround.
The message printed to console is incorrect but connection is actually successful.

**Comment by knallaf** [comment]
Yes, I agree with you, but in my case, the correct adb output is important as I use it to verify adb status by the automatic test framework.

**Comment by codeskyblue** [comment]
@sorccu It seems it is the problem of adbkit it self. The issue can be reproduced with the following steps.

```
npm i -g adbkit
adbkit usb-device-to-tcp -p 20067 FFKDU17314004185
```

Then open another shell

```
$ adb version
# should show adb version 1.0.40
$ adb connect 127.0.0.1:20067
```

The first terminal will show

```
Connect with `adb connect localhost:20067`
An error occured: Unrecognizable public key format
An error occured: Unrecognizable public key format
An error occured: Unrecognizable public key format
An error occured: Unrecognizable public key format
...
```

**Comment by jlvandusen** [comment]
@codeskyblue - how do I merge this into my HASS.IO install?

**Comment by codeskyblue** [comment]
What is HASS.IO?

**Comment by johnnypha** [comment]
I have the same problem but in addition, the device is connected but appears to be offline.
***********************************************************************************************
C:\Users\XXXX>adb version
Android Debug Bridge version 1.0.40
Version 28.0.2-5303910
Installed as C:\Users\XXXX\AppData\Local\Android\Sdk\platform-tools\adb.exe

C:\Users\XXXX>adb connect 10.2.110.21:7425
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to authenticate to 10.2.110.21:7425

C:\Users\XXXX>adb devices
List of devices attached
10.2.110.21:7425        offline

********************************************************************************************************
Do you guys have an estemation when can it be marge?

P.S.
When I'm doing the same from another laptop with an older version of ADB it works fine but I'm currently not able to find a way to downgrade the ADB version (Win 10)

**Comment by TheBogan** [comment]
Hi,

I have deployed OpenSTF using Docker-Compose.
While I used Public Ip, I unable to remote connect devices using **adb connect ip:port**
I am using sorccu/adb docker image.
However I able to connect remote adb connect when running services hosted in local IP(Within LAN).

The ADB version in docker is 

```
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as /opt/platform-tools/adb
```
In remote machine, I tried with 1.0.39 too
**Android Debug Bridge version 1.0.40** 

Is any idea about this?

**Comment by dexterm** [comment]
did you run whereis adb
or which adb
sometimes the container may be using ver 1.0.40 in such cases copy the the older version or execute adb using the full path /home/usr/<adb ver 0.39>

**Comment by TheBogan** [comment]
> did you run whereis adb
> or which adb
> sometimes the container may be using ver 1.0.40 in such cases copy the the older version or execute adb using the full path /home/usr/<adb ver 0.39>

yes, I am using 1.0.39 version inside the container.

/ # adb version
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as /opt/platform-tools/adb

**Comment by TheBogan** [comment]
issue is not resolved. Please give any idea.

**Comment by TheBogan** [comment]
I am facing as follow

Facing issue only while OpenSTF goes live in Public IP domain.

Everything seems fine in local network.

**Comment by TheBogan** [comment]
```
2019-05-03T15:57:47.853Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:48.246Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:48.667Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:49.106Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:49.635Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:50.066Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:50.943Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:51.469Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:52.971Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:53.533Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:53.947Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:54.411Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:55.064Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:55.941Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:56.417Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:57.130Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:57.308Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:57.891Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
provider_1              | 2019-05-03T15:57:58.402Z INF/device:plugins:connect 53 [353003080063628] New remote ADB connection from ::ffff:49.207.180.110
```

It seems fingerprint is not added. Also popup is not shown in STF Client.

**Comment by TheBogan** [comment]
Issue fixed with patch update. Likely the system reboot cools off the issue.

Thanks a lot.

**Comment by kolyakrasnik** [comment]
@TheBogan Which patch are you talking about?

**Comment by sqamike** [comment]
The critical step in getting this to work is disconnecting the usb cable after issuing the adb connect xx.x.x.xx:5555 command. At this point you are connected but unauthorized. Execute adb kill-server and re-issue the connect command. Verify with execution of adb shell date.
