### ISSUE TITLE
Sometimes File Explorer not working

### ISSUE THREAD

**Issue by clarkshu1016** [openstf/stf#974]
**What is the issue or idea you have?**
Sometimes File Explorer not working, it's just empty and no any directory shows

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
I am not sure it happens on a specific device, my device is Nexus5x, version 7.1.2, haven't rooted yet.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

No any stf local error output.

**Please run `stf doctor` and paste the output here.**

2018-10-29T11:16:57.451Z INF/cli:doctor 39904 [*] OS Arch: x64
2018-10-29T11:16:57.453Z INF/cli:doctor 39904 [*] OS Platform: darwin
2018-10-29T11:16:57.453Z INF/cli:doctor 39904 [*] OS Platform: 18.0.0
2018-10-29T11:16:57.453Z INF/cli:doctor 39904 [*] Using Node 8.12.0
2018-10-29T11:16:57.474Z INF/cli:doctor 39904 [*] Using ZeroMQ 4.2.5
2018-10-29T11:16:57.490Z INF/cli:doctor 39904 [*] Using GraphicsMagick 1.3.30
2018-10-29T11:16:57.505Z INF/cli:doctor 39904 [*] Using ADB 1.0.39
2018-10-29T11:16:57.507Z INF/cli:doctor 39904 [*] Using RethinkDB 2.3.6
2018-10-29T11:16:57.508Z INF/cli:doctor 39904 [*] Using ProtoBuf 3.6.1

**Comment by thinkhy** [comment]
First  make sure you have read permission with adb shell user to access the default directory "/" .

**Comment by vanshu** [comment]
some of hiding system files, adb shell it doesn't have read permission, but directory has read permission


bullhead:/ $ ls
ls: ./persist: Permission denied
ls: ./verity_key: Permission denied
ls: ./ueventd.rc: Permission denied
ls: ./ueventd.bullhead.rc: Permission denied
ls: ./service_contexts: Permission denied
ls: ./sepolicy: Permission denied
ls: ./selinux_version: Permission denied
ls: ./seapp_contexts: Permission denied
ls: ./init.zygote64_32.rc: Permission denied
ls: ./init.zygote32.rc: Permission denied
ls: ./init.usb.rc: Permission denied
ls: ./init.usb.configfs.rc: Permission denied
ls: ./init.recovery.bullhead.rc: Permission denied
ls: ./init.rc: Permission denied
ls: ./init.environ.rc: Permission denied
ls: ./init.bullhead.usb.rc: Permission denied
ls: ./init.bullhead.sensorhub.rc: Permission denied
ls: ./init.bullhead.rc: Permission denied
ls: ./init.bullhead.ramdump.rc: Permission denied
ls: ./init.bullhead.misc.rc: Permission denied
ls: ./init.bullhead.fp.rc: Permission denied
ls: ./init.bullhead.diag.rc: Permission denied
ls: ./init: Permission denied
ls: ./fstab.bullhead: Permission denied
ls: ./file_contexts.bin: Permission denied
ls: ./default.prop: Permission denied
acct       charger data firmware proc              root   storage vendor
bugreports config  dev  mnt      property_contexts sbin   sys
cache      d       etc  oem      res               sdcard system

**Comment by thinkhy** [comment]
what about some public directories like "/sdcard"?

**Comment by sorccu** [comment]
Btw don’t use “adb shell ls”. Use just “adb ls”. It uses a different service behind the scenes, the same one STF uses. Would be useful to know what output that command gives you.

**Comment by vanshu** [comment]
> what about some public directories like "/sdcard"?
I can get all directories on sdcard from " adb shell ls /sdcard " command.

**Comment by vanshu** [comment]
> Btw don’t use “adb shell ls”. Use just “adb ls”. It uses a different service behind the scenes, the same one STF uses. Would be useful to know what output that command gives you.

Hi sorccu, I am not sure  there is a command called adb ls, I tried this command on Terminal,
it shows incorrectly:

'adb: usage: ls requires an argument'

**Comment by sorccu** [comment]
“adb ls /“

**Comment by vanshu** [comment]
> “adb ls /“

I typed this command, it shows no any output.

but I tried to use "adb ls /sdcard" ,  it shows all directories correctly.
