### ISSUE TITLE
Stf service apk didn't get installed on OPPO device

### ISSUE THREAD

**Issue by KeshavP96** [openstf/stf#978]
Hi, I am trying to connect OPPO device but stf service apk is not getting installed. Although I checked all security settings.

**Comment by thinkhy** [comment]
which model of OPPO devices did you use?  I just guess that the specific
ROM of OPPO added a new security limitation: ban against installation of
any apk without launch activity(desktop icon).

KeshavP96 <notifications@github.com> 于2018年10月31日周三 下午2:53写道：

**Comment by KeshavP96** [comment]
Thanks for quick reply.
These are the devices I am using.
Device 1: OPPO A57
Device 2: OPPO R9s
While installing this error is showing stated that it doesn't have desktop icon.

**Comment by thinkhy** [comment]
Well, actually I've resolved the problem on devices OPPO A57 and R9s, I modified a little code of STFService.apk and added launch activity for it.
@sorccu just wondering why STFService.apk doesn't provider launch activity in manifest.xml?

**Comment by sorccu** [comment]
The original thinking behind that is that STF should interfere with the device as little as possible. Ideally you wouldn’t even be able to tell that STF was running, which isn’t the case though (there’s the notification). STF is meant to provide access to real user devices, and real users wouldn’t have STF installed.

I’m OK to add one now, though.

**Comment by KeshavP96** [comment]
hi thinky,
can you please provide the code to change or give latest apk?

**Comment by KeshavP96** [comment]
Also getting problem in OPPO R9m

**Comment by KeshavP96** [comment]
I am pasting output here please chceck

This is happening for OPPO A57, R9s and R9m

Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:11.574Z INF/provider 1 [*] Restarting device worker "6473569"
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:11.574Z ERR/provider 1 [*] Device worker "6473569" died with code 1
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:11.574Z INF/provider 1 [*] Cleaning up device worker "6473569"
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:11.571Z FTL/util:lifecycle 3709 [6473569] Shutting down due to fatal error
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]:     at processImmediate [as _immediateCallback] (timers.js:617:5)
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]:     at tryOnImmediate (timers.js:645:5)
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]:     at runCallback (timers.js:672:20)
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]:     at /app/node_modules/adbkit/lib/adb/command/host-transport/install.js:28:23
Nov 12 09:14:11 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:11.571Z FTL/device 3709 [6473569] Setup had an error Error: /data/local/tmp/STFService.apk could not be installed [-99]
Nov 12 09:14:09 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:09.825Z INF/device:resources:service 3717 [e68d602] Installing STFService
Nov 12 09:14:09 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:09.295Z INF/device:resources:service 3709 [6473569] Installing STFService
Nov 12 09:14:09 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:09.224Z INF/device:resources:service 3717 [e68d602] Checking whether we need to install STFService
Nov 12 09:14:09 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:09.062Z INF/device:resources:minicap 3717 [e68d602] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-23/minicap.so" as "/data/local/tmp/min
Nov 12 09:14:09 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:09.062Z INF/device:resources:minicap 3717 [e68d602] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.956Z INF/device:support:abi 3717 [e68d602] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.955Z INF/device:support:sdk 3717 [e68d602] Supports SDK 23
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.923Z INF/device:support:properties 3717 [e68d602] Loading properties
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.871Z INF/device:support:sub 3717 [e68d602] Subscribing to permanent channel "*ALL"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.870Z INF/device:support:sub 3717 [e68d602] Receiving input from "tcp://10.88.4.59:7111"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.645Z INF/device 3717 [e68d602] Preparing device
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.642Z INF/device:support:push 3717 [e68d602] Sending output to "tcp://10.88.4.59:7113"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.552Z INF/device:resources:service 3709 [6473569] Checking whether we need to install STFService
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.410Z INF/device:resources:minicap 3709 [6473569] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-23/minicap.so" as "/data/local/tmp/min
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.409Z INF/device:resources:minicap 3709 [6473569] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.282Z INF/device:support:abi 3709 [6473569] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.282Z INF/device:support:sdk 3709 [6473569] Supports SDK 23
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.194Z INF/device:support:properties 3709 [6473569] Loading properties
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.142Z INF/device:support:sub 3709 [6473569] Subscribing to permanent channel "*ALL"
Nov 12 09:14:08 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:08.141Z INF/device:support:sub 3709 [6473569] Receiving input from "tcp://10.88.4.59:7111"
Nov 12 09:14:07 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:07.916Z INF/device 3709 [6473569] Preparing device
Nov 12 09:14:07 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:07.914Z INF/device:support:push 3709 [6473569] Sending output to "tcp://10.88.4.59:7113"
Nov 12 09:14:07 ZenReplica-ProviderTW docker[1119]: 2018-11-12T09:14:07.848Z INF/provider 1 [*] Restarting device worker "e68d602"
