### ISSUE TITLE
How can I disable the red screen ?

### ISSUE THREAD

**Issue by floor23** [openstf/stf#979]
I want to disable the red screen which shows the mobile info. Is there any features I can use to do this?

The red screen looks like this
![_20181031181504](https://user-images.githubusercontent.com/6335512/47781769-850e9580-dd39-11e8-9ded-d9c0d5e1e1a6.png)

Thank you all

**Comment by sorccu** [comment]
You can’t completely remove it without modifying STFService.apk.

**Comment by thinkhy** [comment]
@floor23  curious about the reason why you want to disable the feature? and when would the activity be showed in your case?

**Comment by floor23** [comment]
> You can’t completely remove it without modifying STFService.apk.

Thanks for your reply

**Comment by floor23** [comment]
> @floor23 curious about the reason why you want to disable the feature? and when would the activity be showed in your case?

There is some cases I want to do something automatically. These cases base on **Xposed**, the red screen would interrupt the auto scripts.

**Comment by thinkhy** [comment]
@floor23 sounds interesting, saying you  xposed module would launch the stfservice identify  activity ...

**Comment by benedikt-bartscher** [comment]
You can mitigate this by revoking the permission:

```bash
pm revoke jp.co.cyberagent.stf android.permission.SYSTEM_ALERT_WINDOW
```
