### ISSUE TITLE
Orientation change issue

### ISSUE THREAD

**Issue by ahmetkocu** [openstf/stf#98]
When I change the orientation to landscape and then to potrait, device is frozen. Only device can use after reboot.

How can I fix this issue, what is the problem you think.

Device: HTC One X Android:4.2.2

Some part of log:

INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: Using projection 720x1280@292x519/0"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Connecting to minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:259) Creating buffer queue"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Reading minicap banner
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:display 7860 [HT25BW100273] Rotation changed to 90
INF/device:plugins:screen:stream 7860 [HT25BW100273] Setting frame producer rotation to 90
INF/device:plugins:screen:stream 7860 [HT25BW100273] Disconnecting from minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Stopping minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:284) Destroying virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Launching screen service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "PID: 8474"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: Using projection 720x1280@292x519/1"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Connecting to minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:259) Creating buffer queue"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Reading minicap banner
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:display 7860 [HT25BW100273] Rotation changed to 0
INF/device:plugins:screen:stream 7860 [HT25BW100273] Setting frame producer rotation to 0
INF/device:plugins:screen:stream 7860 [HT25BW100273] Disconnecting from minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Stopping minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:284) Destroying virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Launching screen service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "PID: 8491"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: Using projection 720x1280@292x519/0"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Connecting to minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:259) Creating buffer queue"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Reading minicap banner
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:display 7860 [HT25BW100273] Rotation changed to 90
INF/device:plugins:screen:stream 7860 [HT25BW100273] Setting frame producer rotation to 90
INF/device:plugins:screen:stream 7860 [HT25BW100273] Disconnecting from minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Stopping minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:284) Destroying virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Launching screen service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "PID: 8513"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: Using projection 720x1280@292x519/1"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Connecting to minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:259) Creating buffer queue"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:display 7860 [HT25BW100273] Rotation changed to 0
INF/device:plugins:screen:stream 7860 [HT25BW100273] Setting frame producer rotation to 0
INF/device:plugins:screen:stream 7860 [HT25BW100273] Reading minicap banner
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Disconnecting from minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Stopping minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:284) Destroying virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Launching screen service
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "PID: 8527"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: Using projection 720x1280@292x519/0"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:259) Creating buffer queue"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:265) Creating frame waiter"
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:269) Publishing virtual display"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Connecting to minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Disconnecting from minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Stopping minicap service
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 7860 [HT25BW100273] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 7860 [HT25BW100273] Sending SIGKILL to minicap
FTL/device:plugins:screen:stream 7860 [HT25BW100273] Frame producer had an error FailError: Failure: 'closed'
    at /usr/local/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:226:31
    at processImmediate [as _immediateCallback] (timers.js:371:17)
FTL/util:lifecycle 7860 [HT25BW100273] Shutting down due to fatal error
INF/provider 7449 [*] Cleaning up device worker "HT25BW100273"
ERR/provider 7449 [*] Device worker "HT25BW100273" died with code 1
INF/provider 7449 [*] Restarting device worker "HT25BW100273"
INF/device:support:push 7893 [HT25BW100273] Sending output to "tcp://127.0.0.1:7116"

**Comment by ahmetkocu** [comment]
I solve that issue. It was because of timeout error. (stream.js)

**Comment by luisxiaomai** [comment]
@ahmetkocu , how you solve this problem. I met the same issue.
