### ISSUE TITLE
[QUESTION]   How stf implemented frames are only sent when something changes on the screen ?

### ISSUE THREAD

**Issue by harborless** [openstf/stf#984]
Hi Guys,
Extrmely impressive for your great work!

I wonder how stf/minicap implemented the feature:
     - On Android 4.2+, frames are only sent when something changes on the screen. 
What is the idea behind it?  Is there any Android feature related? 

Thank you for your time.

**Comment by sorccu** [comment]
That’s how the Android API minicap uses works. Nothing specific needs to be done, if there are frames to read it tells you, if not it doesn’t. So minicap just reads frames whenever the system tells it to.

**Comment by harborless** [comment]
Got it. The Android API -- android::ConsumerBase::FrameAvailableListener does it. Thank you so much!
