### ISSUE TITLE
Minicap stream shows black area on video playback area for netflix

### ISSUE THREAD

**Issue by ACBNair** [openstf/stf#988]
This is mainly seen in Android 7.0 devices. When I stream from Netflix, it is showing black screen on video playback area. Same app could stream from higher versions. 

Devices tried : 
               

- Moto G4
- Sony F3116
- Samsung J7

First I doubt the HDCP settings. Following are the HDCP settings : 

MOTO G4 : 
 Security Level : L1
Max HDCP support : HDCP 2.2 
 SDK 24

Samsung J7 
  Security Level : L1
  Max HDCP support : Disconnected 
  SDK 24

Sony F3116 
   Security Level : L3 
   Max HDCP support : Unprotected 
   SDK 24

**Comment by sorccu** [comment]
Likely due to DRM. I don’t think there’s much we can do about this but feel free to try.

**Comment by ACBNair** [comment]
Any suggestions to try out?

**Comment by sorccu** [comment]
Not really. Personally I think it’s a losing game; even if we find a way, Netflix can dedicate a team of engineers to find a new way to hide the stream.
