### ISSUE TITLE
 Providing all 0 of 1 device(s); ignoring "0123456789ABCDEF"

### ISSUE THREAD

**Issue by chunyuong** [openstf/stf#989]
I use docker  start provider:  docker run  -d  --name stf-privider  openstf/stf  stf provider --name......  

The following problems with  docker logs：
INF/provider 22257 [*] Tracking devices
INF/provider 22257 [*] Found device "0123456789ABCDEF" (device)
INF/provider 22257 [*] Providing all 0 of 1 device(s); ignoring "0123456789ABCDEF"

**Comment by ysxAAA** [comment]
did u fix it?can u tell me the solution 555555555 help me

**Comment by gounthar** [comment]
I'm sorry @thinkhy I don't get it...

**Comment by thinkhy** [comment]
I hit the same problem when there are devices with duplicate serial.

**Comment by chunyuong** [comment]
@thinkhy @ysxAAA   I have  solved this problem，Because the port configuration errors ：“--connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116”   If you don't know what is this port，You can use this command : "stf local --public-ip 127.0.0.1 --allow-remote"  ，You can be based on the analysis of log, red box to the red area as follows:
![image](https://user-images.githubusercontent.com/26139195/49578693-4ba6f680-f985-11e8-9cce-c2b7fd8f44a8.png)

**Comment by sorccu** [comment]
Sounds like this was simply a connectivity issue, but like @thinkhy mentioned you can only have one  device with the same serial number. Some makers like Micromax are lazy bastards and set all of theirs to `0123456789ABCDEF`, which means that you can only connect one to STF.
