### ISSUE TITLE
stf api failed to authenticate to 192.168.187.109:7409

### ISSUE THREAD

**Issue by djcm75** [openstf/stf#991]
Hi
I use stf api inside a docker container to access devices connected on aother system.
The same docker image and api code works on production environment but fails on local environment
I get this response back from stf "success":true,"remoteConnectUrl":"192.168.187.109:7409"
followed by this line failed to authenticate to 192.168.187.109:7409
The user account associated with the container is root. I suspect it is an adb permission problem, I verified that keys are copied to container root/.andorid folder

Please advise how to grant permissions

**Comment by djcm75** [comment]
Hi 
Stf automatically generates a new key called "unknown" , inspite of deleting the key, it keeps getting added to the list of keys, when ever I use the adb connect command inside a docker container. I suspect stf isn't use the key provided in the container located in /root/.android folder

**Comment by rugaba** [comment]
hello @djcm75 , have you got the answer for that ? i am facing the same issue currently. thx.

**Comment by djcm75** [comment]
Yes, the problem was with adb ver 40.0, If you downgrade to version 39.0, you wont experience the bug. There was a previous version of adb on the system, simply copying the older adb into the container solved the problem

**Comment by automatisation-team** [comment]
thx @djcm75  , it worked !!
