### ISSUE TITLE
cyberagent.stf is restricted

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#994]
**What is the issue or idea you have?**
I have set up the openstf on a machine and connected a device through a provider running on other machine, everything is fine but as i plugged in a new device i get this error in my slack chaneel, i am not sure what it means but i think my device is stopping or restricting the installation of the stf agaent on it, am i right? how do i trouble shoot this
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
`Setup had an error Error: Service had an error: "Error: Unable to launch app jp.co.cyberagent.stf/10128 for service Intent { act=jp.co.cyberagent.stf.ACTION_START cmp=jp.co.cyberagent.stf/.Service }: jp.co.cyberagent.stf is restricted"
    at /app/lib/units/device/plugins/service.js:101:23
From previous event:
    at /app/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`
**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
What kind of a device is it?

**Comment by thinkhy** [comment]
@habeebshk from my experience, I have two ways to resolve this kind of problems:
    1. Start activity first, then start service:
      *  `adb shell am start -n jp.co.cyberagent.stf/.IdentityActivity`
      *  `adb shell am startservice -a jp.co.cyberagent.stf.ACTION_START -n jp.co.cyberagent.stf/.Service`
    2. Enable some special permission like "auto-start" and "background run" for the STFService.apk

Hope above would be helpful.

**Comment by habeebshk** [comment]
hey guys, it worked thanks, I was able to set up the openstf from scratch with the help of you guys. This is a really an awesome application.
